import {invalidateReadingCache} from './reading-cache.ts';
import {UPDATE_PAGES,hasPageUpdate,type PageRevision,type PageUpdate,type UpdateMap,type UpdatePageKey} from '@aihot/contracts/navigation-updates';
type Fetcher=(url:string,init?:RequestInit)=>Promise<Response>;
export type NavigationSnapshot={pages:UpdateMap;ready:boolean;error:string};
export function createNavigationStore(fetcher:Fetcher=(...args)=>fetch(...args)){
 let state:NavigationSnapshot={pages:{},ready:false,error:''},confirmed:UpdateMap={},generation=0;
 const pending=new Map<UpdatePageKey,PageRevision>(),listeners=new Set<()=>void>();let queue=Promise.resolve();let refreshing:Promise<void>|null=null;
 const emit=(error=state.error)=>{const pages={...confirmed};for(const [key,r] of pending){const p=pages[key];if(p)pages[key]={...p,seenRevision:Math.max(p.seenRevision??0,r.revision),seenVersion:Math.max(p.seenVersion??0,r.version)}}state={pages,ready:state.ready,error};listeners.forEach(fn=>fn())};
 const merge=(pages:UpdateMap)=>{for(const def of UPDATE_PAGES){const p=pages[def.key];if(!p)continue;const old=confirmed[def.key];if(old&&(p.revision>old.revision||p.version>old.version))invalidateReadingCache();confirmed[def.key]=old?{...p,revision:Math.max(old.revision,p.revision),version:Math.max(old.version,p.version),seenRevision:old.seenRevision===null?p.seenRevision:p.seenRevision===null?old.seenRevision:Math.max(old.seenRevision,p.seenRevision),seenVersion:old.seenVersion===null?p.seenVersion:p.seenVersion===null?old.seenVersion:Math.max(old.seenVersion,p.seenVersion)}:p;}state={...state,ready:true};emit('')};
 const request=async(body?:unknown)=>{const res=await fetcher('/api/site/navigation-updates',{credentials:'same-origin',cache:'no-store',...(body?{method:'PUT',headers:{'Content-Type':'application/json','X-HKIS-Request':'1'},body:JSON.stringify(body),keepalive:true}:{})});const value=await res.json();if(!res.ok)throw Error(value.detail||'更新提示暂未同步');return value.pages as UpdateMap};
 function refresh(){if(refreshing)return refreshing;const start=generation;refreshing=(async()=>{try{const pages=await request();if(start===generation)merge(pages)}catch(e){emit((e as Error).message)}finally{refreshing=null}})();return refreshing}
 function write(body:any,onFinish?:()=>void){generation++;const work=async()=>{try{merge(await request(body));return true}catch(e){emit((e as Error).message);return false}finally{onFinish?.();emit()}};const result=queue.then(work,work);queue=result.then(()=>{});return result;}
 function initialize(legacyVersion:number|null=null){const revisions=UPDATE_PAGES.flatMap(p=>{const r=confirmed[p.key];return r&&r.seenRevision===null?[{key:r.key,revision:r.revision,version:r.key==='changelog'&&legacyVersion!==null?Math.min(legacyVersion,r.version):r.version,...(r.latestDate?{latestDate:r.latestDate}:{})}]:[]});return revisions.length?write({action:'initialize',revisions}):Promise.resolve(true)}
 function seen(r:PageRevision){const p=confirmed[r.key];if(p&&p.seenRevision!==null&&p.seenVersion!==null&&p.seenRevision>=r.revision&&p.seenVersion>=r.version)return Promise.resolve(true);if(pending.get(r.key)?.revision===r.revision&&pending.get(r.key)?.version===r.version)return Promise.resolve(true);pending.set(r.key,r);emit('');return write({action:'seen',revisions:[r]},()=>{if(pending.get(r.key)===r)pending.delete(r.key)})}
 return {subscribe(fn:()=>void){listeners.add(fn);return()=>{listeners.delete(fn)}},getSnapshot:()=>state,refresh,initialize,seen,setEnabled:(key:UpdatePageKey,enabled:boolean)=>write({action:'preference',key,enabled}),unread:(key:UpdatePageKey)=>hasPageUpdate(state.pages[key])};
}
export type NavigationStore=ReturnType<typeof createNavigationStore>;
