/** Local, explicit diagnostic session only. Never sends telemetry or retains user text. */
type Row={kind:string;at:number;duration?:number;[key:string]:unknown};
let enabled=false,started=0,lastAction=0,mountPanel:(()=>void)|null=null,records:Row[]=[];
const apiRoutes=new Set(['meta','navigation-updates','research/papers','research/status','research/themes','research/feed','research/weekly','research/keyword-map','research/daily','research/daily/calendar','research/reader-state','research/reader-state/favorites','ai/settings','ai/chat','ai/test','ai/preferences','logs','changelog']);
const apiRoute=(path:string)=>{const suffix=path.replace(/^\/api\/site\//,'');return apiRoutes.has(suffix)?suffix:'other'};
const round=(n:number)=>Math.round(n*100)/100;
function add(kind:string,values:Record<string,unknown>={}){if(!enabled)return;records.push({kind,at:round(performance.now()),...values});if(records.length>1200)records.shift()}
const route=(path:string)=>/^\/(?:research|daily)\/[^/]+$/.test(path)?path.startsWith('/research/')?'paper-detail':'daily-detail':['/','/research','/all','/hot','/daily','/topics','/starred','/settings','/changelog','/agent','/about','/feedback'].includes(path)?path:'other';
export function profileRoute(){if(enabled)add('route-effect',{route:route(location.pathname),sinceAction:lastAction?round(performance.now()-lastAction):null})}
export function profileHydrated(){if(enabled){add('hydration-effect',{duration:round(performance.now()-started),sinceNavigation:round(performance.now())});if(mountPanel){const mount=mountPanel;mountPanel=null;requestAnimationFrame(mount)}}}
export function startProfile(){
 try{const flag=new URL(location.href).searchParams.get('hkis_profile');if(flag==='1')sessionStorage.setItem('hkis-profile','1');if(flag==='0')sessionStorage.removeItem('hkis-profile');enabled=sessionStorage.getItem('hkis-profile')==='1'}catch{return}
 if(!enabled)return;started=performance.now();add('bootstrap',{schema:1,viewport:{width:innerWidth,height:innerHeight},dpr:devicePixelRatio,timeOrigin:performance.timeOrigin});
 for(const type of ['longtask','layout-shift','event','paint','largest-contentful-paint']){try{const observer=new PerformanceObserver(list=>{for(const e of list.getEntries()){const v=e as any;if(type==='event'&&!['click','keydown','input','pointerdown'].includes(e.name))continue;add(type,{duration:round(e.duration),start:round(e.startTime),...(type==='event'?{event:e.name,processingStart:round(v.processingStart),processingEnd:round(v.processingEnd),interactionId:v.interactionId}:{}),...(type==='layout-shift'?{value:v.value,hadRecentInput:v.hadRecentInput}:{})})}});observer.observe({type,buffered:true,...(type==='event'?{durationThreshold:16}:{})});}catch{add('unsupported',{type})}}
 const original=window.fetch;
 window.fetch=async(input,init)=>{const url=new URL(input instanceof Request?input.url:String(input),location.href);const same=url.origin===location.origin;const t=performance.now();let options=init;if(same){const headers=new Headers(init?.headers||(input instanceof Request?input.headers:undefined));headers.set('X-HKIS-Profile','1');options={...init,headers}}try{const response=await original(input,options);if(same)add('fetch-headers',{route:route(url.pathname),api:url.pathname.startsWith('/api/site/')?apiRoute(url.pathname):undefined,status:response.status,duration:round(performance.now()-t),serverTiming:response.headers.get('Server-Timing')});return response}catch(e){if(same)add('fetch-error',{duration:round(performance.now()-t)});throw e}};
 const action=(e:Event)=>{if((e.target as Element)?.closest?.('[data-hkis-profile]'))return;const el=(e.target as Element)?.closest?.('button,a,input,select,textarea,summary');if(!el)return;lastAction=performance.now();const tag=el.tagName.toLowerCase();add('action',{event:e.type,control:tag,route:route(location.pathname)});const t=lastAction;requestAnimationFrame(()=>requestAnimationFrame(()=>add('action-two-raf',{event:e.type,control:tag,duration:round(performance.now()-t)})))};
 for(const type of ['click','change','input','pointerdown'])document.addEventListener(type,action,{capture:true,passive:true});
 let previous=0,frames=0,maxGap=0,longFrames=0;
 const frame=(t:number)=>{if(!enabled)return;if(document.visibilityState==='visible'&&previous){const gap=t-previous;maxGap=Math.max(maxGap,gap);frames++;if(gap>50)longFrames++}previous=document.visibilityState==='visible'?t:0;requestAnimationFrame(frame)};requestAnimationFrame(frame);
 window.addEventListener('load',()=>add('load',{sinceNavigation:round(performance.now())}),{once:true});
 const mount=()=>{const panel=document.createElement('details');panel.dataset.hkisProfile='1';panel.style.cssText='position:fixed;bottom:8px;right:8px;z-index:99999;max-width:90vw;max-height:75vh;overflow:auto;background:white;color:black;border:1px solid #999;padding:8px;font:12px monospace';const summary=document.createElement('summary');summary.textContent='性能诊断（本地）';panel.append(summary);const info=document.createElement('p');info.textContent='仅当前标签页；不记录输入内容、不上传。双帧间隔不等于绘制/React commit。';panel.append(info);const reset=document.createElement('button');reset.textContent='开始新样本';reset.onclick=()=>{records=[];frames=0;maxGap=0;longFrames=0;performance.clearResourceTimings();add('sample-start',{route:route(location.pathname)})};panel.append(reset);const button=document.createElement('button');button.textContent='生成脱敏性能快照';const output=document.createElement('textarea');output.setAttribute('aria-label','脱敏性能快照');output.readOnly=true;output.style.cssText='display:block;width:650px;max-width:80vw;height:180px';button.onclick=()=>{const resources=performance.getEntriesByType('resource') as PerformanceResourceTiming[];const nav=performance.getEntriesByType('navigation')[0] as PerformanceNavigationTiming|undefined;output.value=JSON.stringify({schema:1,exportedAt:new Date().toISOString(),viewport:{width:innerWidth,height:innerHeight},route:route(location.pathname),navigation:nav?{type:nav.type,duration:round(nav.duration),ttfb:round(nav.responseStart-nav.requestStart),domContentLoaded:round(nav.domContentLoadedEventEnd),loadEnd:round(nav.loadEventEnd),transferSize:nav.transferSize,encodedBodySize:nav.encodedBodySize,serverTiming:nav.serverTiming.map(x=>({name:x.name,duration:x.duration,description:x.description}))}:null,frames:{count:frames,maxGap:round(maxGap),over50ms:longFrames},resources:resources.filter(r=>new URL(r.name).origin===location.origin).map(r=>({type:r.initiatorType,duration:round(r.duration),transferSize:r.transferSize,encodedBodySize:r.encodedBodySize,cacheZeroTransfer:r.transferSize===0})),records},null,2)};panel.append(button,output);const stop=document.createElement('button');stop.textContent='退出诊断';stop.onclick=()=>{sessionStorage.removeItem('hkis-profile');const u=new URL(location.href);u.searchParams.delete('hkis_profile');location.replace(u.href)};panel.append(stop);document.body.append(panel)};
 mountPanel=mount;
}
