import {NavigationUpdateSettings,usePageRead} from '../components/NavigationUpdates';
import {readClientPage} from '../lib/page-update-load';
import {scholarlyRequest} from '../lib/scholarly-client';
import {anysearchRequest} from '../lib/anysearch-client';
import type {PageRevision} from '@aihot/contracts/navigation-updates';
import {AnySearchSettings} from '../components/AnySearchSettings';
import {ServiceRow} from '../components/ServiceRow';
import {ScholarlySettings} from '../components/ScholarlySettings';
import {AI_OUTPUT_TOKENS} from '@aihot/contracts/ai-limits';
import {RuntimeLogs} from '../components/RuntimeLogs';
import {useEffect,useState} from 'react';
import {Link} from 'react-router';
import {aiRequest,type Proposal} from '../lib/ai-client';
import {AIProposal} from '../components/AIProposal';
export const headers=()=>({'Cache-Control':'private, no-store'});
export function meta(){return [{title:'网站设置 · HKIS'},{name:'robots',content:'noindex, nofollow'}]}
const KIMI_CODE='https://api.kimi.com/coding/v1';
const DEFAULT={endpoint:'https://api.openai.com/v1',model:'gpt-5.6-luna',protocol:'responses',reasoning:'xhigh',dailyLimit:20,maxTokens:Number(AI_OUTPUT_TOKENS.default),enabled:false,hasKey:false,encryptionReady:false,revision:0,allowedEndpoints:[] as string[],callsToday:0,testStatus:null as string|null,testedAt:null as string|null,lastTestError:null as string|null};
export default function AISettings(){
 const [pageUpdate,setPageUpdate]=useState<PageRevision|null>(null),[scholarly,setScholarly]=useState<any>(null),[anysearch,setAnysearch]=useState<any>(null);usePageRead(pageUpdate);
 const [config,setConfig]=useState(DEFAULT),[saved,setSaved]=useState(DEFAULT),[apiKey,setApiKey]=useState(''),[removeKey,setRemoveKey]=useState(false),[consent,setConsent]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
 const [network,setNetwork]=useState<any>(null);
 const [prefs,setPrefs]=useState<any>(null),[included,setIncluded]=useState(''),[excluded,setExcluded]=useState(''),[intervals,setIntervals]=useState<Record<string,number>>({}),[proposal,setProposal]=useState<Proposal|null>(null);
 async function loadPrefs(){const p=await aiRequest('preferences');setPrefs(p);setIncluded(p.value.keywords.join('\n'));setExcluded(p.value.excludedKeywords.join('\n'));setIntervals(p.value.sourceIntervals)}
 useEffect(()=>{let active=true;readClientPage('settings',async()=>{const [config,,scholarly,anysearch]=await Promise.all([aiRequest('settings'),loadPrefs(),scholarlyRequest('settings'),anysearchRequest('settings')]);return {config,scholarly,anysearch}}).then(d=>{if(!active)return;setConfig(d.config);setSaved(d.config);setScholarly(d.scholarly);setAnysearch(d.anysearch);setLoaded(true);setPageUpdate(d.pageUpdate)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 const dirty=JSON.stringify(config)!==JSON.stringify(saved)||!!apiKey||removeKey;
 function kimiPreset(){setConfig(c=>({...c,endpoint:KIMI_CODE,model:'kimi-for-coding',protocol:'responses',reasoning:'max'}));setConsent(false);setMessage('Kimi Code 预设已填入，尚未保存；请核对后保存设置。')}
 function edit(key:string,value:unknown){setConfig(c=>({...c,[key]:value}));setMessage('');if(key==='endpoint')setConsent(false)}
 async function save(e:React.FormEvent){e.preventDefault();setBusy('save');setError('');setMessage('');try{const result=await aiRequest('settings',{...config,apiKey:apiKey||undefined,removeKey,confirmedDestination:consent?config.endpoint.replace(/\/+$/,''):null});setConfig(result);setSaved(result);setApiKey('');setRemoveKey(false);setConsent(false);setMessage('设置已保存。API key 不会回显；保存本身不会调用模型。')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function test(){setBusy('test');setError('');setMessage('');try{const r=await aiRequest('test',{requestId:crypto.randomUUID()});setMessage(r.message)}catch(e){setError((e as Error).message)}finally{try{const c=await aiRequest('settings');setConfig(c);setSaved(c)}catch{}setBusy('')}}
 async function diagnoseNetwork(){setBusy('network');setError('');setNetwork(null);try{setNetwork(await aiRequest('network',{requestId:crypto.randomUUID()}))}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function proposeChanges(){setBusy('prefs');setError('');try{const split=(s:string)=>s.split(/\n|,|，/).map(x=>x.trim()).filter(Boolean);const r=await aiRequest('preferences/propose',{value:{keywords:split(included),excludedKeywords:split(excluded),sourceIntervals:intervals}});setProposal(r.proposal)}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <div className="research-page ai-settings"><header className="research-heading"><div><p className="research-eyebrow">HKIS / SETTINGS</p><h1>网站设置</h1><p>模型、学术与联网检索服务，个人研究偏好与运行诊断</p></div><Link to="/research" className="ai-secondary">返回论文</Link></header>
 {error&&<p className="ai-error" role="alert">{error}</p>}{message&&<p className="research-notice" role="status">{message}</p>}
 {!loaded?<section className="research-panel"><p>{error?'设置未加载，请确认已使用站点所有者账号登录，再刷新重试。':'正在安全读取配置…'}</p><a href="/signin-with-chatgpt?return_to=%2Fsettings" target="_top">使用 ChatGPT 登录</a></section>:<>
 <div className="service-list"><ServiceRow testLabel="测试（调用模型）" name="LLM · 第三方模型" endpoint={saved.endpoint} hasKey={saved.hasKey} status={saved.testStatus} busy={!!busy} onTest={test} testDisabled={dirty||!saved.hasKey||!saved.encryptionReady}><form onSubmit={save} className="ai-form"><h2>第三方模型设置</h2><p className="ai-muted">只有站点所有者可以读写配置。API key 加密保存在服务端，模型、聊天记录和浏览器存储均无法读取它。</p>
 <label>API 接入点（Base URL）<input type="url" list="ai-endpoints" value={config.endpoint} onChange={e=>edit('endpoint',e.target.value)} required placeholder="https://api.openai.com/v1"/></label><datalist id="ai-endpoints">{config.allowedEndpoints.map(url=><option key={url} value={url}/>)}</datalist><p className="ai-muted">包括 /v1 等路径，不包含 /responses 或 /chat/completions。仅允许下列公开接入点；其他网关需先加入服务器白名单。</p><div className="ai-endpoints">{config.allowedEndpoints.map(url=><button type="button" key={url} onClick={()=>edit('endpoint',url)}>{new URL(url).hostname}</button>)}</div>
 <button type="button" className="ai-secondary" onClick={kimiPreset}>可选：填入 Kimi Code 预设（Responses / max）</button>{config.endpoint.replace(/\/+$/,'')===KIMI_CODE&&<p className="research-notice">Kimi Code：仅限本人主动发起的对话、分析或连接测试，不用于无人值守的批量 AI 分析。普通论文采集不调用模型；自动 AI 管线需另配适用的开放平台 API。<a href="https://www.kimi.com/code/docs/en/kimi-code/community-guidelines.html" target="_blank" rel="noreferrer">使用范围</a> · <a href="https://www.kimi.com/code/docs/en/third-party-tools/codex.html" target="_blank" rel="noreferrer">Responses 兼容说明</a>。本站以真实 HKIS 身份请求；供应商拒绝时不会冒充其他客户端。</p>}
 <div className="ai-two-columns"><label>接口协议<select value={config.protocol} onChange={e=>edit('protocol',e.target.value)}><option value="responses">Responses（OpenAI 推荐）</option><option value="chat_completions">Chat Completions（兼容接入点）</option></select></label><label>模型名称<input value={config.model} onChange={e=>edit('model',e.target.value)} maxLength={120} required spellCheck={false}/></label></div>
 <div className="ai-two-columns"><label>思考等级<select value={config.reasoning} onChange={e=>edit('reasoning',e.target.value)}>{['none','low','medium','high','xhigh','max'].map(v=><option key={v}>{v}</option>)}</select></label><label>单次输出上限（含思考 tokens）<input type="number" min={AI_OUTPUT_TOKENS.min} max={AI_OUTPUT_TOKENS.max} step={1} required aria-describedby="output-token-help" value={config.maxTokens} onChange={e=>edit('maxTokens',Number(e.target.value))}/></label></div><p className="ai-muted" id="output-token-help">可设 1,024–1,048,576 的整数，默认仍为 4,096；已有配置不会自动提高。这是每次请求的输出预算（含供应商计入的思考 tokens），不是上下文窗口大小。请按模型的实际最大输出能力设置，供应商仍可能拒绝过高数值。提高预算可能明显增加费用。</p><p className="ai-muted"><a href="https://developers.openai.com/api/docs/models/gpt-5.6-luna" target="_blank" rel="noreferrer">gpt-5.6-luna / xhigh 官方支持说明</a> · 其他接入点需验证模型、思考参数和工具兼容性。不会自动更换模型或降低思考等级。</p>
 <label>API key <span className="ai-muted">{config.hasKey?'已加密保存 · 留空保留现有凭证':'尚未配置'}</span><input type="password" value={apiKey} onChange={e=>{setApiKey(e.target.value);setRemoveKey(false);setConsent(false)}} autoComplete="off" spellCheck={false} disabled={!config.encryptionReady} placeholder={config.encryptionReady?'粘贴该接入点的 API key':'安全存储待配置，暂不能输入凭证'} maxLength={4096}/></label>
 {!config.encryptionReady&&<p className="ai-error">安全存储未就绪。可以先保存接入点和模型，API key 保存与 AI 调用暂不可用。</p>}
 {config.hasKey&&<label className="ai-check"><input type="checkbox" checked={removeKey} onChange={e=>{setRemoveKey(e.target.checked);if(e.target.checked){setApiKey('');edit('enabled',false)}}}/>移除已保存的 API key 并关闭 AI（保存后生效）</label>}
 {apiKey&&<label className="ai-check ai-consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} required/>确认此凭证用于 {config.endpoint}；测试或使用 AI 时，问题及检索到的论文元数据/摘要会发送给该接入点。请先核对地址。</label>}
 <div className="ai-two-columns"><label>每日模型请求上限（UTC）<input type="number" min={1} max={100} value={config.dailyLimit} onChange={e=>edit('dailyLimit',Number(e.target.value))}/></label><div className="ai-usage"><strong>{saved.callsToday} / {saved.dailyLimit}</strong><span>今日已尝试 / 已保存限额</span></div></div>
 <label className="ai-check"><input type="checkbox" checked={config.enabled} onChange={e=>edit('enabled',e.target.checked)} disabled={removeKey||!config.encryptionReady}/>启用按需 AI 助手，允许将我的提问和检索到的论文摘要发送给上方接入点</label><p className="ai-muted">打开页面不会调用模型。每次对话：同一工具和相同参数最多连续 5 次，同一工具最多连续 15 次，全部工具最多累计 200 次尝试；达到对应上限后不再执行下一次。并行返回的调用按列表顺序计数，跨模型轮次累计；缓存命中、无效参数也计数。重复读取或相同配置建议会复用，不重复写入。连接测试计 1 次模型请求。每分钟最多 6 次模型请求、每日额度仍按保存值执行，200 次工具上限不保证全部用满。完整输入上限 256 KiB，任务结果与证据上限 2 MiB，最多 201 个模型轮次（含最后无工具回答）；先遇到独立限制会保留部分结果和停止原因。失败和超时也计入限额，费用以供应商账单为准。没有自动批量分析。每次请求仍限时 90 秒、响应最多 1,000,000 字节；回答正文最多显示 12,000 字符，超出会标注截断。较大的 token 设置不保证能接收或显示同等长度的回答。</p>
 <p className="ai-muted">网络诊断只从服务器向已保存接入点发送一次空的无凭证请求，不读取或使用 API key、不发送模型名或论文、不会跟随重定向。</p><button className="ai-secondary" type="button" onClick={diagnoseNetwork} disabled={!!busy||dirty||!saved.revision}>{busy==='network'?'网络诊断中…':'网络诊断（不使用密钥）'}</button>{network&&<p className="research-notice" role="status">{network.message}<br/>本次诊断的已保存接入点：{network.testedEndpoint} · {network.testedProtocol}<br/>HTTP {network.httpStatus??'未收到'} · 内容 {network.contentKind||'未知'} · 分类 {network.bodyClass||network.transport||'未知'}{network.reference&&<> · 诊断标识 {network.reference}</>}</p>}<div className="ai-actions"><button className="research-primary" disabled={!!busy} type="submit">{busy==='save'?'保存中…':'保存设置'}</button><button className="ai-secondary" type="button" onClick={test} disabled={!!busy||dirty||!saved.hasKey||!saved.encryptionReady}>{busy==='test'?'验证中，可能需 90 秒…':'测试连接（会调用模型）'}</button></div><p className="ai-muted">{dirty?'修改尚未保存，请先保存后测试':saved.testStatus==='ok'?`最近测试成功：${saved.testedAt}`:saved.testStatus==='failed'?`最近测试未通过：${saved.testedAt}`:'尚未进行实际连接测试'}</p>{saved.testStatus==='failed'&&<p className="research-notice" role="status">{saved.lastTestError||'上次测试来自旧版本，未保留具体错误。请主动再测试一次以获取诊断；可能再次计费。'}</p>}</form></ServiceRow><ScholarlySettings initialData={scholarly}/><AnySearchSettings initialData={anysearch}/></div>
 {prefs&&<section className="research-panel ai-form"><h2>关键词与信源频次</h2><p className="ai-muted">关键词用于 AI 检索与筛选，不改动已有论文或原有规则分。采集间隔是期望配置；实际自动任务状态单独核实。</p><div className="ai-two-columns"><label>关注关键词<textarea rows={5} value={included} onChange={e=>setIncluded(e.target.value)} placeholder={'TCAD\nimage sensor\nferroelectric'}/></label><label>排除关键词<textarea rows={5} value={excluded} onChange={e=>setExcluded(e.target.value)} placeholder="每行一个，或逗号分隔"/></label></div><p className="ai-muted">已配置 {prefs.sources.length} 本期刊，覆盖 IEEE、Wiley、Elsevier、Nature 与 Science / AAAS。新增期刊仅入库匹配关注方向的公开元数据；RSS 范围有限，不代表完整目录。<Link to="/research">查看来源、字段覆盖与采集记录</Link></p><div className="ai-sources">{prefs.sources.map((s:any)=><label key={s.id}>{s.name}<span><input aria-label={s.name+' 期望间隔小时'} type="number" min={1} max={168} value={intervals[s.id]??12} onChange={e=>setIntervals(v=>({...v,[s.id]:Number(e.target.value)}))}/>小时</span></label>)}</div><p className={prefs.scheduler?.enabled?"research-notice":"ai-error"}>{prefs.scheduler?.message||'尚未获得调度状态'}{prefs.scheduler?.verifiedAt&&<> 最近核实：{prefs.scheduler.verifiedAt}</>}{prefs.scheduler?.nextRun&&<>；下次：{prefs.scheduler.nextRun}</>}</p><button className="ai-secondary" disabled={!!busy} onClick={proposeChanges}>预览配置变更</button>{proposal&&<AIProposal key={proposal.id} proposal={proposal} onResolved={()=>{loadPrefs().catch(e=>setError(e.message))}}/>}</section>}
 <NavigationUpdateSettings/>
 <RuntimeLogs/>
 </>}
 </div>
}
