import {PaperSelection,PaperBulkToolbar,PaperCardState,PaperSourceLink} from '../components/PaperReader';
import {PUBLISHERS,RESEARCH_SOURCES} from '../../../../sites/research-config.ts';
import {Form,Link,useLoaderData,useRevalidator,type LoaderFunctionArgs} from 'react-router';
import {loadOr404} from '../lib/api.server';
import {SITE} from '@aihot/industry/site';
import type {buildWeeklyDigest,RankedPaper} from '../../../../sites/weekly.ts';
import type {JournalMetric} from '../../../../sites/journal-metrics.ts';
type Digest=ReturnType<typeof buildWeeklyDigest>;
export async function loader({request}:LoaderFunctionArgs){return loadOr404<Digest>('/api/site/research/weekly'+new URL(request.url).search,{signal:request.signal});}
export const headers=()=>({'Cache-Control':'no-store'});
export function meta(){return [{title:`本周论文热点 · ${SITE.name}`},{name:'description',content:'近七日论文按已核实的期刊影响因子排序，关键词合并与可追溯的摘要证据。'},{name:'robots',content:'noindex, nofollow'}];}
const time=(s:string|null)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+' UTC+08:00':'尚未采集';
function Citation({paper}:{paper:RankedPaper}){return <PaperSourceLink paperId={paper.id} className="weekly-citation" href={paper.url} target="_blank" rel="noreferrer" title={paper.title} aria-label={`参考文献 ${paper.reference}：${paper.title}`}>[{paper.reference}]</PaperSourceLink>;}
function Metric({metric}:{metric:JournalMetric}){return metric.status==='verified'&&metric.value!=null&&metric.year&&metric.sourceUrl?<a href={metric.sourceUrl} target="_blank" rel="noreferrer" className="weekly-metric" title={`核实于 ${metric.verifiedAt}；点击官方来源`}>JIF {metric.value.toFixed(1)} <span>({metric.year})</span></a>:<span className="weekly-metric weekly-missing">JIF 未核实</span>;}
function PaperCard({p}:{p:RankedPaper}){return <PaperCardState id={p.id} title={p.title} anchor={'paper-'+p.id} className="weekly-paper"><div className="weekly-paper-top"><span className="weekly-rank">{String(p.reference).padStart(2,'0')}</span><div><p className="weekly-journal">{p.journal} · {p.publisher}</p><p className="weekly-meta">{p.publicationDate} · {p.dateBasis}</p></div><Metric metric={p.metric}/></div><h3><Link to={p.detailUrl}>{p.title}</Link><Citation paper={p}/></h3><dl className="weekly-breakdown"><div><dt>研究对象</dt><dd>{p.extractedKeywords.join(' · ')||'仅匹配领域标签，未提取到细分关键词'}<small>规则提取，非作者关键词</small></dd></div><div><dt>摘要证据</dt><dd>{p.evidence?<><span lang="en">“{p.evidence.text}{p.evidence.truncated?'…':''}”</span><Citation paper={p}/><small>{p.evidence.kind==='result'?'摘要选句（命中结果词）':'摘要选句（背景 / 方法）'} · {p.abstractSource||'来源未标注'}{p.evidence.truncated?' · 节选未包含完整结论':''}</small></>:<span className="weekly-no-evidence">当前无可用摘要，仅列题名和元数据；未生成进展结论</span>}</dd></div><div><dt>作者关键词</dt><dd>{p.keywords.length?p.keywords.join(' · '):'来源未提供'}</dd></div></dl><div className="weekly-links"><Link to={p.detailUrl+'#abstract'}>查看摘要与证据</Link><PaperSourceLink paperId={p.id} href={p.url} target="_blank" rel="noreferrer">对应论文原文</PaperSourceLink></div></PaperCardState>;}
export default function Hot(){const d=useLoaderData<typeof loader>();const revalidator=useRevalidator();const byId=new Map(d.papers.map(p=>[p.id,p]));const refs=(ids:string[])=>ids.map(id=>byId.get(id)).filter((p):p is RankedPaper=>!!p).map(p=><Citation key={p.id} paper={p}/>);const known=d.papers.filter(p=>p.metric.status==='verified'),unknown=d.papers.filter(p=>p.metric.status!=='verified');
 return <PaperSelection ids={d.papers.map(p=>p.id)} scopeKey={JSON.stringify(d.filters)}><main className="research-page weekly-page"><header className="research-heading"><div><p className="research-eyebrow">HKIS / WEEKLY RESEARCH</p><h1>本周论文热点</h1><p>{d.window.startDate} 至 {d.window.endDate} · {d.window.offset} · 含今天的近 7 个自然日</p></div><button className="research-primary" onClick={()=>revalidator.revalidate()} disabled={revalidator.state!=='idle'}>{revalidator.state!=='idle'?'重算中…':'重算本周报告'}</button></header>
 <div className="weekly-scope">先进逻辑 · DRAM · NAND · 新型器件 · 工艺机理 · 图像传感器 · TCAD</div>
 <div className="research-stats"><div><b>{d.coverage.shown}</b><span>本周匹配论文</span></div><div><b>{d.coverage.withJif}/{d.coverage.shown}</b><span>期刊 JIF 已核实</span></div><div><b>{d.coverage.withAbstract}/{d.coverage.shown}</b><span>有摘要可供拆解</span></div><div><b>{d.groups.length}</b><span>合并领域 · 可交叉归组</span></div></div>
 <Form method="get" className="research-filters" key={d.filters.topic+d.filters.publisher}><label>研究方向<select name="topic" defaultValue={d.filters.topic}><option value="">全部研究方向</option>{d.topics.map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</select></label><label>出版商<select name="publisher" defaultValue={d.filters.publisher}><option value="">全部出版商</option>{PUBLISHERS.map(p=><option key={p}>{p}</option>)}</select></label><button className="research-primary" type="submit">应用筛选</button>{(d.filters.topic||d.filters.publisher)&&<Link className="research-back" to="/hot">清除筛选</Link>}</Form>
 <p className="weekly-updated">最近采集：{time(d.lastCollectedAt)}<br/>报告计算：{time(d.window.generatedAt)}。重算只读取已入库数据，<Link to="/research">检查新论文</Link>会更新信源。</p>
 <nav className="weekly-jump" aria-label="本周报告内容"><a href="#weekly-digest">领域进展摘要</a><a href="#weekly-ranking">JIF 论文榜</a><a href="#weekly-method">方法与来源</a></nav>
 <section id="weekly-digest" className="weekly-section"><div className="weekly-section-title"><h2>本周领域进展摘要</h2><span>证据摘录版 · 未调用 AI 模型</span></div><p className="weekly-intro">按题名、摘要中的关键词合并研究主题，提取可核对的原文证据。跨论文只汇总共同关注点，不推断共识、突破程度或因果关系。</p>
 {!d.papers.length?<div className="research-empty"><h3>这个时间窗与筛选条件下暂无可用论文</h3><p>当前已入库数据中，本周全部研究方向共 {d.coverage.inScopeWeekly} 篇。日期缺失、仅有月份或未来发表日的记录不会充当本周新论文。</p><Link className="research-back" to="/research">查看论文库与信源状态</Link></div>:<div className="weekly-groups">{d.groups.map(g=><article key={g.id} className="research-card weekly-group"><div className="weekly-group-heading"><h3>{g.label}</h3><span>{g.total} 篇 · {g.withAbstract} 篇有摘要</span></div><p className="weekly-group-summary">本周有 {g.total} 篇论文匹配该主题，{g.withAbstract} 篇提供摘要证据。{refs(g.paperIds)}</p>{g.keywordGroups.length>0&&<div className="weekly-keywords"><p>关键词合并（系统提取）</p>{g.keywordGroups.map(k=><div key={k.label}><strong>{k.label}</strong><span>{k.count} 篇</span>{refs(k.paperIds)}</div>)}</div>}
 <ul className="weekly-evidence">{g.evidence.map(e=>{const p=byId.get(e.paperId)!;return <li key={e.paperId}><p><span lang="en">“{e.text}{e.truncated?'…':''}”</span><Citation paper={p}/></p><div><span>{e.kind==='result'?'摘要选句（结果词匹配）':'摘要选句（背景 / 方法）'} · {p.abstractSource||'来源未标注'}</span><Link to={p.detailUrl+'#abstract'}>核对完整摘要</Link></div></li>})}</ul>{!g.evidence.length&&<p className="weekly-no-evidence">该组暂无摘要，不能可靠提炼研究结果。</p>}{g.withoutAbstract.length>0&&<p className="weekly-metadata-only">仅题名 / 元数据待核对：{refs(g.withoutAbstract)}。未据此生成研究结论。</p>}{g.withAbstract>g.evidence.length&&<p className="weekly-meta">此处节选 JIF 排序靠前的 {g.evidence.length} 篇证据，其余见下方论文拆解</p>}</article>)}</div>}</section>
 <section id="weekly-ranking" className="weekly-section"><div className="weekly-section-title"><h2>JIF 论文榜与逐篇拆解</h2><span>{d.papers.length} 篇</span></div><p className="weekly-intro">按各期刊已核实的 Journal Impact Factor 降序；同值按发表日降序。JIF 是期刊层面指标，不代表单篇质量。每条指标标注统计年并链接官方来源。</p><PaperBulkToolbar/><div className="research-list">{known.map(p=><PaperCard p={p} key={p.id}/>)}</div>{unknown.length>0&&<div className="weekly-unknown"><h3>JIF 尚未核实 · 单列 {unknown.length} 篇</h3><p>不以 0 分代替；按发表日降序列出，等待核实期刊指标与年度</p><div className="research-list">{unknown.map(p=><PaperCard p={p} key={p.id}/>)}</div></div>}{!d.papers.length&&<p className="research-empty">暂无符合条件的本周论文</p>}</section>
 <details id="weekly-method" className="research-panel weekly-method"><summary>统计方法、JIF 来源与数据缺口</summary><p>{d.window.dateSemantics}。优先采用 Crossref 的在线发表日；否则采用来源提供的明确年月日。若在线日期仅精确到月/年，保留不确定性，不用发现时间替代。未来日期不进入榜单。</p><p>本周范围内共 {d.coverage.inScopeWeekly} 篇符合研究主题，当前筛选显示 {d.coverage.shown} 篇。全库领域相关记录中：日期缺失或精度不足 {d.exclusions.missingOrImpreciseDate} 篇，未来日期 {d.exclusions.futureDate} 篇，早于窗口 {d.exclusions.outsideWindow} 篇。范围仅为 {RESEARCH_SOURCES.length} 本已配置期刊，并非全领域论文普查。</p><p>分组允许一篇论文出现在多个领域，组内去重计数。系统标签来自公开题名 / 摘要 / 实际作者关键词的可解释词匹配；作者关键词覆盖 {d.coverage.withAuthorKeywords}/{d.coverage.shown}。共同关键词只表示内容重叠，不表示研究结果相互验证。</p><p>证据句从实际摘要按结果词、数字、主题匹配选择，最多摘录 25 个词，省略以“…”标注；保留英文原句。选句不能替代全文审读，也不会从缺失摘要生成结论。此报告是规则归组和抽取式摘要，不是模型生成的深度综合评价。</p><p>指标以核实时官方可见、明确年份的 JIF 为准；可能落后于最新 JCR，不同年份不宜直接比较。未采用 CiteScore、SJR 或五年 JIF。摘要版权仍属于原作者 / 出版商，本站不采集付费全文。</p><ul className="weekly-metric-sources">{d.metrics.map(m=><li key={m.sourceId}><strong>{m.name}</strong><Metric metric={m}/>{m.status!=='verified'&&m.sourceUrl&&<a href={m.sourceUrl} target="_blank" rel="noreferrer">查看核实来源</a>}<span>{m.evidence} · 核实 {m.verifiedAt}</span></li>)}</ul><p>版本 {d.version}。打开此页、重算或采集后重新访问都会基于当前数据库计算；此机制不建立定时采集，自动更新状态以<Link to="/research">论文情报</Link>页为准。</p></details>
 </main></PaperSelection>;
}
