import {invalidateReadingCache} from '../lib/reading-cache';
import {cachedRouteLoader} from '../lib/reading-cache';
export const clientLoader=cachedRouteLoader;
import {usePageRead} from '../components/NavigationUpdates';
import {isPageOverview} from '@aihot/contracts/navigation-updates';
import {useMemo,useState} from 'react';
import {Form,Link,useLoaderData,useLocation,useRevalidator,type LoaderFunctionArgs} from 'react-router';
import {RailDisclosure} from '../components/ui/AdaptiveRail';
import {ControlReadingLayout} from '../components/ui/ControlReadingLayout';
import {PaperSelection,PaperBulkToolbar,PaperCardState,PaperSourceLink} from '../components/PaperReader';
import {PUBLISHERS} from '../../../../sites/research-config.ts';
import type {KeywordMap} from '../../../../sites/keyword-map.ts';
import {loadOr404,withPageUpdate} from '../lib/api.server';
import {SITE} from '@aihot/industry/site';
type Keyword=KeywordMap['keywords'][number];
export async function loader({request}:LoaderFunctionArgs){return withPageUpdate('hot',()=>loadOr404<KeywordMap>('/api/site/research/keyword-map'+new URL(request.url).search,{signal:request.signal}));}
export const headers=()=>({'Cache-Control':'no-store'});
export function meta(){return [{title:`关键词热点分布 · ${SITE.name}`},{name:'description',content:'近七日更新论文的关键词数量、阅读优先级与逐篇分数分布。全量统计，悬停联动。'},{name:'robots',content:'noindex, nofollow'}];}
const num=(n:number|null)=>n===null?'未评分':Number.isInteger(n)?String(n):n.toFixed(1);
const sourceNames={author:'作者关键词','publisher-index':'供应商索引','openalex-keyword':'OpenAlex 索引词','openalex-topic':'OpenAlex 主题',ai:'AI 提取',derived:'规则提取'};
const time=(s:string|null)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'暂无';
export function keywordSummary(k:Keyword){return `${k.label}：${k.count} 篇，中位数 ${num(k.median)}，四分位区间 ${num(k.q1)}–${num(k.q3)}，范围 ${num(k.min)}–${num(k.max)}，已评分 ${k.scored}，未评分 ${k.unscored}`;}
export function histogram(papers:KeywordMap['papers']){const bins=Array.from({length:11},(_,i)=>({label:i===10?'未评分':`${i*10}–${i===9?100:i*10+9}`,count:0}));for(const p of papers)bins[p.score===null?10:Math.min(9,Math.floor(p.score/10))]!.count++;return bins;}
export function KeywordExplorer({d}:{d:KeywordMap}){
 const [hover,setHover]=useState<string|null>(null),[pinned,setPinned]=useState<string|null>(null),[search,setSearch]=useState(''),[linear,setLinear]=useState(false),[showPapers,setShowPapers]=useState(false),[showUnclassified,setShowUnclassified]=useState(false);
 const active=hover??pinned,keyword=d.keywords.find(k=>k.id===active),selected=useMemo(()=>new Set(keyword?.paperIds||[]),[keyword]),shown=keyword?d.papers.filter(p=>selected.has(p.id)):d.papers;
 const pinnedKeyword=d.keywords.find(k=>k.id===pinned),drillPapers=pinnedKeyword?d.papers.filter(p=>pinnedKeyword.paperIds.includes(p.id)):d.papers;
 const allBins=useMemo(()=>histogram(d.papers),[d.papers]),chosenBins=useMemo(()=>histogram(shown),[shown]);
 const plotted=d.keywords.filter(k=>showUnclassified||k.id!=='unclassified');
 const maxCount=Math.max(2,...plotted.map(k=>k.count));
 const scale=(n:number)=>linear?n/maxCount:Math.log10(Math.max(1,n))/Math.log10(maxCount);
 const x=(n:number)=>70+scale(n)*640,y=(n:number|null)=>n===null?316:270-n*2.2;
 const ticks=linear?[0,Math.round(maxCount/4),Math.round(maxCount/2),Math.round(maxCount*3/4),maxCount]:[1,2,5,10,20,50,100,200,500,1000,2000,5000,10000].filter(n=>n<=maxCount);
 const pin=(id:string)=>setPinned(p=>p===id?null:id),reset=()=>{setPinned(null);setHover(null)};
 const matchingKeywords=d.keywords.filter(k=>k.label.toLowerCase().includes(search.toLowerCase()));
 const keywordEvents=(id:string)=>({onMouseEnter:()=>setHover(id),onMouseLeave:()=>setHover(null),onFocus:()=>setHover(id),onBlur:()=>setHover(null),onClick:()=>pin(id)});
 return <PaperSelection ids={drillPapers.map(p=>p.id)} scopeKey={JSON.stringify(d.filters)+String(pinned)}><main className="research-page keyword-page" onKeyDown={e=>{if(e.key==='Escape')reset()}}>
 <header className="research-heading"><div><p className="research-eyebrow">HKIS / KEYWORD OBSERVATORY</p><h1>关键词热点分布</h1><p>{d.window.startDate} 至 {d.window.endDate} · UTC+08 · 近 7 个自然日</p></div><Link className="research-back" to="/research">论文库 ↗</Link></header>
 <div className="keyword-coverage" aria-label="全量统计覆盖"><div><b>{d.coverage.shown.toLocaleString()}</b><span>{d.filters.basis==='publication'?'窗口内发表':'窗口内更新'}论文 · 去重</span></div><div><b>{d.keywords.filter(k=>k.id!=='unclassified').length}</b><span>关键词 · 可交叉归组</span></div><div><b>{d.coverage.scored.toLocaleString()} <small>/ {d.coverage.shown.toLocaleString()}</small></b><span>当前指标有评分</span></div><div><b>{d.coverage.unclassified.toLocaleString()}</b><span>未分类 · 仍纳入统计</span></div></div>
 <ControlReadingLayout label="窗口与关键词" summary={`${d.coverage.shown} 篇 · ${keyword?.label||'全部关键词'}`} rail={<>
 <details className="reading-filter-card keyword-filter-details"><summary>统计口径 · {d.filters.basis==='publication'?'发表日':d.filters.basis==='collection'?'入库日':'实质更新'} / {d.filters.metric==='ai'?'AI':'规则'}</summary><Form method="get" preventScrollReset className="research-filters" key={JSON.stringify(d.filters)}>
 <label>日期依据<select name="basis" defaultValue={d.filters.basis}><option value="updated">首次入库 / 实质更新</option><option value="publication">来源发表日</option><option value="collection">首次入库日</option></select></label>
 <label>纵轴指标<select name="metric" defaultValue={d.filters.metric}><option value="rule">规则阅读优先级</option><option value="ai">AI 重要性（摘要暂评）</option></select></label>
 <label>研究方向<select name="topic" defaultValue={d.filters.topic}><option value="">全部方向（含未分类）</option>{d.topics.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>
 <label>出版商<select name="publisher" defaultValue={d.filters.publisher}><option value="">全部出版商</option>{PUBLISHERS.map(p=><option key={p}>{p}</option>)}</select></label>
 <button className="research-primary" type="submit">应用口径</button><Link className="research-back" to="/hot">清除筛选</Link></Form></details>
 <section className="keyword-legend"><div className="keyword-legend-heading"><h2>全部关键词</h2><button type="button" onClick={reset} disabled={!active}>重置</button></div><label className="keyword-search">查找关键词<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="例如 TCAD / DRAM"/></label><p>悬停高亮 · 点击固定 · Esc 重置<br/>查找只缩小列表，不改变统计</p><div className="keyword-legend-list">{matchingKeywords.slice(0,5).map(k=><button type="button" key={k.id} {...keywordEvents(k.id)} aria-pressed={pinned===k.id} aria-label={keywordSummary(k)} className={active===k.id?'is-active':''}><span>{k.label}</span><b>{k.count}</b></button>)}</div>{matchingKeywords.length>5&&<RailDisclosure title={`其余关键词 · ${matchingKeywords.length-5}`}><div className="keyword-legend-list">{matchingKeywords.slice(5).map(k=><button type="button" key={k.id} {...keywordEvents(k.id)} aria-pressed={pinned===k.id} aria-label={keywordSummary(k)} className={active===k.id?'is-active':''}><span>{k.label}</span><b>{k.count}</b></button>)}</div></RailDisclosure>}{!matchingKeywords.length&&<p>没有匹配关键词</p>}</section>
 </>}>
 <section className="keyword-overview" aria-labelledby="keyword-scatter-title"><div className="keyword-section-heading"><h2 id="keyword-scatter-title">数量 × {d.metric.label}</h2><label className="keyword-scale"><input type="checkbox" checked={showUnclassified} onChange={e=>setShowUnclassified(e.target.checked)}/>图中包含未分类</label><label className="keyword-scale"><input type="checkbox" checked={linear} onChange={e=>setLinear(e.target.checked)}/>线性数量轴</label></div>
 <p className="keyword-caption">每点一个关键词 · 纵轴为已评分论文的中位数 · 竖线为中间 50% 区间</p>
 <svg className="keyword-scatter" viewBox="0 0 780 370" role="group" aria-label="关键词数量与重要性散点图" data-point-count={plotted.length}>
 <text x="70" y="24" className="chart-axis-label">{d.metric.label} · 0–100</text>
 {[0,25,50,75,100].map(v=><g key={v}><line x1="70" x2="710" y1={y(v)} y2={y(v)} className="chart-grid"/><text x="54" y={y(v)+5} textAnchor="end">{v}</text></g>)}
 {[...new Set(ticks)].map(v=><g key={v}><line x1={x(v)} x2={x(v)} y1="50" y2="270" className="chart-grid chart-grid-vertical"/><text x={x(v)} y="292" textAnchor="middle">{v}</text></g>)}
 <line x1="70" x2="710" y1="270" y2="270" className="chart-axis"/><line x1="70" x2="70" y1="50" y2="270" className="chart-axis"/>
 <line x1="70" x2="710" y1="316" y2="316" className="chart-unknown-line"/><text x="54" y="322" textAnchor="end">未评分</text>
 {plotted.map(k=><g key={k.id} className={'keyword-point'+(active&&active!==k.id?' is-dimmed':'')+(active===k.id?' is-active':'')} data-keyword={k.id} data-count={k.count} data-median={k.median??'unknown'} role="button" tabIndex={0} aria-label={keywordSummary(k)} aria-pressed={pinned===k.id} {...keywordEvents(k.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pin(k.id);}}}>
 {k.q1!==null&&k.q3!==null&&<line x1={x(k.count)} x2={x(k.count)} y1={y(k.q1)} y2={y(k.q3)} className="keyword-whisker"/>}<circle cx={x(k.count)} cy={y(k.median)} r={active===k.id?8:6} className={k.id==='unclassified'?'keyword-unclassified':''}/><circle cx={x(k.count)} cy={y(k.median)} r="15" fill="transparent" stroke="none"/>
 {active===k.id&&<text x={x(k.count)+(x(k.count)>550?-13:13)} y={y(k.median)-12} textAnchor={x(k.count)>550?'end':'start'} className="keyword-point-label">{k.label}</text>}
 </g>)}<text x="390" y="356" textAnchor="middle" className="chart-axis-label">{d.filters.basis==='publication'?'发表':'更新'}论文数量（篇） · {linear?'线性刻度':'对数刻度'}</text></svg>
 <div className="keyword-inspector" role="status" aria-live="polite" aria-atomic="true">{keyword?<><div><strong>{keyword.label}</strong><span>{pinned===keyword.id?'已固定':'悬停 / 焦点预览'} · {keyword.sources.map(s=>sourceNames[s]).join(' + ')||'未匹配关键词'}</span></div><p><b>{keyword.count} 篇</b> · 中位数 {num(keyword.median)} · 中间 50% {num(keyword.q1)}–{num(keyword.q3)} · 全范围 {num(keyword.min)}–{num(keyword.max)}<br/>已评分 {keyword.scored} · 未评分 {keyword.unscored} · 窗口内发表 {keyword.publishedCount}</p></>:<><div><strong>指向关键词，查看它的论文分布</strong><span>图中圆点或右侧关键词都可以操作</span></div><p>{d.metric.description}</p></>}</div>
 {!d.papers.length&&<p className="research-empty">当前窗口和筛选下没有论文。可清除筛选或切换日期依据。</p>}
 </section>
 <section className="keyword-distribution" aria-labelledby="keyword-distribution-title"><div className="keyword-section-heading"><h2 id="keyword-distribution-title">逐篇分数分布</h2><span>{keyword?`${keyword.label} · ${shown.length} 篇`:`全部 ${d.papers.length} 篇`}</span></div><p className="keyword-caption">{keyword?`橙色：关键词内占比（${shown.length} 篇）；淡色：全窗口占比（${d.papers.length} 篇），分母各自独立`:'每篇论文仅计一次；柱高为全窗口占比，柱顶标篇数；未评分单列'} · 分箱左含右不含，最后一箱含 100</p>
 <svg className="keyword-histogram" viewBox="0 0 780 190" role="img" aria-label={`逐篇分数分布：${chosenBins.map(b=>b.label+(b.label==='未评分'?'':'分')+' '+b.count+'篇').join('，')}`}><text x="40" y="19">占比</text>{[0,50,100].map((v,i)=><g key={i}><line x1="65" x2="735" y1={145-v} y2={145-v} className="chart-grid"/><text x="52" y={150-v} textAnchor="end">{v}%</text></g>)}{allBins.map((b,i)=><g key={b.label}><rect x={68+i*61} y={145-b.count/Math.max(1,d.papers.length)*100} width="48" height={b.count/Math.max(1,d.papers.length)*100} className={active?'distribution-background is-dimmed':'distribution-background'}/>{active&&<rect data-selected-bin={i} data-count={chosenBins[i]!.count} x={68+i*61} y={145-chosenBins[i]!.count/Math.max(1,shown.length)*100} width="48" height={chosenBins[i]!.count/Math.max(1,shown.length)*100} className="distribution-selected"/>}<text x={92+i*61} y={139-(active?chosenBins[i]!.count/Math.max(1,shown.length):b.count/Math.max(1,d.papers.length))*100} textAnchor="middle" className="distribution-value">{active?chosenBins[i]!.count:b.count}</text><text x={92+i*61} y="170" textAnchor="middle" className={i%2===1?'distribution-label-alternate':''}>{b.label}</text></g>)}</svg>
 <p className="keyword-footnote">一篇可归属多个关键词，关键词篇数不能相加作为总量。当前窗口内实际发表 {d.coverage.publishedInWindow} 篇；其余可能是旧论文新入库或元数据更新。</p>
 </section>
 <details className="research-panel keyword-data-table"><summary>关键词数据表（{d.keywords.length} 组，完整无分页）</summary><div className="keyword-table-scroll"><table><thead><tr><th>关键词</th><th>篇数</th><th>中位数</th><th>中间 50%</th><th>未评分</th><th>来源</th></tr></thead><tbody>{d.keywords.map(k=><tr key={k.id}><th><button type="button" {...keywordEvents(k.id)} aria-pressed={pinned===k.id}>{k.label}</button></th><td>{k.count}</td><td>{num(k.median)}</td><td>{num(k.q1)}–{num(k.q3)}</td><td>{k.unscored}</td><td>{k.sources.map(s=>sourceNames[s]).join(' / ')||'未分类'}</td></tr>)}</tbody></table></div></details>
 <section className="research-panel keyword-paper-section"><button type="button" className="keyword-disclosure" onClick={()=>setShowPapers(p=>!p)} aria-expanded={showPapers} aria-controls="keyword-paper-list">{showPapers?'收起':'展开'}{pinnedKeyword?'关联':'全部'}论文 · {drillPapers.length} 篇 <span>{pinnedKeyword?.label||'当前窗口 · 点击关键词可固定关联列表'}</span></button>{showPapers&&<div id="keyword-paper-list"><PaperBulkToolbar scopeLabel="当前结果"/><div className="keyword-paper-list">{drillPapers.map(p=><PaperCardState key={p.id} id={p.id} title={p.title} className="keyword-paper"><div><h3><Link to={p.detailUrl}>{p.title}</Link></h3><p>{p.journal} · {d.metric.label} {num(p.score)} · {p.hasAbstract?'有摘要':'当前无可用摘要'}</p><p>发表 {p.publicationDate||'日期未明确'} · 入库 {time(p.firstSeen)} · 更新 {time(p.updatedAt)}</p><p>{p.keywords.map(k=>k.label).join(' · ')||'未分类'}<br/>{p.scoreSource}{p.scoreReason?'：'+p.scoreReason:''}</p>{p.jif.status==='verified'?<p>期刊 JIF {p.jif.value}（{p.jif.year}）· <a href={p.jif.sourceUrl!} target="_blank" rel="noreferrer">官方来源</a> · 不代表单篇质量</p>:<p>JIF 尚未核实</p>}<PaperSourceLink paperId={p.id} href={p.url} target="_blank" rel="noreferrer">论文原文 ↗</PaperSourceLink></div></PaperCardState>)}</div></div>}</section>
 <details className="research-panel keyword-method"><summary>统计依据与覆盖边界</summary><p>{d.window.dateSemantics}。窗口从 {time(d.window.startAt)} 到计算时刻 {time(d.window.endAt)}（UTC+08）。发表日模式使用来源明确的年月日，优先在线发表日，不以入库时间代替；缺失日期不进入发表日窗口。</p><p>统计读取窗口内的全部已入库记录，不受论文列表页码、分数、摘要或 JIF 完整度限制。本窗口去重前排除 {d.coverage.excludedNonResearch} 条标记为非研究内容的审计记录；合并重复身份 {d.coverage.duplicates} 条。全窗口 {d.coverage.windowUnique} 篇，当前筛选 {d.coverage.shown} 篇、{d.coverage.journals} 本期刊。不是全领域的发表普查。</p><p>DOI 优先，其次规范原文 URL 去重；同一论文内同义词只计一次。仅合并明确同义名，铁电与 FeFET、忆阻器与 RRAM 等仍分别保留。每篇按作者词、供应商索引词、OpenAlex 索引词/主题、已有有效 AI、规则证据的顺序，去重取前三个有效词；不足三词不补造。OpenAlex 为机器索引，非作者原词。关键词来源包括作者（{d.coverage.withAuthorKeywords} 篇有提供）、当前有效 AI 摘要提取和可解释规则提取；没有关键词的 {d.coverage.unclassified} 篇保留“未分类”。无可用词的论文保留未分类；图中默认单列，数据表及论文清单仍完整保留。每组分母为该组唯一论文；同篇最多贡献三个组，各组篇数之和可能超过全库。</p><p>{d.metric.description} AI 模式有效覆盖 {d.coverage.withAI}/{d.coverage.shown}，其余留在未评分区。规则 0 分表示未命中现有阅读优先规则，不表示论文没有价值。两种评分不混用；JIF 只在逐篇参考资料中展示，不参与本图坐标。AI 评分基于摘要，尚未核查全文，不能视为已证实的影响力。</p><p>纵轴固定 0–100，点为组内已评分论文中位数，竖线为第 25–75 百分位；悬停显示全范围、已评分分母与缺失数。重叠坐标可用关键词列表或数据表逐一选择。下方直方图按唯一论文计数；柱顶是篇数，柱高是各自分母的占比，避免全库数量压扁少量关键词的分布。全部数据无分页参与聚合。</p><p>内容最近实质更新：{time(d.contentRevision)} UTC+08。页面计算：{time(d.window.generatedAt)} UTC+08 · {d.version}。打开、筛选与重算仅读取已有数据，不调用模型或启动采集。</p></details>
 </ControlReadingLayout></main></PaperSelection>;
}
export default function Hot(){const d=useLoaderData<typeof loader>(),r=useRevalidator();usePageRead(d.pageUpdate,isPageOverview('hot',useLocation().search));return <><KeywordExplorer key={JSON.stringify(d.filters)+d.contentRevision} d={d}/><button className="keyword-recompute research-back" disabled={r.state!=='idle'} onClick={()=>{invalidateReadingCache();window.dispatchEvent(new Event('hkis:reading-refresh'));r.revalidate()}}>{r.state!=='idle'?'重算中…':'重算当前分布'}</button></>;}
