import {useEffect,useState} from 'react';
import {Form,Link,useLoaderData,useRevalidator,type LoaderFunctionArgs} from 'react-router';
import {apiGet} from '../lib/api.server';
import {SITE} from '@aihot/industry/site';
export const headers=()=>({'Cache-Control':'no-store'});
export function meta(){return [{title:`论文情报 · ${SITE.name}`},{name:'robots',content:'noindex, nofollow'}]}
export async function loader({request}:LoaderFunctionArgs){const q=new URL(request.url).search;const [feed,status]=await Promise.all([apiGet<any>('/api/site/research/papers'+q),apiGet<any>('/api/site/research/status')]);return {feed,status};}
const time=(value:any)=>value?new Date(value).toLocaleString('zh-CN',{timeZone:'UTC',hour12:false})+' UTC':'尚无记录';
export default function Research(){const {feed,status}=useLoaderData<typeof loader>();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const revalidator=useRevalidator();
 async function sync(){setBusy(true);let added=0,errors=0;for(const [i,s] of status.sources.entries()){setMessage(`正在读取 ${i+1}/${status.sources.length} · ${s.name}`);try{const r=await fetch('/api/site/research/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceId:s.id,maxPages:1})});const d=await r.json();added+=d.added||0;if(!r.ok||d.status==='error')errors++;}catch{errors++;}}setMessage(`本轮新增 ${added} 篇${errors?`；${errors} 个来源失败，已保留原数据`:''}。未读完的历史分页将在下轮续取。`);setBusy(false);revalidator.revalidate();}
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc)return;const ac=new AbortController();Promise.resolve(mc.registerTool({name:'research_status',description:'Read scholarly-source coverage, missing metadata, collection runs and saved schedule state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(){return (await fetch('/api/site/research/status')).json()}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[]);
 const filters=feed.filters;const paging=(n:number)=>{const q=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v!==''&&v!=null)q.set(k,String(v));q.set('page',String(n));return '?'+q};
 return <div className="research-page"><header className="research-heading"><div><p className="research-eyebrow">HKIS / RESEARCH</p><h1>论文情报</h1><p>先进逻辑 · DRAM · NAND · 新型器件 · 工艺与机理 · CIS · TCAD</p></div><button onClick={sync} disabled={busy} className="research-primary">{busy?'采集中…':'立即检查更新'}</button></header>
 <div className="research-stats"><div><b>{status.total}</b><span>已入库论文</span></div><div><b>{status.sources.length}</b><span>核心期刊 / 3 家出版商</span></div><div><b>规则评分</b><span>未接入 AI 模型</span></div><div><b>{status.schedule.enabled?'每 12 小时':'定时待启用'}</b><span>{status.schedule.enabled?`下次 ${time(status.schedule.nextRun)}`:'目标每 12 小时；当前未自动运行'}</span></div></div>
 {message&&<p role="status" className="research-notice">{message}</p>}
 <Form method="get" className="research-filters"><label>搜索<input name="q" defaultValue={filters.q} placeholder="论文、作者、单位" type="search"/></label><label>出版商<select name="publisher" defaultValue={filters.publisher}><option value="">全部</option>{['IEEE','Wiley','Elsevier'].map(p=><option key={p}>{p}</option>)}</select></label><label>研究方向<select name="topic" defaultValue={filters.topic}><option value="">全部方向</option>{status.topics.map((t:any)=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label>最低阅读优先级<select name="min" defaultValue={String(filters.min)}>{[0,25,45,60,75].map(n=><option key={n} value={n}>{n===0?'全部入库论文':`${n} 分`}</option>)}</select></label><label>排序<select name="sort" defaultValue={filters.sort}><option value="priority">阅读优先级</option><option value="latest">最新发现</option></select></label><button className="research-primary" type="submit">筛选</button></Form>
 <p className="research-result-note">{feed.total} 篇符合筛选 · 优先级为可解释规则，不代表论文质量或已获科学验证。原始作者关键词与系统标签分开保存。</p>
 <div className="research-list">{!feed.papers.length?<div className="research-empty">当前条件下没有论文。可将最低阅读优先级设为“全部入库论文”，或检查来源状态。</div>:feed.papers.map((p:any)=><article className="research-card" key={p.id}><div className="research-card-top"><span>{p.publisher} · {p.journal}</span><strong>{p.priority}<small> 阅读优先级</small></strong></div><h2><Link to={`/research/${p.id}`}>{p.title}</Link></h2><p className="research-authors">{p.authors.length?`${p.authors[0].name}${p.authors.length>1?` 等 ${p.authors.length} 位作者`:''}`:'作者：来源未提供'} · {p.publishedAt||'发表日期未提供'}{p.datePrecision==='month'?'（卷期月份）':''}</p><p className="research-abstract">{p.abstract||'摘要：当前可用信源未提供。可通过论文原文链接查看。'}</p><div className="research-tags">{p.topics.map((id:string)=><span key={id}>{status.topics.find((t:any)=>t.id===id)?.label||id}</span>)}</div><div className="research-card-bottom"><span>相关度 {p.relevance} · {p.provenance.abstract?`摘要来自 ${p.provenance.abstract}`:'摘要缺失'}</span><a href={p.doi?`https://doi.org/${p.doi}`:p.url} target="_blank" rel="noreferrer">论文原文</a></div></article>)}</div>
 <nav className="research-pagination" aria-label="论文分页">{feed.page>1&&<Link to={paging(feed.page-1)}>上一页</Link>}<span>第 {feed.page} / {feed.pageCount} 页</span>{feed.page<feed.pageCount&&<Link to={paging(feed.page+1)}>下一页</Link>}</nav>
 <details className="research-panel"><summary>信源、字段完整度与采集记录</summary><p>当前范围是以下 9 本核心期刊，并非三家出版商的全部目录。首次回溯近 90 天发表、近 45 天被索引的记录；后续按索引时间增量续取并重叠 24 小时去重。RSS 仅覆盖其实际发布的最新条目。</p><p>IEEE 官方 RSS 可补充摘要；Wiley / Elsevier 的 RSS 若被限制或返回非订阅页面，会保留明确失败状态。Crossref 是出版商存入的注册元数据；OpenAlex 仅按精确 DOI 补缺并单独标注。</p><p>OpenAlex 补充状态：{status.runs.some((r:any)=>String(r.details_json).includes('OpenAlex: HTTP 429'))?'当前受到限流，缺少的字段保持缺失':'以实际读取结果为准；不保证每篇都有补充字段'}</p><div className="research-coverage">{status.counts.map((s:any)=><div key={s.publisher}><strong>{s.publisher} · {s.total} 篇</strong><p>作者 {s.authors}/{s.total} · 单位 {s.affiliations}/{s.total} · 摘要 {s.abstracts}/{s.total} · 作者关键词 {s.authorKeywords}/{s.total}</p></div>)}</div><ul className="research-sources">{status.sources.map((s:any)=><li key={s.id}><strong>{s.name}</strong><span>ISSN {s.issn} · {s.count} 篇 · 最近成功 {time(s.last_success)}</span><span>{s.error||`Crossref ${s.last_success?'可用':'尚未验证'}`}{s.backfillPending?' · 历史分页待续取':''} · 官方 RSS {s.rss_status==='ok'?'可用':s.rss_error||'尚未验证'}</span></li>)}</ul><p>单位按来源实际记录保存；主要作者默认显示首位作者并保留完整作者表。通讯作者仅在信源明确标注时显示。未来卷期日期与发现时间分别保留，不把未来卷期当作已发表日。</p></details>
 <details className="research-panel"><summary>阅读优先级如何计算</summary><p>v1 规则：标题或摘要中的研究方向匹配决定相关度；在标题中命中按完整权重，在摘要中命中按 75% 权重。相关度取最高方向权重 + 多方向奖励（每方向 12，最多 30）+15，上限 100。</p><p>阅读优先级 = 相关度 ×75% + 机理/实验/可靠性/仿真词信号 10 + 近 30 天发表信号 10 + 综述/路线图信号 5，上限 100。缺少摘要意味着证据信息不足，不据此判断论文质量。未使用热度、期刊影响因子或模型推断。</p><p>{status.topics.map((t:any)=>`${t.label} ${t.weight}`).join('；')}</p></details>
 </div>
}
