import {PaperDetailState,PaperSourceLink} from '../components/PaperReader';
import {PaperAssessment} from '../components/PaperAssessment';
import {ScholarlySearch} from '../components/ScholarlySearch';
import {Link,useLoaderData,type LoaderFunctionArgs} from 'react-router';
import {loadOr404} from '../lib/api.server';
import {openAI} from '../lib/ai-client';
import {SITE} from '@aihot/industry/site';
export async function loader({params}:LoaderFunctionArgs){return loadOr404<any>('/api/site/research/papers/'+params.id)}
export const headers=()=>({'Cache-Control':'no-store'});
export function meta({data}:any){return [{title:`${data?.title||'论文'} · ${SITE.shortName}`},{name:'robots',content:'noindex, nofollow'}]}
const from=(p:any,field:string)=>p.provenance[field]||'来源未提供';
export default function Paper(){const p=useLoaderData<typeof loader>();return <article className="research-page research-detail"><Link to="/research" className="research-back">返回论文情报</Link><div className="research-heading"><div><p className="research-eyebrow">{p.publisher} / {p.journal}</p><h1>{p.title}</h1></div></div><p>{p.publishedAt||'发表日期未提供'}{p.datePrecision==='month'?'（来源卷期月份）':''} · DOI {p.doi||'未提供'}</p><PaperDetailState id={p.id}/><div className="research-actions"><PaperSourceLink paperId={p.id} className="research-primary" href={p.doi?`https://doi.org/${p.doi}`:p.url} target="_blank" rel="noreferrer">打开论文原文</PaperSourceLink><button className="ai-secondary" onClick={()=>openAI('请基于这篇论文的实际摘要分析研究方法、主要发现、局限，并给出是否值得阅读的建议。没有摘要时请明确说明，勿推测。',[p.id])}>AI 分析摘要</button><span>相关度 {p.relevance} · 阅读优先级 {p.priority} · 规则评分，非 AI 评价</span></div>
 <ScholarlySearch paperId={p.id}/><PaperAssessment paper={p}/>
 <section id="abstract"><h2>摘要</h2><p className="research-field-source">字段来源：{from(p,'abstract')}</p><p className="research-full-abstract">{p.abstract||'当前可用信源未提供摘要，未自动生成替代内容。'}</p></section>
 {p.provenance.publisherSummary&&<section><h2>出版商导读</h2><p className="research-field-source">来自官方 RSS，可能截短；不是论文摘要，不用于生成研究结论</p><p className="research-full-abstract">{p.provenance.publisherSummary}</p></section>}
 <section><h2>主要作者与单位</h2><p>首位作者：{p.authors.find((a:any)=>a.first)?.name||p.authors[0]?.name||'来源未提供'}</p><p>首位作者单位：{(p.authors.find((a:any)=>a.first)||p.authors[0])?.affiliations.join('；')||'当前信源未提供与首位作者明确关联的单位'}</p><p>通讯作者：{p.authors.filter((a:any)=>a.corresponding===true).map((a:any)=>a.name).join('；')||'未获明确信源标注'}</p><details><summary>完整作者表（{p.authors.length} 人）</summary><ol className="research-author-list">{p.authors.map((a:any,i:number)=><li key={i}><strong>{a.name}</strong>{a.first?' · 首位':''}{a.corresponding?' · 通讯作者':''}<p>{a.affiliations.join('；')||'单位未提供'}</p><small>{a.source}{a.affiliationSource?` / 单位补充 ${a.affiliationSource}`:''}</small></li>)}</ol></details><p>已记录的全部单位（{from(p,'affiliations')}）：{p.affiliations.join('；')||'未提供'}</p></section>
 <section><h2>关键词与筛选依据</h2><p>前三分类词：{(p.categories||[]).map((k:any)=><Link key={k.id} to={'/research?min=0&keyword='+encodeURIComponent(k.id)}>{k.label}（{k.sources.join(' / ')}） · </Link>)}{!p.categories?.length&&'未分类'}</p><p>补全状态：{p.provenance.keywordEvidence?.status||'尚未检查'}；索引词更新时间 {p.provenance.keywordEvidence?.checkedAt||'暂无'}。索引词为供应商机器标注，不是作者关键词。</p><details><summary>完整索引词与来源</summary>{(p.provenance.keywordEvidence?.records||[]).map((e:any)=><p key={e.kind}>{e.kind}：{e.terms.map((k:any)=>typeof k==='string'?k:k.label).join('；')||'来源未提供'}</p>)}</details><p>作者关键词（{from(p,'keywords')}）：{p.keywords.join('；')||'来源未提供'}</p><p>系统主题标签：{p.topics.join(' · ')||'无匹配'}。这些是规则匹配标签，不能替代作者关键词。</p><ul>{p.reasons.map((r:string)=><li key={r}>{r}</li>)}</ul><p>规则版本 {p.ruleVersion}。阅读优先级用于排阅读顺序，不是论文质量结论。</p></section>
 <section><h2>来源记录与元数据修订</h2><p>元数据版本 {p.metadataRevision} · 最近注册校对 {p.metadataCheckedAt||'尚未校对'}</p><ul>{p.changes?.map((r:any,i:number)=><li key={i}>{r.created_at} · {r.channel} · {JSON.parse(r.fields_json).join('、')}</li>)}</ul><p>首次入库 {p.firstSeen} · 最近读取 {p.lastSeen}</p><ul>{p.records.map((r:any)=><li key={r.channel+r.record_url}><a href={r.record_url} target="_blank" rel="noreferrer">{r.channel}</a> · {r.retrieved_at}</li>)}</ul><p>出版商保留摘要的相应版权；这里只保存可用信源实际返回的摘要和元数据，不抓取付费全文。</p></section></article>}
