import {RESEARCH_THEMES} from '../../../../sites/research-topics.ts';
import {readingCache,statusCache,readJSON,invalidateReadingCache} from '../lib/reading-cache';
import {readClientPage} from '../lib/page-update-load';
import {usePageRead} from '../components/NavigationUpdates';
import {isPageOverview} from '@aihot/contracts/navigation-updates';
import {RailDisclosure} from '../components/ui/AdaptiveRail';
import {ControlReadingLayout} from '../components/ui/ControlReadingLayout';
import {PaperSelection,PaperBulkToolbar,PaperCardState,PaperSourceLink} from '../components/PaperReader';
import {AssessmentBadge} from '../components/PaperAssessment';
import {PUBLISHERS} from '../../../../sites/research-config.ts';
import {ScholarlySearch} from '../components/ScholarlySearch';
import {useEffect,useState} from 'react';
import {Form,Link,useLoaderData,useRevalidator,useLocation,type LoaderFunctionArgs} from 'react-router';
import {apiGet,withPageUpdate} from '../lib/api.server';
import {openAI} from '../lib/ai-client';
import {SITE} from '@aihot/industry/site';
export const headers=()=>({'Cache-Control':'no-store'});
export function meta(){return [{title:`论文情报 · ${SITE.name}`},{name:'robots',content:'noindex, nofollow'}]}
export async function loader({request}:LoaderFunctionArgs){const u=new URL(request.url),q=u.search;return withPageUpdate(u.pathname==='/'?'home':'research',async()=>{const [feed,status]=await Promise.all([apiGet<any>('/api/site/research/papers'+q),apiGet<any>('/api/site/research/status')]);return {feed,status};});}
export function clientLoader({request}:{request:Request}){const u=new URL(request.url);return readingCache.read(u.pathname+u.search,()=>readClientPage(u.pathname==='/'?'home':'research',async()=>{const [feed,status]=await Promise.all([readJSON<any>('/api/site/research/papers'+u.search,request.signal),statusCache.read('status',()=>readJSON<any>('/api/site/research/status',request.signal),{signal:request.signal})]);return {feed,status}}),{signal:request.signal})}
const time=(value:any,timezone='Asia/Singapore')=>value?new Date(value).toLocaleString('zh-CN',{timeZone:timezone,hour12:false})+' '+timezone:'调度器尚未返回';
export default function Research(){const data=useLoaderData<typeof loader>(),{feed,status}=data;const readLocation=useLocation();usePageRead(data.pageUpdate,isPageOverview(readLocation.pathname==='/'?'home':'research',readLocation.search));const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const revalidator=useRevalidator();
 async function sync(){setBusy(true);let added=0,errors=0;for(const [i,s] of status.sources.entries()){setMessage(`正在读取 ${i+1}/${status.sources.length} · ${s.name}`);try{const r=await fetch('/api/site/research/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceId:s.id,maxPages:1})});const d=await r.json();added+=d.added||0;if(!r.ok||d.status==='error')errors++;}catch{errors++;}}let analysisMessage='';try{const r=await fetch('/api/site/research/process',{method:'POST',headers:{'Content-Type':'application/json','X-HKIS-Request':'1'},body:JSON.stringify({maxPapers:3})});const d=await r.json();analysisMessage=d.blocked?`；AI 暂缓：${d.blocked}`:`；AI 已保存 ${d.completed||0} 篇，待处理 ${d.remainingQueued||0} 篇`;}catch{analysisMessage='；AI 处理状态暂不可用'}setMessage(`本轮新增 ${added} 篇${errors?`；${errors} 个来源失败，已保留原数据`:''}${analysisMessage}。未读完的当月分页留到下轮。`);setBusy(false);invalidateReadingCache();revalidator.revalidate();}
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc)return;const ac=new AbortController();Promise.resolve(mc.registerTool({name:'research_status',description:'Read scholarly-source coverage, missing metadata, collection runs and saved schedule state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(){return (await fetch('/api/site/research/status')).json()}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort()},[]);
 const location=useLocation();const filters=feed.filters;const paging=(n:number)=>{const q=new URLSearchParams();for(const [k,v] of Object.entries(filters))if(v!==''&&v!=null)q.set(k,String(v));q.set('page',String(n));return '?'+q};
 return <PaperSelection ids={feed.papers.map((p:any)=>p.id)} scopeKey={JSON.stringify(feed.filters)+feed.page}><div className="research-page"><header className="research-heading"><div><p className="research-eyebrow">HKIS / RESEARCH</p><h1>论文情报</h1><p>先进逻辑 · DRAM · NAND · 新型器件 · 工艺与机理 · CIS · TCAD</p></div><button onClick={sync} disabled={busy} className="research-primary">{busy?'采集中…':'立即检查更新'}</button></header>
 <div className="research-stats"><div><b>{status.total}</b><span>已入库论文</span></div><div><b>{status.sources.length}</b><span>已配置期刊 / {PUBLISHERS.length} 个出版来源组</span></div><div><b>脚本优先</b><span>{status.processing?.eligible?`复杂内容用 ${status.processing.model}`:`AI 暂缓：${status.processing?.blocked||'尚未配置'}`}</span></div><div><b>{status.schedule.enabled?'每 12 小时':'定时待启用'}</b><span>{status.schedule.enabled?`下次 ${time(status.schedule.nextRun,status.schedule.timezone||'Asia/Singapore')}`:'目标每 12 小时；当前未自动运行'}</span></div></div>
 {message&&<p role="status" className="research-notice">{message}</p>}
 <details className="scholarly-discovery"><summary>跨库检索与论文入库 · Semantic Scholar / OpenAlex</summary><ScholarlySearch/></details>
 <ControlReadingLayout label="论文筛选" summary={`${feed.total} 篇符合条件`} rail={<section className="reading-filter-card"><h2>论文筛选</h2><Form method="get" preventScrollReset className="research-filters" key={JSON.stringify(filters)}><label>搜索<input name="q" defaultValue={filters.q} placeholder="论文、作者、单位" type="search"/></label><label>主题章节<select name="theme" defaultValue={filters.theme||''}><option value="">全部研究主题</option>{RESEARCH_THEMES.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}{filters.theme?.startsWith('org:')&&<option value={filters.theme}>当前单位署名</option>}</select></label><label>分类关键词<input name="keyword" defaultValue={filters.keyword||''} placeholder="前三分类词或分类 ID"/></label><label>研究方向<select name="topic" defaultValue={filters.topic}><option value="">全部方向</option>{status.topics.map((t:any)=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><RailDisclosure title={`更多筛选${filters.publisher||Number(filters.min)>0||filters.analysis||filters.aiTopic||filters.sort!=='priority'?' · 已设置':''}`}><label>出版商<select name="publisher" defaultValue={filters.publisher}><option value="">全部</option>{PUBLISHERS.map(p=><option key={p}>{p}</option>)}</select></label><label>最低阅读优先级<select name="min" defaultValue={String(filters.min)}>{[0,25,45,60,75].map(n=><option key={n} value={n}>{n===0?'全部入库论文':`${n} 分`}</option>)}</select></label><label>处理状态<select name="analysis" defaultValue={filters.analysis}><option value="">全部状态</option><option value="completed">AI 已评估</option><option value="queued">等待 AI</option><option value="rules_only">仅脚本</option><option value="insufficient">摘要证据不足</option><option value="unknown">模型结果未知</option><option value="failed">处理失败</option></select></label><label>AI 分类<select name="aiTopic" defaultValue={filters.aiTopic}><option value="">全部 AI 分类</option>{status.topics.map((t:any)=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label><label>排序<select name="sort" defaultValue={filters.sort}><option value="priority">阅读优先级</option><option value="latest">最新发现</option></select></label></RailDisclosure><div className="rail-filter-actions"><button className="research-primary" type="submit">筛选</button><Link className="research-back" to={location.pathname}>重置筛选</Link></div></Form></section>}>
 <div className="ai-actions"><button className="ai-secondary" disabled={!feed.papers.length} onClick={()=>openAI('请根据当前附带论文的实际摘要，筛选与我的关注方向最相关、值得阅读的论文。分别给出有引用证据的建议和 AI 适配分，缺少摘要则不评分。',feed.papers.slice(0,4).map((p:any)=>p.id))}>AI 筛选当前前 4 篇</button><Link to="/settings">模型与关键词设置</Link></div>
 <p className="research-result-note">{feed.total} 篇符合筛选 · 优先级为可解释规则，不代表论文质量或已获科学验证。原始作者关键词与系统标签分开保存。</p>
 <PaperBulkToolbar/><div className="research-list">{!feed.papers.length?<div className="research-empty">当前条件下没有论文。可将最低阅读优先级设为“全部入库论文”，或检查来源状态。</div>:feed.papers.map((p:any)=><PaperCardState id={p.id} title={p.title} key={p.id}><div className="research-card-top"><span>{p.publisher} · {p.journal}</span><strong>{p.priority}<small> 阅读优先级</small></strong></div><h2><Link to={`/research/${p.id}`}>{p.title}</Link></h2><p className="research-authors">{p.authors.length?`${p.authors[0].name}${p.authors.length>1?` 等 ${p.authors.length} 位作者`:''}`:'作者：来源未提供'} · {p.publishedAt||'发表日期未提供'}{p.datePrecision==='month'?'（卷期月份）':''}</p><p className="research-abstract">{p.abstract||'摘要：当前可用信源未提供。可通过论文原文链接查看。'}</p><p><AssessmentBadge paper={p}/></p><div className="research-tags">{(p.categories||[]).map((k:any)=><Link key={k.id} to={'/research?min=0&keyword='+encodeURIComponent(k.id)}>{k.label}</Link>)}{!p.categories?.length&&<span>未分类</span>}</div><div className="research-card-bottom"><span>相关度 {p.relevance} · {p.provenance.abstract?`摘要来自 ${p.provenance.abstract}`:'摘要缺失'}</span><PaperSourceLink paperId={p.id} href={p.doi?`https://doi.org/${p.doi}`:p.url} target="_blank" rel="noreferrer">论文原文</PaperSourceLink></div></PaperCardState>)}</div>
 <nav className="research-pagination" aria-label="论文分页">{feed.page>1&&<Link to={paging(feed.page-1)}>上一页</Link>}<span>第 {feed.page} / {feed.pageCount} 页</span>{feed.page<feed.pageCount&&<Link to={paging(feed.page+1)}>下一页</Link>}</nav>
 <details className="research-panel"><summary>信源、字段完整度与采集记录</summary><p>当前范围为 {status.sources.length} 本已配置期刊，并非出版商全部目录。每次只抓取 UTC+08 最近一个日历月内明确到日的在线/发表记录：{status.window?.startDate} 至 {status.window?.endDate}（含端点，月末夹到上月最后一天）。缺失、月份/年份精度和未来日期不冒充确切发表日。已有旧论文保留，仅退出更新窗口。按索引增量重叠 24 小时去重，并轮流复查近期已存 DOI；RSS 同样限于该窗口。</p><p>IEEE 与 Science Advances 官方 RSS 可在明确提供时补充摘要；Nature 和 Science First Release 的导读与摘要分开保存。RSS 被限制或返回非订阅页面时保留明确失败状态。Crossref 是出版商存入的注册元数据；OpenAlex 仅按精确 DOI 补缺并单独标注；匿名接口限流时退避，已保存的学术服务密钥不用于自动采集。Nature / Science 新来源按既有主题规则筛选；缺少摘要时题名未命中可能漏收，注册类型不等于已确认原创研究。</p><p>OpenAlex 补充状态：{status.runs.some((r:any)=>String(r.details_json).includes('OpenAlex: HTTP 429'))?'当前受到限流，缺少的字段保持缺失':'以实际读取结果为准；不保证每篇都有补充字段'}</p><div className="research-coverage">{status.counts.map((s:any)=><div key={s.publisher}><strong>{s.publisher} · {s.total} 篇</strong><p>作者 {s.authors}/{s.total} · 单位 {s.affiliations}/{s.total} · 摘要 {s.abstracts}/{s.total} · 作者关键词 {s.authorKeywords}/{s.total}</p></div>)}</div><ul className="research-sources">{status.sources.map((s:any)=><li key={s.id}><strong><a href={s.homepage} target="_blank" rel="noreferrer">{s.name}</a></strong><span>{s.publisherName} · {s.feedCoverage}{s.topicFilter?' · 仅入库匹配关注方向的记录':''}</span><span>ISSN {s.issn} · {s.count} 篇 · 最近成功 {time(s.last_success)}</span><span>{s.error||`Crossref ${s.last_success?'可用':'尚未验证'}`}{s.backfillPending?' · 当月分页待续取':''} · 官方 RSS {s.rss_status==='ok'?'可用':s.rss_error||'尚未验证'}</span></li>)}</ul><p>单位按来源实际记录保存；主要作者默认显示首位作者并保留完整作者表。通讯作者仅在信源明确标注时显示。未来卷期日期与发现时间分别保留，不把未来卷期当作已发表日。</p></details>
 <details className="research-panel"><summary>脚本与 AI 如何分工</summary><p>实际保存状态：{status.processing?.counts?.map((c:any)=>`${c.status} ${c.total} 篇`).join('；')||'尚无处理记录'}。每次最多 3 个模型请求，使用当前保存且通过连接验证的模型，共享既有每日请求额度；不提高配额。未变化的内容/模型/规则版本复用，失败或未知结果不自动重试。关键词与分类的 AI 结果有独立筛选，不替换作者关键词或规则标签。</p><p>AI 重要性与摘要方法证据分均为暂定判断，不是已核验的科学质量。原文证据不足不评分；不使用期刊影响因子替代单篇质量。</p><h3>阅读优先级如何计算</h3><p>v1 规则：标题或摘要中的研究方向匹配决定相关度；在标题中命中按完整权重，在摘要中命中按 75% 权重。相关度取最高方向权重 + 多方向奖励（每方向 12，最多 30）+15，上限 100。</p><p>阅读优先级 = 相关度 ×75% + 机理/实验/可靠性/仿真词信号 10 + 近 30 天发表信号 10 + 综述/路线图信号 5，上限 100。缺少摘要意味着证据信息不足，不据此判断论文质量。未使用热度、期刊影响因子或模型推断。</p><p>{status.topics.map((t:any)=>`${t.label} ${t.weight}`).join('；')}</p></details>
 </ControlReadingLayout></div></PaperSelection>
}
