import {PageHeader} from '../components/ui/PageFrame';
import {withPageUpdate} from '../lib/api.server';
import {usePageRead} from '../components/NavigationUpdates';
import {updatePageForPath} from '@aihot/contracts/navigation-updates';
import {Link,useLoaderData} from 'react-router';
import {SITE} from '@aihot/industry/site';
export async function loader({request}:{request:Request}){return withPageUpdate(updatePageForPath(new URL(request.url).pathname),async()=>({}));}
export function meta(){return [{title:`运行说明 · ${SITE.name}`},{name:'robots',content:'noindex, nofollow'}];}
export default function Info(){usePageRead(useLoaderData<typeof loader>().pageUpdate);return <article className="research-page info-page"><PageHeader><div><p className="research-eyebrow">HKIS / INFORMATION</p><h1>当前版本说明</h1></div></PageHeader><div className="page-prose space-y-4 text-ink-3"><p>本站为基于 AIHOT 开源框架的私人研究动态工作台，已将订阅读取与持久存储适配到 Sites。首页已接入 IEEE、Wiley、Elsevier、Nature、Science / AAAS 的 17 本已配置期刊，覆盖先进逻辑、DRAM、NAND、新型器件、工艺机理、图像传感器和 TCAD。“研究进展”“论文日报”和“热点榜”共用真实论文库。</p><p>点击“检查信源更新”读取 RSS / Atom，按原文地址去重并保存在数据库中。“全部动态”显示来源标题和摘要，不显示原文全文，不声称已做相关性判断或模型评分。</p><p>论文页保留可解释规则分，另提供按需 AI 助手、摘要分析与筛选。接入点、API key、模型和思考等级可在网站设置中配置；未配置或关闭时不调用模型。API key 服务端加密保存；用户主动测试或发送对话才会把提问与检索到的论文元数据/摘要发送到所选接入点。页面聊天不跨会话显示，但服务端保留调用回执与结果，用于计费限额、错误排查及防止重复请求；超过 7 天的回答内容在后续访问时清理，保留不含对话内容的请求状态以防重放。配置建议必须在站内核对差异并确认。论文定时更新的实际启用状态、上次采集时间与字段完整度请以论文情报页为准；示范 RSS 仍是手动更新。事件聚类和原版热度排名尚未迁移。本站新增前一日批次的AI论文日报与月历归档，实际每天08点调度启用状态以日报页为准。原版公开 API、原后台及反馈收集尚未迁移；HKIS 的私有 RSS 与 MCP 只读接点见下方。</p><p>论文阅读记录与收藏按本站账户保存在数据库中，论文页、日报、进展与热点共用；打开详情或论文原文后自动标为已读，批量操作仅作用于当前页勾选的论文。原版订阅内容的本机收藏继续保留，与论文收藏分开。订阅文章和采集状态存储在此站点数据库中。访问权限由 Sites 控制，当前仅供本人使用。正式对外分享前，需要另行确定条款、隐私说明和权限。</p><section aria-labelledby="integrations-title"><h2 id="integrations-title" className="text-lg font-semibold text-ink">RSS / MCP 只读接入</h2><p>论文详情、研究进展、历史日报及引用、热点关键词、已读收藏与更新日志使用同一读取层。接口不会采集、调用模型、修改配置或标记已读。</p><p>MCP 地址：<span className="break-all">https://myhot-research.sea0monsters15.chatgpt.site/mcp</span>。使用本站的 Sites 私有插件完成平台连接。通用本地 agent 的认证兼容尚未验证。</p><p>RSS 需要所有者登录。下列链接可在登录后查看或保存 XML；普通 RSS 阅读器持续订阅的认证通道尚未验证，不要把登录凭据放进订阅地址。</p><ul className="flex flex-wrap gap-x-5 gap-y-2">{[['papers','论文情报'],['progress','研究进展'],['daily','历史日报'],['keywords','热点关键词'],['reader','我的收藏'],['changelog','更新日志'],['status','覆盖状态']].map(([key,label])=><li key={key}><a className="text-accent underline" href={'/feeds/research.xml?section='+key}>{label} XML</a></li>)}</ul><p><a className="text-accent underline" href="https://github.com/sea-monsters/AIHOT/blob/main/docs/research-integrations.md">筛选、分页与接入说明</a> · <a className="text-accent underline" href="/api/site/integrations">接口能力</a></p></section><p>代码基于 <a className="text-accent underline" href="https://github.com/sea-monsters/AIHOT">sea-monsters/AIHOT</a>，MIT 许可证，版权所有 © 2026 数字生命卡兹克。AIHOT 名称和 Logo 不属于代码授权，本站使用独立品牌 {SITE.name}，英文名 {SITE.englishName}，简写 {SITE.shortName}。</p><Link className="text-accent underline" to="/all">查看来源摘要 →</Link></div></article>}
