import {Link,useLoaderData} from 'react-router';
import {apiGet,withPageUpdate} from '../lib/api.server';
import {usePageRead} from '../components/NavigationUpdates';
import {cachedRouteLoader} from '../lib/reading-cache';
export const clientLoader=cachedRouteLoader;
export async function loader({request}:{request:Request}){return withPageUpdate('topics',()=>apiGet<{topics:{id:string;label:string;group:string;definition:string;total:number;recent:number;href:string}[];total:number}>('/api/site/research/themes',{signal:request.signal}));}
export const headers=()=>({'Cache-Control':'private, no-store'});
export const meta=()=>[{title:'研究主题 · HKIS'},{name:'description',content:'先进半导体器件与工艺、图像传感器、TCAD 研究论文主题入口'},{name:'robots',content:'noindex'}];
const groups=[{id:'company',label:'公司 / 机构'},{id:'field',label:'领域方向'},{id:'genre',label:'内容形态'}];
export default function Topics(){const data=useLoaderData<typeof loader>();usePageRead(data.pageUpdate);return <main className="research-page"><header className="research-heading"><div><p className="eyebrow">HKIS / TOPICS</p><h1>研究主题</h1><p>按单位署名、研究方向与文献形式 / 研究方法进入 {data.total.toLocaleString()} 篇已收录论文。主题可交叉归属，篇数不按阅读分数裁剪。</p></div><Link to="/hot">查看前三关键词分布 ↗</Link></header>{groups.map(g=><section key={g.id} className="research-panel"><h2>{g.label}</h2><div>{data.topics.filter(t=>t.group===g.id).slice(0,g.id==='company'?12:9999).map(t=><Link key={t.id} to={'/topics/'+t.id} prefetch="intent" className="block border-b border-line py-5"><div className="flex items-baseline justify-between gap-4"><h3 className="font-semibold text-ink">{t.label}</h3><span className="text-accent">{t.total} 篇 →</span></div><p className="mt-1 text-sm text-ink-3">{t.definition}</p><p className="mt-2 text-xs text-ink-4">近 7 日首次收录 {t.recent} 篇{!t.total?' · 暂无匹配论文':''}</p></Link>)}</div>{g.id==='company'&&data.topics.filter(t=>t.group===g.id).length>12&&<details className="mt-4"><summary>查看其余全部单位署名（{data.topics.filter(t=>t.group===g.id).length-12}）</summary>{data.topics.filter(t=>t.group===g.id).slice(12).map(t=><p className="border-b border-line py-3" key={t.id}><Link to={t.href}>{t.label} · {t.total} 篇 →</Link></p>)}</details>}</section>)}<p className="text-sm text-ink-3">主题依据标题、摘要、作者词与当前前三分类词的明确词义匹配；同一论文可属于多个主题。机构只依据现有作者单位，不以出版社替代；同一单位的不同院系署名暂不强行合并。内容形态区分文献形式与研究方法线索，可多选归属；缺证据保持待核实。这里的主题不改变论文评分。细关键词来源及缺失状态见论文详情。</p></main>}
