import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {scholarlyApi,saveEvidence} from './api.ts';
import {SERVICES,doiId,parseIdentifier,normalizeRecord,reconstructAbstract,compareRecord} from './domain.ts';
import {requestUrl,fetchJSON,reserveRequest,lookup,responseError} from './provider.ts';
import {credentialContext} from './settings.ts';
import {unseal} from '../ai/security.ts';
import {savePaper} from '../research.ts';
const OA={id:'https://openalex.org/W12345',doi:'https://doi.org/10.9999/TEST',title:'TCAD 二维器件 interface trap mechanism',publication_date:'2026-09-20',publication_year:2026,authorships:[{author_position:'first',is_corresponding:true,author:{display_name:'Jane Researcher',orcid:'https://orcid.org/0000-0000-0000-0001'},institutions:[{display_name:'Test Institute'}]}],abstract_inverted_index:{TCAD:[0],confirms:[1],interface:[2],traps:[3]},primary_location:{source:{display_name:'Test Journal',host_organization_name:'Test Publisher',issn:['1234-5678']}},cited_by_count:12,open_access:{oa_url:'https://example.org/paper'},keywords:[{display_name:'Machine assigned topic'}]};
const S2={paperId:'a'.repeat(40),externalIds:{DOI:'10.9999/test'},title:OA.title,publicationDate:'2026-09-20',authors:[{name:'Jane Researcher'}],abstract:'TCAD confirms interface traps',journal:{name:'Test Journal'},citationCount:13};
const ownerHeaders={'oai-authenticated-user-id':'owner-123','oai-authenticated-user-email':'owner@example.org'};
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(statements:any[]){sql.exec('BEGIN');try{const r=statements.map(s=>s.runSync());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,env:{DB:db,HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)}}}
async function request(f:any,path:string,body?:any,headers:any={}){return scholarlyApi(new Request('https://local.test/api/site/scholarly/'+path,{method:body===undefined?'GET':'POST',headers:{...ownerHeaders,...(body===undefined?{}:{origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'}),...headers},body:body===undefined?undefined:JSON.stringify(body)}),f.env)}
async function savedKey(f:any,service:string,key:string){const r=await request(f,'settings',{service,endpoint:SERVICES[service as keyof typeof SERVICES].endpoint,apiKey:key,revision:0,confirmedDestination:SERVICES[service as keyof typeof SERVICES].endpoint});assert.equal(r.status,200,await r.clone().text());return r.json()}
const mock=async(url:any)=>String(url).includes('openalex')?Response.json(String(url).includes('/works?')?{meta:{count:11},results:[OA]}:OA):Response.json(String(url).includes('/search?')?{total:11,next:10,data:[S2]}:S2);
async function withMock(fn:()=>Promise<void>,fetcher:any=mock){const orig=globalThis.fetch;globalThis.fetch=fetcher;try{await fn()}finally{globalThis.fetch=orig}}

test('official endpoints, DOI canonicalization, exact identity and provider IDs',()=>{assert.equal(doiId('https://doi.org/10.9999/TEST'),'10.9999/test');assert.equal(doiId('10.9999/test?token=secret'),null);assert.deepEqual(parseIdentifier('https://openalex.org/W12345'),{kind:'openalex',id:'W12345'});assert.equal(parseIdentifier('CorpusId:123')?.kind,'semanticscholar');assert.equal(parseIdentifier('ARXIV:2106.15928')?.kind,'semanticscholar');assert.throws(()=>requestUrl('openalex','CorpusId:123'));assert.throws(()=>requestUrl('semanticscholar','W12345'));for(const service of ['openalex','semanticscholar'] as const){const u=new URL(requestUrl(service,'10.9999/test').url);assert.equal(u.origin,new URL(SERVICES[service].endpoint).origin);assert.ok(u.pathname.includes('10.9999%2Ftest'));assert.ok(!u.href.includes('api_key'))}});
test('search pagination is explicit and field selection bounded',()=>{const oa=new URL(requestUrl('openalex','TCAD',3).url),s2=new URL(requestUrl('semanticscholar','TCAD',3).url);assert.equal(oa.searchParams.get('page'),'3');assert.equal(oa.searchParams.get('per_page'),'10');assert.equal(s2.searchParams.get('offset'),'20');assert.equal(s2.searchParams.get('limit'),'10');assert.ok(oa.searchParams.get('select')!.includes('abstract_inverted_index'));assert.ok(s2.searchParams.get('fields')!.includes('externalIds'))});
test('normalize metadata with field ledger, abstract reconstruction and honest missingness',()=>{const r=normalizeRecord('openalex',OA,'2026-10-01T12:00:00Z');assert.equal(r.abstract,'TCAD confirms interface traps');assert.equal(r.doi,'10.9999/test');assert.equal(r.authors[0]!.corresponding,true);assert.equal(r.fields.abstract!.rawFieldPath,'abstract_inverted_index');assert.equal(r.fields.title!.providerRecordId,'W12345');assert.deepEqual(r.indexedKeywords,['Machine assigned topic']);const empty=normalizeRecord('semanticscholar',{...S2,abstract:null,publicationDate:null,year:2024});assert.equal(empty.abstract,null);assert.equal(empty.datePrecision,'year');assert.deepEqual(empty.affiliations,[]);assert.equal(reconstructAbstract({word:[-1,999999999,'2']}).abstract,null);assert.equal(reconstructAbstract({word:[999999]}).truncated,true)});
test('same DOI differing Unicode titles is a conflict; exact titles never override different DOI or absent IDs',()=>{const r=normalizeRecord('openalex',OA);const p={...r,provenance:{title:'crossref'}};assert.equal(compareRecord(p,r).canMerge,true);assert.equal(compareRecord({...p,title:'TCAD 三维器件 interface trap mechanism'},r).identity,'title_conflict');assert.equal(compareRecord({...p,doi:'10.9999/other'},r).identity,'doi_conflict');assert.equal(compareRecord({...p,doi:null},{...r,doi:null}).canMerge,false);assert.equal(compareRecord({...p,doi:null,provenance:{scholarlyIds:{openalex:'W12345'}}},{...r,doi:null}).canMerge,true)});
test('owner authorization and same-origin protections fail closed',async()=>{const f=fixture();assert.equal((await request(f,'settings',undefined,{'oai-authenticated-user-id':''})).status,403);assert.equal((await request(f,'settings',undefined,{'oai-authenticated-user-email':'viewer@example.org'})).status,403);for(const h of [{origin:'https://evil.example'},{origin:''},{'X-HKIS-Request':''}])assert.equal((await request(f,'search',{query:'TCAD',services:['openalex']},h)).status,403);f.sql.close()});
test('separate encrypted service keys, no readback, no cross-service context or endpoint widening',async()=>{const f=fixture();const a='TEST_S2_KEY_NOT_REAL',b='TEST_OA_KEY_NOT_REAL';await savedKey(f,'semanticscholar',a);await savedKey(f,'openalex',b);const rows=f.sql.prepare('SELECT * FROM scholarly_settings').all();assert.equal(rows.length,2);assert.ok(!JSON.stringify(rows).includes(a));const safe=await (await request(f,'settings')).text();assert.ok(!safe.includes(a)&&!safe.includes(b)&&!safe.includes('cipher'));const row=rows.find(r=>r.service==='openalex')!;assert.equal(await unseal(row.key_ciphertext as string,f.env,credentialContext('owner-123','openalex',SERVICES.openalex.endpoint)),b);await assert.rejects(()=>unseal(row.key_ciphertext as string,f.env,credentialContext('owner-123','semanticscholar',SERVICES.semanticscholar.endpoint)));assert.equal((await request(f,'settings',{service:'openalex',endpoint:SERVICES.semanticscholar.endpoint,revision:1})).status,400);assert.equal((await request(f,'settings',{service:'openalex',endpoint:SERVICES.openalex.endpoint,revision:0})).status,409);assert.equal((await request(f,'settings',{service:'openalex',endpoint:SERVICES.openalex.endpoint,revision:1,apiKey:b})).status,400);f.sql.close()});
test('provider transport isolates keys in headers, blocks redirect and never leaks upstream errors',async()=>{for(const service of ['semanticscholar','openalex'] as const){const key='TEST_PRIVATE_KEY_NOT_REAL';let calls=0;const data=await fetchJSON(requestUrl(service,'10.9999/test').url,service,key,AbortSignal.timeout(1000),(async(url:any,init:any)=>{calls++;assert.ok(!String(url).includes(key));assert.equal(init.redirect,'manual');assert.equal(init.headers[service==='openalex'?'Authorization':'x-api-key'],service==='openalex'?'Bearer '+key:key);assert.equal(init.headers[service==='openalex'?'x-api-key':'Authorization'],undefined);return Response.json({title:key})}) as any);assert.equal(calls,1);assert.ok(!JSON.stringify(data).includes(key));for(const status of [301,302,401,403,404,429,500]){await assert.rejects(()=>fetchJSON(requestUrl(service,'TCAD').url,service,key,AbortSignal.timeout(1000),(async()=>new Response(key,{status,headers:{'content-type':'text/plain',location:'https://evil.test'}})) as any),(e:any)=>!e.message.includes(key)&&!!e.code)}}});
test('malformed, oversized and network outcomes are distinct and secret safe',async()=>{const u=requestUrl('openalex','TCAD').url;for(const [response,code] of [[new Response('{',{headers:{'content-type':'application/json'}}),'scholarly_format'],[new Response('x',{headers:{'content-type':'application/json','content-length':'2000001'}}),'scholarly_too_large']] as const)await assert.rejects(()=>fetchJSON(u,'openalex','',AbortSignal.timeout(1000),(async()=>response) as any),(e:any)=>e.code===code);await assert.rejects(()=>fetchJSON(u,'openalex','',AbortSignal.timeout(1000),(async()=>{throw Error('SECRET_INTERNAL')}) as any),(e:any)=>e.code==='scholarly_network'&&!e.message.includes('SECRET'));assert.notEqual(responseError(404).code,responseError(403).code);assert.notEqual(responseError(404).code,responseError(429).code)});
test('D1-coordinated rate limit and daily budget reserve before calls',async()=>{const f=fixture(),t=Date.now();await reserveRequest(f.db,'owner-123','semanticscholar',false,t);await assert.rejects(()=>reserveRequest(f.db,'owner-123','semanticscholar',false,t+1000),(e:any)=>e.code==='scholarly_throttle');await reserveRequest(f.db,'owner-123','semanticscholar',false,t+3100);f.sql.prepare("UPDATE scholarly_usage SET used=100,next_allowed=0").run();await assert.rejects(()=>reserveRequest(f.db,'owner-123','semanticscholar',true,t+6200),(e:any)=>e.code==='scholarly_budget');await reserveRequest(f.db,'owner-123','semanticscholar',true,t+86400000);assert.equal(f.sql.prepare('SELECT used FROM scholarly_usage').get()!.used,1);f.sql.close()});
test('search supports partial success, caches results and makes no model calls',async()=>{const f=fixture();let calls=0;await withMock(async()=>{const body={query:'TCAD',services:['semanticscholar','openalex'],page:1};const r=await (await request(f,'search',body)).json();assert.equal(r.results.length,2);assert.ok(r.results.every((r:any)=>r.ok));assert.equal(calls,2);const again=await (await request(f,'search',body)).json();assert.ok(again.results.every((r:any)=>r.cached));assert.equal(calls,2);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0)},async(u:any)=>{calls++;return mock(u)});f.sql.close()});
test('auth failure is unavailable rather than not-found or fallback success',async()=>{const f=fixture();await withMock(async()=>{const data=await (await request(f,'search',{query:'TCAD',services:['openalex','semanticscholar']})).json();assert.equal(data.results[0].ok,true);assert.equal(data.results[1].ok,false);assert.equal(data.results[1].code,'scholarly_auth');assert.equal(data.results[1].records.length,0)},async(u:any)=>String(u).includes('openalex')?mock(u):Response.json({error:'SECRET_KEY'},{status:403}));f.sql.close()});
test('explicit import is idempotent, stores provenance and does not relabel machine keywords',async()=>{const f=fixture();await withMock(async()=>{const data=await (await request(f,'search',{query:'10.9999/test',services:['openalex']})).json();const g=data.results[0],body={cacheKey:g.cacheKey,recordId:g.records[0].recordId};const a=await (await request(f,'apply',body)).json();assert.equal(a.added,true);assert.equal((await request(f,'apply',body)).status,200);const p=f.sql.prepare('SELECT * FROM research_papers').get()!;assert.equal(p.keywords_json,'[]');assert.equal(p.abstract,'TCAD confirms interface traps');assert.ok(String(p.provenance_json).includes('rawFieldPath'));assert.equal(f.sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_records').get()!.n,1)});f.sql.close()});
test('cross-check retains conflicts, fill-missing preserves existing sourced values and scores',async()=>{const f=fixture();const old=await savePaper(f.db,{doi:'10.9999/test',title:OA.title,url:'https://doi.org/10.9999/test',publisher:'IEEE',journal:'Original Journal',sourceId:'test',issn:'',publishedAt:'2025',datePrecision:'year',authors:[],affiliations:[],abstract:null,keywords:[],provenance:{title:'crossref',journal:'crossref',publishedAt:'crossref'},sourceIndexedAt:null,discovery:'crossref'});const before=f.sql.prepare('SELECT * FROM research_papers').get()!;await withMock(async()=>{const response=await (await request(f,'check',{paperId:old.id,services:['openalex']})).json(),g=response.results[0],r=g.records[0];assert.equal(r.comparison.canMerge,true);assert.ok(r.comparison.fields.some((x:any)=>x.field==='journal'&&x.state==='conflict'));assert.equal(f.sql.prepare('SELECT abstract FROM research_papers').get()!.abstract,null);const applied=await (await request(f,'apply',{paperId:old.id,cacheKey:g.cacheKey,recordId:r.recordId})).json();assert.ok(applied.filled.includes('abstract'));const after=f.sql.prepare('SELECT * FROM research_papers').get()!;assert.equal(after.journal,'Original Journal');assert.equal(after.published_at,'2025');assert.equal(after.priority,before.priority);assert.equal(after.abstract,'TCAD confirms interface traps');assert.equal(JSON.parse(after.provenance_json as string).journal,'crossref')});f.sql.close()});
test('title conflict prevents merge even with exact DOI; absent DOI blocks automatic cross-check',async()=>{const f=fixture();const p=await savePaper(f.db,{doi:'10.9999/test',title:'Different authoritative paper title',url:'https://doi.org/10.9999/test',publisher:'IEEE',journal:'Original',sourceId:'test',issn:'',publishedAt:null,datePrecision:null,authors:[],affiliations:[],abstract:null,keywords:[],provenance:{title:'crossref'},sourceIndexedAt:null,discovery:'crossref'});await withMock(async()=>{const data=await (await request(f,'check',{paperId:p.id,services:['openalex']})).json(),g=data.results[0];assert.equal(g.records[0].comparison.identity,'title_conflict');assert.equal((await request(f,'apply',{paperId:p.id,cacheKey:g.cacheKey,recordId:g.records[0].recordId})).status,409);assert.equal(f.sql.prepare('SELECT abstract FROM research_papers').get()!.abstract,null)});f.sql.prepare('UPDATE research_papers SET doi=NULL').run();assert.equal((await request(f,'check',{paperId:p.id,services:['openalex']})).status,409);f.sql.close()});
test('evidence identity excludes attempt timestamp and retains changed-content versions',async()=>{const f=fixture();const r=normalizeRecord('openalex',OA,'2026-10-01T00:00:00Z');await saveEvidence(f.db,'paper',r);await saveEvidence(f.db,'paper',normalizeRecord('openalex',OA,'2026-10-01T01:00:00Z'));assert.equal(f.sql.prepare('SELECT count(*) n FROM research_records').get()!.n,1);await saveEvidence(f.db,'paper',normalizeRecord('openalex',{...OA,cited_by_count:14},'2026-10-01T02:00:00Z'));assert.equal(f.sql.prepare('SELECT count(*) n FROM research_records').get()!.n,2);f.sql.close()});
test('stale or tampered cache records cannot write papers; page bounds reject before network',async()=>{const f=fixture();assert.equal((await request(f,'apply',{cacheKey:'a'.repeat(64),recordId:'W123'})).status,409);const r=await request(f,'search',{query:'TCAD',services:['openalex'],page:11});assert.equal((await r.json()).results[0].code,'invalid_page');assert.equal(f.sql.prepare('SELECT count(*) n FROM scholarly_usage').get()!.n,0);f.sql.close()});
test('normalizing duplicate provider IDs with differing stable data fails closed',async()=>{const f=fixture();await assert.rejects(()=>lookup(f.db,'owner-123',f.env,'openalex','TCAD',1,AbortSignal.timeout(2000),{fetcher:(async()=>Response.json({meta:{count:2},results:[OA,{...OA,title:'Conflicting content'}]})) as any}),(e:any)=>e.code==='scholarly_conflict');assert.equal(f.sql.prepare('SELECT count(*) n FROM scholarly_cache').get()!.n,0);f.sql.close()});
test('single DOI lookup rejects mismatched or absent returned DOI before caching',async()=>{for(const doi of ['https://doi.org/10.9999/different',null]){const f=fixture();await assert.rejects(()=>lookup(f.db,'owner-123',f.env,'openalex','10.9999/test',1,AbortSignal.timeout(2000),{fetcher:(async()=>Response.json({...OA,doi})) as any}),(e:any)=>e.code==='scholarly_conflict');assert.equal(f.sql.prepare('SELECT count(*) n FROM scholarly_cache').get()!.n,0);f.sql.close()}});
test('stale connection test revision cannot use a new key/configuration',async()=>{const f=fixture();await savedKey(f,'openalex','TEST_KEY_NOT_REAL');await assert.rejects(()=>lookup(f.db,'owner-123',f.env,'openalex','10.9999/test',1,AbortSignal.timeout(2000),{expectedRevision:0,fetcher:(async()=>{throw Error('must not contact')}) as any}),(e:any)=>e.code==='settings_conflict');assert.equal(f.sql.prepare('SELECT count(*) n FROM scholarly_usage').get()!.n,0);f.sql.close()});
test('conflicting comparison evidence cannot become a trusted paper identity alias',async()=>{const {existingPaper}=await import('./api.ts');const f=fixture();const p=await savePaper(f.db,{doi:'10.9999/original',title:'Original authoritative paper',url:'https://doi.org/10.9999/original',publisher:'IEEE',journal:'Original',sourceId:'test',issn:'',publishedAt:null,datePrecision:null,authors:[],affiliations:[],abstract:null,keywords:[],provenance:{title:'crossref'},sourceIndexedAt:null,discovery:'crossref'});const different=normalizeRecord('openalex',{...OA,id:'https://openalex.org/W99999',doi:'https://doi.org/10.9999/unrelated'});await saveEvidence(f.db,p.id,different);assert.equal(await existingPaper(f.db,different),null);f.sql.close()});
test('explicit replacement key rearms auth breaker without resetting budget or cooldown',async()=>{const f=fixture();try{await savedKey(f,'openalex','FIRST_TEST_KEY');await assert.rejects(()=>lookup(f.db,'owner-123',f.env,'openalex','10.9999/test',1,AbortSignal.timeout(1000),{fetcher:(async()=>new Response('',{status:401})) as any}));const before=f.sql.prepare("SELECT * FROM scholarly_usage WHERE service='openalex'").get()!;assert.equal(before.blocked_code,'scholarly_auth');f.sql.prepare('UPDATE scholarly_usage SET cooldown_until=?').run(Date.now()+60000);const r=await request(f,'settings',{service:'openalex',endpoint:SERVICES.openalex.endpoint,apiKey:'REPLACEMENT_TEST_KEY',revision:1,confirmedDestination:SERVICES.openalex.endpoint});assert.equal(r.status,200);const after=f.sql.prepare("SELECT * FROM scholarly_usage WHERE service='openalex'").get()!;assert.equal(after.blocked_code,null);assert.equal(after.used,before.used);assert.ok(Number(after.cooldown_until)>Date.now());}finally{f.sql.close()}});
