import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import {strict as assert} from 'node:assert';
const OA={id:'https://openalex.org/W12345',doi:'https://doi.org/10.9999/test',title:'TCAD interface trap test',publication_year:2026,authorships:[{author:{display_name:'Researcher'},author_position:'first',institutions:[]}],abstract_inverted_index:{TCAD:[0],test:[1]},primary_location:{source:{display_name:'Test Journal'}},cited_by_count:2};
const S2={paperId:'b'.repeat(40),externalIds:{DOI:'10.9999/test'},title:OA.title,year:2026,authors:[{name:'Researcher'}],abstract:null};
const KEY='WORKER_ONLY_NOT_REAL_KEY';let requests=0;
const outboundService=async r=>{requests++;assert.ok(!r.url.includes(KEY));assert.equal(r.headers.get('cookie'),null);assert.ok(!r.url.includes('deepseek')&&!r.url.includes('kimi'));if(new URL(r.url).hostname==='api.openalex.org'){assert.equal(r.headers.get('authorization'),'Bearer '+KEY);assert.equal(r.headers.get('x-api-key'),null);return Response.json(OA)}assert.equal(r.headers.get('authorization'),null);assert.equal(r.headers.get('x-api-key'),null);return Response.json(S2)};
const mf=new Miniflare(convertV4MiniflareOptions({outboundService,modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)},assets:{directory:'dist/client',binding:'ASSETS',run_worker_first:true,routerConfig:{has_user_worker:true}}}));
try{
const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const statement of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();
const owner={'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.org'},headers={...owner,origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'};
const req=(path,body,auth=true)=>mf.dispatchFetch('https://local.test/api/site/scholarly/'+path,{method:body===undefined?'GET':'POST',headers:auth?(body===undefined?owner:headers):{},body:body===undefined?undefined:JSON.stringify(body)});
assert.equal((await req('settings',undefined,false)).status,403);assert.equal((await req('settings')).status,200);assert.equal(requests,0);
const initialAI=await (await mf.dispatchFetch('https://local.test/api/site/ai/settings',{headers:owner})).json();const aiSaved=await mf.dispatchFetch('https://local.test/api/site/ai/settings',{method:'POST',headers,body:JSON.stringify({...initialAI,endpoint:'https://api.deepseek.com',model:'deepseek-flash',reasoning:'max',maxTokens:1048576,apiKey:'DEEPSEEK_TEST_ONLY_NOT_REAL',confirmedDestination:'https://api.deepseek.com',enabled:true})});assert.equal(aiSaved.status,200);const aiBefore=await db.prepare('SELECT * FROM ai_settings').first();
assert.equal((await req('settings',{service:'openalex',endpoint:'https://api.openalex.org',revision:0,apiKey:KEY,confirmedDestination:'https://api.openalex.org'})).status,200);
const safe=await (await req('settings')).text();assert.ok(!safe.includes(KEY)&&!safe.includes('cipher'));const cipher=await db.prepare('SELECT key_ciphertext FROM scholarly_settings').first();assert.ok(cipher.key_ciphertext&&!cipher.key_ciphertext.includes(KEY));
const search=await req('search',{query:'10.9999/test',services:['openalex','semanticscholar'],page:1});assert.equal(search.status,200);const data=await search.json();assert.ok(data.results.every(r=>r.ok),JSON.stringify(data));assert.equal(requests,2);assert.equal(data.results[0].records[0].abstract,'TCAD test');assert.equal(data.results[1].records[0].abstract,null);
await req('search',{query:'10.9999/test',services:['openalex','semanticscholar'],page:1});assert.equal(requests,2);
const g=data.results[0],body={cacheKey:g.cacheKey,recordId:g.records[0].recordId};const imported=await (await req('apply',body)).json();assert.equal(imported.added,true);assert.equal((await req('apply',body)).status,200);assert.equal((await db.prepare('SELECT count(*) n FROM research_papers').first()).n,1);
const check=await (await req('check',{paperId:imported.paperId,services:['openalex']})).json();assert.equal(check.results[0].records[0].comparison.canMerge,true);assert.equal(requests,2);
const page=await mf.dispatchFetch('https://local.test/research/'+imported.paperId);assert.equal(page.status,200);const html=await page.text();assert.ok(html.includes('跨库元数据核对'));assert.ok(!html.includes(KEY));assert.equal((await mf.dispatchFetch('https://local.test/settings')).status,200);
assert.deepEqual(await db.prepare('SELECT * FROM ai_settings').first(),aiBefore);assert.equal((await db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0);assert.equal((await db.prepare('SELECT count(*) n FROM research_records').first()).n,1);
console.log('SCHOLARLY WORKER OK: migration, owner isolation, AES-GCM key save/no readback, header isolation, cache, exact import/replay, comparison, SSR, unchanged DeepSeek configuration, zero LLM calls');
}finally{await mf.dispose()}
process.exit(0);
