import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
export const sources = sqliteTable('site_sources', {id:text('id').primaryKey(), name:text('name').notNull(), url:text('url').notNull(), kind:text('kind').notNull(), lastChecked:text('last_checked'), lastSuccess:text('last_success'), error:text('error'), count:integer('count').notNull().default(0)});
export const items = sqliteTable('site_items', {id:text('id').primaryKey(), sourceId:text('source_id').notNull(), url:text('url').notNull().unique(), title:text('title').notNull(), summary:text('summary'), publishedAt:text('published_at'), discoveredAt:text('discovered_at').notNull()},t=>[index('idx_site_items_time').on(t.publishedAt),index('idx_site_items_source').on(t.sourceId)]);
export const researchPapers=sqliteTable('research_papers',{
 id:text('id').primaryKey(),doi:text('doi').unique(),title:text('title').notNull(),normalizedTitle:text('normalized_title').notNull(),url:text('url').notNull(),publisher:text('publisher').notNull(),journal:text('journal').notNull(),sourceId:text('source_id').notNull(),issn:text('issn').notNull(),publishedAt:text('published_at'),datePrecision:text('date_precision'),authors:text('authors_json').notNull(),affiliations:text('affiliations_json').notNull(),abstract:text('abstract'),keywords:text('keywords_json').notNull(),topics:text('topics_json').notNull(),provenance:text('provenance_json').notNull(),relevance:integer('relevance').notNull(),priority:integer('priority').notNull(),reasons:text('reasons_json').notNull(),ruleVersion:text('rule_version').notNull(),sourceIndexedAt:text('source_indexed_at'),firstSeen:text('first_seen').notNull(),lastSeen:text('last_seen').notNull(),updatedAt:text('updated_at').notNull()
},t=>[index('idx_research_papers_priority').on(t.priority,t.publishedAt),index('idx_research_papers_publisher').on(t.publisher,t.priority),index('idx_research_papers_title').on(t.normalizedTitle,t.sourceId),index('idx_research_papers_source').on(t.sourceId),index('idx_research_papers_url').on(t.url)]);
export const researchSources=sqliteTable('research_sources',{id:text('id').primaryKey(),publisher:text('publisher').notNull(),name:text('name').notNull(),issn:text('issn').notNull(),rssUrl:text('rss_url').notNull(),lastChecked:text('last_checked'),lastSuccess:text('last_success'),watermark:text('watermark'),cursor:text('cursor'),windowEnd:text('window_end'),windowStart:text('window_start'),error:text('error'),rssStatus:text('rss_status'),rssError:text('rss_error'),count:integer('count').notNull().default(0)});
export const researchRecords=sqliteTable('research_records',{id:text('id').primaryKey(),paperId:text('paper_id').notNull(),sourceId:text('source_id').notNull(),channel:text('channel').notNull(),recordUrl:text('record_url').notNull(),retrievedAt:text('retrieved_at').notNull(),fields:text('fields_json').notNull()},t=>[index('idx_research_records_paper').on(t.paperId)]);
export const researchRuns=sqliteTable('research_runs',{id:text('id').primaryKey(),startedAt:text('started_at').notNull(),finishedAt:text('finished_at'),status:text('status').notNull(),sourceId:text('source_id'),added:integer('added').notNull().default(0),updated:integer('updated').notNull().default(0),details:text('details_json').notNull().default('{}')});
export const researchSettings=sqliteTable('research_settings',{key:text('key').primaryKey(),value:text('value').notNull()});

// Owner-scoped AI configuration. Provider credentials are AES-256-GCM ciphertext only.
export const aiSettings=sqliteTable('ai_settings',{ownerId:text('owner_id').primaryKey(),endpoint:text('endpoint').notNull(),model:text('model').notNull(),protocol:text('protocol').notNull(),reasoning:text('reasoning').notNull(),keyCiphertext:text('key_ciphertext'),enabled:integer('enabled').notNull().default(0),dailyLimit:integer('daily_limit').notNull().default(20),maxTokens:integer('max_tokens').notNull().default(4096),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),testedAt:text('tested_at'),testStatus:text('test_status')});
export const aiPreferences=sqliteTable('ai_preferences',{ownerId:text('owner_id').primaryKey(),value:text('value_json').notNull(),revision:integer('revision').notNull().default(0)});
export const aiProposals=sqliteTable('ai_proposals',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),before:text('before_json').notNull(),after:text('after_json').notNull(),revision:integer('revision').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull(),expiresAt:text('expires_at').notNull()},t=>[index('idx_ai_proposals_owner').on(t.ownerId,t.createdAt)]);
export const aiRequests=sqliteTable('ai_requests',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),fingerprint:text('fingerprint').notNull(),status:text('status').notNull(),result:text('result_json'),createdAt:text('created_at').notNull()});
export const aiReceipts=sqliteTable('ai_receipts',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),requestId:text('request_id').notNull(),purpose:text('purpose').notNull(),model:text('model').notNull(),status:text('status').notNull(),response:text('response_json'),usage:text('usage_json'),createdAt:text('created_at').notNull(),finishedAt:text('finished_at')},t=>[index('idx_ai_receipts_budget').on(t.ownerId,t.createdAt)]);

// Content-free diagnostics only; independent retention never touches research or AI receipts.
export const runtimeLogs=sqliteTable('runtime_logs',{id:integer('id').primaryKey({autoIncrement:true}),createdAt:text('created_at').notNull(),severity:text('severity').notNull(),component:text('component').notNull(),event:text('event').notNull(),outcome:text('outcome').notNull(),errorCode:text('error_code'),httpStatus:integer('http_status'),phase:text('phase'),correlationId:text('correlation_id'),taskId:text('task_id'),requestId:text('request_id'),sourceId:text('source_id'),durationMs:integer('duration_ms'),metadata:text('metadata_json').notNull().default('{}')},t=>[index('idx_runtime_logs_created').on(t.createdAt,t.id),index('idx_runtime_logs_severity').on(t.severity,t.id),index('idx_runtime_logs_component').on(t.component,t.id)]);

// Independent, owner-scoped scholarly credentials; never reused from AI settings.
export const scholarlySettings=sqliteTable('scholarly_settings',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),service:text('service').notNull(),endpoint:text('endpoint').notNull(),keyCiphertext:text('key_ciphertext'),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull(),testedAt:text('tested_at'),testStatus:text('test_status'),testCode:text('test_code')});
export const scholarlyCache=sqliteTable('scholarly_cache',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),service:text('service').notNull(),payload:text('payload_json').notNull(),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_scholarly_cache_owner').on(t.ownerId,t.createdAt),index('idx_scholarly_cache_expiry').on(t.expiresAt)]);
export const scholarlyUsage=sqliteTable('scholarly_usage',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),service:text('service').notNull(),day:text('day').notNull(),used:integer('used').notNull(),nextAllowed:integer('next_allowed').notNull()});
