import { sqliteTable, text, integer, index, primaryKey } from 'drizzle-orm/sqlite-core';
export const sources = sqliteTable('site_sources', {id:text('id').primaryKey(), name:text('name').notNull(), url:text('url').notNull(), kind:text('kind').notNull(), lastChecked:text('last_checked'), lastSuccess:text('last_success'), error:text('error'), count:integer('count').notNull().default(0)});
export const items = sqliteTable('site_items', {id:text('id').primaryKey(), sourceId:text('source_id').notNull(), url:text('url').notNull().unique(), title:text('title').notNull(), summary:text('summary'), publishedAt:text('published_at'), discoveredAt:text('discovered_at').notNull()},t=>[index('idx_site_items_time').on(t.publishedAt),index('idx_site_items_source').on(t.sourceId)]);
export const researchPapers=sqliteTable('research_papers',{
 id:text('id').primaryKey(),doi:text('doi').unique(),title:text('title').notNull(),normalizedTitle:text('normalized_title').notNull(),url:text('url').notNull(),publisher:text('publisher').notNull(),journal:text('journal').notNull(),sourceId:text('source_id').notNull(),issn:text('issn').notNull(),publishedAt:text('published_at'),datePrecision:text('date_precision'),authors:text('authors_json').notNull(),affiliations:text('affiliations_json').notNull(),abstract:text('abstract'),keywords:text('keywords_json').notNull(),topics:text('topics_json').notNull(),provenance:text('provenance_json').notNull(),relevance:integer('relevance').notNull(),priority:integer('priority').notNull(),reasons:text('reasons_json').notNull(),ruleVersion:text('rule_version').notNull(),sourceIndexedAt:text('source_indexed_at'),firstSeen:text('first_seen').notNull(),lastSeen:text('last_seen').notNull(),updatedAt:text('updated_at').notNull(),contentHash:text('content_hash'),metadataHash:text('metadata_hash'),metadataRevision:integer('metadata_revision').notNull().default(0),metadataCheckedAt:text('metadata_checked_at')
},t=>[index('idx_research_papers_priority').on(t.priority,t.publishedAt),index('idx_research_papers_publisher').on(t.publisher,t.priority),index('idx_research_papers_title').on(t.normalizedTitle,t.sourceId),index('idx_research_papers_source').on(t.sourceId),index('idx_research_papers_url').on(t.url),index('idx_research_papers_updated').on(t.updatedAt),index('idx_research_papers_first_seen').on(t.firstSeen)]);
export const researchSources=sqliteTable('research_sources',{id:text('id').primaryKey(),publisher:text('publisher').notNull(),name:text('name').notNull(),issn:text('issn').notNull(),rssUrl:text('rss_url').notNull(),lastChecked:text('last_checked'),lastSuccess:text('last_success'),watermark:text('watermark'),cursor:text('cursor'),windowEnd:text('window_end'),windowStart:text('window_start'),error:text('error'),rssStatus:text('rss_status'),rssError:text('rss_error'),count:integer('count').notNull().default(0)});
export const researchRecords=sqliteTable('research_records',{id:text('id').primaryKey(),paperId:text('paper_id').notNull(),sourceId:text('source_id').notNull(),channel:text('channel').notNull(),recordUrl:text('record_url').notNull(),retrievedAt:text('retrieved_at').notNull(),fields:text('fields_json').notNull()},t=>[index('idx_research_records_paper').on(t.paperId)]);
export const researchRuns=sqliteTable('research_runs',{id:text('id').primaryKey(),startedAt:text('started_at').notNull(),finishedAt:text('finished_at'),status:text('status').notNull(),sourceId:text('source_id'),batchKey:text('batch_key'),entryPoint:text('entry_point').notNull().default('legacy_unknown'),added:integer('added').notNull().default(0),updated:integer('updated').notNull().default(0),details:text('details_json').notNull().default('{}')});
export const researchSettings=sqliteTable('research_settings',{key:text('key').primaryKey(),value:text('value').notNull()});

// Owner-scoped AI configuration. Provider credentials are AES-256-GCM ciphertext only.
export const aiSettings=sqliteTable('ai_settings',{ownerId:text('owner_id').primaryKey(),endpoint:text('endpoint').notNull(),model:text('model').notNull(),protocol:text('protocol').notNull(),reasoning:text('reasoning').notNull(),keyCiphertext:text('key_ciphertext'),enabled:integer('enabled').notNull().default(0),dailyLimit:integer('daily_limit').notNull().default(20),maxTokens:integer('max_tokens').notNull().default(4096),revision:integer('revision').notNull().default(1),updatedAt:text('updated_at').notNull(),testedAt:text('tested_at'),testStatus:text('test_status')});
export const aiPreferences=sqliteTable('ai_preferences',{ownerId:text('owner_id').primaryKey(),value:text('value_json').notNull(),revision:integer('revision').notNull().default(0)});
export const aiProposals=sqliteTable('ai_proposals',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),before:text('before_json').notNull(),after:text('after_json').notNull(),revision:integer('revision').notNull(),status:text('status').notNull(),createdAt:text('created_at').notNull(),expiresAt:text('expires_at').notNull()},t=>[index('idx_ai_proposals_owner').on(t.ownerId,t.createdAt)]);
export const aiRequests=sqliteTable('ai_requests',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),fingerprint:text('fingerprint').notNull(),status:text('status').notNull(),result:text('result_json'),createdAt:text('created_at').notNull()});
export const aiReceipts=sqliteTable('ai_receipts',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),requestId:text('request_id').notNull(),purpose:text('purpose').notNull(),model:text('model').notNull(),status:text('status').notNull(),response:text('response_json'),usage:text('usage_json'),createdAt:text('created_at').notNull(),finishedAt:text('finished_at')},t=>[index('idx_ai_receipts_budget').on(t.ownerId,t.createdAt)]);

// Content-free diagnostics only; independent retention never touches research or AI receipts.
export const runtimeLogs=sqliteTable('runtime_logs',{id:integer('id').primaryKey({autoIncrement:true}),createdAt:text('created_at').notNull(),severity:text('severity').notNull(),component:text('component').notNull(),event:text('event').notNull(),outcome:text('outcome').notNull(),errorCode:text('error_code'),httpStatus:integer('http_status'),phase:text('phase'),correlationId:text('correlation_id'),taskId:text('task_id'),requestId:text('request_id'),sourceId:text('source_id'),durationMs:integer('duration_ms'),metadata:text('metadata_json').notNull().default('{}')},t=>[index('idx_runtime_logs_created').on(t.createdAt,t.id),index('idx_runtime_logs_severity').on(t.severity,t.id),index('idx_runtime_logs_component').on(t.component,t.id)]);

// Independent, owner-scoped scholarly credentials; never reused from AI settings.
export const scholarlySettings=sqliteTable('scholarly_settings',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),service:text('service').notNull(),endpoint:text('endpoint').notNull(),keyCiphertext:text('key_ciphertext'),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull(),testedAt:text('tested_at'),testStatus:text('test_status'),testCode:text('test_code')});
export const scholarlyCache=sqliteTable('scholarly_cache',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),service:text('service').notNull(),payload:text('payload_json').notNull(),expiresAt:text('expires_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_scholarly_cache_owner').on(t.ownerId,t.createdAt),index('idx_scholarly_cache_expiry').on(t.expiresAt)]);
export const scholarlyUsage=sqliteTable('scholarly_usage',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),service:text('service').notNull(),day:text('day').notNull(),used:integer('used').notNull(),nextAllowed:integer('next_allowed').notNull()});

// Independent AnySearch credentials and bounded query receipts; no anonymous fallback.
export const anysearchSettings=sqliteTable('anysearch_settings',{ownerId:text('owner_id').primaryKey(),endpoint:text('endpoint').notNull(),keyCiphertext:text('key_ciphertext'),enabled:integer('enabled').notNull().default(0),revision:integer('revision').notNull(),updatedAt:text('updated_at').notNull(),testedAt:text('tested_at'),testStatus:text('test_status'),testCode:text('test_code')});
export const anysearchUsage=sqliteTable('anysearch_usage',{ownerId:text('owner_id').primaryKey(),day:text('day').notNull(),used:integer('used').notNull(),nextAllowed:integer('next_allowed').notNull()});
export const anysearchRequests=sqliteTable('anysearch_requests',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),fingerprint:text('fingerprint').notNull(),status:text('status').notNull(),result:text('result_json'),createdAt:text('created_at').notNull(),expiresAt:text('expires_at').notNull()},t=>[index('idx_anysearch_request_cache').on(t.ownerId,t.fingerprint,t.expiresAt),index('idx_anysearch_request_expiry').on(t.expiresAt)]);

// Versioned assessments never overwrite deterministic scores or author keywords.
export const researchAnalyses=sqliteTable('research_analyses',{id:text('id').primaryKey(),paperId:text('paper_id').notNull(),contentHash:text('content_hash').notNull(),configHash:text('config_hash').notNull(),config:text('config_json').notNull(),schemaVersion:text('schema_version').notNull(),status:text('status').notNull(),gate:text('gate_json').notNull(),result:text('result_json'),requestId:text('request_id'),errorCode:text('error_code'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_research_analyses_paper').on(t.paperId,t.updatedAt),index('idx_research_analyses_queue').on(t.status,t.createdAt)]);
export const researchChanges=sqliteTable('research_changes',{id:text('id').primaryKey(),paperId:text('paper_id').notNull(),channel:text('channel').notNull(),fields:text('fields_json').notNull(),before:text('before_json').notNull(),after:text('after_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('idx_research_changes_paper').on(t.paperId,t.createdAt)]);

// Personal reader actions are separate from source metadata and model assessments.
export const paperReaderState=sqliteTable('paper_reader_state',{ownerId:text('owner_id').notNull(),paperId:text('paper_id').notNull().references(()=>researchPapers.id),readAt:text('read_at'),favoriteAt:text('favorite_at'),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.ownerId,t.paperId]}),index('idx_paper_reader_favorites').on(t.ownerId,t.favoriteAt)]);

// Scheduled ingestion provenance and immutable, date-keyed AI daily archives.
export const researchBatches=sqliteTable('research_batches',{key:text('key').primaryKey(),date:text('date').notNull(),slot:integer('slot').notNull(),status:text('status').notNull(),sources:text('sources_json').notNull(),startedAt:text('started_at').notNull(),finishedAt:text('finished_at')});
export const researchBatchMembers=sqliteTable('research_batch_members',{paperId:text('paper_id').primaryKey(),runId:text('run_id').notNull(),batchKey:text('batch_key'),dailyCohortKey:text('daily_cohort_key'),firstSeen:text('first_seen').notNull(),snapshot:text('snapshot_json').notNull(),snapshotAt:text('snapshot_at').notNull()},t=>[index('idx_batch_members_batch').on(t.batchKey,t.firstSeen),index('idx_batch_members_cohort').on(t.dailyCohortKey,t.firstSeen)]);
export const researchDaily=sqliteTable('research_daily',{date:text('date').primaryKey(),sourceDate:text('source_date').notNull(),cutoff:text('cutoff').notNull(),status:text('status').notNull(),coverage:text('coverage_json').notNull(),selection:text('selection_json').notNull(),paperIds:text('paper_ids_json').notNull(),contentHash:text('content_hash').notNull(),schemaVersion:text('schema_version').notNull(),promptVersion:text('prompt_version').notNull(),revision:integer('revision').notNull().default(1),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),finishedAt:text('finished_at')});
export const researchDailyGroups=sqliteTable('research_daily_groups',{id:text('id').primaryKey(),date:text('date').notNull(),ordinal:integer('ordinal').notNull(),keyword:text('keyword').notNull(),status:text('status').notNull(),input:text('input_json').notNull(),paperIds:text('paper_ids_json').notNull(),contentHash:text('content_hash').notNull(),result:text('result_json'),config:text('config_json'),requestId:text('request_id'),errorCode:text('error_code'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('idx_daily_groups_queue').on(t.status,t.date,t.ordinal),index('idx_daily_groups_date').on(t.date,t.ordinal)]);

// Content-free per-page revisions and account acknowledgements, independent of paper reader state.
export const navigationContent=sqliteTable('navigation_content',{scope:text('scope').notNull(),pageKey:text('page_key').notNull(),revision:integer('revision').notNull().default(0)},t=>[primaryKey({columns:[t.scope,t.pageKey]})]);
export const navigationSeen=sqliteTable('navigation_seen',{ownerId:text('owner_id').notNull(),pageKey:text('page_key').notNull(),seenRevision:integer('seen_revision').notNull().default(0),seenVersion:integer('seen_version').notNull().default(0),enabled:integer('enabled').notNull().default(1)},t=>[primaryKey({columns:[t.ownerId,t.pageKey]})]);

export const researchAttributionRepairs=sqliteTable('research_attribution_repairs',{id:text('id').primaryKey(),paperId:text('paper_id').notNull(),runId:text('run_id').notNull(),previousCohort:text('previous_cohort'),dailyCohortKey:text('daily_cohort_key').notNull(),evidenceHash:text('evidence_hash').notNull(),ruleVersion:text('rule_version').notNull(),appliedAt:text('applied_at').notNull()});

// One bounded keyword maintenance pass; separate from paper ingestion and daily cohorts.
export const researchKeywordJobs=sqliteTable('research_keyword_jobs',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),paperIds:text('paper_ids_json').notNull(),cursor:integer('cursor').notNull().default(0),requests:integer('requests').notNull().default(0),status:text('status').notNull(),leaseUntil:text('lease_until'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),errorCode:text('error_code')});
