import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {anysearchApi} from './api.ts';
import {search,fetchJSON,reserveRequest,testConnection} from './provider.ts';
import {ENDPOINT,normalizeResults,publicResultUrl,validateQuery,validateLimit} from './domain.ts';
import {credentialContext} from './settings.ts';
import {unseal} from '../ai/security.ts';
import {aiApi,parseAnswer} from '../ai/api.ts';
import {normalizeToolArgs} from '../ai/tools.ts';
const KEY='TEST_ANYSEARCH_NOT_A_REAL_KEY',LLMKEY='TEST_LLM_NOT_A_REAL_KEY',OWNER='owner-123';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(statements:any[]){sql.exec('BEGIN');try{const r=statements.map(s=>s.runSync());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,env:{DB:db,HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)}}}
const headers={'oai-authenticated-user-id':OWNER,'oai-authenticated-user-email':'owner@example.org'};
async function req(f:any,path:string,body?:any,override:any={}){return anysearchApi(new Request('https://local.test/api/site/anysearch/'+path,{method:body===undefined?'GET':'POST',headers:{...headers,...(body===undefined?{}:{origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'}),...override},body:body===undefined?undefined:JSON.stringify(body)}),f.env)}
async function save(f:any,extra:any={}){const r=await req(f,'settings',{endpoint:ENDPOINT,enabled:true,revision:0,apiKey:KEY,confirmedDestination:ENDPOINT,...extra});assert.equal(r.status,200,await r.clone().text());return r.json()}
const payload=(results:any[]=[{title:'Official TCAD documentation',url:'https://tcad.org/documentation',snippet:'Public documentation about interface traps.',content:'RAW CONTENT MUST NOT LEAK'}])=>({code:0,message:'success',data:{results,metadata:{total_results:results.length,search_time_ms:12}}});
const mock=async()=>Response.json(payload());
const resetRate=(f:any)=>f.sql.exec('UPDATE anysearch_usage SET next_allowed=0');
async function withMock(fn:()=>Promise<void>,fetcher:any=mock){const prior=globalThis.fetch;globalThis.fetch=fetcher;try{await fn()}finally{globalThis.fetch=prior}}

test('query/limit validation and exact canonical agent arguments',()=>{assert.equal(validateQuery('  TCAD  '),'TCAD');for(const q of [null,'x','a'.repeat(501),'key\nquery'])assert.throws(()=>validateQuery(q));for(const n of [0,11,1.5,'10',null])assert.throws(()=>validateLimit(n));assert.deepEqual(normalizeToolArgs('search_web',{query:' TCAD ',maxResults:5}),{query:'TCAD',maxResults:5});assert.throws(()=>normalizeToolArgs('search_web',{query:'TCAD',maxResults:5,endpoint:'https://evil.org'}))});
test('result links reject unsafe protocols, local addresses, credentials, ports and deceptive hosts',()=>{for(const u of ['javascript:alert(1)','data:text/html,x','file:///etc/passwd','https://localhost/x','http://127.0.0.1','https://[::1]','https://user:pass@paper.org','https://paper.org:8080','https://a.local','https://a.internal','https://169.254.169.254','https://2130706433','https://paper.org/\n'])assert.equal(publicResultUrl(u),null,u);assert.equal(publicResultUrl('https://paper.org/article#section'),'https://paper.org/article')});
test('normalization preserves evidence and missingness, dedups, bounds and never fabricates dates/content',async()=>{const r=await normalizeResults(payload([{title:'a'.repeat(400),url:'https://tcad.org/a#one',snippet:'x'.repeat(1600),publishedAt:'2026-01-01'},{title:'duplicate',url:'https://tcad.org/a#two'},{title:'bad',url:'javascript:alert(1)'},{title:'',url:'https://tcad.org/b'}]),10,'2026-10-02T00:00:00Z');assert.equal(r.results.length,2);assert.equal(r.omitted,2);assert.equal(r.results[0]!.title.length,300);assert.equal(r.results[0]!.snippet!.length,1500);assert.equal(r.results[0]!.source,'tcad.org');assert.equal(r.results[0]!.publishedAt,null);assert.equal(r.results[0]!.contentTrust,'untrusted');assert.equal(r.results[1]!.title,'tcad.org');assert.equal(r.results[1]!.snippet,null);assert.equal(r.nextPage,null);assert.equal(r.truncated,true);assert.equal(r.results[0]!.retrievedAt,'2026-10-02T00:00:00Z');assert.ok(!JSON.stringify(r).includes('RAW CONTENT'));await assert.rejects(()=>normalizeResults({code:-1,message:KEY},10),(e:any)=>!e.message.includes(KEY))});
test('owner and same-origin checks block settings/search, GET never searches',async()=>{const f=fixture();try{await withMock(async()=>{assert.equal((await req(f,'settings',undefined,{'oai-authenticated-user-id':''})).status,403);assert.equal((await req(f,'settings',undefined,{'oai-authenticated-user-email':'viewer@example.org'})).status,403);for(const o of [{origin:''},{origin:'https://evil.org'},{'X-HKIS-Request':''},{'sec-fetch-site':'cross-site'}])assert.equal((await req(f,'search',{query:'TCAD'},o)).status,403);assert.equal((await req(f,'search')).status,405);assert.equal((await req(f,'settings')).status,200)},async()=>{throw Error('No external call allowed')})}finally{f.sql.close()}});
test('key is independently encrypted, owner/destination bound, never returned; arbitrary endpoints denied',async()=>{const f=fixture();try{const s=await save(f);assert.equal(s.hasKey,true);const row=f.sql.prepare('SELECT * FROM anysearch_settings').get()!;assert.ok(!JSON.stringify(row).includes(KEY));assert.equal(await unseal(row.key_ciphertext as string,f.env,credentialContext(OWNER)),KEY);for(const context of [credentialContext('other'),'scholarly|owner-123|openalex|https://api.openalex.org','owner-123|https://api.deepseek.com'])await assert.rejects(()=>unseal(row.key_ciphertext as string,f.env,context));assert.ok(!(await (await req(f,'settings')).text()).includes('cipher'));for(const endpoint of ['http://api.anysearch.com','https://api.anysearch.com.evil.org','https://api.anysearch.com/v1','https://127.0.0.1','https://api.anysearch.com?url=evil'])assert.equal((await req(f,'settings',{endpoint,revision:1,enabled:true})).status,400);assert.equal((await req(f,'settings',{endpoint:ENDPOINT,revision:0,enabled:true})).status,409)}finally{f.sql.close()}});
test('missing or disabled configuration never falls back to anonymous or other credentials',async()=>{const f=fixture();try{await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,{fetcher:async()=>{throw Error('must not call')}}),(e:any)=>e.code==='anysearch_not_configured');await save(f,{enabled:false});await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,{agent:true}),(e:any)=>e.code==='anysearch_disabled');const r=await search(f.db,OWNER,f.env,'TCAD',10,{fetcher:mock});assert.equal(r.results.length,1);resetRate(f);await req(f,'settings',{endpoint:ENDPOINT,revision:1,enabled:false,removeKey:true});await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10),(e:any)=>e.code==='anysearch_not_configured')}finally{f.sql.close()}});
test('transport uses fixed official destination/Bearer, no credentials in URL/body, no redirects or raw error messages',async()=>{let calls=0;await fetchJSON('/v1/search',KEY,AbortSignal.timeout(1000),{query:'TCAD',max_results:10},async(url:any,init:any)=>{calls++;assert.equal(url,ENDPOINT+'/v1/search');assert.equal(init.redirect,'manual');assert.equal(init.headers.Authorization,'Bearer '+KEY);assert.equal(init.headers.Cookie,undefined);assert.deepEqual(JSON.parse(init.body),{query:'TCAD',max_results:10,format:'json'});assert.ok(!init.body.includes(KEY));return Response.json(payload())});assert.equal(calls,1);for(const status of [301,302,307,400,401,402,403,415,429,502]){await assert.rejects(()=>fetchJSON('/v1/search',KEY,AbortSignal.timeout(1000),{query:'TCAD',max_results:10},async()=>new Response('username=PRIVATE password=SECRET api_key='+KEY,{status,headers:{location:'https://evil.org'}})),(e:any)=>!!e.code&&!e.message.includes(KEY)&&!e.message.includes('PRIVATE'))}await assert.rejects(()=>fetchJSON('https://evil.org' as any,KEY,AbortSignal.timeout(1000)),(e:any)=>e.code==='endpoint_not_allowed')});
test('business errors, invalid JSON, oversize body, timeout and key echoes are safely handled',async()=>{for(const response of [Response.json({code:-1,message:'password='+KEY}),new Response('{',{headers:{'content-type':'application/json'}}),new Response('notjson'),new Response('x',{headers:{'content-type':'application/json','content-length':'1000001'}}),new Response(' '.repeat(1000001),{headers:{'content-type':'application/json'}})])await assert.rejects(()=>fetchJSON('/v1/search',KEY,AbortSignal.timeout(1000),{query:'TCAD',max_results:10},async()=>response),(e:any)=>['anysearch_format','anysearch_too_large'].includes(e.code)&&!e.message.includes(KEY));await assert.rejects(()=>fetchJSON('/v1/search',KEY,AbortSignal.abort(),{query:'TCAD',max_results:10},async()=>{throw Error(KEY)}),(e:any)=>e.code==='anysearch_timeout');const r=await fetchJSON('/v1/search',KEY,AbortSignal.timeout(1000),{query:'TCAD',max_results:10},async()=>Response.json(payload([{title:KEY,url:'https://tcad.org/x',snippet:'Bearer '+KEY}])));assert.ok(!JSON.stringify(r).includes(KEY))});
test('cache/replay reuse paid result, key revisions isolate cache, expired result does not replay',async()=>{const f=fixture();let calls=0;try{await save(f);const options={requestId:crypto.randomUUID(),fetcher:async()=>{calls++;return mock()}};const first=await search(f.db,OWNER,f.env,'TCAD',10,options);assert.equal(first.cached,false);assert.equal((await search(f.db,OWNER,f.env,'TCAD',10,options)).cached,true);assert.equal((await search(f.db,OWNER,f.env,'TCAD',10,{...options,requestId:crypto.randomUUID()})).cached,true);assert.equal(calls,1);await assert.rejects(()=>search(f.db,OWNER,f.env,'Other',10,options),(e:any)=>e.code==='request_conflict');f.sql.exec("UPDATE anysearch_requests SET expires_at='2000-01-01'");await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,options),(e:any)=>e.code==='request_already_attempted');assert.equal(f.sql.prepare('SELECT result_json FROM anysearch_requests').get()!.result_json,null);assert.equal(calls,1);resetRate(f);await req(f,'settings',{endpoint:ENDPOINT,enabled:true,revision:1});await search(f.db,OWNER,f.env,'TCAD',10,{...options,requestId:crypto.randomUUID()});assert.equal(calls,2)}finally{f.sql.close()}});
test('failure is receipted without content, does not auto retry, and same ID cannot incur another call',async()=>{const f=fixture();let calls=0;try{await save(f);const options={requestId:crypto.randomUUID(),fetcher:async()=>{calls++;return new Response('password='+KEY,{status:402})}};await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,options),(e:any)=>e.code==='anysearch_quota');resetRate(f);await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,options),(e:any)=>e.code==='request_already_attempted');assert.equal(calls,1);assert.equal(f.sql.prepare('SELECT status FROM anysearch_requests').get()!.status,'failed');assert.ok(!JSON.stringify(f.sql.prepare('SELECT * FROM runtime_logs').all()).includes(KEY));assert.ok(!JSON.stringify(f.sql.prepare('SELECT * FROM runtime_logs').all()).includes('TCAD'))}finally{f.sql.close()}});
test('shared D1 budget admits exactly 100 attempts and atomic throttle prevents concurrent requests',async()=>{const f=fixture();try{const now=Date.now();for(let i=0;i<100;i++)await reserveRequest(f.db,OWNER,now+i*2000);await assert.rejects(()=>reserveRequest(f.db,OWNER,now+202000),(e:any)=>e.code==='anysearch_budget');assert.equal(f.sql.prepare('SELECT used FROM anysearch_usage').get()!.used,100);const results=await Promise.allSettled(Array.from({length:8},()=>reserveRequest(f.db,'different-owner',now)));assert.equal(results.filter(r=>r.status==='fulfilled').length,1)}finally{f.sql.close()}});
test('search in flight is not duplicated after cooldown; unsafe query and pagination are rejected',async()=>{const f=fixture();try{await save(f);const options={requestId:crypto.randomUUID(),fetcher:async()=>{throw Error('not executed')}};await assert.rejects(()=>search(f.db,OWNER,f.env,KEY,10,options),(e:any)=>e.code==='invalid_query');assert.equal((await req(f,'search',{query:'TCAD',page:2,requestId:crypto.randomUUID()})).status,400);let resolve:(r:Response)=>void=()=>{};const pending=search(f.db,OWNER,f.env,'TCAD',10,{fetcher:()=>new Promise(r=>{resolve=r})});await new Promise(r=>setTimeout(r,15));resetRate(f);await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,{fetcher:mock}),(e:any)=>e.code==='request_busy');resolve(Response.json(payload()));await pending}finally{f.sql.close()}});
test('connection test reads only quota-free capabilities and reports honest scope',async()=>{const f=fixture();try{await save(f);const result=await testConnection(f.db,OWNER,f.env,1,async(url:any,init:any)=>{assert.equal(url,ENDPOINT+'/v1/sub-domains?domain=code');assert.equal(init.method,'GET');assert.equal(init.headers.Authorization,'Bearer '+KEY);return Response.json({code:0,data:{domains:[{domain:'code',sub_domains:[]}]}})});assert.match(result.message,/尚未执行搜索/);assert.equal(f.sql.prepare('SELECT test_status FROM anysearch_settings').get()!.test_status,'ok');assert.equal(f.sql.prepare('SELECT count(*) n FROM anysearch_requests').get()!.n,0)}finally{f.sql.close()}});
test('external citations use exact fetched IDs, unknown citations blocked and missing paper abstracts remain guarded',async()=>{const r=await normalizeResults(payload(),10),web=new Map(r.results.map(x=>[x.id,x]));const id=r.results[0]!.id;const parsed=parseAnswer(JSON.stringify({answer:'官方资料 [web:'+id+']',paperIds:[],webIds:[id],analyses:[]}),new Map(),web);assert.equal(parsed.webResults[0].url,'https://tcad.org/documentation');assert.match(parsed.answer,/官方资料/);for(const cite of ['a'.repeat(24),'malicious'])assert.throws(()=>parseAnswer(JSON.stringify({answer:'[web:'+cite+']',paperIds:[],analyses:[]}),new Map(),web),(e:any)=>e.code==='unknown_citation');const mixed=parseAnswer(JSON.stringify({answer:'UNVERIFIED [paper:p] [web:'+id+']',paperIds:['p'],webIds:[id],analyses:[]}),new Map([['p',{id:'p',abstract:null}]]),web);assert.ok(!mixed.answer.includes('UNVERIFIED'))});
async function configureAI(f:any){const request=new Request('https://local.test/api/site/ai/settings',{method:'POST',headers:{...headers,origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'},body:JSON.stringify({endpoint:'https://api.deepseek.com',model:'deepseek-flash',protocol:'responses',reasoning:'max',maxTokens:384000,dailyLimit:30,enabled:true,revision:0,apiKey:LLMKEY,confirmedDestination:'https://api.deepseek.com'})});assert.equal((await aiApi(request,f.env)).status,200)}
async function chat(f:any){return aiApi(new Request('https://local.test/api/site/ai/chat',{method:'POST',headers:{...headers,origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'},body:JSON.stringify({message:'查询公开 TCAD 文档',requestId:crypto.randomUUID()})}),f.env)}
test('Agent receives real external evidence, caches repeated calls, retains 5/15/200 governor and preserves LLM config',async()=>{const f=fixture();let modelCalls=0,webCalls=0;try{await save(f);await configureAI(f);const before=f.sql.prepare('SELECT * FROM ai_settings').get();await withMock(async()=>{const r=await chat(f);assert.equal(r.status,200);const d=await r.json();assert.equal(d.partial,true);assert.equal(d.stopReason,'identical_tool_limit');assert.equal(d.toolCalls,5);assert.equal(d.cacheHits,4);assert.equal(d.webResults.length,1);assert.equal(webCalls,1);assert.equal(modelCalls,1);assert.deepEqual(f.sql.prepare('SELECT * FROM ai_settings').get(),before)},async(url:any,init:any)=>{if(String(url).includes('anysearch')){webCalls++;assert.equal(init.headers.Authorization,'Bearer '+KEY);assert.ok(!init.body.includes(LLMKEY));return mock()}modelCalls++;assert.equal(init.headers.Authorization,'Bearer '+LLMKEY);assert.ok(!init.body.includes(KEY));return Response.json({output:Array.from({length:6},(_,i)=>({type:'function_call',call_id:'web'+i,name:'search_web',arguments:'{"query":"TCAD","maxResults":10}'}))})})}finally{f.sql.close()}});
test('Agent final answer cites fetched external results; unavailable AnySearch surfaces setup without fabrication',async()=>{const f=fixture();let modelCalls=0;try{await save(f);await configureAI(f);await withMock(async()=>{const r=await chat(f),d=await r.json();assert.equal(r.status,200);assert.equal(d.partial,false);assert.equal(d.webResults.length,1);assert.match(d.answer,/官方文档/);assert.equal(d.webResults[0].source,'tcad.org')},async(url:any,init:any)=>{if(String(url).includes('anysearch'))return mock();modelCalls++;if(modelCalls===1)return Response.json({output:[{type:'function_call',call_id:'s1',name:'search_web',arguments:'{"query":"TCAD","maxResults":10}'}]});const b=JSON.parse(init.body),out=JSON.parse(b.input.find((v:any)=>v.type==='function_call_output').output),id=out.webResults[0].id;return Response.json({output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'官方文档 [web:'+id+']',paperIds:[],webIds:[id],analyses:[]})}]}]})});await req(f,'settings',{endpoint:ENDPOINT,enabled:false,removeKey:true,revision:1});modelCalls=0;await withMock(async()=>{const d=await (await chat(f)).json();assert.equal(d.webResults.length,0);assert.equal(d.webSearchErrors[0].setupUrl,'/settings#anysearch');assert.ok(!d.answer.includes('FABRICATED'))},async(url:any)=>{assert.ok(!String(url).includes('anysearch'));modelCalls++;return modelCalls===1?Response.json({output:[{type:'function_call',call_id:'s2',name:'search_web',arguments:'{"query":"TCAD","maxResults":10}'}]}):Response.json({output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({answer:'FABRICATED',paperIds:[],analyses:[]})}]}]})})}finally{f.sql.close()}});
test('cache-hit IDs are bound to query and cannot turn into another paid call after expiry',async()=>{const f=fixture();let calls=0;try{await save(f);const fetcher=async()=>{calls++;return mock()};await search(f.db,OWNER,f.env,'TCAD',10,{fetcher});const second=crypto.randomUUID();await search(f.db,OWNER,f.env,'TCAD',10,{fetcher,requestId:second});assert.equal(f.sql.prepare('SELECT status,result_json FROM anysearch_requests WHERE id=?').get(OWNER+':'+second)!.status,'cached');resetRate(f);await assert.rejects(()=>search(f.db,OWNER,f.env,'Different query',10,{fetcher,requestId:second}),(e:any)=>e.code==='request_conflict');f.sql.exec("UPDATE anysearch_requests SET expires_at='2000-01-01'");await assert.rejects(()=>search(f.db,OWNER,f.env,'TCAD',10,{fetcher,requestId:second}),(e:any)=>e.code==='request_already_attempted');assert.equal(calls,1)}finally{f.sql.close()}});
test('identical failed Agent web calls are cached, not automatically charged again',async()=>{const f=fixture();let model=0,web=0;try{await save(f);await configureAI(f);await withMock(async()=>{const d=await (await chat(f)).json();assert.equal(d.stopReason,'identical_tool_limit');assert.equal(d.toolExecutions,1);assert.equal(d.cacheHits,4);assert.equal(web,1)},async(url:any)=>{if(String(url).includes('anysearch')){web++;return new Response('secret error',{status:502})}model++;resetRate(f);return Response.json({output:Array.from({length:3},(_,i)=>({type:'function_call',call_id:'fail'+model+'-'+i,name:'search_web',arguments:'{"query":"TCAD","maxResults":10}'}))})})}finally{f.sql.close()}});
test('uncited fallback marks truncation if more than 20 actual web sources were read',()=>{const entries=Array.from({length:21},(_,i)=>[i.toString(16).padStart(24,'0'),{id:i.toString(16).padStart(24,'0'),url:'https://tcad.org/'+i,source:'tcad.org'}] as [string,any]);const d=parseAnswer(JSON.stringify({answer:'missing citations',paperIds:[],analyses:[]}),new Map(),new Map(entries));assert.equal(d.webResults.length,20);assert.equal(d.displayTruncated,true)});
test('preference updates cannot reset failed-search protection in a live Agent task',async()=>{const f=fixture();let model=0,web=0;try{await save(f);await configureAI(f);await withMock(async()=>{const d=await (await chat(f)).json();assert.equal(d.toolExecutions,1);assert.equal(d.cacheHits,1);assert.equal(web,1)},async(url:any)=>{if(String(url).includes('anysearch')){web++;return new Response('unavailable',{status:502})}model++;if(model===2){f.sql.exec("INSERT INTO ai_preferences(owner_id,value_json,revision) VALUES('owner-123','{\"keywords\":[],\"excludedKeywords\":[],\"sourceIntervals\":{}}',1) ON CONFLICT(owner_id) DO UPDATE SET revision=revision+1");resetRate(f)}if(model<3)return Response.json({output:[{type:'function_call',call_id:'r'+model,name:'search_web',arguments:'{"query":"TCAD","maxResults":10}'}]});return Response.json({output:[{type:'message',content:[{type:'output_text',text:'{"answer":"无结果","paperIds":[],"analyses":[]}'}]}]})})}finally{f.sql.close()}});
