import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
import {readFile,readdir} from 'node:fs/promises';
import {strict as assert} from 'node:assert';
const KEY='WORKER_ONLY_ANYSEARCH_TEST_KEY',LLM='WORKER_ONLY_LLM_KEY';let calls=0,model=0,scenario='search';
const outboundService=async r=>{
 const url=new URL(r.url);assert.equal(r.headers.get('cookie'),null);
 if(url.hostname==='api.deepseek.com'){model++;assert.equal(r.headers.get('authorization'),'Bearer '+LLM);const b=await r.json();assert.equal(b.model,'deepseek-flash');assert.equal(b.max_output_tokens,384000);assert.ok(!JSON.stringify(b).includes(KEY));return Response.json({output:Array.from({length:6},(_,i)=>({type:'function_call',call_id:'web'+i,name:'search_web',arguments:'{"query":"TCAD external","maxResults":10}'}))})}
 calls++;assert.equal(url.origin,'https://api.anysearch.com');assert.equal(r.headers.get('authorization'),'Bearer '+KEY);
 if(url.pathname==='/v1/sub-domains'){assert.equal(r.method,'GET');return Response.json({code:0,data:{domains:[{domain:'code',sub_domains:[]}]}})}
 assert.equal(url.pathname,'/v1/search');assert.equal(r.method,'POST');const body=await r.json();assert.equal(body.max_results,10);assert.equal(body.format,'json');assert.ok(!JSON.stringify(body).includes(KEY));if(scenario==='redirect')return new Response(null,{status:307,headers:{Location:'https://evil.org'}});return Response.json({code:0,data:{results:[{title:'Actual fixture title',url:'https://tcad.org/source',snippet:'Fixture source evidence'}, {title:'Unsafe',url:'javascript:alert(1)'}]}});
};
const mf=new Miniflare(convertV4MiniflareOptions({outboundService,modules:true,scriptPath:'dist/server/index.js',compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],bindings:{HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)},assets:{directory:'dist/client',binding:'ASSETS',run_worker_first:true,routerConfig:{has_user_worker:true}}}));
try{
const db=await mf.getD1Database('DB');for(const file of (await readdir('drizzle')).filter(f=>f.endsWith('.sql')).sort())for(const statement of (await readFile('drizzle/'+file,'utf8')).split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();
const owner={'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.org'},headers={...owner,origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'};
const req=(path,body,auth=true)=>mf.dispatchFetch('https://local.test/api/site/anysearch/'+path,{method:body===undefined?'GET':'POST',headers:auth?(body===undefined?owner:headers):{},body:body===undefined?undefined:JSON.stringify(body)});
const initial=await (await req('settings')).json();assert.equal(initial.hasKey,false);assert.equal(initial.enabled,false);assert.equal((await req('settings',undefined,false)).status,403);assert.equal((await req('search',{query:'TCAD',requestId:crypto.randomUUID()})).status,409);assert.equal(calls,0);
const llm=await mf.dispatchFetch('https://local.test/api/site/ai/settings',{method:'POST',headers,body:JSON.stringify({endpoint:'https://api.deepseek.com',model:'deepseek-flash',protocol:'responses',reasoning:'max',maxTokens:384000,dailyLimit:30,enabled:true,revision:0,apiKey:LLM,confirmedDestination:'https://api.deepseek.com'})});assert.equal(llm.status,200);const before=await db.prepare('SELECT * FROM ai_settings').first();
assert.equal((await req('settings',{...initial,apiKey:KEY,confirmedDestination:initial.endpoint,enabled:true})).status,200);const text=await (await req('settings')).text();assert.ok(!text.includes(KEY)&&!text.includes('cipher'));const row=await db.prepare('SELECT key_ciphertext FROM anysearch_settings').first();assert.ok(!row.key_ciphertext.includes(KEY));assert.equal(calls,0);
const body={query:'TCAD',maxResults:10,requestId:crypto.randomUUID()},r=await req('search',body),d=await r.json();assert.equal(r.status,200,JSON.stringify(d));assert.equal(d.results.length,1);assert.equal(d.omitted,1);assert.equal(d.results[0].source,'tcad.org');assert.equal(d.results[0].publishedAt,null);assert.equal(calls,1);assert.equal((await (await req('search',body)).json()).cached,true);const cachedBody={...body,requestId:crypto.randomUUID()};assert.equal((await (await req('search',cachedBody)).json()).cached,true);assert.equal((await req('search',{...cachedBody,query:'different'})).status,409);assert.equal(calls,1);
await db.prepare('UPDATE anysearch_usage SET next_allowed=0').run();assert.equal((await req('test',{revision:1})).status,200);assert.equal(calls,2);assert.equal(model,0);
await db.prepare('UPDATE anysearch_usage SET next_allowed=0').run();const response=await mf.dispatchFetch('https://local.test/api/site/ai/chat',{method:'POST',headers,body:JSON.stringify({message:'查询 TCAD 文档',requestId:crypto.randomUUID()})});const chat=await response.json();assert.equal(response.status,200,JSON.stringify(chat));assert.equal(chat.toolCalls,5);assert.equal(chat.cacheHits,4);assert.equal(chat.stopReason,'identical_tool_limit');assert.equal(chat.partial,true);assert.equal(chat.webResults.length,1);assert.equal(model,1);assert.equal(calls,3);
await db.prepare('UPDATE anysearch_usage SET next_allowed=0').run();scenario='redirect';const redirect=await req('search',{query:'new query',requestId:crypto.randomUUID()});assert.equal(redirect.status,502);assert.equal((await redirect.json()).code,'anysearch_redirect');assert.equal(calls,4);
assert.deepEqual(await db.prepare('SELECT * FROM ai_settings').first(),before);assert.equal((await db.prepare('SELECT count(*) n FROM research_papers').first()).n,0);const logs=await db.prepare('SELECT * FROM runtime_logs').all();assert.ok(logs.results.some(r=>r.component==='anysearch'));assert.ok(!JSON.stringify(logs).includes(KEY));assert.ok(!JSON.stringify(logs).includes('TCAD'));
for(const path of ['/changelog','/daily','/all','/hot','/settings']){const r=await mf.dispatchFetch('https://local.test'+path),html=await r.text();assert.equal(r.status,200);assert.ok(html.includes('quick-search-desktop')&&html.includes('quick-search-mobile'));assert.equal((html.match(/<dialog/g)||[]).length,2);if(path==='/changelog'){assert.ok(html.includes('aria-expanded="false"'));assert.ok(html.includes('changelog-category-toggle'));assert.ok(html.includes('changelog-entry-title'));assert.ok(html.includes('changelog-content'));assert.ok(html.includes('id="d-2026-10-02"'))}}
assert.equal(calls,4);assert.equal(model,1);console.log('ANYSEARCH WORKER OK: incremental migrations, owner/CSRF, encrypted independent key, search/cache/replay, no redirects, Agent 5-call boundary and partial evidence, safe logs, unchanged LLM/research, SSR search/accordion UI; all providers mocked');
}finally{await mf.dispose()}
process.exit(0);
