import {Notice,ActionButton} from './ui/ResearchControls';
import {DisclosureSummary,DisclosureIndicator} from './ui/Interaction';
import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router';
import {aiRequest,type Proposal} from '../lib/ai-client';
import {WebResult} from './WebSearch';
import {AIProposal} from './AIProposal';
type Message={role:'user'|'assistant';content:string;papers?:any[];analyses?:any[];proposals?:Proposal[];notice?:string;displayTruncated?:boolean;webResults?:any[];webSearchErrors?:any[];dailyStatus?:{date:string|null;url:string;summary:string}};
function Citations({text,webResults=[],onNavigate}:{text:string;webResults?:any[];onNavigate:()=>void}){return <>{text.split(/(\[(?:paper:[\w-]+|web:[a-f0-9]{24})\])/g).map((part,i)=>{if(/^\[paper:/.test(part))return <Link key={i} to={'/research/'+part.slice(7,-1)} className="ai-inline-cite" onClick={onNavigate}>[论文]</Link>;if(/^\[web:/.test(part)){const r=webResults.find(r=>r.id===part.slice(5,-1));return r?<a key={i} href={r.url} target="_blank" rel="noopener noreferrer" className="ai-inline-cite">[{r.source}]</a>:<span key={i}>[来源不可用]</span>}return <span key={i}>{part}</span>})}</>}

export function AIAssistant({home=false}:{home?:boolean}){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[paperIds,setPaperIds]=useState<string[]>([]),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[config,setConfig]=useState<any>(null),[allowProposals,setAllowProposals]=useState(false),[expanded,setExpanded]=useState(true);
 const inFlight=useRef(false),body=useRef<HTMLDivElement>(null);
 const dialog=useRef<HTMLDialogElement>(null),textarea=useRef<HTMLTextAreaElement>(null),opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{const listener=(e:Event)=>{opener.current=document.activeElement as HTMLElement;const d=(e as CustomEvent).detail;if(d?.message||d?.paperIds?.length){setInput(d?.message||'');setPaperIds(d?.paperIds||[]);}setExpanded(true);setOpen(true);if(home)requestAnimationFrame(()=>textarea.current?.focus({preventScroll:true}))};window.addEventListener('hkis:open-ai',listener);return()=>window.removeEventListener('hkis:open-ai',listener)},[home]);
 useEffect(()=>{if(home||open){let active=true;aiRequest('settings').then(c=>{if(active)setConfig(c)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}}},[home,open]);
 useEffect(()=>{if(home)return;if(open){dialog.current?.showModal();textarea.current?.focus()}else{dialog.current?.close();opener.current?.focus({preventScroll:true})}},[home,open]);
 useEffect(()=>{body.current?.scrollTo({top:body.current.scrollHeight,behavior:'auto'})},[messages,busy]);
 async function send(e:React.FormEvent){e.preventDefault();if(inFlight.current||busy||!input.trim()||!config?.enabled||!config?.hasKey)return;inFlight.current=true;const message=input.trim(),history=messages.slice(-8).map(({role,content})=>({role,content})),ids=paperIds;setMessages(v=>[...v,{role:'user',content:message}]);setInput('');setPaperIds([]);setBusy(true);setError('');
  try{const result=await aiRequest('chat',{message,history,paperIds:ids,allowProposals,latestDaily:home,requestId:crypto.randomUUID()});setMessages(v=>[...v,{role:'assistant',content:result.answer,papers:result.papers,analyses:result.analyses,proposals:result.proposals,notice:result.notice,displayTruncated:result.displayTruncated,webResults:result.webResults,webSearchErrors:result.webSearchErrors,dailyStatus:result.dailyStatus}]);aiRequest('settings').then(setConfig).catch(()=>{})}catch(e){setError((e as Error).message);setInput(current=>current||message);setPaperIds(current=>current.length?current:ids)}finally{inFlight.current=false;setBusy(false);textarea.current?.focus({preventScroll:true})}}
 function prompt(text:string){setInput(text);setPaperIds([]);textarea.current?.focus({preventScroll:true})}
 const content=<><header className="ai-header"><div className="ai-identity"><img className="ai-avatar" src="/firedot-avatar.png" width="44" height="44" alt="firedot，戴橙色耳机的蓝色小伙伴"/><div><h2 id="ai-title">firedot <span>站内助手</span></h2><p>使用你配置的模型{config?.model?` · ${config.model}`:""}</p></div></div><div className="ai-actions"><Link to="/settings" onClick={()=>setOpen(false)} aria-label="打开网站设置">设置</Link><button type="button" onClick={()=>home?setExpanded(v=>!v):setOpen(false)} aria-label={home?(expanded?"收起对话记录":"展开对话记录"):"收起 AI 助手"} aria-expanded={home?expanded:undefined} aria-controls={home?"ai-chat-history":undefined}>{home?<DisclosureIndicator open={expanded} label={false}/>:"×"}</button></div></header>
 <div ref={body} className="ai-chat-body" id="ai-chat-history" hidden={home&&!expanded}><details className="ai-privacy"><DisclosureSummary>数据使用与调用说明</DisclosureSummary><p>可检索本站论文；AnySearch 保存独立密钥并启用后，可补充网页来源。联网查询词会发送到 AnySearch，结果摘要会进入当前模型上下文。页面对话不跨会话展示；服务端保留调用回执用于限额与防重复，超过 7 天的回答内容在后续访问时清理。配置变更须再次确认。不要在聊天中输入 API key 或其他秘密。头像仅作本站角色标识；对话由你配置的模型服务处理。</p></details>
 {config&&(!config.hasKey||!config.enabled)&&<div className="ai-empty"><strong>{config.hasKey?'AI 当前已关闭':'先配置模型接入'}</strong><p>前往设置填写接入点和 API key，确认模型与思考等级后启用。尚未发起任何模型请求。</p><Link to="/settings" onClick={()=>setOpen(false)}>打开网站设置 →</Link></div>}
 {!messages.length&&<div className="ai-prompts"><p>试着问</p>{(home?['最新日报有什么进展？','为什么这一期没有精选论文？','找近期与 TCAD 和界面陷阱有关的论文']:['找近期与 TCAD 和界面陷阱有关的论文','按摘要筛选值得阅读的图像传感器论文','查看我的关键词和采集频次设置']).map(q=><button type="button" key={q} onClick={()=>prompt(q)}>{q}</button>)}</div>}
 {messages.map((m,i)=><article className={'ai-message ai-'+m.role} key={i}><span className="ai-message-label">{m.role==='user'?'你':'firedot · AI 生成，请核对原文'}</span>{m.displayTruncated&&<Notice tone="notice" role="status">显示内容已截断，不是完整分析：正文最多 12,000 字符，单篇分析摘要最多 1,200 字符，最多展示 8 项分析和 16 篇论文引用、20 个网页来源。请缩小问题范围；重新发送可能再次计费。</Notice>}<>{m.dailyStatus&&<div className="ai-daily-source"><Link to={m.dailyStatus.url} onClick={()=>setOpen(false)}>{m.dailyStatus.date?`依据 ${m.dailyStatus.date} 日报`:"查看日报归档"}</Link><p>{m.dailyStatus.summary}</p><small>以上为已保存状态，不是模型推测</small></div>}</><p className="ai-message-text"><Citations text={m.content} webResults={m.webResults} onNavigate={()=>setOpen(false)}/></p>{m.papers?.map(p=><Link className="ai-paper" key={p.id} to={'/research/'+p.id} onClick={()=>setOpen(false)}><strong>{p.title}</strong><span>{p.journal} · 原规则分 {p.ruleScore} · {p.hasAbstract?'有摘要':'摘要缺失'}</span></Link>)}{m.webResults?.map(r=><WebResult key={r.id} result={r}/>)}{m.webSearchErrors?.map(e=><Notice tone="error" key={e.code}>{e.error}{e.setupUrl&&<Link to="/settings#anysearch" onClick={()=>setOpen(false)}> 配置 AnySearch →</Link>}</Notice>)}{m.analyses?.map(a=><div className="ai-analysis" key={a.paperId}><strong>{a.decision==='include'?'建议阅读':a.decision==='exclude'?'暂缓阅读':'证据不足'}{a.score!==null?` · AI 适配分 ${a.score}`:''}</strong><p>{a.summary}</p>{a.evidence&&<p className="ai-evidence">摘要证据：“{a.evidence}”</p>}<Link to={'/research/'+a.paperId+'#abstract'} onClick={()=>setOpen(false)}>核对摘要 →</Link></div>)}{m.proposals?.map(p=><AIProposal key={p.id} proposal={p}/>)}{m.notice&&<p className="ai-muted">{m.notice}</p>}</article>)}
 {busy&&<p className="ai-thinking" role="status">正在检索与分析… 同工具同参数最多连续 5 次，同工具最多连续 15 次，最多累计 200 次工具尝试；达到对应上限后不再执行下一次。模型请求仍受每分钟 / 每日额度与 90 秒超时限制；收起窗口不会重复发送。</p>}{error&&<Notice tone="error" role="alert">{error}</Notice>}</div>
 <form className="ai-composer" onSubmit={send}>{home&&<p className="ai-home-context">随问题附带最新已保存日报的简要状态；按需读取论文</p>}{paperIds.length>0&&<p className="ai-context">已附带 {paperIds.length} 篇本站论文 <button type="button" onClick={()=>setPaperIds([])}>移除</button></p>}<label className="ai-check ai-proposal-toggle"><input type="checkbox" checked={allowProposals} onChange={e=>setAllowProposals(e.target.checked)}/>允许提出关键词 / 频次变更建议（仍须确认）</label><label className="sr-only" htmlFor="ai-input">向 AI 助手提问</label><textarea ref={textarea} id="ai-input" rows={home?2:3} value={input} onChange={e=>setInput(e.target.value)} maxLength={4000} placeholder="问问最新进展，或输入论文问题…" onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><div className="ai-composer-bottom"><span>{config?`今日请求 ${config.callsToday}/${config.dailyLimit} · 发送可能计费`:'Ctrl / ⌘ + Enter 发送'}</span><ActionButton appearance="primary" disabled={busy||!input.trim()||!config?.enabled||!config?.hasKey} type="submit">{busy?'思考中…':'发送'}</ActionButton></div></form></>;
 return home?<aside className="ai-home-rail" aria-label="firedot 站内助手" data-expanded={expanded}><section className="ai-home-panel">{content}</section></aside>:<dialog ref={dialog} className="ai-dialog" aria-labelledby="ai-title" onCancel={e=>{e.preventDefault();setOpen(false)}}>{content}</dialog>;
}
