import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router';
import {aiRequest,type Proposal} from '../lib/ai-client';
import {AIProposal} from './AIProposal';
type Message={role:'user'|'assistant';content:string;papers?:any[];analyses?:any[];proposals?:Proposal[];notice?:string;displayTruncated?:boolean};
function Citations({text}:{text:string}){return <>{text.split(/(\[paper:[\w-]+\])/g).map((part,i)=>/^\[paper:/.test(part)?<Link key={i} to={'/research/'+part.slice(7,-1)} className="ai-inline-cite">[论文]</Link>:<span key={i}>{part}</span>)}</>}
export function AIAssistant(){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[paperIds,setPaperIds]=useState<string[]>([]),[messages,setMessages]=useState<Message[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[config,setConfig]=useState<any>(null),[allowProposals,setAllowProposals]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),textarea=useRef<HTMLTextAreaElement>(null),end=useRef<HTMLDivElement>(null),opener=useRef<HTMLElement|null>(null);
 useEffect(()=>{const listener=(e:Event)=>{opener.current=document.activeElement as HTMLElement;const d=(e as CustomEvent).detail;setInput(d?.message||'');setPaperIds(d?.paperIds||[]);setOpen(true)};window.addEventListener('hkis:open-ai',listener);return()=>window.removeEventListener('hkis:open-ai',listener)},[]);
 useEffect(()=>{if(open){dialog.current?.showModal();aiRequest('settings').then(setConfig).catch(e=>setError(e.message));setTimeout(()=>textarea.current?.focus(),0)}else{dialog.current?.close();opener.current?.focus()}},[open]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,busy]);
 async function send(e:React.FormEvent){e.preventDefault();if(busy||!input.trim())return;const message=input.trim(),history=messages.slice(-8).map(({role,content})=>({role,content})),ids=paperIds;setMessages(v=>[...v,{role:'user',content:message}]);setInput('');setPaperIds([]);setBusy(true);setError('');
  try{const result=await aiRequest('chat',{message,history,paperIds:ids,allowProposals,requestId:crypto.randomUUID()});setMessages(v=>[...v,{role:'assistant',content:result.answer,papers:result.papers,analyses:result.analyses,proposals:result.proposals,notice:result.notice,displayTruncated:result.displayTruncated}]);aiRequest('settings').then(setConfig).catch(()=>{})}catch(e){setError((e as Error).message);setInput(message);setPaperIds(ids)}finally{setBusy(false);textarea.current?.focus()}}
 function prompt(text:string){setInput(text);setPaperIds([]);textarea.current?.focus()}
 return <>
 <dialog ref={dialog} className="ai-dialog" aria-labelledby="ai-title" onCancel={e=>{e.preventDefault();setOpen(false)}}><header className="ai-header"><div><h2 id="ai-title">HKIS AI 助手</h2><p>{config?`${config.model} · ${config.reasoning}`:'检索 · 分析 · 配置建议'}</p></div><div className="ai-actions"><Link to="/settings" onClick={()=>setOpen(false)} aria-label="打开网站设置">设置</Link><button type="button" onClick={()=>setOpen(false)} aria-label="收起 AI 助手">×</button></div></header>
 <div className="ai-chat-body"><p className="ai-privacy">只检索本站已收集论文。页面对话不跨会话展示；服务端保留调用回执用于限额与防重复，超过 7 天的回答内容在后续访问时清理。配置变更须再次确认。不要在聊天中输入 API key 或其他秘密。</p>
 {config&&(!config.hasKey||!config.enabled)&&<div className="ai-empty"><strong>{config.hasKey?'AI 当前已关闭':'先配置模型接入'}</strong><p>前往设置填写接入点和 API key，确认模型与思考等级后启用。尚未发起任何模型请求。</p><Link to="/settings" onClick={()=>setOpen(false)}>打开网站设置 →</Link></div>}
 {!messages.length&&<div className="ai-prompts"><p>试着问</p>{['找近期与 TCAD 和界面陷阱有关的论文','按摘要筛选值得阅读的图像传感器论文','查看我的关键词和采集频次设置'].map(q=><button type="button" key={q} onClick={()=>prompt(q)}>{q}</button>)}</div>}
 {messages.map((m,i)=><article className={'ai-message ai-'+m.role} key={i}><span className="ai-message-label">{m.role==='user'?'你':'HKIS · AI 生成，请核对原文'}</span>{m.displayTruncated&&<p className="research-notice" role="status">显示内容已截断，不是完整分析：正文最多 12,000 字符，单篇分析摘要最多 1,200 字符，最多展示 8 项分析和 16 篇引用。请缩小问题范围；重新发送可能再次计费。</p>}<p className="ai-message-text"><Citations text={m.content}/></p>{m.papers?.map(p=><Link className="ai-paper" key={p.id} to={'/research/'+p.id} onClick={()=>setOpen(false)}><strong>{p.title}</strong><span>{p.journal} · 原规则分 {p.ruleScore} · {p.hasAbstract?'有摘要':'摘要缺失'}</span></Link>)}{m.analyses?.map(a=><div className="ai-analysis" key={a.paperId}><strong>{a.decision==='include'?'建议阅读':a.decision==='exclude'?'暂缓阅读':'证据不足'}{a.score!==null?` · AI 适配分 ${a.score}`:''}</strong><p>{a.summary}</p>{a.evidence&&<p className="ai-evidence">摘要证据：“{a.evidence}”</p>}<Link to={'/research/'+a.paperId+'#abstract'} onClick={()=>setOpen(false)}>核对摘要 →</Link></div>)}{m.proposals?.map(p=><AIProposal key={p.id} proposal={p}/>)}{m.notice&&<p className="ai-muted">{m.notice}</p>}</article>)}
 {busy&&<p className="ai-thinking" role="status">正在检索与分析… 同工具同参数最多连续 5 次，同工具最多连续 15 次，最多累计 200 次工具尝试；达到对应上限后不再执行下一次。模型请求仍受每分钟 / 每日额度与 90 秒超时限制；收起窗口不会重复发送。</p>}{error&&<p className="ai-error" role="alert">{error}</p>}<div ref={end}/></div>
 <form className="ai-composer" onSubmit={send}>{paperIds.length>0&&<p className="ai-context">已附带 {paperIds.length} 篇本站论文 <button type="button" onClick={()=>setPaperIds([])}>移除</button></p>}<label className="ai-check"><input type="checkbox" checked={allowProposals} onChange={e=>setAllowProposals(e.target.checked)}/>允许提出关键词 / 频次变更建议（仍须确认）</label><label className="sr-only" htmlFor="ai-input">向 AI 助手提问</label><textarea ref={textarea} id="ai-input" rows={3} value={input} onChange={e=>setInput(e.target.value)} maxLength={4000} placeholder="找论文、对比摘要，或提出配置调整…" onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><div className="ai-composer-bottom"><span>{config?`今日请求 ${config.callsToday}/${config.dailyLimit} · 发送可能计费`:'Ctrl / ⌘ + Enter 发送'}</span><button className="research-primary" disabled={busy||!input.trim()||!config?.enabled||!config?.hasKey} type="submit">{busy?'思考中…':'发送'}</button></div></form></dialog></>
}
