import {useEffect,useState} from 'react';
import {ServiceRow} from './ServiceRow';
import {anysearchRequest} from '../lib/anysearch-client';
export function AnySearchSettings({initialData}:{initialData?:any}){
 const [s,setS]=useState<any>(initialData??null),[key,setKey]=useState(''),[remove,setRemove]=useState(false),[enabled,setEnabled]=useState(!!initialData?.enabled),[consent,setConsent]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{if(initialData)return;anysearchRequest('settings').then(s=>{setS(s);setEnabled(s.enabled)}).catch(e=>setError(e.message))},[]);
 const dirty=!!key||remove||enabled!==s?.enabled;
 async function save(e:React.FormEvent){e.preventDefault();setBusy('save');setError('');setMessage('');try{const result=await anysearchRequest('settings',{endpoint:s.endpoint,revision:s.revision,enabled,apiKey:key||undefined,removeKey:remove,confirmedDestination:consent?s.endpoint:null});setS(result);setEnabled(result.enabled);setKey('');setRemove(false);setConsent(false);setMessage('AnySearch 设置已保存，保存本身不会发起搜索。')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function test(){setBusy('test');setError('');setMessage('');try{setMessage((await anysearchRequest('test',{revision:s.revision})).message)}catch(e){setError((e as Error).message)}finally{try{setS(await anysearchRequest('settings'))}catch{}setBusy('')}}
 return <section id="anysearch" className="anysearch-settings">{s?<ServiceRow name="AnySearch · 联网检索" endpoint={s.endpoint} hasKey={s.hasKey} status={s.testStatus} busy={!!busy} onTest={test} testDisabled={dirty||!s.hasKey} testLabel="测试连接"><form className="ai-form" onSubmit={save}><div className="ai-two-columns"><label>官方 Base URL<input value={s.endpoint} readOnly aria-readonly="true"/></label><label>AnySearch API key · {s.hasKey?'留空保留':'尚未配置'}<input type="password" value={key} autoComplete="off" spellCheck={false} maxLength={4096} disabled={!s.encryptionReady} placeholder="只填写 AnySearch 的独立密钥" onChange={e=>{setKey(e.target.value);setRemove(false);setConsent(false)}}/></label></div><p className="ai-muted"><a href={s.docs} target="_blank" rel="noopener noreferrer">官方 API 文档</a> · <a href={s.keyUrl} target="_blank" rel="noopener noreferrer">打开 AnySearch 管理密钥</a>。不复用 LLM、Semantic Scholar 或 OpenAlex 密钥，不启用匿名模式。</p>{s.hasKey&&<label className="ai-check"><input type="checkbox" checked={remove} onChange={e=>{setRemove(e.target.checked);setKey('');if(e.target.checked)setEnabled(false)}}/>移除此服务密钥并关闭 Agent 联网检索（保存后生效）</label>}{key&&<label className="ai-check ai-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>确认这是 AnySearch 密钥，仅发送到 {s.endpoint}。主动检索会将关键词发送给该服务；开启下方选项后，Agent 会按对话需要发送检索词，搜索结果会进入已配置模型的上下文。搜索可能消耗配额或计费。</label>}<label className="ai-check"><input type="checkbox" checked={enabled} disabled={remove||(!s.hasKey&&!key)} onChange={e=>setEnabled(e.target.checked)}/>允许 Agent 在我主动发起的对话中按需使用 AnySearch 联网检索</label><p className="ai-muted">侧栏关键词检索独立于模型与此开关，只在提交时请求；输入和打开页面不会搜索。密钥仅服务端加密保存，不回显、不进入聊天或浏览器存储。不要搜索秘密或敏感个人信息。</p><p className="ai-muted">测试只读取官方能力目录，不消耗搜索配额，也不验证搜索额度与质量。本站测试和搜索共用每日 100 次尝试上限（UTC），目前 {s.callsToday} 次；失败也计数。每次最多 10 条、20 秒、1 MB，不自动重试。相同查询短时复用；官方暂无分页或发布日期字段。</p>{!s.encryptionReady&&<p className="ai-error">安全存储尚未就绪，暂不能保存密钥。</p>}<div className="ai-actions"><button type="submit" className="research-primary" disabled={!!busy}>保存 AnySearch</button><span className="ai-muted">{dirty?'有未保存修改':s.testedAt?`最近连接测试 ${s.testedAt}`:'尚未测试连接'}</span></div></form></ServiceRow>:!error&&<p className="ai-muted">正在读取 AnySearch 设置…</p>}{error&&<p className="ai-error" role="alert">{error}</p>}{message&&<p className="research-notice" role="status">{message}</p>}</section>
}
