import {useContentProfile} from '../lib/use-content-profile';
import {MonthControls,CalendarTable} from './ui/Calendar';
import {ActionButton,Notice,EmptyState,SectionHeading,Stats} from './ui/ResearchControls';
import {DisclosureSummary} from './ui/Interaction';
import {PageHeader} from './ui/PageFrame';
import {SectionLink} from './ReadingContinuity';
import {invalidateReadingCache,calendarCache,readJSON} from '../lib/reading-cache';
import {RailDisclosure} from './ui/AdaptiveRail';
import {ControlReadingLayout} from './ui/ControlReadingLayout';
import {useId,useEffect,useState,type ReactNode} from 'react';
import {Link,useNavigate,useRevalidator,useLocation} from 'react-router';
import {monthParts} from '../features/changelog/calendar-domain';
import {PaperSelection,PaperBulkToolbar,PaperCardState,PaperSourceLink} from './PaperReader';
const labels:Record<string,string>={completed:'已生成',partial:'部分完成',queued:'等待生成',running:'生成中',empty:'无达标论文',incomplete:'采集覆盖不完整',insufficient:'摘要证据不足',needs_review:'部分结果待核对',failed:'未通过检查',unknown:'调用结果未知'};
const waitReasons:Record<string,string>={budget_exceeded:'共享调用额度已用完或触及分钟限额',daily_call_cap:'本地当天两次日报调用额度已用完',time_budget:'本次调度时间不足',ai_disabled:'AI已关闭',key_unavailable:'模型凭证不可用',interactive_only:'当前模型接入不支持无人值守日报',connection_test_required:'当前模型尚未通过连接测试',not_configured:'尚无唯一可用的所有者模型配置'};
const time=(s?:string|null)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Singapore',hour12:false}):'未记录';
export type DailyData={today:string;date:string;month:string;invalidDate:boolean;days:{date:string;count:number;status:string}[];report:any;window:any;schedule:any;limits:any;timezone:string};
export function DailyCalendar({d}:{d:DailyData}){
 const navigate=useNavigate(),location=useLocation(),id=useId(),params=new URLSearchParams(location.search);
 const requested=params.get('month')||d.month,displayMonth=/^(?:19\d{2}|[2-9]\d{3})-(?:0[1-9]|1[0-2])$/.test(requested)?requested:d.month;
 const [year,m]=monthParts(displayMonth),[calendar,setCalendar]=useState({month:d.month,days:d.days}),[calendarError,setCalendarError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const update=()=>setRefresh(n=>n+1);window.addEventListener('hkis:reading-refresh',update);return()=>window.removeEventListener('hkis:reading-refresh',update)},[]);
 useEffect(()=>{let active=true;const abort=new AbortController();setCalendarError('');
  if(displayMonth===d.month&&refresh===0){setCalendar({month:d.month,days:d.days});return}
  const url='/api/site/research/daily/calendar?month='+displayMonth;
  calendarCache.read<{month:string;days:DailyData['days']}>(url,()=>readJSON(url,abort.signal),{signal:abort.signal}).then(value=>{if(active)setCalendar(value)}).catch(()=>{if(active)setCalendarError('月历暂未加载，请重试；当前日报保持不变')});
  return()=>{active=false;abort.abort()};
 },[displayMonth,d.month,d.days,refresh]);
 const change=(month:string)=>{const q=new URLSearchParams(location.search);q.set('month',month);navigate({pathname:location.pathname,search:'?'+q},{preventScrollReset:true})};
 const days=new Map((calendar.month===displayMonth?calendar.days:[]).map(x=>[x.date,x])),loading=calendar.month!==displayMonth&&!calendarError;
 return <section className="changelog-calendar" aria-labelledby={id}><div className="calendar-heading"><h2 id={id}>日报月历</h2><button type="button" onClick={()=>change(d.today.slice(0,7))}>本月</button></div><MonthControls month={displayMonth} onMonth={change} yearLabel="日报年份" monthLabel="日报月份"/><CalendarTable month={displayMonth} caption={<>{year}年{m}月日报日历</>} renderDay={date=>{const entry=days.get(date);return date>d.today?<span className="calendar-day">{Number(date.slice(-2))}</span>:<Link preventScrollReset to={'/daily?date='+date+'&month='+displayMonth} className={'calendar-day'+(entry?' has-update':'')+(date===d.date?' is-selected':'')} aria-current={date===d.today?'date':undefined} aria-label={`${date}，${entry?labels[entry.status]||entry.status:'未生成日报'}${date===d.date?'，已选择':''}`}><span>{Number(date.slice(-2))}</span>{entry&&<small>{entry.status==='completed'?'日报':entry.status==='empty'?'空档':'待查看'}</small>}</Link>;}}/><p className="calendar-legend"><span className="calendar-key" aria-hidden="true"/>有归档 · 点击切换一天<span>描边为今天</span></p>{loading&&<p className="calendar-empty" role="status">正在读取本月归档…</p>}{calendarError&&<p role="alert">{calendarError} <button type="button" onClick={()=>setRefresh(n=>n+1)}>重试</button></p>}{!loading&&!calendarError&&!calendar.days.length&&<p className="calendar-empty">本月暂无日报归档</p>}</section>;
}
function DailyLayout({home,children,header,...props}:{home:boolean;children:ReactNode;header:ReactNode;rail:ReactNode;label:string;summary:string}){return home?<>{header}{children}</>:<ControlReadingLayout header={header} {...props}>{children}</ControlReadingLayout>}
export function PaperDaily({d,home=false}:{d:DailyData;home?:boolean}){
 useContentProfile(d,'daily');const r=useRevalidator(),report=d.report,groups=report?.groups||[],papers:any[]=[...new Map<string,any>(groups.flatMap((g:any)=>g.papers).map((p:any)=>[p.id,p])).values()],complete=groups.filter((g:any)=>g.status==='completed'),queued=groups.filter((g:any)=>['queued','running'].includes(g.status)).length;
 return <div className={"research-page daily-page"+(home?" home-daily-page":"")}><DailyLayout header={<> <PageHeader><div><p className="research-eyebrow">HKIS / PAPER DAILY</p><h1>{home?"最新论文日报":"论文日报"}</h1><p>日报日期 <time dateTime={d.date}>{d.date}</time> · 来源日 {d.report?.sourceDate||d.window.sourceDate} · UTC+08</p>{home&&<p className="home-daily-caption">{d.report?"最近已保存的日报；仅汇总来源日首次入库的论文，不等于论文发表日期。":"尚无已保存日报；打开首页不会启动生成。"}</p>}</div><ActionButton appearance="primary" disabled={r.state!=='idle'} onClick={()=>{invalidateReadingCache();window.dispatchEvent(new Event('hkis:reading-refresh'));r.revalidate()}}>{r.state==='idle'?'刷新归档状态':'读取中…'}</ActionButton></PageHeader><nav className="progress-tabs" aria-label="论文视图"><SectionLink to="/daily" aria-current={home?undefined:"page"}>{home?"历史日报 / 月历":"论文日报"}</SectionLink><SectionLink to="/all">研究进展</SectionLink><SectionLink to="/hot">本周热点</SectionLink><SectionLink to="/research">论文库 / 采集状态</SectionLink></nav> </>} home={home} label="日报日期" summary={d.date} rail={<> <DailyCalendar d={d}/><RailDisclosure title="生成时间与入选口径"><p>{d.schedule?.enabled&&d.schedule?.daily?.enabled&&d.schedule?.daily?.contractVersion==='hkis-daily-v1'?'已关联每天 08:00 的日报调度':'目标每天 08:00；日报调度尚未核实'}</p><p>先处理前一天 08 / 20 点批次，再开始今天采集。生成需要时间，刷新页面只读取归档。</p><p>入选条件：阅读优先级规则分严格大于 75。AI 重要性、方法证据分和期刊影响因子不替代此分数。</p></RailDisclosure> </>}><section aria-label="选中日期的日报" className="daily-day-content" aria-live="polite" data-daily-date={d.date}>
 {d.invalidDate&&<Notice tone="notice" role="alert">日期无效，请通过月历选择有效日期</Notice>}
 {!report?<EmptyState  as="section"><h2>{d.date} 尚无日报归档</h2><p>该日期尚未保存日报。页面不会把规则摘录冒充 AI 日报，也不会因打开页面调用模型。</p><p>可点击月历中的其他日期，或刷新查看调度后的生成状态。</p></EmptyState>:<><p className="daily-saved-at">归档保存 {time(report.createdAt)} · {report.finishedAt?`处理结束 ${time(report.finishedAt)}`:`状态更新 ${time(report.updatedAt)}`}（UTC+08）</p><SectionHeading ><h2><time dateTime={report.date}>{report.date}</time></h2><span>{labels[report.status]||report.status}</span></SectionHeading><Stats ><div><b>{report.selection.newPapers}</b><span>有批次记录的新论文</span></div><div><b>{report.selection.eligible}</b><span>阅读优先级 &gt;75</span></div><div><b>{complete.length}</b><span>已生成关键词段落</span></div><div><b>{queued}</b><span>等待处理的段落</span></div></Stats>
 {!report.coverage.complete&&<Notice tone="notice">前一天采集覆盖不完整：这里只总结实际留下批次记录的论文，不代表两次采集全部成功。</Notice>}
 {report.coverage.untrackedNewPapers>0&&<Notice tone="notice">另有 {report.coverage.untrackedNewPapers} 篇当日首次入库论文缺少对应的 08 / 20 点批次记录，未混入日报。旧数据不追溯伪造批次。</Notice>}
 {report.diagnostics?.countsMatchArchive&&<Notice tone="notice">来源日候选摘要证据：{report.diagnostics.evidenceCoverage.withAdequateAbstract} / {report.diagnostics.evidenceCoverage.totalCandidates} 篇达到最低长度；{report.diagnostics.evidenceCoverage.missingOrShortAbstract} 篇缺失或过短。规则门槛与摘要覆盖分别统计，未评估不等于低质量；AI 评分不参与当前入选。{report.diagnostics.reconstructed?' 这是按来源日快照重建的只读诊断，原归档未改写。':''}</Notice>}
 {!report.selection.eligible&&<EmptyState  as="section"><h3>已记录批次中，没有阅读优先级大于 75 的新论文</h3><p>{report.coverage.complete?'当日无符合条件内容，没有调用模型生成填充段落。':'采集记录尚不完整，不能据此断言当天没有相关新论文。'}</p><Link to="/research" className="research-back">查看论文库与原始论文 →</Link></EmptyState>}
 {(report.selection.missingAbstract>0||report.selection.oversizedEvidence>0||report.selection.unresolvedScores>0||report.selection.capacityDeferred>0)&&<Notice tone="notice">未生成部分：摘要缺失或过短 {report.selection.missingAbstract} 篇；证据超出单篇安全上限 {report.selection.oversizedEvidence} 篇；分数无法确定 {report.selection.unresolvedScores} 篇；超过本日日报容量 {report.selection.capacityDeferred} 篇。容量外论文仍保留在论文库，本归档不会自动增加收费重跑。</Notice>}
 <PaperSelection ids={papers.map(p=>p.id)} scopeKey={'daily:'+report.date+':'+report.revision}><PaperBulkToolbar/>{groups.map((g:any)=><section className="research-card daily-keyword-group" key={g.id}><SectionHeading ><h3>{g.keyword}</h3><span>{g.papers.length} 篇 · {labels[g.status]||g.status}</span></SectionHeading>{g.status==='completed'?<><p className="daily-progress-paragraph">{g.result.sentences.map((s:any,i:number)=>{const n=g.papers.findIndex((p:any)=>p.id===s.paperId);return <span key={i}>{s.text}<Link to={'/research/'+s.paperId+'#abstract'} className="weekly-citation" title={g.papers[n]?.title}>[{n+1}]</Link>{' '}</span>})}</p><p className="weekly-meta">AI 摘要 · {g.result.hanCharacters} 个汉字 · {g.config?.model} · 仅依据实际摘要，未核对全文</p><details className="progress-provenance"><DisclosureSummary>查看逐句摘要证据</DisclosureSummary><ol>{g.result.sentences.map((s:any,i:number)=><li key={i}><p>{s.text}</p><p lang="en">“{s.quote}” <Link to={'/research/'+s.paperId+'#abstract'}>核对对应论文</Link></p></li>)}</ol></details></>:<p className="weekly-no-evidence">{g.status==='queued'?`${waitReasons[g.errorCode]?waitReasons[g.errorCode]+'；':''}等待后续 08 点调度；每日处理次数有限，页面刷新不会启动模型。`:g.status==='running'?'本次生成中；若请求中断，将在后续调度核对回执，不重复未知收费请求。':g.status==='insufficient'?g.result?.reason||'摘要不足以支持 200–300 字进展描述，未编造内容。':g.status==='unknown'?'供应商调用结果未知，已停止自动重试。':'本次输出未通过引用或 200–300 字检查，未作为摘要发布，也未自动再次收费。'}</p>}
 <div className="daily-paper-references">{g.papers.map((p:any,i:number)=><PaperCardState key={p.id} id={p.id} title={p.title} className="daily-source-paper"><h4><Link to={'/research/'+p.id}>[{i+1}] {p.title}</Link></h4><p>{p.authors?.length?p.authors.slice(0,3).map((a:any)=>a.name).join(' · ')+(p.authors.length>3?' 等':''):'作者：来源未提供'} · {p.journal}</p><p>阅读优先级 {p.readingScore.value} · {p.readingScore.ruleVersion} · 摘要来源 {p.abstractSource||'缺失'}</p><PaperSourceLink paperId={p.id} href={p.url} target="_blank" rel="noreferrer">DOI / 出版商原文</PaperSourceLink></PaperCardState>)}</div></section>)}</PaperSelection>
 <details className="research-panel"><DisclosureSummary>采集覆盖、截止时间与归档版本</DisclosureSummary><p>本期仅包含 {report.sourceDate} 的 08 点 / 20 点批次首次新增论文；按首次入库时间，不按发表日期，不把旧论文元数据更新重复算作新增。固定截止：{time(report.cutoff)}。</p>{report.coverage.batches.map((b:any)=><section key={b.key}><h3>{b.key} · {b.status==='complete'?'记录完整':b.status==='missing'?'缺少批次记录':'部分覆盖'}</h3><p>已尝试 {b.attemptedSources} / {b.expectedSources} 个信源；完整 {b.completeSources} 个。开始 {time(b.startedAt)}；结束 {time(b.finishedAt)}。</p>{b.missingSources.length>0&&<p>未尝试：{b.missingSources.join('、')}</p>}<ul>{b.runs.map((run:any)=><li key={run.id}>{run.sourceId} · {run.status} · {run.id}</li>)}</ul></section>)}<p>归档修订 {report.revision} · {report.schema} · 提示词 {report.prompt}。首次保存 {time(report.createdAt)}；最近状态更新 {time(report.updatedAt)}。</p><p>每次最多 {d.limits.callsPerRun} 次模型请求，每次最多 {d.limits.groupsPerCall} 段；与助手、论文评估共享现有每日调用额度，不提高额度。排队内容可由后续 08 点调度继续；已完成、失败和结果未知的调用不会自动重复收费。</p><p>每句引用必须匹配对应论文的实际摘要，仍需人工核对语义和全文。不同论文单独归属，不以摘要判断科学质量。历史入选分数、来源和内容快照冻结保存，后续元数据更新不会悄悄重写归档。</p><p className="daily-hash">内容校验：{report.contentHash}</p></details></>}
 </section></DailyLayout></div>;
}
