import {ActionButton,Notice} from './ui/ResearchControls';
import {DisclosureSummary} from './ui/Interaction';
import {useEffect,useState} from 'react';
const labels:Record<string,string>={research:'论文采集',feed:'RSS 采集',ai:'AI 助手',provider:'模型供应商',scholarly:'学术数据源',anysearch:'AnySearch 检索',settings:'配置',server:'服务',network_probe:'无密钥网络诊断',collection_started:'采集开始',collection_finished:'采集结束',collection_failed:'采集失败',request_finished:'请求完成',request_failed:'请求失败',config_saved:'配置已保存',tool_failed:'工具未完成',unexpected_exception:'服务异常',ok:'成功',partial:'部分完成',failed:'失败',unknown:'结果未知',backfill_pending:'待续采',blocked:'已拦截',started:'开始'};
export function RuntimeLogs(){
 const [severity,setSeverity]=useState('issues'),[component,setComponent]=useState('all'),[cursor,setCursor]=useState<number|null>(null),[history,setHistory]=useState<(number|null)[]>([]),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const q=new URLSearchParams({severity,component});if(cursor)q.set('before',String(cursor));fetch('/api/site/logs?'+q,{credentials:'same-origin',cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'日志读取失败');return d}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[severity,component,cursor,refresh]);
 function filter(set:(v:string)=>void,value:string){set(value);setCursor(null);setHistory([]);setData(null)}
 return <section className="research-panel ai-form" id="diagnostics" aria-labelledby="diagnostics-title"><h2 id="diagnostics-title">运行日志与诊断</h2><p className="ai-muted">默认显示 warning / error，仅所有者可读。保留最近 30 天、最多 10,000 条；访问或写入时分批清理，无独立定时任务。只记录状态、阶段、计数与散列关联标识，不记录密钥、聊天正文、论文摘要或供应商原文。旧日志会自动到期，不影响论文和 AI 调用回执。</p>
 <div className="ai-two-columns"><label>日志级别<select value={severity} onChange={e=>filter(setSeverity,e.target.value)}><option value="issues">警告与错误</option><option value="error">error · 错误</option><option value="warning">warning · 警告</option><option value="info">info · 运行结果</option><option value="all">全部级别</option></select></label><label>组件<select value={component} onChange={e=>filter(setComponent,e.target.value)}><option value="all">全部组件</option>{['research','feed','ai','provider','scholarly','anysearch','settings','server'].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label></div>
 <ActionButton type="button" appearance="secondary" disabled={loading} onClick={()=>{setCursor(null);setHistory([]);setRefresh(v=>v+1)}}>刷新日志（不调用模型）</ActionButton>
 {error&&<Notice tone="error" role="alert">{error}</Notice>}<div aria-live="polite" aria-busy={loading}>{loading?<p>正在读取日志…</p>:!error&&data?.entries.length===0?<p>当前筛选下暂无日志。日志从本次功能上线后开始记录，未补录旧事件。</p>:null}</div>
 {!loading&&!error&&<ol className="runtime-log-list">{data?.entries.map((r:any)=><li key={r.id}><details className="runtime-log-row"><DisclosureSummary><span className="runtime-log-time"><time dateTime={r.created_at}>{new Date(r.created_at).toLocaleString()}</time></span><strong className={'runtime-log-level is-'+r.severity}>{r.severity.toUpperCase()}</strong><span className="runtime-log-summary">{labels[r.component]||r.component} · {labels[r.event]||r.event} · {labels[r.outcome]||r.outcome}{r.http_status&&` · HTTP ${r.http_status}`}{r.error_code&&` · ${r.error_code}`}</span></DisclosureSummary><div className="runtime-log-detail"><p className="ai-muted">本地时间；{r.duration_ms!==null?`耗时 ${r.duration_ms} ms`:'耗时未记录'}{r.phase&&` · 阶段 ${r.phase}`}</p><dl>{Object.entries({...r.metadata,correlation:r.correlation_id,task:r.task_id,request:r.request_id,source:r.source_id}).filter(([,v])=>v!==null&&v!==undefined).map(([k,v])=><div key={k}><dt>{k}: </dt><dd>{String(v)}</dd></div>)}</dl><p className="ai-muted">关联标识为 SHA-256 前 24 位，不含账号或原始请求内容</p></div></details></li>)}</ol>}
 <nav className="ai-actions" aria-label="日志分页"><ActionButton type="button" appearance="secondary" disabled={loading||!history.length} onClick={()=>{setCursor(history.at(-1)??null);setHistory(h=>h.slice(0,-1))}}>上一页</ActionButton><span>第 {history.length+1} 页 · 每页最多 50 条</span><ActionButton type="button" appearance="secondary" disabled={loading||!!error||!data?.nextCursor} onClick={()=>{setHistory(h=>[...h,cursor]);setCursor(data.nextCursor)}}>下一页</ActionButton></nav>
 </section>
}
