import {Notice,ActionButton} from './ui/ResearchControls';
import {useEffect,useState} from 'react';
import {ServiceRow} from './ServiceRow';
import {scholarlyRequest} from '../lib/scholarly-client';
export function ScholarlySettings({initialData}:{initialData?:any}){
 const [data,setData]=useState<any>(initialData??null),[error,setError]=useState('');
 useEffect(()=>{if(initialData)return;scholarlyRequest('settings').then(setData).catch(e=>setError(e.message))},[]);
 if(error)return <Notice tone="error" role="alert">{error}</Notice>;if(!data)return <p className="ai-muted">正在读取学术服务配置…</p>;
 return <>{data.services.map((s:any)=><ScholarlyService key={s.service} service={s} encryptionReady={data.encryptionReady} onSaved={setData}/>)}</>;
}
function ScholarlyService({service:s,encryptionReady,onSaved}:{service:any;encryptionReady:boolean;onSaved:(value:any)=>void}){
 const [endpoint,setEndpoint]=useState(s.endpoint),[key,setKey]=useState(''),[remove,setRemove]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const dirty=endpoint!==s.endpoint||!!key||remove;
 async function save(e:React.FormEvent){e.preventDefault();setBusy('save');setError('');setMessage('');try{const result=await scholarlyRequest('settings',{service:s.service,endpoint,revision:s.revision,apiKey:key||undefined,removeKey:remove,confirmedDestination:consent?endpoint:null});onSaved(result);setKey('');setRemove(false);setConsent(false);setMessage('已保存。密钥不会回显，保存不会访问外部服务。')}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function test(){setBusy('test');setError('');setMessage('');try{const result=await scholarlyRequest('test',{service:s.service,revision:s.revision});setMessage(result.message)}catch(e){setError((e as Error).message)}finally{try{onSaved(await scholarlyRequest('settings'))}catch{}setBusy('')}}
 return <><ServiceRow name={s.name} endpoint={s.endpoint} hasKey={s.hasKey} status={s.testStatus} busy={!!busy} onTest={test} testDisabled={dirty}><form className="ai-form" onSubmit={save}><div className="ai-two-columns"><label>Base URL<input type="url" value={endpoint} onChange={e=>{setEndpoint(e.target.value);setConsent(false)}} required/></label><label>API key · {s.hasKey?'留空保留':'可留空使用公共额度'}<input type="password" value={key} onChange={e=>{setKey(e.target.value);setRemove(false);setConsent(false)}} autoComplete="off" spellCheck={false} disabled={!encryptionReady} maxLength={4096} placeholder="只填写此服务的独立密钥"/></label></div><p className="ai-muted">默认地址来自官方文档，仅允许此官方地址。<a href={s.docs} target="_blank" rel="noreferrer">API 文档</a> · <a href={s.keyUrl} target="_blank" rel="noreferrer">官方 key 设置 / 申请</a></p>{s.hasKey&&<label className="ai-check"><input type="checkbox" checked={remove} onChange={e=>{setRemove(e.target.checked);setKey('')}}/>移除此服务已保存的密钥，恢复公共额度（保存后生效）</label>}{key&&<label className="ai-check ai-consent"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>确认此密钥属于 {s.name}，只发送至 {s.endpoint}；主动测试、检索和核对会向该服务发送查询词或论文标识。</label>}{!encryptionReady&&<Notice tone="error">安全存储未就绪，暂不能输入或保存 key；仍可使用无密钥公共查询。</Notice>}<p className="ai-muted">密钥仅所有者可配置，服务端独立加密，无法回显，不会复用模型 key。测试读取一篇公开论文，不调用模型。检索与测试共用本站每日 100 次请求上限；供应商可能另有限额或计费。无密钥时可能受到共享额度限流。</p><div className="ai-actions"><ActionButton type="submit" appearance="primary" disabled={!!busy}>保存此服务</ActionButton><span className="ai-muted">{dirty?'有未保存修改':s.testedAt?`最近测试 ${s.testedAt}`:'尚未保存实际测试记录'}</span></div></form></ServiceRow>{error&&<Notice tone="error" role="alert">{s.name}：{error}</Notice>}{message&&<Notice tone="notice" role="status">{message}</Notice>}</>;
}
