import {DisclosureSummary} from './ui/Interaction';
import {PaperCardState,PaperSourceLink} from './PaperReader';
import {useState} from 'react';
import {Link,useRevalidator} from 'react-router';
import {scholarlyRequest,scholarlyNames} from '../lib/scholarly-client';
const fieldNames:Record<string,string>={title:'标题',doi:'DOI',publishedAt:'发表日期',authors:'作者',affiliations:'单位',abstract:'摘要',journal:'期刊'};
const valueText=(v:any)=>v==null||v===''||Array.isArray(v)&&!v.length?'未提供':Array.isArray(v)?v.map(a=>typeof a==='string'?a:a.name).join('；'):String(v);
export function ScholarlySearch({paperId}:{paperId?:string}){
 const [query,setQuery]=useState(''),[provider,setProvider]=useState('both'),[results,setResults]=useState<any[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[searched,setSearched]=useState(false),[activeQuery,setActiveQuery]=useState('');const revalidator=useRevalidator();
 async function search(page=1,service?:string){setBusy('search');setError('');setMessage('');try{const services=service?[service]:provider==='both'?['semanticscholar','openalex']:[provider];const q=service?activeQuery:query;const data=await scholarlyRequest(paperId?'check':'search',{services,query:q,paperId,page});setResults(old=>!service?data.results:old.map(r=>r.service===service?data.results[0]:r));if(!service)setActiveQuery(q);setSearched(true)}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 async function apply(group:any,r:any){setBusy(r.service+r.recordId);setError('');setMessage('');try{const result=await scholarlyRequest('apply',{cacheKey:group.cacheKey,recordId:r.recordId,paperId:paperId||r.existingPaperId||undefined});setMessage(result.message);setResults(old=>old.map(g=>({...g,records:g.records.map((v:any)=>v.service===r.service&&v.recordId===r.recordId?{...v,existingPaperId:result.paperId,applied:true}:v)})));revalidator.revalidate()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <section className="research-panel scholarly-panel"><h2>{paperId?'跨库元数据核对':'Semantic Scholar / OpenAlex 检索'}</h2><form onSubmit={e=>{e.preventDefault();search()}} className="research-filters">{!paperId&&<label>关键词、DOI 或论文 ID<input type="search" value={query} onChange={e=>setQuery(e.target.value)} minLength={2} maxLength={500} required placeholder="TCAD；10.…；W…；S2 / CorpusId / ARXIV"/></label>}<label>数据源<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="both">两个数据源</option><option value="semanticscholar">Semantic Scholar</option><option value="openalex">OpenAlex</option></select></label><button type="submit" className="research-primary" disabled={!!busy}>{busy==='search'?'读取中…':paperId?'按 DOI 核对':'检索论文'}</button></form><p className="ai-muted">点击后将{paperId?'此论文 DOI':'输入的查询词 / 标识'}发送给所选服务，不调用模型。可无密钥查询，公共额度可能限流；<Link to="/settings">配置独立 API key</Link>。每源每页 10 篇，最多 10 页，最多 20 秒；结果缓存 1 小时，单篇 6 小时。</p>{paperId&&<p className="ai-muted">只预览差异。点击“补充缺失字段”后才更新论文；已有字段、冲突值与规则分保留，标题不同不会自动合并。</p>}{error&&<p className="ai-error" role="alert">{error}</p>}{message&&<p className="research-notice" role="status">{message}</p>}
 {results.map(group=><div className="scholarly-source" key={group.service}><div className="scholarly-source-heading"><h3>{scholarlyNames[group.service]}</h3>{group.ok&&<span>{group.total??'未知'} 条 · 第 {group.page} 页 · {group.cached?'缓存':'实时读取'}{group.keyed?' · 独立 key':' · 公共额度'}</span>}</div>{!group.ok?<p className="research-notice" role="status">{group.error}</p>:<>{!group.records.length&&<p className="research-empty">此数据源未返回匹配论文</p>}<div className="research-list">{group.records.map((r:any)=><PaperCardState id={r.existingPaperId||undefined} title={r.title} key={r.recordId}><h3><PaperSourceLink paperId={r.existingPaperId} href={r.recordUrl} target="_blank" rel="noreferrer">{r.title}</PaperSourceLink></h3><p className="research-authors">{r.publishedAt||'日期缺失'} · {r.journal||'期刊未提供'} · {r.authors.map((a:any)=>a.name).slice(0,3).join('；')||'作者缺失'}{r.authors.length>3?` 等 ${r.authors.length} 人`:''}</p><p className="scholarly-meta">DOI {r.doi||'未提供'} · 引用 {r.citationCount??'未提供'}（该库口径） · {r.recordId}</p><p className="research-abstract">{r.abstract||'此来源未提供摘要，不能据此作科学结论。'}</p>{r.truncated&&<p className="ai-muted">来源内容超过本次显示 / 保存边界，已明确截断，请核对原始记录。</p>}{r.indexedKeywords.length>0&&<p className="ai-muted">OpenAlex 机器关键词：{r.indexedKeywords.slice(0,8).join(' · ')}（不是作者关键词）</p>}
 {r.comparison&&<details className="scholarly-comparison" open={!!paperId}><DisclosureSummary>{r.comparison.canMerge?'已核对标识，查看字段差异':r.comparison.identity==='title_conflict'?'同 DOI 标题不同，暂不合并':r.comparison.identity==='doi_conflict'?'DOI 冲突，暂不合并':'身份未充分验证，暂不合并'}</DisclosureSummary><div className="scholarly-fields">{r.comparison.fields.map((f:any)=><div key={f.field} className={'scholarly-field '+(f.state==='conflict'?'is-conflict':'')}><strong>{fieldNames[f.field]} · {{same:'一致',missing:'本站缺失',unavailable:'来源缺失',conflict:'有差异'}[f.state as string]}</strong><p><span>本站（{f.storedSource}）</span>{valueText(f.stored)}</p><p><span>{scholarlyNames[f.incomingSource]}</span>{valueText(f.incoming)}</p></div>)}</div></details>}
 <details><DisclosureSummary>字段来源与完整元数据</DisclosureSummary><p className="ai-muted">读取时间 {r.retrievedAt} · 适配器 {r.adapterVersion}</p><p className="research-full-abstract">{r.abstract||'摘要缺失'}</p><p>全部作者：{r.authors.map((a:any)=>a.name).join('；')||'缺失'}</p><p>全部单位：{r.affiliations.join('；')||'缺失'}</p><ul>{Object.entries(r.fields).map(([name,v]:[string,any])=><li key={name}>{fieldNames[name]||name}：{v.provider} / {v.providerRecordId} / {v.rawFieldPath}</li>)}</ul>{r.openAccessUrl&&<PaperSourceLink paperId={r.existingPaperId} href={r.openAccessUrl} target="_blank" rel="noreferrer">来源标记的开放访问链接</PaperSourceLink>}</details><div className="ai-actions">{r.existingPaperId&&<Link to={'/research/'+r.existingPaperId}>查看已入库论文</Link>}<button className="ai-secondary" onClick={()=>apply(group,r)} disabled={!!busy||r.applied||!!r.comparison&&!r.comparison.canMerge}>{r.applied?'已处理':r.existingPaperId?'补充缺失字段':'入库此论文'}</button><PaperSourceLink paperId={r.existingPaperId} href={r.recordUrl} target="_blank" rel="noreferrer">核对原始记录</PaperSourceLink></div></PaperCardState>)}</div><nav className="research-pagination" aria-label={scholarlyNames[group.service]+' 结果分页'}>{group.page>1&&<button className="ai-secondary" disabled={!!busy} onClick={()=>search(group.page-1,group.service)}>上一页</button>}{group.nextPage&&<button className="ai-secondary" disabled={!!busy} onClick={()=>search(group.nextPage,group.service)}>下一页</button>}</nav>{group.bounded&&<p className="ai-muted">已达到单次范围上限，请缩小查询；未声称完整检索所有论文。</p>}</>}</div>)}{searched&&<p className="ai-muted">不同数据源的记录独立保留。相同 DOI 的不同标题会标记冲突；无 DOI 的记录只按同一数据源 ID 去重，不以相似标题认定同一论文。</p>}
 </section>;
}
