import {useEffect,useState} from 'react';
import {Link,useRevalidator} from 'react-router';
export function SitesStatus(){const [status,setStatus]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[expanded,setExpanded]=useState(false);const revalidator=useRevalidator();
 const load=()=>fetch('/api/site/status').then(r=>{if(!r.ok)throw Error('数据库暂不可用');return r.json()}).then(setStatus).catch(e=>setMessage(e.message));
 useEffect(()=>{void load();},[]);
 async function refresh(){if(busy||!status)return;setBusy(true);let added=0,failed=0;for(let i=0;i<status.sources.length;i++){const s=status.sources[i];setMessage(`正在检查 ${i+1}/${status.sources.length} · ${s.name}`);try{const r=await fetch('/api/site/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:s.id})});const d=await r.json();added+=d.added||0;if(!r.ok||d.ok===false)failed++;}catch{failed++;}}setMessage(`检查完成：新增 ${added} 条${failed?`，${failed} 个来源暂不可用`:''}`);setBusy(false);await load();revalidator.revalidate();}
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc)return;const ac=new AbortController();Promise.resolve(mc.registerTool({name:'read_source_status',description:'读取当前订阅来源的实际采集状态',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input:any){if(Object.keys(input||{}).length)throw Error('不接受参数');const r=await fetch('/api/site/status');if(!r.ok)throw Error('状态读取失败');return r.json();}},{signal:ac.signal})).catch(()=>{});return()=>ac.abort();},[]);
 return <section className="mb-5 mt-3 rounded-panel border border-line bg-surface p-4 text-[13px]" aria-label="运行状态"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>示范 RSS 订阅</strong><p className="mt-1 text-ink-3">此区域保留原版 AI 行业示范订阅。半导体论文请前往首页的论文情报。</p></div><button disabled={busy||!status} onClick={refresh} className="rounded-control bg-accent px-4 py-2 font-semibold text-white disabled:opacity-50">{busy?'检查中…':'检查信源更新'}</button></div><p className="mt-2 text-ink-3">{status?`${status.sources.length} 个订阅 · 已保存 ${status.total} 条`:'正在读取状态…'} · <Link className="text-accent underline" to="/all">浏览来源摘要</Link> · 未启用后台定时更新</p><p className="mt-1 text-ink-4">这里的示范订阅未启用 AI 评分；论文情报有独立的规则筛选与采集状态。</p>{message&&<p role="status" className="mt-2 text-accent">{message}</p>}<button className="mt-2 text-ink-3 underline" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'收起信源状态':'查看信源状态'}</button>{expanded&&<ul className="mt-3 divide-y divide-line">{status?.sources.map((s:any)=><li key={s.id} className="flex flex-wrap justify-between gap-2 py-2"><span>{s.name} · {s.count} 条</span><span className={s.error?'text-hot':'text-ink-4'}>{s.error|| (s.last_success?`最近成功 ${new Date(s.last_success).toLocaleString('zh-CN')}`:'尚未检查')}</span></li>)}</ul>}</section>;
}
