import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router';
import {anysearchRequest,openWebSearch} from '../lib/anysearch-client';
export function QuickSearch({mobile=false}:{mobile?:boolean}){const [query,setQuery]=useState('');return <form role="search" aria-label="AnySearch 快速联网检索" className={'quick-search'+(mobile?' quick-search-mobile':'')} onSubmit={e=>{e.preventDefault();if(query.trim().length>=2)openWebSearch(query.trim())}}><label className="sr-only" htmlFor={mobile?'quick-search-mobile':'quick-search-desktop'}>AnySearch 检索关键词</label><input id={mobile?'quick-search-mobile':'quick-search-desktop'} type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="关键词检索" minLength={2} maxLength={500} required autoComplete="off"/><button type="submit" aria-label="提交 AnySearch 检索" title="提交检索，可能消耗 AnySearch 配额"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg></button></form>}
export function WebResult({result:r}:{result:any}){return <article className="web-result"><h3><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title} <span aria-hidden="true">↗</span></a></h3><p className="web-source">{r.source} · 检索于 <time dateTime={r.retrievedAt}>{r.retrievedAt.slice(0,16).replace('T',' ')} UTC</time> · 发布时间未提供</p>{r.snippet?<p className="web-snippet">{r.snippet}{r.truncated&&<span className="web-source">（已截短）</span>}</p>:<p className="web-source">来源未提供摘要，请打开原文核对</p>}</article>}
export function WebSearch(){
 const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),opener=useRef<HTMLElement|null>(null),pending=useRef(false);
 const [query,setQuery]=useState(''),[busy,setBusy]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState<any>(null);
 async function search(q:string){if(pending.current)return;pending.current=true;setBusy(true);setError(null);setData(null);setQuery(q);try{setData(await anysearchRequest('search',{query:q,maxResults:10,requestId:crypto.randomUUID()}))}catch(e){setError(e)}finally{pending.current=false;setBusy(false)}}
 useEffect(()=>{const listener=(event:Event)=>{const q=(event as CustomEvent).detail?.query;if(typeof q!=='string'||q.trim().length<2)return;opener.current=document.activeElement as HTMLElement;dialog.current?.showModal();input.current?.focus();void search(q.trim())};window.addEventListener('hkis:web-search',listener);return()=>window.removeEventListener('hkis:web-search',listener)},[]);
 function close(){dialog.current?.close();opener.current?.focus()}
 return <dialog ref={dialog} className="web-search-dialog" aria-labelledby="web-search-title" onCancel={e=>{e.preventDefault();close()}}><header className="web-search-header"><div><h2 id="web-search-title">联网检索</h2><p>AnySearch · 最多 10 条来源</p></div><button type="button" aria-label="关闭联网检索" onClick={close}>×</button></header><form className="web-search-form" role="search" aria-label="修改联网检索" onSubmit={e=>{e.preventDefault();void search(query.trim())}}><label className="sr-only" htmlFor="web-search-query">联网检索关键词</label><input ref={input} id="web-search-query" type="search" value={query} onChange={e=>setQuery(e.target.value)} required minLength={2} maxLength={500} autoComplete="off"/><button type="submit" className="research-primary" disabled={busy||query.trim().length<2}>{busy?'检索中…':'检索'}</button></form><p className="web-search-policy">主动提交才会将关键词发送到 AnySearch，可能消耗配额；不调用模型。不要输入秘密或敏感个人信息。收起窗口不会重发请求。</p><WebSearchResults busy={busy} data={data} error={error} onClose={close}/></dialog>
}

export function WebSearchResults({busy,data,error,onClose}:{busy:boolean;data:any;error:any;onClose:()=>void}){return <div className="web-search-body" aria-busy={busy}>{busy&&<p role="status">正在检索，最多等待 20 秒…</p>}{error&&<div className="ai-error" role="alert"><p>{error.message}</p>{error.setupUrl&&<Link to="/settings#anysearch" onClick={onClose}>配置 AnySearch →</Link>}</div>}{data&&<><p className="web-source" role="status">“{data.query}” · 返回 {data.results.length} 条{data.cached?' · 已复用 15 分钟内的结果':''}{data.omitted?` · ${data.omitted} 条重复或不安全链接已略过`:''}{data.truncated?' · 部分内容已截短':''}</p>{!data.results.length?<p className="web-empty">没有可展示的结果，试着缩小范围或换一个关键词</p>:data.results.map((r:any)=><WebResult key={r.id} result={r}/>)}<p className="web-search-policy">{data.notice}</p></>}</div>}
