import {queueMetadata,enrichMetadata} from './research-enrichment.ts';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {admitRun,fencedRunDatabase,reconcileBatches,batchLifecycle} from './research-lifecycle.ts';
import {finishBatch,startBatch,batchCoverage,briefMissingness} from './research-batches.ts';
import {initResearch,researchApi,savePaper,syncSource} from './research.ts';
import {RESEARCH_SOURCES} from './research-config.ts';
import {fromCrossref} from './research-domain.ts';
import {monthWindow} from './research-pipeline.ts';
function database(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db:any={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},async run(){return {meta:{changes:Number(s.run(...this.args).changes)}}}}},async batch(statements:any[]){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const now=()=>new Date(),later=(at:Date,ms:number)=>new Date(at.getTime()+ms);
const source=RESEARCH_SOURCES[0]!;
function batch(sql:any,at:Date,ids=[source.id],key='2026-10-10/08'){sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,'2026-10-10',8,'running',?,?)").run(key,JSON.stringify(ids),at.toISOString());return key}
const record=(doi='10.1234/recovery',title='TCAD transistor test')=>({type:'journal-article',DOI:doi,title:[title],published:{'date-parts':[monthWindow().endDate.split('-').map(Number)]}});

test('finish queued before the last commit persists a database cutoff covering that member and completed run',async()=>{const {db,sql}=database();try{await initResearch(db);const at=now(),key=batch(sql,later(at,-1000)),run=await admitRun(db,source.id,key,'internal',at.toISOString()),committed=later(at,5000).toISOString();let gap=true;const paused={...db,prepare(q:string){const s=db.prepare(q);if(q==='SELECT * FROM research_batches WHERE key=?'){const read=s.first.bind(s);s.first=async()=>{const row=await read();if(gap){gap=false;await savePaper(fencedRunDatabase(db,run.id),fromCrossref(record(),source)!,committed,{runId:run.id,batchKey:key});sql.prepare("UPDATE research_runs SET status='ok',finished_at=?,details_json=? WHERE id=?").run(committed,JSON.stringify({rssStatus:'ok'}),run.id);sql.prepare('DELETE FROM research_settings WHERE key=?').run(run.key);}return row}}return s}};const result=await finishBatch(paused,key,at),stored=sql.prepare('SELECT finished_at FROM research_batches').get()!.finished_at;assert.ok(stored>=committed);assert.equal(result.finishedAt,stored);assert.equal(result.status,'complete');assert.equal(result.brief.evidence.newPapers,1);assert.equal(result.brief.evidence.coverage.finishedAt,stored);assert.equal(sql.prepare('SELECT count(*) n FROM research_brief_evidence').get()!.n,1);const retry=await finishBatch(db,key,later(at,-10000));assert.equal(retry.brief.contentHash,result.brief.contentHash);assert.equal(retry.status,'complete');assert.equal(retry.finishedAt,stored);}finally{sql.close()}});

test('head discovery defers all DOI rechecks and provider enrichment until after collection',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;let extra=0;try{await initResearch(db);globalThis.fetch=async(input)=>{const u=new URL(String(input));if(u.hostname==='api.crossref.org'&&!u.pathname.startsWith('/works/'))return Response.json({message:{items:[record('10.1234/head')]}});if(u.hostname==='api.crossref.org'||u.hostname==='api.openalex.org'){extra++;throw Error('inline enrichment forbidden')}return new Response('<rss><channel/></rss>')};const result=await syncSource(db,source,1);assert.equal(result.rechecked,0);assert.equal(extra,0);assert.equal(sql.prepare('SELECT status FROM research_enrichment_queue').get().status,'pending');}finally{globalThis.fetch=oldFetch;sql.close()}});

test('DOI-less historical URL upgraded to two identities does not strand its healthy RSS neighbor',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;try{await initResearch(db);const url='https://example.invalid/early-view',p={...fromCrossref(record('10.1234/seed'),source)!,doi:null,url};await savePaper(db,p);await savePaper(db,{...p,doi:'10.1234/a'});await savePaper(db,{...p,doi:'10.1234/b',title:'Different TCAD study'});globalThis.fetch=async(input:any)=>{const u=new URL(String(input));if(u.hostname==='api.crossref.org')return Response.json({message:u.pathname.startsWith('/works/')?record(decodeURIComponent(u.pathname.slice(7))):{items:[]}});if(u.hostname==='api.openalex.org')return Response.json({results:[]});return new Response(`<rss><channel><item><title>Unidentified TCAD entry</title><link>${url}</link><pubDate>${new Date().toUTCString()}</pubDate></item><item><title>Healthy TCAD RSS neighbor</title><link>https://doi.org/10.1234/healthy</link><pubDate>${new Date().toUTCString()}</pubDate></item></channel></rss>`)};const result=await syncSource(db,source,1);assert.equal(result.rssStatus,'ok');assert.equal(result.identityAmbiguous,1);assert.ok(['backfill_pending','identity_ambiguous'].includes(result.status));assert.equal(sql.prepare('SELECT count(*) n FROM research_papers WHERE doi=?').get('10.1234/healthy')!.n,1);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers WHERE doi IS NULL').get()!.n,0);assert.match(result.warnings.join(' '),/ambiguous DOI-less/);assert.equal(JSON.parse(sql.prepare('SELECT details_json FROM research_runs').get()!.details_json).identityAmbiguous,1);}finally{globalThis.fetch=oldFetch;sql.close()}});

test('queue admission retains candidates beyond the old 2000 cap without deleting audit evidence',async()=>{const {db,sql}=database();try{await initResearch(db);const p=fromCrossref(record(),source);sql.exec("WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<2000) INSERT INTO research_enrichment_queue(doi,source_id,paper_json,status,next_attempt_at,updated_at) SELECT '10.1234/reserved'||x,'other','{}','blocked','2099-01-01T00:00:00Z','2026-10-10T00:00:00Z' FROM n");await queueMetadata(db,[p]);assert.equal(sql.prepare('SELECT count(*) n FROM research_enrichment_queue').get().n,2001);assert.equal(sql.prepare('SELECT status FROM research_enrichment_queue WHERE doi=?').get(p.doi).status,'overflow');}finally{sql.close()}});

test('fence preserves D1 prepared statement raw method instead of mistaking it for a wrapper',async()=>{const {db,sql}=database();try{const actual={...db,prepare(q:string){const s=db.prepare(q);s.raw=async()=>{throw Error('unexpected raw call')};return s}};const run=await admitRun(actual,source.id,null,'internal',now().toISOString()),fenced=fencedRunDatabase(actual,run.id);await fenced.prepare("INSERT INTO research_settings(key,value) VALUES('raw-method','ok')").run();await fenced.batch([fenced.prepare("UPDATE research_settings SET value=? WHERE key='raw-method'").bind('still-ok')]);assert.equal(sql.prepare("SELECT value FROM research_settings WHERE key='raw-method'").get()!.value,'still-ok');}finally{sql.close()}});

test('unexpected pre-fetch error closes source and run together without invalidating its own fence',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('unexpected egress')};try{await initResearch(db);const failing={...db,prepare(q:string){const s=db.prepare(q);if(q==='SELECT * FROM research_sources WHERE id=?')s.first=async()=>{throw Error('synthetic state read failure')};return s}};const result=await syncSource(failing,source,1);assert.equal(result.status,'error');assert.equal(result.error,'synthetic state read failure');assert.equal(sql.prepare('SELECT status FROM research_runs').get()!.status,'error');assert.equal(sql.prepare('SELECT error FROM research_sources WHERE id=?').get(source.id)!.error,result.error);assert.equal(sql.prepare("SELECT count(*) n FROM research_settings WHERE key=?").get('lock:'+source.id)!.n,0);}finally{globalThis.fetch=oldFetch;sql.close()}});
test('deadline is a pure projection; zero-source disconnect closes interrupted after workflow grace, never completed',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at,[]);assert.equal(batchLifecycle(sql.prepare('SELECT * FROM research_batches').get(),later(at,260000))!.executionState,'awaiting_reconciliation');assert.equal((await reconcileBatches(db,later(at,539999))).closed,0);assert.equal((await reconcileBatches(db,later(at,540000))).closed,1);assert.equal((await reconcileBatches(db,later(at,600000))).closed,0);const row=sql.prepare('SELECT * FROM research_batches').get()!;assert.equal(row.status,'interrupted');assert.equal(row.finished_at,null);assert.ok(row.closed_at);const coverage=await batchCoverage(db,key,later(at,700000).toISOString());assert.equal(coverage.status,'partial');assert.equal(coverage.batchStatus,'interrupted');assert.equal((await finishBatch(db,key,later(at,800000))).brief,null);}finally{sql.close()}});
test('active lease and legacy source lock prevent finish and timeout close',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at),run=await admitRun(db,source.id,key,'internal',at.toISOString());assert.ok(run);await assert.rejects(finishBatch(db,key,later(at,5000)),{code:'batch_in_flight'});assert.equal((await reconcileBatches(db,later(at,540000))).closed,0);assert.equal((await reconcileBatches(db,later(at,601000))).closed,1);assert.equal(sql.prepare('SELECT finished_at,status,closed_at FROM research_runs').get()!.finished_at,null);assert.equal(sql.prepare('SELECT status FROM research_runs').get()!.status,'interrupted');}finally{sql.close()}});
test('legacy running request without a lock waits its conservative ten-minute lease',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at);sql.prepare("INSERT INTO research_runs(id,started_at,status,source_id,batch_key) VALUES('old',?,'running',?,?)").run(at.toISOString(),source.id,key);assert.equal((await reconcileBatches(db,later(at,540000))).closed,0);assert.equal((await reconcileBatches(db,later(at,600001))).closed,1);}finally{sql.close()}});
test('source lock acquired before run registration is protected, and terminal batch rejects admission',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at);sql.prepare("INSERT INTO research_settings(key,value) VALUES(?,?)").run('lock:'+source.id,later(at,700000).toISOString());assert.equal((await reconcileBatches(db,later(at,600000))).closed,0);await assert.rejects(finishBatch(db,key,later(at,600000)),{code:'batch_in_flight'});sql.prepare('DELETE FROM research_settings WHERE key=?').run('lock:'+source.id);await finishBatch(db,key,later(at,610000));assert.equal(await admitRun(db,source.id,key,'internal',at.toISOString()),null);assert.equal(sql.prepare('SELECT count(*) n FROM research_runs').get()!.n,0);}finally{sql.close()}});
test('run write fence rolls back every write after expiry or ownership replacement',async()=>{for(const mode of ['expiry','replacement','closed']){const {db,sql}=database();try{const at=now(),key=batch(sql,at),run=await admitRun(db,source.id,key,'internal',at.toISOString()),fenced=fencedRunDatabase(db,run.id);await fenced.prepare("INSERT INTO research_settings(key,value) VALUES('before','ok')").run();if(mode==='expiry')sql.prepare("UPDATE research_runs SET lease_until='2000-01-01T00:00:00Z'").run();if(mode==='replacement')sql.prepare('UPDATE research_settings SET value=? WHERE key=?').run('2099-01-01T00:00:00Z|other',run.key);if(mode==='closed')sql.prepare("UPDATE research_batches SET status='interrupted'").run();await assert.rejects(fenced.batch([fenced.prepare("INSERT INTO research_settings(key,value) VALUES('late','bad')"),fenced.prepare("UPDATE research_settings SET value='bad' WHERE key='before'")]),{code:'collection_lease_lost'});assert.equal(sql.prepare("SELECT count(*) n FROM research_settings WHERE key='late'").get()!.n,0);assert.equal(sql.prepare("SELECT value FROM research_settings WHERE key='before'").get()!.value,'ok');assert.equal(sql.prepare('SELECT count(*) n FROM research_run_write_guards').get()!.n,0);}finally{sql.close()}}});
test('finish retry repairs missing brief atomically and cannot rewrite published evidence',async()=>{const {db,sql}=database();try{await initResearch(db);const at=now(),key=batch(sql,at,[]);sql.prepare("UPDATE research_batches SET status='finished',finished_at=?").run(at.toISOString());const first=await finishBatch(db,key,later(at,1));assert.equal(first.brief.status,'awaiting_analysis');sql.prepare("UPDATE research_briefs SET status='published',summary='Frozen published evidence'").run();const again=await finishBatch(db,key,later(at,2));assert.equal(again.brief.summary,'Frozen published evidence');assert.equal(again.brief.contentHash,first.brief.contentHash);}finally{sql.close()}});
test('all successful source records with lost finish remain partial, and missingness keeps collection incomplete',async()=>{const {db,sql}=database();try{const at=new Date('2026-10-10T00:00:00Z'),key=batch(sql,at);sql.prepare("INSERT INTO research_runs(id,source_id,batch_key,started_at,finished_at,status,details_json) VALUES('ok',?,?,?,?,'ok',?)").run(source.id,key,at.toISOString(),later(at,1000).toISOString(),JSON.stringify({rssStatus:'ok'}));await reconcileBatches(db,later(at,700000));const coverage=await batchCoverage(db,key,later(at,700001).toISOString());assert.equal(coverage.completeSources,1);assert.equal(coverage.status,'partial');const tracking=await briefMissingness(db,later(at,3*3600000));assert.equal(tracking.slots.find((s:any)=>s.batchKey===key)!.collection,'incomplete');}finally{sql.close()}});
test('GET status/day/brief reads and no-op reconcile send no requests and do not close stale batch',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('unexpected external request')};try{await initResearch(db);const key=batch(sql,new Date('2026-10-01T00:00:00Z'));const before=sql.prepare('SELECT * FROM research_batches').get();for(const path of ['/status','/daily?date=2026-10-10'])assert.equal((await researchApi(new Request('https://local.test/api/site/research'+path),{DB:db})).status,200);assert.deepEqual(sql.prepare('SELECT * FROM research_batches').get(),before);const response=await researchApi(new Request('https://local.test/api/site/research/batch/reconcile',{method:'POST',body:'{}'}),{DB:db});assert.equal(response.status,200);assert.equal((await response.json()).closed,1);assert.equal((await reconcileBatches(db)).closed,0);assert.equal(sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.equal((await finishBatch(db,key)).batchStatus,'interrupted');}finally{globalThis.fetch=oldFetch;sql.close()}});
test('late fetch after interruption cannot save papers, records, snapshots or advance cursor',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;let release:any,entered:any;const waiting=new Promise<void>(r=>entered=r);globalThis.fetch=async()=>{entered();return new Promise<Response>(r=>release=()=>r(Response.json({message:{items:[record()],'next-cursor':'next'}})))};try{await initResearch(db);const at=now(),key=batch(sql,at);const running=syncSource(db,source,1,key);await waiting;const before=sql.prepare("SELECT value FROM research_settings WHERE key=?").get('crossref:'+source.id)!.value;sql.prepare("UPDATE research_runs SET lease_until='2000-01-01T00:00:00Z'").run();sql.prepare("UPDATE research_settings SET value='2000-01-01T00:00:00Z' WHERE key=?").run('lock:'+source.id);await reconcileBatches(db,later(at,700000));release();const result=await running;assert.equal(result.status,'interrupted');assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_records').get()!.n,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_batch_members').get()!.n,0);assert.equal(sql.prepare("SELECT value FROM research_settings WHERE key=?").get('crossref:'+source.id)!.value,before);}finally{globalThis.fetch=oldFetch;sql.close()}});
test('missing provider connection defers without changing stored evidence or scoring pending papers',async()=>{const {db,sql}=database();const old=globalThis.fetch;try{await initResearch(db);const p=fromCrossref(record(),source);await savePaper(db,p,now().toISOString(),{runId:'discovery',batchKey:null,deferScoring:true});await queueMetadata(db,[p]);globalThis.fetch=async()=>{throw Error('no external request without configured key')};await enrichMetadata(db,{});assert.equal(sql.prepare('SELECT metadata_status FROM research_papers').get().metadata_status,'pending');assert.equal(sql.prepare('SELECT priority FROM research_papers').get().priority,0);assert.equal(sql.prepare('SELECT status FROM research_enrichment_queue').get().status,'deferred');}finally{globalThis.fetch=old;sql.close()}});

test('maintenance deadline preserves queue with an independent released run lease',async()=>{const {db,sql}=database();const old=globalThis.fetch;try{await initResearch(db);const papers=Array.from({length:41},(_,n)=>fromCrossref(record('10.1234/chunk'+n),source));await queueMetadata(db,papers);globalThis.fetch=async()=>{throw Error('deadline must not dispatch')};const result=await enrichMetadata(db,{}, {maxMs:1});assert.equal(result.reason,'deadline');assert.equal(sql.prepare('SELECT count(*) n FROM research_enrichment_queue').get().n,41);assert.equal(sql.prepare("SELECT count(*) n FROM research_settings WHERE key='lock:__metadata__'").get().n,0);assert.equal(sql.prepare('SELECT phase FROM research_runs').get().phase,'metadata');}finally{globalThis.fetch=old;sql.close()}});

test('vague titles retain scope_pending and original attribution without inline enrichment',async()=>{const {db,sql}=database();const old=globalThis.fetch;const s=RESEARCH_SOURCES.find(s=>s.id==='nature-electronics');try{await initResearch(db);const raw={type:'journal-article',ISSN:s.issns,DOI:'10.1234/scope',title:['An unexpected observation'],'published-online':{'date-parts':[monthWindow().endDate.split('-').map(Number)]}};globalThis.fetch=async(input)=>new URL(String(input)).hostname==='api.crossref.org'?Response.json({message:{items:[raw]}}):new Response('<rss><channel/></rss>');const result=await syncSource(db,s,1);assert.equal(result.scopeUnresolved,1);assert.equal(result.scopePending,1);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get().n,0);const queued=sql.prepare('SELECT * FROM research_enrichment_queue').get();assert.equal(queued.scope_pending,1);assert.equal(queued.origin_run_id,result.runId);assert.ok(queued.daily_cohort_key);}finally{globalThis.fetch=old;sql.close()}});
