import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {admitRun,fencedRunDatabase,reconcileBatches,batchLifecycle} from './research-lifecycle.ts';
import {finishBatch,startBatch,batchCoverage,briefMissingness} from './research-batches.ts';
import {initResearch,researchApi,savePaper,syncSource,enrichBatch} from './research.ts';
import {RESEARCH_SOURCES} from './research-config.ts';
import {fromCrossref} from './research-domain.ts';
import {monthWindow} from './research-pipeline.ts';
function database(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db:any={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},async run(){return {meta:{changes:Number(s.run(...this.args).changes)}}}}},async batch(statements:any[]){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const now=()=>new Date(),later=(at:Date,ms:number)=>new Date(at.getTime()+ms);
const source=RESEARCH_SOURCES[0]!;
function batch(sql:any,at:Date,ids=[source.id],key='2026-10-10/08'){sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,'2026-10-10',8,'running',?,?)").run(key,JSON.stringify(ids),at.toISOString());return key}
const record=(doi='10.1234/recovery',title='TCAD transistor test')=>({type:'journal-article',DOI:doi,title:[title],published:{'date-parts':[monthWindow().endDate.split('-').map(Number)]}});

test('completed queue entries cannot bypass the shared pending and blocked capacity when reactivated',async()=>{const {db,sql}=database();try{await initResearch(db);const p=(await savePaper(db,fromCrossref(record(),source)!)).paper;sql.exec("WITH RECURSIVE n(x) AS (SELECT 1 UNION ALL SELECT x+1 FROM n WHERE x<2000) INSERT INTO research_enrichment_queue(doi,source_id,paper_json,status,next_attempt_at,updated_at) SELECT '10.1234/reserved'||x,'other','{}','blocked','2099-01-01T00:00:00Z','2026-10-10T00:00:00Z' FROM n");sql.prepare("INSERT INTO research_enrichment_queue(doi,source_id,paper_json,status,next_attempt_at,updated_at) VALUES(?,?,?,'done',?,?)").run(p.doi,p.sourceId,JSON.stringify(p),now().toISOString(),now().toISOString());const result=await enrichBatch(db,[p],{added:0,updated:0},undefined,Date.now());assert.match(result.failures.join(' '),/queue_capacity_deferred/);assert.equal(sql.prepare("SELECT count(*) n FROM research_enrichment_queue WHERE status IN ('pending','blocked')").get()!.n,2000);assert.equal(sql.prepare('SELECT status FROM research_enrichment_queue WHERE doi=?').get(p.doi)!.status,'done');}finally{sql.close()}});

test('fence preserves D1 prepared statement raw method instead of mistaking it for a wrapper',async()=>{const {db,sql}=database();try{const actual={...db,prepare(q:string){const s=db.prepare(q);s.raw=async()=>{throw Error('unexpected raw call')};return s}};const run=await admitRun(actual,source.id,null,'internal',now().toISOString()),fenced=fencedRunDatabase(actual,run.id);await fenced.prepare("INSERT INTO research_settings(key,value) VALUES('raw-method','ok')").run();await fenced.batch([fenced.prepare("UPDATE research_settings SET value=? WHERE key='raw-method'").bind('still-ok')]);assert.equal(sql.prepare("SELECT value FROM research_settings WHERE key='raw-method'").get()!.value,'still-ok');}finally{sql.close()}});

test('unexpected pre-fetch error closes source and run together without invalidating its own fence',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('unexpected egress')};try{await initResearch(db);const failing={...db,prepare(q:string){const s=db.prepare(q);if(q==='SELECT * FROM research_sources WHERE id=?')s.first=async()=>{throw Error('synthetic state read failure')};return s}};const result=await syncSource(failing,source,1);assert.equal(result.status,'error');assert.equal(result.error,'synthetic state read failure');assert.equal(sql.prepare('SELECT status FROM research_runs').get()!.status,'error');assert.equal(sql.prepare('SELECT error FROM research_sources WHERE id=?').get(source.id)!.error,result.error);assert.equal(sql.prepare("SELECT count(*) n FROM research_settings WHERE key=?").get('lock:'+source.id)!.n,0);}finally{globalThis.fetch=oldFetch;sql.close()}});
test('deadline is a pure projection; zero-source disconnect closes interrupted after workflow grace, never completed',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at,[]);assert.equal(batchLifecycle(sql.prepare('SELECT * FROM research_batches').get(),later(at,260000))!.executionState,'awaiting_reconciliation');assert.equal((await reconcileBatches(db,later(at,539999))).closed,0);assert.equal((await reconcileBatches(db,later(at,540000))).closed,1);assert.equal((await reconcileBatches(db,later(at,600000))).closed,0);const row=sql.prepare('SELECT * FROM research_batches').get()!;assert.equal(row.status,'interrupted');assert.equal(row.finished_at,null);assert.ok(row.closed_at);const coverage=await batchCoverage(db,key,later(at,700000).toISOString());assert.equal(coverage.status,'partial');assert.equal(coverage.batchStatus,'interrupted');assert.equal((await finishBatch(db,key,later(at,800000))).brief,null);}finally{sql.close()}});
test('active lease and legacy source lock prevent finish and timeout close',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at),run=await admitRun(db,source.id,key,'internal',at.toISOString());assert.ok(run);await assert.rejects(finishBatch(db,key,later(at,5000)),{code:'batch_in_flight'});assert.equal((await reconcileBatches(db,later(at,540000))).closed,0);assert.equal((await reconcileBatches(db,later(at,601000))).closed,1);assert.equal(sql.prepare('SELECT finished_at,status,closed_at FROM research_runs').get()!.finished_at,null);assert.equal(sql.prepare('SELECT status FROM research_runs').get()!.status,'interrupted');}finally{sql.close()}});
test('legacy running request without a lock waits its conservative ten-minute lease',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at);sql.prepare("INSERT INTO research_runs(id,started_at,status,source_id,batch_key) VALUES('old',?,'running',?,?)").run(at.toISOString(),source.id,key);assert.equal((await reconcileBatches(db,later(at,540000))).closed,0);assert.equal((await reconcileBatches(db,later(at,600001))).closed,1);}finally{sql.close()}});
test('source lock acquired before run registration is protected, and terminal batch rejects admission',async()=>{const {db,sql}=database();try{const at=now(),key=batch(sql,at);sql.prepare("INSERT INTO research_settings(key,value) VALUES(?,?)").run('lock:'+source.id,later(at,700000).toISOString());assert.equal((await reconcileBatches(db,later(at,600000))).closed,0);await assert.rejects(finishBatch(db,key,later(at,600000)),{code:'batch_in_flight'});sql.prepare('DELETE FROM research_settings WHERE key=?').run('lock:'+source.id);await finishBatch(db,key,later(at,610000));assert.equal(await admitRun(db,source.id,key,'internal',at.toISOString()),null);assert.equal(sql.prepare('SELECT count(*) n FROM research_runs').get()!.n,0);}finally{sql.close()}});
test('run write fence rolls back every write after expiry or ownership replacement',async()=>{for(const mode of ['expiry','replacement','closed']){const {db,sql}=database();try{const at=now(),key=batch(sql,at),run=await admitRun(db,source.id,key,'internal',at.toISOString()),fenced=fencedRunDatabase(db,run.id);await fenced.prepare("INSERT INTO research_settings(key,value) VALUES('before','ok')").run();if(mode==='expiry')sql.prepare("UPDATE research_runs SET lease_until='2000-01-01T00:00:00Z'").run();if(mode==='replacement')sql.prepare('UPDATE research_settings SET value=? WHERE key=?').run('2099-01-01T00:00:00Z|other',run.key);if(mode==='closed')sql.prepare("UPDATE research_batches SET status='interrupted'").run();await assert.rejects(fenced.batch([fenced.prepare("INSERT INTO research_settings(key,value) VALUES('late','bad')"),fenced.prepare("UPDATE research_settings SET value='bad' WHERE key='before'")]),{code:'collection_lease_lost'});assert.equal(sql.prepare("SELECT count(*) n FROM research_settings WHERE key='late'").get()!.n,0);assert.equal(sql.prepare("SELECT value FROM research_settings WHERE key='before'").get()!.value,'ok');assert.equal(sql.prepare('SELECT count(*) n FROM research_run_write_guards').get()!.n,0);}finally{sql.close()}}});
test('finish retry repairs missing brief atomically and cannot rewrite published evidence',async()=>{const {db,sql}=database();try{await initResearch(db);const at=now(),key=batch(sql,at,[]);sql.prepare("UPDATE research_batches SET status='finished',finished_at=?").run(at.toISOString());const first=await finishBatch(db,key,later(at,1));assert.equal(first.brief.status,'awaiting_analysis');sql.prepare("UPDATE research_briefs SET status='published',summary='Frozen published evidence'").run();const again=await finishBatch(db,key,later(at,2));assert.equal(again.brief.summary,'Frozen published evidence');assert.equal(again.brief.contentHash,first.brief.contentHash);}finally{sql.close()}});
test('all successful source records with lost finish remain partial, and missingness keeps collection incomplete',async()=>{const {db,sql}=database();try{const at=new Date('2026-10-10T00:00:00Z'),key=batch(sql,at);sql.prepare("INSERT INTO research_runs(id,source_id,batch_key,started_at,finished_at,status,details_json) VALUES('ok',?,?,?,?,'ok',?)").run(source.id,key,at.toISOString(),later(at,1000).toISOString(),JSON.stringify({rssStatus:'ok'}));await reconcileBatches(db,later(at,700000));const coverage=await batchCoverage(db,key,later(at,700001).toISOString());assert.equal(coverage.completeSources,1);assert.equal(coverage.status,'partial');const tracking=await briefMissingness(db,later(at,3*3600000));assert.equal(tracking.slots.find((s:any)=>s.batchKey===key)!.collection,'incomplete');}finally{sql.close()}});
test('GET status/day/brief reads and no-op reconcile send no requests and do not close stale batch',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;globalThis.fetch=async()=>{throw Error('unexpected external request')};try{await initResearch(db);const key=batch(sql,new Date('2026-10-01T00:00:00Z'));const before=sql.prepare('SELECT * FROM research_batches').get();for(const path of ['/status','/daily?date=2026-10-10'])assert.equal((await researchApi(new Request('https://local.test/api/site/research'+path),{DB:db})).status,200);assert.deepEqual(sql.prepare('SELECT * FROM research_batches').get(),before);const response=await researchApi(new Request('https://local.test/api/site/research/batch/reconcile',{method:'POST',body:'{}'}),{DB:db});assert.equal(response.status,200);assert.equal((await response.json()).closed,1);assert.equal((await reconcileBatches(db)).closed,0);assert.equal(sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.equal((await finishBatch(db,key)).batchStatus,'interrupted');}finally{globalThis.fetch=oldFetch;sql.close()}});
test('late fetch after interruption cannot save papers, records, snapshots or advance cursor',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;let release:any,entered:any;const waiting=new Promise<void>(r=>entered=r);globalThis.fetch=async()=>{entered();return new Promise<Response>(r=>release=()=>r(Response.json({message:{items:[record()],'next-cursor':'next'}})))};try{await initResearch(db);const at=now(),key=batch(sql,at);const running=syncSource(db,source,1,key);await waiting;const before=sql.prepare("SELECT value FROM research_settings WHERE key=?").get('crossref:'+source.id)!.value;sql.prepare("UPDATE research_runs SET lease_until='2000-01-01T00:00:00Z'").run();sql.prepare("UPDATE research_settings SET value='2000-01-01T00:00:00Z' WHERE key=?").run('lock:'+source.id);await reconcileBatches(db,later(at,700000));release();const result=await running;assert.equal(result.status,'interrupted');assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_records').get()!.n,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_batch_members').get()!.n,0);assert.equal(sql.prepare("SELECT value FROM research_settings WHERE key=?").get('crossref:'+source.id)!.value,before);}finally{globalThis.fetch=oldFetch;sql.close()}});
test('OpenAlex conflicting identifiers are isolated without losing valid neighbors',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;try{await initResearch(db);const papers=[];for(let n=0;n<3;n++)papers.push((await savePaper(db,fromCrossref(record('10.1234/oa'+n,'TCAD paper '+n),source)!)).paper);globalThis.fetch=async()=>Response.json({results:[{id:'https://openalex.org/W1',doi:papers[0].doi,title:papers[0].title,abstract_inverted_index:{Wrong:[0]}},{id:'https://openalex.org/W2',doi:papers[0].doi,title:papers[0].title,abstract_inverted_index:{Other:[0]}},{id:'invalid',doi:papers[1].doi,title:papers[1].title},{id:'https://openalex.org/W3',doi:papers[2].doi,title:papers[2].title,abstract_inverted_index:{Valid:[0],evidence:[1]},keywords:[]} ]});const result=await enrichBatch(db,papers,{added:0,updated:0});assert.equal(result.enriched,1);assert.equal(sql.prepare('SELECT abstract FROM research_papers WHERE doi=?').get(papers[0].doi)!.abstract,null);assert.equal(sql.prepare('SELECT abstract FROM research_papers WHERE doi=?').get(papers[2].doi)!.abstract,'Valid evidence');assert.equal(sql.prepare("SELECT count(*) n FROM research_enrichment_queue WHERE status='blocked'").get()!.n,2);}finally{globalThis.fetch=oldFetch;sql.close()}});
test('forty-item chunk defers remaining work durably at shared gate without sending a throttled second request',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;let calls=0;try{await initResearch(db);const papers=[];for(let n=0;n<41;n++)papers.push((await savePaper(db,fromCrossref(record('10.1234/chunk'+n,'TCAD paper '+n),source)!)).paper);globalThis.fetch=async()=>{calls++;return Response.json({results:[]})};const first=await enrichBatch(db,papers,{added:0,updated:0});assert.equal(calls,1);assert.match(first.failures.join(' '),/shared interval deferred/);assert.equal(sql.prepare("SELECT count(*) n FROM research_enrichment_queue WHERE status='pending'").get()!.n,41);await enrichBatch(db,[],{added:0,updated:0},undefined,Date.now()+75000,{},source.id);assert.equal(calls,1);sql.prepare("UPDATE scholarly_usage SET next_allowed=0 WHERE service='openalex'").run();sql.prepare("UPDATE research_enrichment_queue SET next_attempt_at='2000-01-01T00:00:00Z' WHERE doi='10.1234/chunk9'").run();await enrichBatch(db,[],{added:0,updated:0},undefined,Date.now()+75000,{},source.id);assert.equal(calls,2);}finally{globalThis.fetch=oldFetch;sql.close()}});
test('vague current-month title is screened only after bounded DOI evidence; unrelated abstract stays outside papers',async()=>{const {db,sql}=database();const oldFetch=globalThis.fetch;const s=RESEARCH_SOURCES.find(s=>s.id==='nature-electronics')!;let requested=false;try{await initResearch(db);const day=monthWindow().endDate,raw={type:'journal-article',ISSN:s.issns,DOI:'10.1234/scope',title:['An unexpected observation'],'published-online':{'date-parts':[day.split('-').map(Number)]}};globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org')return Response.json({message:{items:[raw,{...raw,DOI:'10.1234/unrelated',title:['A second observation']}]}});if(u.hostname==='api.openalex.org'){requested=true;return Response.json({results:[{id:'https://openalex.org/W100',doi:raw.DOI,title:raw.title[0],abstract_inverted_index:{TCAD:[0],transistor:[1],simulation:[2]},keywords:[]},{id:'https://openalex.org/W101',doi:'10.1234/unrelated',title:'A second observation',abstract_inverted_index:{Biology:[0],specimen:[1]},keywords:[]}]})}return new Response('<rss><channel/></rss>')};const result=await syncSource(db,s,1);assert.equal(requested,true);assert.equal(result.scopeUnresolved,2);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);assert.equal(sql.prepare('SELECT abstract FROM research_papers').get()!.abstract,'TCAD transistor simulation');assert.equal(sql.prepare('SELECT count(*) n FROM research_batch_members').get()!.n,1);}finally{globalThis.fetch=oldFetch;sql.close()}});
