import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';import {mkdir,writeFile,readFile} from 'node:fs/promises';
await mkdir('.sites-runtime',{recursive:true});
await writeFile('.sites-runtime/component-controls-fixture.tsx',`import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {ActionButton,Notice,Stats,Pagination,SectionHeading,FilterActions,EmptyState} from '../apps/web/app/components/ui/ResearchControls';import {MonthControls,CalendarTable} from '../apps/web/app/components/ui/Calendar';export function controls(){return renderToStaticMarkup(<><ActionButton appearance="primary" type="submit" disabled aria-busy="true">保存</ActionButton><ActionButton appearance="secondary">操作</ActionButton><Notice tone="error" role="alert">错误</Notice><Notice tone="notice">静态说明</Notice><EmptyState as="section"><h2>暂无内容</h2></EmptyState><Stats><div><b>2</b><span>论文</span></div></Stats><Pagination aria-label="分页"><a href="?page=2">下一页</a></Pagination><SectionHeading><h2>章节</h2></SectionHeading><FilterActions><button type="submit">筛选</button></FilterActions></>)}export function calendar(month){return renderToStaticMarkup(<><MonthControls month={month} onMonth={()=>{}} yearLabel="年份" monthLabel="月份"/><CalendarTable month={month} caption="月份日历" renderDay={date=><a href={'?date='+date}>{date}</a>}/></>)};`);
await build({entryPoints:['.sites-runtime/component-controls-fixture.tsx'],outfile:'.sites-runtime/component-controls-fixture.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',logLevel:'silent'});
const {controls,calendar}=await import('../.sites-runtime/component-controls-fixture.mjs');
test('shared controls preserve native elements, classes, explicit submit and live-region semantics without wrappers',()=>{assert.equal(controls(),'<button class="research-primary" type="submit" disabled="" aria-busy="true">保存</button><button class="ai-secondary">操作</button><p class="ai-error" role="alert">错误</p><p class="research-notice">静态说明</p><section class="research-empty"><h2>暂无内容</h2></section><div class="research-stats"><div><b>2</b><span>论文</span></div></div><nav class="research-pagination" aria-label="分页"><a href="?page=2">下一页</a></nav><div class="weekly-section-title"><h2>章节</h2></div><div class="rail-filter-actions"><button type="submit">筛选</button></div>')});
test('shared calendar preserves Monday-first cells, bounded native controls and caller-owned day links',()=>{const h=calendar('2024-02');assert.equal((h.match(/<th scope="col">/g)||[]).length,7);assert.equal((h.match(/href="\?date=/g)||[]).length,29);assert.ok(h.includes('?date=2024-02-29'));assert.match(calendar('1900-01'),/aria-label="上个月" disabled=""/);assert.match(calendar('9999-12'),/aria-label="下个月" disabled=""/);assert.ok(!h.includes('role="grid"'))});
test('calendar keyboard commit and invalid-year restoration remain in one controller',async()=>{const source=await readFile('apps/web/app/components/ui/Calendar.tsx','utf8');for(const token of ["e.key==='Enter'",'e.preventDefault();apply(draft)','onBlur={e=>apply(e.target.value)}','next>=1900&&next<=9999','else setDraft(String(year))','useEffect(()=>setDraft(String(year)),[year])'])assert.ok(source.includes(token),token)});
test('visual tokens, interaction feedback and shell ownership are not copied into research controls',async()=>{const ui=await readFile('apps/web/app/components/ui/ResearchControls.tsx','utf8'),root=await readFile('apps/web/app/root.tsx','utf8');assert.ok(!/useEffect|fetch\(|style=|useState/.test(ui));assert.equal((root.match(/<AIAssistant /g)||[]).length,1);const css=await readFile('apps/web/app/interactions.css','utf8');for(const term of ['--interaction-duration:160ms','@media(hover:hover)',':active',':focus-visible','@media(prefers-reduced-motion:reduce)','min-height:44px'])assert.ok(css.includes(term),term)});
