import {test} from 'node:test';
import assert from 'node:assert/strict';
import {publicationQuery,publicationWindow,publishHkis,publicationLink} from '../packages/backend/src/publication/hkis.ts';
import {hkisEndpoint,rssDocument} from './hkis-endpoints.ts';
const url='https://myhot-research.sea0monsters15.chatgpt.site';
const env={HKIS_OWNER_EMAIL:'test@example.org'};
const identity={'oai-authenticated-user-id':'test-user','oai-authenticated-user-email':'test@example.org'};
const rpc=(body:any,headers:any={})=>hkisEndpoint(new Request(url+'/mcp',{method:'POST',headers:{'content-type':'application/json',...headers},body:typeof body==='string'?body:JSON.stringify(body)}),env);
const call=(method:string,params:any={},headers:any={})=>rpc({jsonrpc:'2.0',id:1,method,params},headers);
test('strict query validation and per-section semantics',()=>{assert.deepEqual(publicationQuery({}),{section:'papers',limit:25});for(const p of [{limit:0},{limit:51},{limit:2.1},{section:'write'},{token:'secret'},{date_since:'2026-01-01'},{date_since:'2026-02-30T00:00:00Z'},{section:'daily',date:'2026-02-30'},{section:'daily',q:'ignored'},{state:'invalid'},{section:'reader',state:'other'}])assert.throws(()=>publicationQuery(p));});
test('tracking pagination parameters stay separate from the brief-list cursor',()=>{assert.deepEqual(publicationQuery({section:'briefs',limit:7,cursor:'brief-page',tracking_limit:'5',tracking_cursor:'tracking-page'}),{section:'briefs',limit:7,cursor:'brief-page',tracking_limit:5,tracking_cursor:'tracking-page'});assert.throws(()=>publicationQuery({section:'papers',tracking_limit:5}));assert.throws(()=>publicationQuery({section:'briefs',tracking_limit:0}));});
test('stable Unicode cursor binds filters and rejects tampering',async()=>{const q=publicationQuery({section:'keywords',limit:1});const w=await publicationWindow(q,new Date('2026-10-05'));const token=w.next({id:'keyword:界面',updatedAt:'2026-10-04T00:00:00.000Z',title:'',summary:'',url:'',keywords:[],data:{}});const decoded=await publicationWindow({...q,cursor:token},new Date('2026-10-06'));assert.equal(decoded.after![1],'keyword:界面');await assert.rejects(()=>publicationWindow({...q,limit:2,cursor:token}));await assert.rejects(()=>publicationWindow({...q,cursor:'!!!'}));});
test('publication pages stable IDs, inclusive timestamp, no fake empty items',async()=>{const entries=[1,2,3].map(n=>({id:'paper:'+n,title:'paper',updatedAt:'2026-10-01T00:00:00.000Z',url:url+'/research/'+n,summary:'',keywords:[],data:{}}));const q=publicationQuery({limit:2,date_since:'2026-10-01T00:00:00Z'});const page=await publishHkis(q,async()=>({items:entries,coverage:{}}));assert.deepEqual(page.items.map(i=>i.id),['paper:3','paper:2']);const second=await publishHkis({...q,cursor:page.nextCursor!},async()=>({items:entries,coverage:{}}));assert.deepEqual(second.items.map(i=>i.id),['paper:1']);const empty=await publishHkis(q,async()=>({items:[],coverage:{}}));assert.equal(empty.nextCursor,null);assert.deepEqual(empty.items,[]);});
test('RSS XML removes forbidden controls, escapes content, retains emoji and stable GUID',()=>{const page:any={section:'papers',items:[{id:'paper:a',title:'A < B & "C"\u0001😀',url:url+'/research/a',updatedAt:'2026-10-01T00:00:00Z',summary:'</description><script>x</script>',keywords:['A&B'],data:{abstract:'<test>'}}],nextCursor:'next',coverage:{empty:false}};const text=rssDocument(page,{section:'papers'});assert.ok(text.includes('A &lt; B &amp; &quot;C&quot;😀'));assert.ok(!text.includes('\u0001'));assert.ok(!text.includes('<script>'));assert.ok(text.includes('urn:hkis:paper:a'));assert.ok(text.includes('rel="next"'));assert.ok(text.includes('<hkis:data>'));});
test('URLs discard credentials and token query parameters',()=>{assert.equal(publicationLink('javascript:alert(1)'),null);assert.equal(publicationLink('https://me:secret@example.com'),null);assert.equal(publicationLink('https://example.com/p?token=secret&x=1&sig=secret'),'https://example.com/p?x=1');});
test('MCP initialization negotiates version with no private data',async()=>{const r=await call('initialize',{protocolVersion:'1999',capabilities:{},clientInfo:{name:'test',version:'1'}});assert.equal(r.status,200);const data=await r.json();assert.equal(data.result.protocolVersion,'2025-11-25');assert.ok(!JSON.stringify(data).includes('test@example.org'));});
test('MCP discovery only advertises read-only tools',async()=>{const r=await call('tools/list');const data=await r.json();assert.equal(data.result.tools.length,2);for(const tool of data.result.tools){assert.equal(tool.annotations.readOnlyHint,true);assert.equal(tool.annotations.destructiveHint,false)}assert.equal((await (await call('tools/call',{name:'hkis_capabilities'})).json()).result.isError,false);});
test('MCP notifications never execute data reads',async()=>{const response=await rpc({jsonrpc:'2.0',method:'tools/call',params:{name:'hkis_read'}});assert.equal(response.status,202);assert.equal(await response.text(),'');});
test('MCP returns protocol, JSON parse, method and argument errors',async()=>{assert.equal((await rpc('{')).status,400);assert.equal((await rpc({jsonrpc:'1.0',id:1,method:'ping'})).status,400);assert.equal((await (await call('write')).json()).error.code,-32601);assert.equal((await (await call('tools/call',{name:'delete'})).json()).error.code,-32602);assert.equal((await (await call('tools/call',{name:'hkis_read',arguments:{limit:99}},identity)).json()).error.code,-32602);assert.equal((await call('ping',{}, {'mcp-protocol-version':'invalid'})).status,400);assert.equal((await call('ping',{}, {origin:'https://evil.invalid'})).status,403);});
test('private data requires actual owner identity, never bypass bearer',async()=>{for(const [headers,status] of [[{},401],[{'OAI-Sites-Authorization':'Bearer fake'},401],[{...identity,'oai-authenticated-user-email':'wrong@example.org'},403]] as const){assert.equal((await call('tools/call',{name:'hkis_read'},headers)).status,status);assert.equal((await hkisEndpoint(new Request(url+'/feeds/research.xml',{headers}),env)).status,status);}});
test('RSS owner capability feed has private caching, weak ETag revalidation and HEAD',async()=>{const req=()=>new Request(url+'/feeds/research.xml?section=capabilities',{headers:identity});const r=await hkisEndpoint(req(),env);assert.equal(r.status,200);assert.match(r.headers.get('cache-control')!,/^private/);assert.match(r.headers.get('content-type')!,/application\/rss\+xml/);assert.ok(r.headers.get('vary')!.includes('Authorization'));const etag=r.headers.get('etag')!;assert.ok(etag.startsWith('W/'));const revalidated=await hkisEndpoint(new Request(req(),{headers:{...identity,'if-none-match':etag}}),env);assert.equal(revalidated.status,304);const head=await hkisEndpoint(new Request(req(),{method:'HEAD'}),env);assert.equal(head.status,200);assert.equal(await head.text(),'');});
test('RSS rejects duplicate, unknown or token query parameters and writes',async()=>{for(const query of ['?limit=2&limit=3','?token=secret','?section=daily&q=x'])assert.equal((await hkisEndpoint(new Request(url+'/feeds/research.xml'+query,{headers:identity}),env)).status,400);assert.equal((await hkisEndpoint(new Request(url+'/feeds/research.xml',{method:'POST',headers:identity}),env)).status,405);});
test('request bodies are bounded and private errors never reflect content',async()=>{const r=await rpc('x'.repeat(25000));assert.equal(r.status,413);assert.ok(!(await r.text()).includes('xxx'));});
test('per-isolate burst protection returns retry-after',async()=>{let r;for(let i=0;i<92;i++)r=await call('tools/call',{name:'hkis_read',arguments:{section:'capabilities'}},{...identity,'oai-authenticated-user-id':'burst-test'});assert.equal(r!.status,429);assert.equal(r!.headers.get('retry-after'),'60');});

test('JSON-valid batches and primitives are invalid requests, not parse errors',async()=>{for(const b of ['[]','null','1','true'])assert.equal((await (await rpc(b)).json()).error.code,-32600);assert.equal((await call('ping',{}, {accept:'image/png'})).status,406);});

test('MCP numeric schema is strict while RSS query numbers are parsed',async()=>{const r=await call('tools/call',{name:'hkis_read',arguments:{section:'capabilities',limit:'2'}},identity);assert.equal((await r.json()).error.code,-32602);});
