import {AIError,owner} from './ai/security.ts';
import {publicationQuery,publicationHash,publicationLink,PublicationError,type HkisPage} from '../packages/backend/src/publication/hkis.ts';
import {HKIS_CAPABILITIES,HKIS_ORIGIN,readHkis} from './hkis-publication.ts';
export const PRIVATE_HEADERS={'Cache-Control':'private, no-cache, must-revalidate','Vary':'Cookie, Authorization, OAI-Sites-Authorization','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'};
const noStore={...PRIVATE_HEADERS,'Cache-Control':'private, no-store'};
const json=(value:unknown,status=200,extra:Record<string,string>={})=>Response.json(value,{status,headers:{...noStore,...extra}});
export const PROTOCOLS=['2025-11-25','2025-06-18','2025-03-26'];
export const HKIS_TOOLS=[{name:'hkis_capabilities',description:'Discover read-only HKIS page coverage, filtering, limits and authentication constraints. Contains no private research data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}},{name:'hkis_read',description:'Read stored HKIS papers/details, progress, dated daily reports with citations, keyword statistics and paper lists, owner reading/favorites, changelog, or safe coverage status. Never crawls, calls models or changes data. All data requires the authenticated Site owner.',inputSchema:{type:'object',properties:{section:{type:'string',enum:HKIS_CAPABILITIES.sections},limit:{type:'integer',minimum:1,maximum:50,default:25},cursor:{type:'string',maxLength:1200,description:'Stored publication-list cursor; for briefs this paginates brief records only.'},tracking_cursor:{type:'string',maxLength:1200,description:'Independent batch-missingness tracking cursor; use only with section briefs.'},tracking_limit:{type:'integer',minimum:1,maximum:50,default:25,description:'Batch-missingness slots per page; independent of limit.'},date_since:{type:'string',format:'date-time',description:'Inclusive UTC material-update lower bound; retain overlapping checkpoints and deduplicate by stable ID/update'},date:{type:'string',format:'date',description:'UTC+08 archive date (daily) or paper date (progress)'},id:{type:'string',maxLength:240,description:'Paper ID or DOI'},q:{type:'string',maxLength:240},topic:{type:'string',maxLength:240},publisher:{type:'string',maxLength:240},min:{type:'number',minimum:0,maximum:100},keyword:{type:'string',maxLength:240},state:{type:'string',enum:['read','unread','favorite','all']},basis:{type:'string',enum:['updated','collection','publication']},metric:{type:'string',enum:['rule','ai']}},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}}];
// Per-isolate burst protection bounds CPU/DB work, not a global quota or persistent identity store.
const buckets=new Map<string,{at:number;n:number}>();
function throttle(id:string){const time=Date.now();if(buckets.size>1024)for(const [key,value] of buckets)if(time-value.at>60000)buckets.delete(key);const old=buckets.get(id);if(old&&time-old.at<60000){if(++old.n>90)throw new PublicationError('rate_limited',429)}else{if(buckets.size>=2048)throw new PublicationError('rate_limited',429);buckets.set(id,{at:time,n:1})}}
function authenticate(request:Request,env:any){if(!request.headers.get('oai-authenticated-user-id')||!request.headers.get('oai-authenticated-user-email'))throw new PublicationError('authentication_required',401);return owner(request,env)}
const xml=(v:unknown)=>String(v??'').replace(/[^\u0009\u000A\u000D\u0020-\uD7FF\uE000-\uFFFD\u{10000}-\u{10FFFF}]/gu,'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!));
export function rssDocument(page:HkisPage,query:Record<string,string>){
 const params=new URLSearchParams(query),self=HKIS_ORIGIN+'/feeds/research.xml?'+params;
 const next=new URL(self);if(page.nextCursor)next.searchParams.set('cursor',page.nextCursor);
 const update=page.items.map(i=>i.updatedAt).filter((v):v is string=>!!v).sort().at(-1);
 const items=page.items.map(e=>`<item><guid isPermaLink="false">${xml('urn:hkis:'+e.id)}</guid><title>${xml(e.title)}</title><link>${xml(publicationLink(e.url)||HKIS_ORIGIN)}</link>${e.updatedAt?`<pubDate>${xml(new Date(e.updatedAt).toUTCString())}</pubDate><hkis:updated>${xml(e.updatedAt)}</hkis:updated>`:''}<description>${xml(e.summary)}</description>${e.keywords.map(k=>`<category>${xml(k)}</category>`).join('')}<hkis:data>${xml(JSON.stringify(e.data))}</hkis:data></item>`).join('');
 return `<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:hkis="urn:hkis:read:v1"><channel><title>HKIS · ${xml(page.section)}</title><link>${HKIS_ORIGIN}</link><description>所有者私有只读情报；分页为有界读取，不是不可变数据库快照。通用外部客户端鉴权尚未验证。</description><language>zh-CN</language><atom:link href="${xml(self)}" rel="self" type="application/rss+xml"/>${page.nextCursor?`<atom:link href="${xml(next.href)}" rel="next" type="application/rss+xml"/>`:''}${update?`<lastBuildDate>${xml(new Date(update).toUTCString())}</lastBuildDate>`:''}<hkis:coverage>${xml(JSON.stringify(page.coverage))}</hkis:coverage>${items}</channel></rss>`;
}
function failure(e:unknown){return {code:e instanceof PublicationError||e instanceof AIError?e.code:'read_unavailable',status:e instanceof PublicationError||e instanceof AIError?e.status:503}}
export async function hkisEndpoint(request:Request,env:any){
 const url=new URL(request.url);
 if(url.pathname==='/api/site/integrations')return request.method==='GET'?json(HKIS_CAPABILITIES):json({code:'method_not_allowed'},405,{Allow:'GET'});
 if(url.pathname==='/feeds/research.xml'){
  try{if(!['GET','HEAD'].includes(request.method))return json({code:'method_not_allowed'},405,{Allow:'GET, HEAD'});const id=authenticate(request,env);throttle(id);
   const raw:Record<string,string>={};for(const [key,value] of url.searchParams){if(key in raw)throw new PublicationError('duplicate_argument');raw[key]=value}const query=publicationQuery(raw);const page=await readHkis(env.DB,id,query);const document=rssDocument(page,Object.fromEntries(Object.entries(query).map(([k,v])=>[k,String(v)])));const etag='W/"'+await publicationHash({query,items:page.items,coverage:page.coverage,more:!!page.nextCursor})+'"';const headers={...PRIVATE_HEADERS,'Content-Type':'application/rss+xml; charset=utf-8',ETag:etag};
   if(request.headers.get('if-none-match')?.split(',').map(v=>v.trim().replace(/^W\//,'')).includes(etag.replace(/^W\//,'')))return new Response(null,{status:304,headers});return new Response(request.method==='HEAD'?null:document,{headers});
  }catch(e){const f=failure(e);return json({code:f.code},f.status,f.status===429?{'Retry-After':'60'}:{})}
 }
 if(url.pathname!=='/mcp')return json({code:'not_found'},404);
 if(request.method!=='POST')return json({code:'method_not_allowed'},405,{Allow:'POST'});
 if(!request.headers.get('content-type')?.toLowerCase().startsWith('application/json'))return json({jsonrpc:'2.0',id:null,error:{code:-32600,message:'Content-Type application/json required'}},415);
 const accept=request.headers.get('accept');if(accept&&!accept.includes('application/json')&&!accept.includes('*/*'))return json({code:'not_acceptable'},406);
 const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return json({code:'origin_rejected'},403);
 const version=request.headers.get('mcp-protocol-version');if(version&&!PROTOCOLS.includes(version))return json({jsonrpc:'2.0',id:null,error:{code:-32600,message:'Unsupported protocol version'}},400);
 let body:any;try{const reader=request.body?.getReader();if(!reader)throw new PublicationError('invalid_json');let text='',size=0;const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>24000){await reader.cancel();throw new PublicationError('request_too_large',413)}text+=decoder.decode(value,{stream:true})}text+=decoder.decode();body=JSON.parse(text)}catch(e){const f=failure(e);return json({jsonrpc:'2.0',id:null,error:{code:f.status===413?-32600:-32700,message:f.status===413?'Request too large':'Parse error'}},f.status===413?413:400)}
 if(!body||typeof body!=='object'||Array.isArray(body))return json({jsonrpc:'2.0',id:null,error:{code:-32600,message:'Invalid request'}},400);
 const validId=body.id===undefined||body.id===null||typeof body.id==='string'||typeof body.id==='number'&&Number.isFinite(body.id);
 if(body.jsonrpc!=='2.0'||typeof body.method!=='string'||!validId||body.params!==undefined&&(!body.params||typeof body.params!=='object'||Array.isArray(body.params)))return json({jsonrpc:'2.0',id:null,error:{code:-32600,message:'Invalid request'}},400);
 const id=body.id??null,params=body.params||{},reply=(result:any)=>json({jsonrpc:'2.0',id,result}),error=(code:number,message:string,status=200)=>json({jsonrpc:'2.0',id,error:{code,message}},status);
 if(body.id===undefined){if(!body.method.startsWith('notifications/'))return new Response(null,{status:202,headers:noStore});return new Response(null,{status:202,headers:noStore})}
 if(body.method==='initialize'){if(typeof params.protocolVersion!=='string'||!params.capabilities||typeof params.capabilities!=='object'||Array.isArray(params.capabilities)||!params.clientInfo||typeof params.clientInfo.name!=='string'||typeof params.clientInfo.version!=='string')return error(-32602,'Invalid initialization parameters');return reply({protocolVersion:PROTOCOLS.includes(params.protocolVersion)?params.protocolVersion:PROTOCOLS[0],capabilities:{tools:{listChanged:false}},serverInfo:{name:'hkis-read',version:'1.0.0'},instructions:'Private read-only research. Use hkis_capabilities first. Only stored data; no side effects. External-client authentication must be supported by Sites.'})}
 if(body.method==='ping')return reply({});
 if(body.method==='tools/list'){if(Object.keys(params).some(k=>k!=='_meta'))return error(-32602,'Unexpected tool-list parameters');return reply({tools:HKIS_TOOLS})}
 if(body.method!=='tools/call')return error(-32601,'Method not found');
 if(!['hkis_capabilities','hkis_read'].includes(params.name))return error(-32602,'Unknown tool');
 if(Object.keys(params).some(k=>!['name','arguments','_meta'].includes(k))||params.arguments!==undefined&&(!params.arguments||typeof params.arguments!=='object'||Array.isArray(params.arguments)))return error(-32602,'Invalid tool parameters');
 if(params.name==='hkis_capabilities'){if(Object.keys(params.arguments||{}).length)return error(-32602,'No arguments accepted');return reply({content:[{type:'text',text:JSON.stringify(HKIS_CAPABILITIES)}],structuredContent:HKIS_CAPABILITIES,isError:false})}
 try{const user=authenticate(request,env);throttle(user);const args=params.arguments||{};if(['limit','min','tracking_limit'].some(k=>args[k]!==undefined&&typeof args[k]!=='number'))throw new PublicationError('invalid_numeric_argument');const query=publicationQuery(args),page=await readHkis(env.DB,user,query);return reply({content:[{type:'text',text:JSON.stringify(page)}],structuredContent:page,isError:false})}catch(e){const f=failure(e);if([401,403,429].includes(f.status))return json({jsonrpc:'2.0',id,error:{code:-32000,message:f.code}},f.status,f.status===429?{'Retry-After':'60'}:{});if(f.status===400)return error(-32602,f.code);return reply({content:[{type:'text',text:f.code}],isError:true})}
}
