import {providerRequest} from './scholarly/provider.ts';
import {owner,AIError} from './ai/security.ts';
import {normalizeDoi} from './research-domain.ts';
import {validKeyword,KEYWORD_POLICY} from './paper-keywords.ts';
export const KEYWORD_JOB='keyword-backfill-20261005';
export function openAlexEvidence(raw:any,doi:string,at:string){
 if(!raw||normalizeDoi(raw.doi)!==normalizeDoi(doi))return {policy:KEYWORD_POLICY,checkedAt:at,status:doi?'not_found':'missing_doi',records:[]};
 const terms=(list:any)=>Array.isArray(list)?list.filter(x=>validKeyword(x?.display_name)).map(x=>({label:x.display_name,score:typeof x.score==='number'?x.score:null,id:typeof x.id==='string'?x.id:null})):[];
 const keywords=terms(raw.keywords),topics=terms(raw.topics);
 return {policy:KEYWORD_POLICY,checkedAt:at,status:keywords.length?'found':topics.length?'topics_only':'no_keywords',provider:'openalex',recordUrl:raw.id,providerUpdatedAt:raw.updated_date||null,records:[{kind:'openalex-keyword',method:'model-generated-index',rawTerms:raw.keywords||[],terms:keywords},{kind:'openalex-topic',method:'model-generated-topic',rawTerms:raw.topics||[],terms:topics}]};
}
export async function fetchKeywordBatch(papers:any[],fetcher:typeof fetch=fetch,context?:{db:any;env:any;ownerId:string}){
 if(!context)throw new AIError('gateway_required',409,'元数据查询必须经过共享安全网关');
 const dois=[...new Set(papers.map(p=>normalizeDoi(p.doi)).filter(Boolean))].sort();if(!dois.length)return [];if(dois.length>100)throw new AIError('batch_too_large',400,'单批最多100个DOI');
 const u=new URL('https://api.openalex.org/works');u.searchParams.set('filter','doi:'+dois.map(d=>'https://doi.org/'+d).join('|'));u.searchParams.set('per_page','100');u.searchParams.set('select','id,doi,title,keywords,primary_topic,topics,updated_date');
 const {data}=await providerRequest(context.db,context.env,'openalex',u.href,AbortSignal.timeout(30000),{ownerId:context.ownerId,fetcher});if(!Array.isArray(data.results))throw new AIError('openalex_format',502,'元数据列表无效');return data.results;
}
export function keywordEvidenceStatement(db:any,paper:any,evidence:any){
 // JSON-path updates preserve simultaneous metadata edits; no ingestion timestamps or scores change.
 const old=JSON.parse(paper.provenance_json||'{}').keywordEvidence;
 const stable=(e:any)=>JSON.stringify(e?{...e,checkedAt:undefined,revision:undefined,updatedAt:undefined}:null);
 const incomingRecords=evidence.records||[];const retained=(old?.records||[]).filter((r:any)=>!incomingRecords.some((n:any)=>n.kind===r.kind&&n.terms?.length));evidence={...evidence,records:[...retained,...incomingRecords.filter((r:any)=>r.terms?.length||!retained.some((o:any)=>o.kind===r.kind))]};
 const changed=stable(old)!==stable(evidence),value={...evidence,revision:(old?.revision||0)+(changed?1:0),updatedAt:changed?evidence.checkedAt:old?.updatedAt||null};
 return {changed,statement:db.prepare("UPDATE research_papers SET provenance_json=json_set(provenance_json,'$.keywordEvidence',json(?)) WHERE id=? AND doi IS ? AND coalesce(json_extract(provenance_json,'$.keywordEvidence.checkedAt'),'')<=?").bind(JSON.stringify(value),paper.id,paper.doi,evidence.checkedAt)};
}
export async function applyKeywordEvidence(db:any,paper:any,evidence:any){const op=keywordEvidenceStatement(db,paper,evidence);await op.statement.run();return op.changed;}
export async function keywordJobStep(db:any,id:string,fetcher:typeof fetch=fetch,env:any={}){
 const now=new Date().toISOString();let job=await db.prepare('SELECT * FROM research_keyword_jobs WHERE id=? AND owner_id=?').bind(KEYWORD_JOB,id).first();
 if(!job){const rows=(await db.prepare('SELECT id FROM research_papers WHERE priority>=0 ORDER BY id').all()).results;if(rows.length>3000)throw new AIError('scope_changed',409,'论文数量超过本次维护上限');await db.prepare('INSERT OR IGNORE INTO research_keyword_jobs(id,owner_id,paper_ids_json,cursor,requests,status,created_at,updated_at) VALUES(?,?,?,0,0,?,?,?)').bind(KEYWORD_JOB,id,JSON.stringify(rows.map((r:any)=>r.id)),'ready',now,now).run();job=await db.prepare('SELECT * FROM research_keyword_jobs WHERE id=? AND owner_id=?').bind(KEYWORD_JOB,id).first();}
 if(job.status==='completed')return job;if(job.status==='paused')throw new AIError('job_paused',409,'该批次因供应商错误暂停，未自动重试');
 const lease=new Date(Date.now()+60000).toISOString();const claim=await db.prepare("UPDATE research_keyword_jobs SET lease_until=?,status='running',requests=requests+1 WHERE id=? AND owner_id=? AND (lease_until IS NULL OR lease_until<?) AND cursor=? AND requests<60 AND status!='completed'").bind(lease,KEYWORD_JOB,id,now,job.cursor).run();if(!claim.meta?.changes)throw new AIError('job_busy',409,'已有批次运行或已达到请求上限');
 try{const ids=JSON.parse(job.paper_ids_json).slice(job.cursor,job.cursor+50);const rows=(await db.prepare('SELECT * FROM research_papers WHERE id IN (SELECT value FROM json_each(?)) ORDER BY id').bind(JSON.stringify(ids)).all()).results;const results=await fetchKeywordBatch(rows,fetcher,{db,env,ownerId:id});for(const p of rows){const matches=results.filter((r:any)=>normalizeDoi(r.doi)===normalizeDoi(p.doi));const evidence=matches.length>1?{policy:KEYWORD_POLICY,checkedAt:now,status:'ambiguous_doi',records:[]}:openAlexEvidence(matches[0],p.doi,now);await applyKeywordEvidence(db,p,evidence);}
 const cursor=job.cursor+ids.length,status=cursor>=JSON.parse(job.paper_ids_json).length?'completed':'ready';await db.prepare('UPDATE research_keyword_jobs SET cursor=?,status=?,lease_until=?,updated_at=?,error_code=NULL WHERE id=? AND lease_until=?').bind(cursor,status,new Date(Date.now()+1200).toISOString(),new Date().toISOString(),KEYWORD_JOB,lease).run();return {cursor,status,total:JSON.parse(job.paper_ids_json).length};
 }catch(e){await db.prepare("UPDATE research_keyword_jobs SET status='paused',error_code=?,updated_at=? WHERE id=? AND lease_until=?").bind(e instanceof AIError?e.code:'metadata_error',now,KEYWORD_JOB,lease).run();throw e;}
}
export const IMPORT_DIGEST='6362d99d5ee003f858b251f51a5f2cb6d0c9cc70de6c8ba6840d830822705a94';
async function sha(value:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
export async function validateKeywordImport(text:string,expectedDigest=IMPORT_DIGEST){
 if(new TextEncoder().encode(text).length>3000000||await sha(text)!==expectedDigest)throw new AIError('import_integrity',400,'文件大小或已核实响应缓存校验不匹配');
 const data=JSON.parse(text);if(data.schema!=='hkis-keyword-import-v1'||data.source!=='https://api.openalex.org/works'||!Array.isArray(data.entries)||data.entries.length>3000||Object.keys(data).some(k=>!['schema','source','requests','entries'].includes(k)))throw new AIError('import_schema',400,'缓存结构无效');
 const seen=new Set<string>();for(const e of data.entries){if(!e||typeof e!=='object'||Object.keys(e).some(k=>!['paperId','doi','checkedAt','status','recordId','providerUpdatedAt','keywords','topics'].includes(k))||typeof e.paperId!=='string'||!/^[a-f0-9]{32}$/.test(e.paperId)||seen.has(e.paperId)||e.doi!==null&&(typeof e.doi!=='string'||e.doi.length>500)||!['found','not_found','no_keywords','missing_doi','ambiguous_doi'].includes(e.status)||!Number.isFinite(Date.parse(e.checkedAt))||Date.parse(e.checkedAt)>Date.now())throw new AIError('import_record',400,'缓存身份或字段无效');seen.add(e.paperId);if(e.recordId!==null&&!/^https:\/\/openalex\.org\/W\d+$/.test(e.recordId))throw new AIError('import_source',400,'缓存来源无效');for(const field of ['keywords','topics'])if(!Array.isArray(e[field])||e[field].length>100||e[field].some((k:any)=>!k||typeof k.display_name!=='string'||k.display_name.length>500||typeof k.id!=='string'||k.id.length>500||typeof k.score!=='number'||!Number.isFinite(k.score)))throw new AIError('import_terms',400,'缓存词列表无效');}
 return data;
}
async function protectedSnapshot(db:any){const papers=(await db.prepare('SELECT * FROM research_papers ORDER BY id').all()).results.map((p:any)=>{const provenance=JSON.parse(p.provenance_json);delete provenance.keywordEvidence;return {...p,provenance_json:JSON.stringify(provenance)}});const other=[];for(const name of ['paper_reader_state','research_batch_members','research_daily','research_daily_groups','ai_receipts'])other.push([name,(await db.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()).results]);return sha(JSON.stringify({papers,other}));}
export async function importKeywordCache(db:any,id:string,text:string,expectedDigest=IMPORT_DIGEST){
 const data=await validateKeywordImport(text,expectedDigest),job=await db.prepare('SELECT * FROM research_keyword_jobs WHERE id=? AND owner_id=?').bind(KEYWORD_JOB,id).first();if(!job)throw new AIError('job_missing',409,'缺少已冻结资格清单');if(job.status==='completed')return {status:'completed',cursor:job.cursor};const ids=JSON.parse(job.paper_ids_json),byId=new Map(data.entries.map((e:any)=>[e.paperId,e]));if(ids.length!==data.entries.length||ids.some((x:string)=>!byId.has(x)))throw new AIError('import_scope',409,'缓存与冻结清单不一致');
 const all=(await db.prepare('SELECT id,doi FROM research_papers WHERE id IN (SELECT value FROM json_each(?)) ORDER BY id').bind(job.paper_ids_json).all()).results;if(all.length!==ids.length||all.some((p:any)=>normalizeDoi(p.doi)!==normalizeDoi((byId.get(p.id) as any).doi)))throw new AIError('import_identity',409,'论文ID与DOI核对不一致');
 const now=new Date().toISOString(),lease=new Date(Date.now()+300000).toISOString();const claim=await db.prepare("UPDATE research_keyword_jobs SET status='importing',lease_until=? WHERE id=? AND owner_id=? AND status IN ('paused','ready','importing') AND (lease_until IS NULL OR lease_until<?)").bind(lease,KEYWORD_JOB,id,now).run();if(!claim.meta?.changes)throw new AIError('job_busy',409,'维护正在运行');const before=await protectedSnapshot(db);let applied=0;
 try{for(let i=job.cursor;i<ids.length;i+=50){const chunk=ids.slice(i,i+50),rows=(await db.prepare('SELECT * FROM research_papers WHERE id IN (SELECT value FROM json_each(?)) ORDER BY id').bind(JSON.stringify(chunk)).all()).results;const ops=rows.map((p:any)=>{const e:any=byId.get(p.id);const raw=e.recordId?{id:e.recordId,doi:e.doi,keywords:e.keywords,topics:e.topics,updated_date:e.providerUpdatedAt}:null;const evidence:any=openAlexEvidence(raw,p.doi,e.checkedAt);if(e.status==='ambiguous_doi')evidence.status='ambiguous_doi';return keywordEvidenceStatement(db,p,evidence).statement});ops.push(db.prepare('UPDATE research_keyword_jobs SET cursor=?,updated_at=? WHERE id=? AND lease_until=?').bind(i+chunk.length,now,KEYWORD_JOB,lease));await db.batch(ops);applied+=rows.length;}
 const after=await protectedSnapshot(db),protectedUnchanged=before===after;const audit={importDigest:expectedDigest,source:data.source,imported:applied,total:ids.length,localMetadataRequests:data.requests,probeRequests:1,productionRequests:job.requests,productionFailure:job.error_code,productionRetryAfterSeconds:33797,providerRetried:false,modelCalls:0,protectedUnchanged,beforeHash:before,afterHash:after,finishedAt:new Date().toISOString(),statuses:data.entries.reduce((a:any,e:any)=>(a[e.status]=(a[e.status]||0)+1,a),{})};await db.batch([db.prepare("INSERT INTO research_settings(key,value) VALUES('keyword-import-audit',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(JSON.stringify(audit)),db.prepare('UPDATE research_keyword_jobs SET status=?,lease_until=NULL,updated_at=? WHERE id=? AND lease_until=?').bind(protectedUnchanged?'completed':'review_required',audit.finishedAt,KEYWORD_JOB,lease)]);return audit;
 }catch(e){await db.prepare("UPDATE research_keyword_jobs SET status='paused',lease_until=NULL,updated_at=? WHERE id=? AND lease_until=?").bind(now,KEYWORD_JOB,lease).run();throw e;}
}
export async function keywordMaintenance(request:Request,env:any){
 const headers={'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store'};try{const id=owner(request,env),u=new URL(request.url);if(request.method==='POST'){if(request.headers.get('origin')!==u.origin||!request.headers.get('content-type')?.startsWith('multipart/form-data')||Number(request.headers.get('content-length'))>3100000)throw new AIError('csrf_rejected',403,'请求来源或大小无效');const form=await request.formData();if(form.get('action')!=='import'||[...form.keys()].some(k=>!['action','cache'].includes(k)))throw new AIError('invalid_action',400,'操作无效');const file=form.get('cache');if(!file||typeof file==='string'||file.size>3000000)throw new AIError('invalid_file',400,'需要已核实响应缓存文件');await importKeywordCache(env.DB,id,await file.text());return new Response(null,{status:303,headers:{Location:u.pathname,'Cache-Control':'no-store'}})}if(request.method!=='GET')return new Response('Method not allowed',{status:405});const j=await env.DB.prepare('SELECT cursor,status,requests,paper_ids_json FROM research_keyword_jobs WHERE id=? AND owner_id=?').bind(KEYWORD_JOB,id).first();return new Response('<!doctype html><html lang="zh"><meta charset="utf-8"><title>关键词维护 · HKIS</title><style>body{background:#fff9ef;color:#3e3024;font:16px system-ui;max-width:760px;margin:60px auto;line-height:1.8}button{padding:14px;background:#f0803b;border:0;border-radius:4px;font:inherit}</style><h1>关键词缓存导入</h1><p>只接受本次已核实的 OpenAlex 缓存，校验文件摘要及冻结论文ID与DOI。最多3MB、3000篇，每批50篇；不发出供应商请求、不调用模型，不修改论文日期、分数、已读收藏和日报。</p><p>进度：'+(j?j.cursor+' / '+JSON.parse(j.paper_ids_json).length+'；状态 '+j.status+'；生产请求 '+j.requests:'缺少冻结清单')+'</p>'+(j?.status==='completed'?'<p>本次冻结清单已全部检查；保护快照一致。缺词保留原因。</p>':'<form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="import"><label>已核实响应缓存<input type="file" name="cache" accept=".json" required></label><button>导入既有关键词缓存</button></form>')+'<p><a href="/hot">查看热点</a> · <a href="/topics">查看研究主题</a></p></html>',{headers});}catch(e){return new Response(e instanceof AIError?e.message:'维护操作暂不可用',{status:e instanceof AIError?e.status:503,headers})}
}
