import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {buildKeywordMap,canonicalKeyword,keywordMembership,mapWindow,statistics} from './keyword-map.ts';
import type {Paper} from './research-domain.ts';
const at=new Date('2026-10-03T12:00:00Z');
const p=(id:string,extra:any={})=>({id,doi:'10.9999/'+id,title:'TCAD device simulation',url:'https://doi.org/10.9999/'+id,publisher:'IEEE',journal:'Test',sourceId:'ieee-ted',issn:'0018-9383',publishedAt:'2026-06-01',datePrecision:'day',authors:[],affiliations:[],abstract:null,keywords:[],provenance:{},sourceIndexedAt:null,discovery:'fixture',priority:0,firstSeen:'2026-09-27T00:00:00Z',updatedAt:'2026-09-27T00:00:00Z',...extra} as Paper&any);
test('UTC+08 seven-day meaningful updates include old papers, exclude poll touches and future timestamps',()=>{const w=mapWindow(new URLSearchParams(),at);assert.equal(w.startAt,'2026-09-26T16:00:00.000Z');const d=buildKeywordMap([p('start',{firstSeen:w.startAt,updatedAt:w.startAt}),p('end',{firstSeen:at.toISOString(),updatedAt:at.toISOString()}),p('old',{firstSeen:'2026-01-01T00:00:00Z',updatedAt:'2026-09-26T15:59:59.999Z',lastSeen:at.toISOString()}),p('changed',{firstSeen:'2026-01-01T00:00:00Z',updatedAt:at.toISOString()}),p('future',{firstSeen:'2026-10-04T00:00:00Z',updatedAt:'2026-10-04T00:00:00Z'}),p('missing',{firstSeen:null,updatedAt:null})],new URLSearchParams(),at);assert.deepEqual(d.papers.map(p=>p.id),['changed','end','start']);assert.equal(d.coverage.publishedInWindow,0);});
test('publication and first-ingested windows have independent date semantics',()=>{const rows=[p('oldpub',{publishedAt:'2025-01-01'}),p('newpub',{publishedAt:'2026-10-03',firstSeen:'2026-01-01T00:00:00Z',updatedAt:'2026-10-03T11:00:00Z'}),p('month',{publishedAt:'2026-10',datePrecision:'month'})];assert.deepEqual(buildKeywordMap(rows,new URLSearchParams('basis=publication'),at).papers.map(p=>p.id),['newpub']);assert.deepEqual(buildKeywordMap(rows,new URLSearchParams('basis=collection'),at).papers.map(p=>p.id),['month','oldpub']);});
test('DOI casing, DOI URL, repeated source ingestion and canonical URL do not inflate counts',()=>{const rows=[p('a',{doi:'https://doi.org/10.9999/DUP'}),p('b',{doi:'10.9999/dup'}),p('c',{doi:null,url:'https://example.org/paper?utm_source=rss'}),p('d',{doi:null,url:'https://example.org/paper'}),p('e',{doi:null,url:'https://doi.org/10.9999/a'})];const d=buildKeywordMap(rows,new URLSearchParams(),at);assert.equal(d.coverage.shown,2);assert.equal(d.coverage.duplicates,3);assert.equal(d.keywords.find(k=>k.id==='tcad')!.count,2)});
test('synonyms count once within a paper while distinct concepts stay separate',()=>{assert.equal(canonicalKeyword('Technology computer-aided design').id,'tcad');const keys=keywordMembership(p('a',{title:'FeFET ferroelectric RRAM memristor',keywords:['TCAD','tcad','Technology computer-aided design','ReRAM','RRAM']}));assert.equal(keys.filter(k=>k.id==='tcad').length,1);assert.equal(keys.filter(k=>k.id==='rram').length,1);assert.equal(keys.length,3);assert.ok(keys.some(k=>k.id==='fefet'));assert.ok(!keys.some(k=>k.id==='memristor'));assert.deepEqual(keys.find(k=>k.id==='tcad')!.sources,['author','derived']);});
test('all records beyond page caps, score zero, missing abstract/keywords/scores and nonresearch audit exclusions',()=>{const rows=Array.from({length:1501},(_,i)=>p(String(i),{title:'Unmatched general record',priority:i===0?null:0}));rows.push(p('excluded',{priority:-1}));const d=buildKeywordMap(rows,new URLSearchParams(),at);assert.equal(d.coverage.shown,1501);assert.equal(d.coverage.unclassified,1501);assert.equal(d.coverage.scored,1500);assert.equal(d.coverage.unscored,1);assert.equal(d.keywords[0]!.count,1501);assert.equal(d.keywords[0]!.median,0);assert.equal(d.coverage.excludedNonResearch,1);});
test('AI scores require current validated abstract evidence, never mix rule values into unknown AI bucket',()=>{const quote='We compare device simulation and measurement results in this study.';const analysis={status:'completed',config:{model:'fixture'},result:{decision:'assessed',importanceScore:81,qualityEvidenceScore:60,keywords:['TCAD'],rubric:{importance:'comparison'},evidence:[{field:'abstract',quote}]}};const rows=[p('ai',{abstract:quote,analysis,priority:10}),p('none',{priority:99}),p('bad',{abstract:'different abstract',analysis,priority:80}),p('stale',{analysis:{...analysis,status:'queued'},priority:50})];const d=buildKeywordMap(rows,new URLSearchParams('metric=ai'),at);assert.equal(d.coverage.scored,1);assert.equal(d.coverage.unscored,3);assert.equal(d.keywords.find(k=>k.id==='tcad')!.median,81);assert.equal(d.papers.find(p=>p.id==='none')!.score,null);assert.equal(buildKeywordMap(rows,new URLSearchParams(),at).papers.find(p=>p.id==='none')!.score,99)});
test('distribution quantiles retain zeros and do not average missing values',()=>{assert.deepEqual(statistics([0,20,80,100,null]),{scored:4,unscored:1,mean:50,median:50,q1:15,q3:85,min:0,max:100});assert.equal(statistics([null]).median,null)});
test('paper rows retain independent priority and all institution evidence in AI chart mode',()=>{
 const data=buildKeywordMap([p('display',{priority:81,affiliations:['Original Institute'],keywords:['TCAD','additional author keyword'],provenance:{metadataEvidence:{sources:[{provider:'openalex',authors:[{name:'Author',institutions:[{name:'Supplemented Institute',openalex:'https://openalex.org/I1'}]}]}]}}})],new URLSearchParams('metric=ai'),at).papers[0]!;
 assert.equal(data.score,null);assert.equal(data.priority,81);assert.equal(data.analysis,null);assert.ok(data.affiliations.includes('Original Institute'));assert.ok(data.affiliations.includes('Supplemented Institute'));assert.deepEqual(data.sourceKeywords,['TCAD','additional author keyword']);
});
