import {AIError,owner} from './ai/security.ts';
import {rowPaper} from './research.ts';
import {normalizeDoi} from './research-domain.ts';
import {paperMetadata,mergeMetadata,storedMetadataSource,sourceMetadata} from './paper-metadata.ts';
import {providerRequest,fingerprint,inheritedCooldown} from './scholarly/provider.ts';
const JOB='metadata-evidence-20261005';
const parse=(s:any,fallback:any={})=>{try{return JSON.parse(s)}catch{return fallback}};
const escape=(s:any)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function metadataAudit(db:any){
 const rows=(await db.prepare('SELECT * FROM research_papers WHERE priority>=0 ORDER BY id').all()).results;
 const counts:any={papers:rows.length,institutionUnknown:0,rawAffiliation:0,normalizedInstitution:0,formUnknown:0,sourceTypesRecoverable:0,institutionsRecoverable:0};
 const records=(await db.prepare('SELECT paper_id,channel,record_url,retrieved_at,fields_json FROM research_records').all()).results;
 for(const row of rows){const p=rowPaper(row),m=paperMetadata(p);if(!m.institutions.length)counts.institutionUnknown++;else if(m.institutions.some(x=>x.normalized))counts.normalizedInstitution++;else counts.rawAffiliation++;if(m.publication.forms.includes('form-unknown'))counts.formUnknown++;
 const matching=records.filter((r:any)=>r.paper_id===row.id).map((r:any)=>parse(r.fields_json)).filter((f:any)=>p.doi&&normalizeDoi(f.doi)===normalizeDoi(p.doi));if(m.publication.forms.includes('form-unknown')&&matching.some((f:any)=>!!f.provenance?.recordType))counts.sourceTypesRecoverable++;if(!m.institutions.length&&matching.some((f:any)=>f.affiliations?.length||f.authors?.some((a:any)=>a.affiliations?.length)))counts.institutionsRecoverable++;}
 const gates=(await db.prepare("SELECT service,day,used,next_allowed,cooldown_until,lease_until,blocked_code FROM scholarly_usage WHERE owner_id='__site__'").all()).results;
 const legacy=(await db.prepare("SELECT key,value FROM research_settings WHERE key IN ('openalex_retry_after','keyword-import-audit')").all()).results.map((r:any)=>r.key==='keyword-import-audit'?{key:r.key,audit:parse(r.value)}:r);
 const jobs=(await db.prepare('SELECT id,cursor,requests,status,updated_at,error_code,paper_ids_json FROM research_keyword_jobs WHERE id LIKE ?').bind(JOB+'%').all()).results.map((j:any)=>({...j,paper_ids_json:undefined,total:parse(j.paper_ids_json,[]).length}));
 return {counts,gates,jobs,legacy,openalexConservativeCooldownUntil:new Date(await inheritedCooldown(db,'openalex')).toISOString()};
}
export async function metadataProtectedSnapshot(db:any){const papers=(await db.prepare('SELECT * FROM research_papers ORDER BY id').all()).results.map((p:any)=>{const prov=parse(p.provenance_json);delete prov.metadataEvidence;return {...p,provenance_json:JSON.stringify(prov)}});const other=[];for(const table of ['paper_reader_state','research_batch_members','research_daily','research_daily_groups','ai_receipts'])other.push([table,(await db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all()).results]);return fingerprint(JSON.stringify({papers,other}));}
export function metadataStatement(db:any,row:any,sources:any[],at:string){
 const old=parse(row.provenance_json).metadataEvidence,evidence=mergeMetadata(old,sources,at);
 return {changed:(evidence.revision||0)!==(old?.revision||0),statement:db.prepare("UPDATE research_papers SET provenance_json=json_set(provenance_json,'$.metadataEvidence',json(?)) WHERE id=? AND doi IS ? AND provenance_json=? AND content_hash IS ?").bind(JSON.stringify(evidence),row.id,row.doi,row.provenance_json,row.content_hash)};
}
async function getJob(db:any,id:string,provider:string){
 const key=JOB+':'+provider;let job=await db.prepare('SELECT * FROM research_keyword_jobs WHERE id=? AND owner_id=?').bind(key,id).first();if(job)return job;
 const rows=(await db.prepare('SELECT * FROM research_papers WHERE priority>=0 ORDER BY id').all()).results;if(rows.length>3000)throw new AIError('scope_changed',409,'本维护批次最多3000篇');const eligible=provider==='local'?rows:rows.filter((r:any)=>!!r.doi&&(paperMetadata(rowPaper(r)).institutionStatus!=='found'||paperMetadata(rowPaper(r)).publication.forms.includes('form-unknown')));
 const now=new Date().toISOString();await db.prepare('INSERT OR IGNORE INTO research_keyword_jobs(id,owner_id,paper_ids_json,cursor,requests,status,created_at,updated_at) VALUES(?,?,?,0,0,?,?,?)').bind(key,id,JSON.stringify(eligible.map((p:any)=>({id:p.id,doi:p.doi,hash:p.content_hash}))),'ready',now,now).run();return db.prepare('SELECT * FROM research_keyword_jobs WHERE id=? AND owner_id=?').bind(key,id).first();
}
export async function metadataStep(db:any,env:any,id:string,provider:'local'|'openalex',sample:boolean,fetcher:typeof fetch=fetch){
 const job=await getJob(db,id,provider),entries=parse(job.paper_ids_json,[]);if(job.status==='completed')return {status:'completed',cursor:job.cursor,total:entries.length};if(job.status==='review_required')throw new AIError('review_required',409,'保护快照有并发变化，需核对后再继续');
 if(!sample&&job.cursor===0)throw new AIError('sample_required',409,'请先验证5篇样本');if(provider==='openalex'&&job.requests>=60)throw new AIError('job_budget',409,'本批次已达到60次请求上限');
 const now=new Date().toISOString(),lease=new Date(Date.now()+90000).toISOString(),claim=await db.prepare("UPDATE research_keyword_jobs SET lease_until=?,status='running',updated_at=? WHERE id=? AND owner_id=? AND cursor=? AND (lease_until IS NULL OR lease_until<?)").bind(lease,now,job.id,id,job.cursor,now).run();if(!claim.meta?.changes)throw new AIError('job_busy',409,'维护批次正在执行');
 try{
 const chunk=entries.slice(job.cursor,job.cursor+(sample?5:provider==='local'?100:40)),rows=(await db.prepare('SELECT * FROM research_papers WHERE id IN (SELECT json_extract(value,\'$.id\') FROM json_each(?)) ORDER BY id').bind(JSON.stringify(chunk)).all()).results;
 if(rows.length!==chunk.length||rows.some((r:any)=>{const e=chunk.find((x:any)=>x.id===r.id);return !e||e.doi!==r.doi||e.hash!==r.content_hash}))throw new AIError('input_changed',409,'冻结的论文标识或内容校验已变化，未补写');
 const before=await metadataProtectedSnapshot(db),sources=new Map<string,any[]>();let network=0;
 if(provider==='local'){
  const caches=(await db.prepare('SELECT service,payload_json,created_at FROM scholarly_cache WHERE owner_id=?').bind(id).all()).results;
  const records=(await db.prepare('SELECT * FROM research_records WHERE paper_id IN (SELECT json_extract(value,\'$.id\') FROM json_each(?)) ORDER BY retrieved_at').bind(JSON.stringify(chunk)).all()).results;
  for(const r of rows){const p=rowPaper(r),e=storedMetadataSource(p,p.provenance.recordTypeSource||p.provenance.authors||'stored',p.doi?'https://doi.org/'+p.doi:p.url,now);for(const record of records.filter((x:any)=>x.paper_id===r.id)){const f=parse(record.fields_json);if(!p.doi||normalizeDoi(f.doi)!==normalizeDoi(p.doi))continue;e.push(...storedMetadataSource(f,record.channel,record.record_url,record.retrieved_at));}for(const cache of caches){const data=parse(cache.payload_json),records=Array.isArray(data.records)?data.records:Array.isArray(data.results)?data.results:cache.service==='openalex'&&data.id?[data]:[];for(const c of records){if(!p.doi||normalizeDoi(c.doi)!==normalizeDoi(p.doi))continue;if(c.recordId)e.push(...storedMetadataSource(c,cache.service,c.recordUrl,c.retrievedAt||cache.created_at));else e.push(sourceMetadata(cache.service,c,c.id,cache.created_at));}}sources.set(r.id,e);}
 }else{
  const dois=[...new Set(rows.map((r:any)=>normalizeDoi(r.doi)))].sort(),url=new URL('https://api.openalex.org/works');url.searchParams.set('filter','doi:'+dois.map(d=>'https://doi.org/'+d).join('|'));url.searchParams.set('per_page','100');url.searchParams.set('select','id,doi,title,authorships,type,updated_date');
  const fetched=await providerRequest(db,env,'openalex',url.href,AbortSignal.timeout(30000),{ownerId:id,fetcher,async onReserved(){const r=await db.prepare('UPDATE research_keyword_jobs SET requests=requests+1 WHERE id=? AND lease_until=? AND requests<60').bind(job.id,lease).run();if(!r.meta?.changes)throw new AIError('job_budget',409,'本维护请求上限已达');},validate(data){if(!Array.isArray(data.results))throw new AIError('metadata_format',502,'供应商响应列表无效');const seen=new Set();for(const w of data.results){const doi=normalizeDoi(w.doi);if(!dois.includes(doi)||seen.has(doi))throw new AIError('metadata_identity',409,'供应商DOI重复或不属于批次');seen.add(doi);}}});network=fetched.cached?0:1;
  for(const r of rows){const raw=fetched.data.results.find((w:any)=>normalizeDoi(w.doi)===normalizeDoi(r.doi));sources.set(r.id,raw?[sourceMetadata('openalex',raw,raw.id,now)]:[{provider:'openalex',recordUrl:'https://api.openalex.org/works/doi:'+encodeURIComponent(r.doi),checkedAt:now,authors:[],types:[],affiliationsChecked:true,typesChecked:true,status:'no_matching_record'}]);}
 }
 let changed=0;const ops=rows.map((r:any)=>{const op=metadataStatement(db,r,sources.get(r.id)||[],now);if(op.changed)changed++;return op.statement});for(let i=0;i<ops.length;i+=25){const written=await db.batch(ops.slice(i,i+25));if(written.some((w:any)=>!w.meta?.changes))throw new AIError('input_changed',409,'论文在写入期间发生变化，批次未推进');}
 const after=await metadataProtectedSnapshot(db),protectedUnchanged=before===after,cursor=job.cursor+chunk.length,status=!protectedUnchanged?'review_required':cursor>=entries.length?'completed':'ready';
 const audit={provider,cursor,total:entries.length,changed,requests:network,protectedUnchanged,beforeHash:before,afterHash:after,finishedAt:new Date().toISOString(),modelCalls:0};
 await db.batch([db.prepare('UPDATE research_keyword_jobs SET cursor=?,status=?,lease_until=NULL,updated_at=?,error_code=NULL WHERE id=? AND lease_until=?').bind(cursor,status,audit.finishedAt,job.id,lease),db.prepare('INSERT INTO research_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(job.id+':audit',JSON.stringify(audit))]);return {...audit,status};
 }catch(e){await db.prepare("UPDATE research_keyword_jobs SET status='paused',lease_until=NULL,updated_at=?,error_code=? WHERE id=? AND lease_until=?").bind(new Date().toISOString(),e instanceof AIError?e.code:'metadata_error',job.id,lease).run();throw e;}
}
export async function metadataMaintenance(request:Request,env:any){
 const headers={'Content-Type':'text/html; charset=utf-8','Cache-Control':'private, no-store'};
 try{const id=owner(request,env),url=new URL(request.url);let outcome:any=null;if(request.method==='POST'){if(request.headers.get('origin')!==url.origin||!request.headers.get('content-type')?.startsWith('application/x-www-form-urlencoded')||Number(request.headers.get('content-length'))>500)throw new AIError('csrf_rejected',403,'请求来源或大小无效');const body=await request.text();if(body.length>500)throw new AIError('invalid_action',400,'操作无效');const form=new URLSearchParams(body),action=form.get('action');if([...form.keys()].some(k=>k!=='action')||!['local-sample','local-next','openalex-sample','openalex-next'].includes(action||''))throw new AIError('invalid_action',400,'操作无效');outcome=await metadataStep(env.DB,env,id,action!.startsWith('local')?'local':'openalex',action!.endsWith('sample'));}else if(request.method!=='GET')throw new AIError('method_not_allowed',405,'方法不支持');
 const audit=await metadataAudit(env.DB),prior=(await env.DB.prepare('SELECT key,value FROM research_settings WHERE key LIKE ?').bind(JOB+'%:audit').all()).results.map((r:any)=>parse(r.value));
 const button=(action:string,label:string)=>'<form method="post"><input type="hidden" name="action" value="'+action+'"><button>'+label+'</button></form>';
 return new Response('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>机构与文献形式维护</title><style>body{max-width:960px;margin:2rem auto;padding:0 1rem;font:16px/1.6 system-ui;color:#332d27;background:#faf8f4}button{padding:.7rem 1rem;margin:.4rem 0;border:1px solid #8d8174;border-radius:10px;background:#fff}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><h1>机构与文献形式维护</h1><p>仅所有者可操作。既有证据修复不联网；供应商补充受全站每日100次、单并发和持久冷却限制。每阶段先5篇样本，再断点继续，不调用AI、不修改评分和日报。</p><h2>结果与保护校验</h2><pre>'+escape(JSON.stringify(outcome||prior,null,2))+'</pre><h2>当前覆盖与请求状态</h2><pre>'+escape(JSON.stringify(audit,null,2))+'</pre>'+button('local-sample','验证5篇既有证据（不联网）')+button('local-next','修复下一批既有证据（100篇，不联网）')+button('openalex-sample','补充5篇OpenAlex样本（受冷却限制）')+button('openalex-next','继续OpenAlex补充（最多40篇）')+'<p><a href="/topics">返回研究主题</a></p></html>',{headers});
 }catch(e){return new Response('<!doctype html><html lang="zh-CN"><meta charset="utf-8"><h1>维护已暂停</h1><p>'+escape(e instanceof AIError?e.message:'元数据维护暂不可用')+'</p><p>'+escape(e instanceof AIError?e.code:'metadata_error')+'</p><a href="/api/site/research/metadata-maintenance">返回维护状态</a></html>',{status:e instanceof AIError?e.status:503,headers})}
}
