import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {readFile} from 'node:fs/promises';
import {UPDATE_PAGES,hasPageUpdate,isPageOverview,updatePageForPath} from '../packages/contracts/src/navigation-updates.ts';
import {readPageUpdate} from '../apps/web/app/lib/page-update-load.ts';
import {createNavigationStore} from '../apps/web/app/lib/navigation-updates-store.ts';
const tick=()=>new Promise(r=>setImmediate(r));
const revision=(n=1)=>({key:'all' as const,revision:n,version:1});
function server(){let pages:any={all:{...revision(),seenRevision:null,seenVersion:null,enabled:true}},fail=false;const calls:any[]=[];return {get pages(){return pages},calls,setFail(v:boolean){fail=v},async fetcher(url:string,init?:RequestInit){calls.push({url,init});if(init?.method==='PUT'){if(fail)return Response.json({detail:'暂未同步'},{status:503});const b=JSON.parse(init.body as string);for(const r of b.revisions||[]){if(b.action==='initialize'&&pages[r.key].seenRevision!==null)continue;pages[r.key]={...pages[r.key],seenRevision:Math.max(pages[r.key].seenRevision??0,r.revision),seenVersion:Math.max(pages[r.key].seenVersion??0,r.version)}}if(b.action==='preference')pages[b.key].enabled=b.enabled;}return Response.json({pages:structuredClone(pages)})}}}
test('registry has every actual sidebar entry and exact aliases never consume another overview',async()=>{assert.equal(UPDATE_PAGES.length,12);const nav=await readFile('apps/web/app/components/shell/nav.ts','utf8');for(const p of UPDATE_PAGES)assert.ok(nav.includes(`to: "${p.path}"`),p.key);assert.equal(updatePageForPath('/research/abc'),null);assert.equal(updatePageForPath('/daily/2026-01-01'),null);assert.equal(updatePageForPath('/research/'),'research');assert.equal(updatePageForPath('/'),'home')});
test('filtered, paginated and dated progress do not acknowledge the default overview',()=>{for(const q of ['?q=TCAD','?date=2026-01-01','?page=2','?scope=all','?publisher=IEEE'])assert.equal(isPageOverview('all',q),false,q);assert.equal(isPageOverview('all','?page=1&min=0'),true);assert.equal(isPageOverview('hot','?metric=ai'),false);assert.equal(isPageOverview('hot','?basis=updated&metric=rule'),true)});
test('load captures an exact stable revision and does not write; failures never acknowledge',async()=>{let reads=0;const result=await readPageUpdate('all',async()=>({content:'loaded'}),async()=>{reads++;return revision(3)});assert.deepEqual(result.pageUpdate,revision(3));assert.equal(reads,2);await assert.rejects(()=>readPageUpdate('all',async()=>{throw Error('failed')},async()=>revision()));assert.equal((await readPageUpdate('all',async()=>({}),async()=>{throw Error('unknown')})).pageUpdate,null)});
test('content changed during load cannot acknowledge the unseen later revision',async()=>{let n=0;const result=await readPageUpdate('all',async()=>({content:'old'}),async()=>revision(++n));assert.equal(result.pageUpdate,null)});
test('quiet baseline -> new dot -> loaded acknowledgement clears -> new revision lights again',async()=>{const s=server(),store=createNavigationStore(s.fetcher);await store.refresh();assert.equal(store.unread('all'),false);assert.equal(s.calls.filter(c=>c.init.method).length,0);await store.initialize();assert.equal(store.unread('all'),false);s.pages.all.revision=2;await store.refresh();assert.equal(store.unread('all'),true);const saved=store.seen(revision(2));assert.equal(store.unread('all'),false,'immediate optimistic update');await saved;s.pages.all.revision=3;await store.refresh();assert.equal(store.unread('all'),true);assert.equal(s.pages.all.seenRevision,2)});
test('stale read cannot erase a later revision; reload and another tab read account state',async()=>{const s=server(),a=createNavigationStore(s.fetcher),b=createNavigationStore(s.fetcher);await a.refresh();await a.initialize();s.pages.all.revision=3;await a.refresh();await a.seen(revision(2));assert.equal(a.unread('all'),true);await b.refresh();assert.equal(b.unread('all'),true);await b.seen(revision(3));await a.refresh();assert.equal(a.unread('all'),false);await a.seen(revision(1));assert.equal(s.pages.all.seenRevision,3)});
test('failed save restores dot; disabling and re-enabling do not change the read snapshot',async()=>{const s=server(),store=createNavigationStore(s.fetcher);await store.refresh();await store.initialize();s.pages.all.revision=2;await store.refresh();s.setFail(true);assert.equal(await store.seen(revision(2)),false);assert.equal(store.unread('all'),true);s.setFail(false);await store.setEnabled('all',false);assert.equal(store.unread('all'),false);assert.equal(s.pages.all.seenRevision,1);await store.setEnabled('all',true);assert.equal(store.unread('all'),true)});
test('late refresh cannot overwrite a completed write',async()=>{const s=server();let resolve:any;const store=createNavigationStore(async(u,i)=>{if(resolve!==undefined&&!i?.method)return new Promise(r=>{resolve=()=>r(Response.json({pages:{all:{...revision(2),seenRevision:1,seenVersion:1,enabled:true}}}))});return s.fetcher(u,i)});await store.refresh();await store.initialize();s.pages.all.revision=2;await store.refresh();resolve=null;const stale=store.refresh();await tick();await store.seen(revision(2));resolve();await stale;assert.equal(store.unread('all'),false)});
test('visibility and prerender guards exist only in mounted UI, not loaders or navigation links',async()=>{const ui=await readFile('apps/web/app/components/NavigationUpdates.tsx','utf8')+await readFile('apps/web/app/lib/visible-page-read.ts','utf8');assert.ok(ui.includes("document.visibilityState!=='visible'"));assert.ok(ui.includes('prerendering'));assert.ok(ui.includes('cancelAnimationFrame'));for(const file of ['Sidebar','MobileTabBar']){const s=await readFile(`apps/web/app/components/shell/${file}.tsx`,'utf8');assert.ok(s.includes('prefetch="intent"'));assert.ok(!s.includes('.seen('))}const daily=await readFile('apps/web/app/routes/paper-daily.tsx','utf8');assert.ok(daily.includes('d.date===d.pageUpdate?.latestDate'));const changelog=await readFile('apps/web/app/routes/changelog.tsx','utf8');assert.ok(changelog.includes('IntersectionObserver'));assert.ok(changelog.includes('latestVisible&&latestHash'))});

import {observeVisiblePage} from '../apps/web/app/lib/visible-page-read.ts';
function browser(){const doc:any=new EventTarget(),win:any=new EventTarget();doc.visibilityState='visible';doc.prerendering=false;let seq=0;const frames=new Map<number,()=>void>();win.requestAnimationFrame=(fn:()=>void)=>{frames.set(++seq,fn);return seq};win.cancelAnimationFrame=(id:number)=>frames.delete(id);return {doc,win,paint(){for(const [id,f] of frames){frames.delete(id);f()}},visible(value:string){doc.visibilityState=value;doc.dispatchEvent(new Event('visibilitychange'))}}}
test('background/prerender tabs, rapid navigation and failed acknowledgements do not consume content',async()=>{const b=browser();let calls=0;b.doc.visibilityState='hidden';let ok=true;const dispose=observeVisiblePage(async()=>{calls++;return ok},b.doc,b.win);b.paint();assert.equal(calls,0);b.visible('visible');b.visible('hidden');b.paint();assert.equal(calls,0,'hidden between scheduling and paint');b.visible('visible');b.doc.prerendering=true;b.paint();assert.equal(calls,0);b.doc.prerendering=false;b.doc.dispatchEvent(new Event('prerenderingchange'));ok=false;b.paint();await tick();assert.equal(calls,1);ok=true;b.win.dispatchEvent(new Event('focus'));b.paint();await tick();assert.equal(calls,2,'failed request can retry');b.win.dispatchEvent(new Event('focus'));b.paint();assert.equal(calls,2,'successful loaded snapshot acknowledged once');dispose();const d=observeVisiblePage(async()=>{calls++;return true},b.doc,b.win);d();b.paint();assert.equal(calls,2,'fast route cleanup cancels the scheduled acknowledgement')});

import {updatePageDestination} from '../packages/contracts/src/navigation-updates.ts';
test('unread daily links to its actual newest archive, not an empty today or another date',()=>{const page:any={key:'daily',revision:3,version:1,seenRevision:2,seenVersion:1,enabled:true,latestDate:'2026-10-02'};assert.equal(updatePageDestination('/daily',{daily:page}),'/daily?date=2026-10-02');assert.equal(updatePageDestination('/daily',{daily:{...page,seenRevision:3}}),'/daily');assert.equal(updatePageDestination('/research',{daily:page}),'/research')});
