import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {build} from 'esbuild';
await mkdir('.sites-runtime',{recursive:true});
await writeFile('.sites-runtime/page-layout-fixture.tsx',`import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {PageFrame,PageHeader,PageGrid} from '../apps/web/app/components/ui/PageFrame';import {ControlReadingLayout} from '../apps/web/app/components/ui/ControlReadingLayout';export function render(){return renderToStaticMarkup(<PageFrame><ControlReadingLayout header={<PageHeader><div><p className="research-eyebrow">HKIS / FIXTURE</p><h1>长标题与统一基线</h1></div><button>刷新</button></PageHeader>} label="筛选" rail={<form><label>关键词<input name="q" defaultValue="TCAD"/></label></form>}><article>正文</article></ControlReadingLayout></PageFrame>)};export function assistant(){return renderToStaticMarkup(<PageFrame><PageGrid variant="assistant"><div className="site-reading-content"><PageHeader><h1>首页</h1></PageHeader></div><aside className="ai-home-rail"><textarea aria-label="提问"/></aside></PageGrid></PageFrame>)}`);
await build({entryPoints:['.sites-runtime/page-layout-fixture.tsx'],outfile:'.sites-runtime/page-layout-fixture.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',logLevel:'silent'});
const {render,assistant}=await import('../.sites-runtime/page-layout-fixture.mjs');
test('header, one control tree and primary content have explicit, accessible grid slots',()=>{const h=render();for(const c of ['page-frame','page-grid-controls','reading-page-heading','page-header','reading-control-rail','reading-primary-content'])assert.ok(h.includes(c),c);assert.equal((h.match(/<h1/g)||[]).length,1);assert.equal((h.match(/<form/g)||[]).length,1);assert.ok(h.indexOf('reading-page-heading')<h.indexOf('<aside'));assert.ok(h.indexOf('<aside')<h.indexOf('<article'));assert.ok(h.includes('aria-expanded="false"'));assert.ok(h.includes('name="q" value="TCAD"'))});
test('home uses the same grid primitive without moving or duplicating its chat instance',async()=>{const h=assistant();assert.ok(h.includes('data-page-grid="assistant"'));assert.equal((h.match(/<textarea/g)||[]).length,1);const root=await readFile('apps/web/app/root.tsx','utf8');assert.equal((root.match(/<AIAssistant /g)||[]).length,1);assert.ok(root.includes('<PageFrame>'));assert.ok(root.includes('<ReadingContinuity><Outlet /></ReadingContinuity>'));assert.ok(!root.includes('key={pathname}'));});
test('all active page families explicitly use the shared header and full-width grid',async()=>{for(const f of ['routes/research.tsx','components/ResearchViews.tsx','components/PaperDaily.tsx','routes/hot.tsx','routes/topics.tsx','routes/changelog.tsx','routes/ai-settings.tsx','components/PaperFavorites.tsx','routes/sites-info.tsx','routes/more.tsx','routes/research-paper.tsx','routes/search-busy.tsx','features/report/ReportLayout.tsx']){const s=await readFile('apps/web/app/'+f,'utf8');assert.ok(s.includes('PageHeader'),f)}for(const f of ['routes/research.tsx','components/ResearchViews.tsx','routes/hot.tsx','routes/changelog.tsx'])assert.match(await readFile('apps/web/app/'+f,'utf8'),/<ControlReadingLayout header=/,f);});
test('all registered routes are named in the coverage inventory, including legacy and admin limits',async()=>{const routes=await readFile('apps/web/app/routes.ts','utf8'),coverage=JSON.parse(await readFile('docs/page-layout-coverage.json','utf8'));const paths=['/',...[...routes.matchAll(/\broute\("([^"]+)"/g)].map(m=>'/'+m[1])];assert.deepEqual(coverage.routes.map(r=>r.route).sort(),paths.sort());for(const r of coverage.routes)for(const k of ['template','implementation','browser','desktop1440','desktop1180','short600','mobile390','zoom200','limitation'])assert.ok(k in r,`${r.route}: ${k}`)});
test('one token owner defines tracks, breakpoints, stable scrollbar, long text and mobile reflow',async()=>{const css=await readFile('apps/web/app/app.css','utf8');for(const token of ['site-sidebar-width','site-gutter','site-page-max','site-rail-width','site-column-gap','site-sticky-top'])assert.match(css,new RegExp('--'+token+':'));assert.ok(css.includes('--site-rail-width: 320px'));assert.ok(!css.includes('calc(270dvh'));assert.ok(css.includes('html{scrollbar-gutter:stable}'));assert.ok(css.includes('.page-grid-assistant,.page-grid-controls,.page-grid-article{grid-template-columns:minmax(0,1fr) var(--site-rail-width)}'));assert.ok(css.includes('@media(max-width:1119px)'));assert.ok(css.includes('@media(max-width:960px)'));assert.ok(css.includes('overflow-wrap:anywhere'));assert.ok(css.includes('scroll-margin-top:var(--site-sticky-top)'));assert.ok(css.includes('@container(max-width:700px)'));assert.ok(css.includes('.research-stats>div:nth-child(odd){padding-inline-start:0}'));assert.ok(css.includes('.page-grid-controls{grid-template-rows:auto minmax(0,1fr)}'));assert.ok(css.includes('.page-grid-article>.article-right-rail{grid-column:2;grid-row:1;align-self:stretch}'));});
test('control rails have no nested scrolling; chat retains its bounded message stream and keyboard focus',async()=>{const css=await readFile('apps/web/app/app.css','utf8'),rail=await readFile('apps/web/app/components/ui/AdaptiveRail.tsx','utf8'),chat=await readFile('apps/web/app/components/AIAssistant.tsx','utf8');assert.ok(!/reading-control-rail\{[^}]*(overflow:auto|overflow-y:auto|max-height:calc)/.test(css));assert.ok(rail.includes("getPropertyValue('--site-sticky-top')"));assert.ok(css.includes('.ai-home-panel .ai-chat-body'));assert.ok(css.includes(':focus-visible'));assert.ok(chat.includes('inFlight.current=true'));assert.ok(chat.includes('preventScroll:true'));});

test('legacy article integration does not put duplicated back/source/outline trees above mobile titles',async()=>{const item=await readFile('apps/web/app/routes/item.tsx','utf8');assert.ok(!item.includes('left={'));assert.equal((item.match(/\{outline\}/g)||[]).length,1);assert.ok(item.includes('className="hidden lg:block">{backButton}'));assert.ok(!item.includes('text-[13px] text-ink-3 2xl:hidden'));});
