import {test} from 'node:test';import {strict as assert} from 'node:assert';
import {paperCategories,validKeyword,canonicalKeyword} from './paper-keywords.ts';
import {openAlexEvidence,fetchKeywordBatch} from './keyword-maintenance.ts';
import {matchesResearchTheme,themeSummaries,paperForms,organizationId} from './research-topics.ts';
import {metadataFields} from './research-pipeline.ts';
const p=(extra:any={})=>({title:'TCAD device simulation',abstract:null,keywords:[],provenance:{},affiliations:[],authors:[],...extra} as any);
test('first three distinct valid terms preserve source order and narrow synonyms',()=>{const q=p({keywords:['keywords','TCAD','tcad','ReRAM','RRAM','FeFET','fourth'],provenance:{keywordEvidence:{records:[{kind:'openalex-keyword',terms:[{label:'later'}]}]}}});assert.deepEqual(paperCategories(q).map(k=>k.id),['tcad','rram','fefet']);assert.equal(validKeyword('unknown'),false);assert.equal(validKeyword('<script>'),false);assert.equal(canonicalKeyword('ReRAM').id,'rram')});
test('OpenAlex keyword and topic provenance differ from author evidence, and no invented padding',()=>{const e=openAlexEvidence({id:'https://openalex.org/W1',doi:'https://doi.org/10.1/A',keywords:[{display_name:'Fabry-Perot interferometer',score:.9}],topics:[]},'10.1/a','2026-10-05');const c=paperCategories(p({title:'Test',provenance:{keywordEvidence:e}}));assert.equal(c.length,1);assert.deepEqual(c[0].sources,['openalex-keyword']);assert.equal(e.status,'found');assert.equal(openAlexEvidence(null,'','today').status,'missing_doi')});
test('source priority, original raw terms, missing evidence and non-score revisions',()=>{const base=p({keywords:['author one','author two'],provenance:{keywordEvidence:openAlexEvidence({doi:'10.1/a',keywords:[{display_name:'indexed one'},{display_name:'null'}]},'10.1/a','today')}});assert.deepEqual(paperCategories(base).map(k=>k.label),['author one','author two','indexed one']);assert.equal(base.provenance.keywordEvidence.records[0].rawTerms.length,2);assert.deepEqual(metadataFields(base),metadataFields({...base,provenance:{...base.provenance,keywordEvidence:{checkedAt:'tomorrow'}}}))});
test('keyword transport requires shared gateway context',async()=>{let called=false;await assert.rejects(()=>fetchKeywordBatch([{doi:'10.9999/a'}],async()=>{called=true;return Response.json({results:[]})}),(e:any)=>e.code==='gateway_required');assert.equal(called,false)});
test('domain aliases, multi-membership, organization source and genre layers',()=>{const q=p({title:'TCAD simulations of GAA MOSFETs: review',abstract:'Devices were fabricated experimentally.',affiliations:['University X, Department Y'],provenance:{recordType:'journal-article'}});assert.ok(matchesResearchTheme(q,'gaa'));assert.ok(matchesResearchTheme(q,'tcad'));assert.ok(matchesResearchTheme(q,'devices'));assert.ok(matchesResearchTheme(q,organizationId(q.affiliations[0])));assert.ok(!matchesResearchTheme({...q,affiliations:[],publisher:'University X'},organizationId(q.affiliations[0])));assert.deepEqual(paperForms(q),['form-research','method-simulation','method-experiment']);const summary=themeSummaries([q]);assert.equal(summary.find(t=>t.id==='dram')!.total,0);assert.equal(summary.find(t=>t.id==='logic')!.total,1)});
test('canonical aliases preserve normalization, first match and fresh result objects',()=>{
 for(const word of ['TCAD','tcad','ＴＣＡＤ',' technology computer-aided design ','technology computer aided design'])assert.deepEqual(canonicalKeyword(word),{id:'tcad',label:'TCAD'});
 assert.deepEqual(canonicalKeyword('  Some   New-Term  '),{id:'term:some new term',label:'Some New-Term'});
 const a=canonicalKeyword('ReRAM');a.label='mutated';assert.deepEqual(canonicalKeyword('ReRAM'),{id:'rram',label:'RRAM'});
});
