/** Source-backed classification, separate from scores and scientific method inference. */
export const METADATA_POLICY='institutions-forms-v1';
const list=(v:any)=>Array.isArray(v)?v:[];
const str=(v:any)=>typeof v==='string'?v.replace(/\s+/g,' ').trim().slice(0,2000):'';
const norm=(s:string)=>s.normalize('NFKC').toLowerCase().replace(/[.,;，；]/g,' ').replace(/\s+/g,' ').trim();
export function metadataId(s:string){let h=14695981039346656037n;for(const c of norm(s)){h^=BigInt(c.codePointAt(0)!);h=BigInt.asUintN(64,h*1099511628211n)}return 'org:'+h.toString(16).padStart(16,'0')}
export function normalizedInstitutions(raw:any,provider:string){return list(raw).flatMap((x:any)=>{const name=str(x.display_name||x.name),ror=/^https:\/\/ror\.org\/[a-z0-9]+$/i.test(x.ror||'')?x.ror.toLowerCase():null,openalex=/^https:\/\/openalex\.org\/I\d+$/i.test(x.id||'')?x.id:null;if(!name)return [];return [{name,ror,openalex,source:provider,country:typeof x.country_code==='string'?x.country_code:null,type:typeof x.type==='string'?x.type:null}];})}
export function sourceMetadata(provider:string,raw:any,recordUrl:string,at:string){
 const authors=provider==='openalex'?list(raw.authorships).map((a:any,i:number)=>({name:str(a.raw_author_name||a.author?.display_name),orcid:a.author?.orcid||null,first:a.author_position==='first',corresponding:a.is_corresponding===true?true:null,raw:list(a.raw_affiliation_strings).map(str).filter(Boolean),institutions:normalizedInstitutions(a.institutions,provider),index:i})):provider==='crossref'?list(raw.author).map((a:any,i:number)=>({name:str(a.name||[a.given,a.family].filter(Boolean).join(' ')),orcid:a.ORCID||null,first:a.sequence==='first'||i===0,corresponding:null,raw:list(a.affiliation).map((x:any)=>str(x.name)).filter(Boolean),institutions:normalizedInstitutions(list(a.affiliation).flatMap((x:any)=>list(x['id']).map((id:any)=>({name:x.name,ror:id['id-type']==='ROR'?id.id:null}))),provider),index:i})):[];
 const types=provider==='semanticscholar'?list(raw.publicationTypes).map(str).filter(Boolean):[str(raw.type)].filter(Boolean);
 return {provider,recordUrl,checkedAt:at,rawFieldPaths:{types:provider==='semanticscholar'?'publicationTypes':'type',authors:provider==='openalex'?'authorships':provider==='crossref'?'author':null},authors,types,affiliationsChecked:provider==='crossref'||provider==='openalex'&&Object.hasOwn(raw,'authorships'),typesChecked:provider==='semanticscholar'?Object.hasOwn(raw,'publicationTypes'):Object.hasOwn(raw,'type')};
}
export function metadataSources(p:any){return list((p.provenance?.metadataEvidence||p.metadataEvidence)?.sources)}
function mergeAuthors(old:any,incoming:any){const authors=[...list(old)];for(const a of list(incoming)){const i=authors.findIndex((b:any)=>(a.orcid&&a.orcid===b.orcid)||norm(str(a.name))===norm(str(b.name))&&a.index===b.index);if(i<0)authors.push(a);else{const prior=authors[i];authors[i]={...prior,...a,raw:a.raw?.length?a.raw:prior.raw,institutions:a.institutions?.length?a.institutions:prior.institutions,orcid:a.orcid||prior.orcid,corresponding:a.corresponding??prior.corresponding};}}return authors;}
export function mergeMetadata(old:any,incoming:any[],at:string){
 const sources=[...list(old?.sources)];for(const entry of incoming){const index=sources.findIndex((s:any)=>s.provider===entry.provider&&s.recordUrl===entry.recordUrl);if(index<0)sources.push(entry);else{const prior=sources[index];sources[index]={...entry,types:entry.types?.length?entry.types:prior.types,authors:mergeAuthors(prior.authors,entry.authors)};}}
 const stable=(x:any)=>JSON.stringify(x,(k,v)=>['checkedAt','updatedAt','revision'].includes(k)?undefined:v);const changed=stable(old?.sources||[])!==stable(sources);return {policy:METADATA_POLICY,sources,checkedAt:at,revision:(old?.revision||0)+(changed?1:0),updatedAt:changed?at:old?.updatedAt||null};
}
export function storedMetadataSource(p:any,provider:string,recordUrl:string,at:string){
 const existing=metadataSources(p);if(existing.length)return existing;
 return [{provider,recordUrl,checkedAt:at,types:[str(p.provenance?.recordType)].filter(Boolean),typesChecked:provider==='crossref'||!!p.provenance?.recordType,affiliationsChecked:provider==='crossref'||provider==='openalex',authors:list(p.authors).map((a:any,index:number)=>({name:str(a.name),orcid:a.orcid||null,first:!!a.first,corresponding:a.corresponding??null,raw:list(a.affiliations).map(str).filter(Boolean),institutions:list(a.institutions),index})),rawAffiliations:list(p.affiliations).map(str).filter(Boolean)}];
}
export function paperInstitutionEvidence(p:any){
 const result=new Map<string,any>(),coveredRaw=new Set<string>();
 const add=(label:string,key:string,evidence:any,normalized=false)=>{if(!label)return;const id=metadataId(key),old=result.get(id);if(old){old.evidence.push(evidence);return;}result.set(id,{id,label,normalized,identity:key,evidence:[evidence]});};
 const sources=metadataSources(p),rorByOA=new Map<string,Set<string>>();for(const source of sources)for(const a of list(source.authors))for(const i of list(a.institutions))if(i.openalex&&i.ror){const ids=rorByOA.get(i.openalex)||new Set<string>();ids.add(i.ror);rorByOA.set(i.openalex,ids);}const identity=(i:any)=>i.ror||(rorByOA.get(i.openalex)?.size===1?[...rorByOA.get(i.openalex)!][0]:i.openalex)||'name:'+norm(str(i.name));
 const mappedRaw=new Set<string>();for(const source of sources)for(const a of list(source.authors))if(list(a.institutions).some((i:any)=>i.ror||i.openalex))for(const raw of list(a.raw))mappedRaw.add(norm(str(raw)));
 for(const source of sources)for(const a of list(source.authors)){
  const raw=list(a.raw).map(str).filter(Boolean),institutions=list(a.institutions);for(const r of raw)coveredRaw.add(norm(r));
  const evidence={provider:source.provider,recordUrl:source.recordUrl,author:a.name,orcid:a.orcid,first:a.first,corresponding:a.corresponding,rawAffiliations:raw,checkedAt:source.checkedAt};
  if(institutions.length)for(const i of institutions){coveredRaw.add(norm(str(i.name)));add(str(i.name),identity(i),{...evidence,ror:i.ror,openalex:i.openalex,country:i.country,type:i.type},true);}
  else for(const r of raw)if(!mappedRaw.has(norm(r)))add(r,r,evidence);
 }
 for(const source of sources)for(const raw of list(source.rawAffiliations)){const r=str(raw);if(!coveredRaw.has(norm(r))){coveredRaw.add(norm(r));add(r,r,{provider:source.provider,recordUrl:source.recordUrl,rawAffiliations:[r],checkedAt:source.checkedAt});}}
 for(const a of list(p.authors))for(const raw of list(a.affiliations)){const r=str(raw);if(coveredRaw.has(norm(r)))continue;coveredRaw.add(norm(r));add(r,r,{provider:a.affiliationSource||a.source||p.provenance?.affiliations||'stored',author:a.name,orcid:a.orcid,first:a.first,corresponding:a.corresponding,rawAffiliations:[r]});}
 for(const raw of list(p.affiliations)){const r=str(raw);if(!coveredRaw.has(norm(r))){coveredRaw.add(norm(r));add(r,r,{provider:p.provenance?.affiliations||'stored',rawAffiliations:[r]});}}
 // Equal provider IDs merge; raw department/address text is never guessed into a parent.
 return [...result.values()];
}
const typeMap:Record<string,string>={'journal-article':'form-research','research-article':'form-research',article:'form-research',journalarticle:'form-research',review:'form-review','review-article':'form-review',survey:'form-review',perspective:'form-perspective',roadmap:'form-perspective','proceedings-article':'form-proceeding',conference:'form-proceeding',conferencepaper:'form-proceeding',preprint:'form-preprint','posted-content':'form-preprint',editorial:'form-editorial',letter:'form-letter',letters:'form-letter',dataset:'form-data',data:'form-data',book:'form-book','book-chapter':'form-book'};
export function paperPublicationEvidence(p:any){
 const sources=metadataSources(p),evidence:any[]=sources.flatMap((s:any)=>list(s.types).map((raw:any)=>({provider:s.provider,recordUrl:s.recordUrl,raw:str(raw),form:typeMap[str(raw).toLowerCase()]||null,checkedAt:s.checkedAt,basis:'source-field'})));
 if(p.provenance?.recordType&&!evidence.some((x:any)=>x.raw===p.provenance.recordType))evidence.push({provider:p.provenance.recordTypeSource||'stored',raw:p.provenance.recordType,form:typeMap[String(p.provenance.recordType).toLowerCase()]||null,basis:'source-field'});
 const specific=[...new Set<string>(evidence.map((e:any)=>e.form).filter((f:any)=>f&&f!=='form-research'))],generic=evidence.some((e:any)=>e.form==='form-research');
 const conflict=specific.length>1;let forms=conflict?['form-unknown']:specific.length?specific:generic?['form-research']:['form-unknown'];
 const clue=str(p.title).match(/\b(review|survey|roadmap|perspective)\b/i);if(clue&&!specific.length){evidence.push({provider:'title-rule',raw:clue[0],form:'form-review',basis:'title-clue'});if(!generic)forms=['form-unknown'];}
 const status=conflict?'conflict':forms[0]!=='form-unknown'?'found':sources.some((s:any)=>s.status==='ambiguous_doi')?'conflict':clue?'needs_verification':sources.some((s:any)=>s.status==='no_matching_record')?'no_matching_record':sources.some((s:any)=>s.typesChecked)?'source_missing':'not_collected';
 return {forms,status,evidence,reviewTitleClue:clue?.[0]||null,container:generic?'journal-article':null};
}
export function paperMethodEvidence(p:any){const out:any[]=[];const fields=[['title',str(p.title)],['abstract',str(p.abstract)]];for(const [field,text] of fields){const patterns=[['method-experiment',/\b(?:we (?:fabricated|measured|experimentally demonstrate)|experimentally demonstrated|measurements (?:show|reveal)|was fabricated|were fabricated)\b/ig],['method-simulation',/\b(?:TCAD|simulations?|numerical model(?:ing)?|finite.element)\b/ig],['method-tool',/\b(?:dataset|benchmark|software|algorithm|method(?:ology)?)\b/ig]] as const;for(const [id,re] of patterns){if(id==='method-tool'&&field!=='title')continue;for(const m of text!.matchAll(re)){const prefix=text!.slice(Math.max(0,m.index!-50),m.index);if(/\b(?:no|not|without|lack of|previous|prior|earlier)\b/i.test(prefix))continue;if(!out.some(x=>x.id===id))out.push({id,field,quote:m[0],basis:'text-clue',policy:METADATA_POLICY});}}}return out;}
export function paperMetadata(p:any){const institutions=paperInstitutionEvidence(p),sources=metadataSources(p),publication=paperPublicationEvidence(p);return {policy:METADATA_POLICY,revision:p.provenance?.metadataEvidence?.revision||0,updatedAt:p.provenance?.metadataEvidence?.updatedAt||null,providerConflicts:sources.filter((s:any)=>s.status==='ambiguous_doi').map((s:any)=>({provider:s.provider,recordUrl:s.recordUrl,checkedAt:s.checkedAt,records:s.conflictingRecords||[]})),institutions,institutionStatus:institutions.length?(institutions.some(x=>x.normalized)?institutions.some(x=>!x.normalized)?'partial':'found':'raw_affiliation'):sources.some((s:any)=>s.status==='ambiguous_doi')?'conflict':sources.some((s:any)=>s.status==='no_matching_record')?'no_matching_record':sources.some((s:any)=>s.affiliationsChecked)?'source_missing':'not_collected',publication,methods:paperMethodEvidence(p)};}
