import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {build} from 'esbuild';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
await mkdir('.sites-runtime',{recursive:true});
await writeFile('.sites-runtime/reader-ui.tsx',`import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {MemoryRouter} from 'react-router';import {PaperReaderProvider,PaperSelection,PaperBulkToolbar,PaperCardState,PaperSourceLink,PaperDetailState} from '../apps/web/app/components/PaperReader';export function render(){return renderToStaticMarkup(<MemoryRouter><PaperReaderProvider><PaperSelection ids={['a','b']} scopeKey="one"><PaperBulkToolbar/><PaperCardState id="a" title="Safe <title>"><h2>Safe &lt;title&gt;</h2><PaperSourceLink paperId="a" href="https://example.org/paper" target="_blank" rel="noreferrer">原文</PaperSourceLink></PaperCardState><PaperDetailState id="a"/></PaperSelection></PaperReaderProvider></MemoryRouter>)}`);
await build({entryPoints:['.sites-runtime/reader-ui.tsx'],outfile:'.sites-runtime/reader-ui.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',logLevel:'silent'});
const {render}=await import('../.sites-runtime/reader-ui.mjs');
test('SSR exposes current-page scope, zero selected, accessible favorite/checkbox and safe escaped title',()=>{const html=render();assert.match(html,/全选当前页（2 篇）/);assert.match(html,/已选 0 篇/);assert.match(html,/批量已读/);assert.match(html,/设为未读/);assert.match(html,/选择论文：Safe &lt;title&gt;/);assert.match(html,/aria-pressed="false"/);assert.match(html,/data-read="false"/);assert.match(html,/data-selected="false"/);assert.ok(!html.includes('<title>'));assert.match(html,/href="\/starred"/)});
test('all research surfaces share canonical card state; legacy RSS state remains separate',async()=>{for(const path of ['routes/research.tsx','routes/hot.tsx','components/ResearchViews.tsx','components/ScholarlySearch.tsx','components/PaperFavorites.tsx']){const text=await readFile('apps/web/app/'+path,'utf8');assert.match(text,/PaperCardState/);assert.match(text,/PaperSourceLink/);assert.ok(!text.includes('localStorage'));}const detail=await readFile('apps/web/app/routes/research-paper.tsx','utf8');assert.match(detail,/PaperDetailState id=\{p.id\}/);const root=await readFile('apps/web/app/root.tsx','utf8');assert.match(root,/PaperReaderProvider/);const starred=await readFile('apps/web/app/routes/starred.tsx','utf8');assert.match(starred,/原版订阅内容的本机收藏/);assert.match(starred,/private, no-store/)});
test('opened effect is visible-detail only; source links accept primary/middle clicks without blocking navigation',async()=>{const src=await readFile('apps/web/app/components/PaperReader.tsx','utf8');assert.match(src,/document.visibilityState==='visible'/);assert.match(src,/prerendering/);assert.match(src,/e.button===0/);assert.match(src,/e.button===1/);assert.ok(!src.includes('onMouseEnter'));assert.ok(!src.includes('preventDefault()'));assert.match(src,/indeterminate=count>0&&count<total/);assert.match(src,/createPaperSelectionStore\(ids\)/);assert.match(src,/\[key,scopeKey\]/);assert.match(src,/currentSelection.current!==target/)});
test('read styling has no blanket opacity, keeps title and favorite semantic contrast',async()=>{const css=(await readFile('apps/web/app/app.css','utf8')).split('/* Personal reading state:')[1].split('/* Public-page framework.')[0];assert.ok(!css.includes('opacity'));assert.ok(!css.includes('shadow'));assert.match(css,/is-read\{background:var\(--inset\)/);assert.match(css,/is-read :is\(h2,h3,h4\)\{color:var\(--ink-2\)/);assert.match(css,/paper-favorite.is-favorite\{color:var\(--accent-ink\);background:var\(--selected\)/);assert.match(css,/min-height:44px/)});

test('each card shares one reader subscription with its favorite and uses constant-time selection membership',async()=>{const src=await readFile('apps/web/app/components/PaperReader.tsx','utf8'),card=src.split('export function PaperCardState')[1].split('export function PaperFavorite')[0];assert.equal((card.match(/usePaper\(id\)/g)||[]).length,1);assert.match(card,/<PaperFavoriteButton id={id} {\.\.\.reader}/);assert.ok(!card.includes('<PaperFavorite id='));assert.ok(card.includes('selection?.idSet.has(id)'));assert.ok(!card.includes('selection?.ids.includes(id)'));});
