import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {createPaperReaderStore,type PaperState} from '../apps/web/app/lib/paper-reader-store.ts';
const blank=(id:string):PaperState=>({id,readAt:null,favoriteAt:null});
const tick=()=>new Promise(r=>setImmediate(r));
function server(){const values:Record<string,PaperState>={},calls:any[]=[];let fail=false;const fetcher=async(url:string,init?:RequestInit)=>{calls.push({url,init});if(init?.method==='PUT'){if(fail)return Response.json({detail:'保存失败'},{status:503});const b=JSON.parse(init.body as string),column=b.field==='read'?'readAt':'favoriteAt';for(const id of b.ids){values[id]??=blank(id);(values[id] as any)[column]=b.value?((values[id] as any)[column]||'saved'):null}return Response.json({states:Object.fromEntries(b.ids.map((id:string)=>[id,values[id]]))})}const ids=new URL(url,'https://test').searchParams.getAll('id');return Response.json({states:Object.fromEntries(ids.map(id=>[id,values[id]||blank(id)]))})};return {values,calls,fetcher,setFail(v:boolean){fail=v}}}
test('visible reads batch same-turn hooks and never mutate state in GET',async()=>{const s=server(),store=createPaperReaderStore(s.fetcher);await Promise.all(['a','b','a'].map(id=>store.load([id])));assert.equal(s.calls.length,1);assert.deepEqual(Object.keys(store.getSnapshot().states),['a','b']);assert.equal(s.calls[0].init.method,undefined);assert.equal(Object.keys(s.values).length,0)});
test('read/favorite independent, repeat idempotent, explicit clear does not erase other field',async()=>{const s=server(),store=createPaperReaderStore(s.fetcher);await store.set(['a'],'favorite',true);await store.set(['a'],'read',true);await store.set(['a'],'read',true);assert.deepEqual(store.getSnapshot().states.a,{id:'a',readAt:'saved',favoriteAt:'saved'});await store.set(['a'],'read',false);assert.equal(store.getSnapshot().states.a.favoriteAt,'saved');assert.equal(store.getSnapshot().states.a.readAt,null);for(const c of s.calls.filter(c=>c.init.method==='PUT')){assert.equal(c.init.keepalive,true);assert.equal(c.init.headers['X-HKIS-Request'],'1')}});
test('failed optimistic write rolls back to confirmed state and surfaces failure',async()=>{const s=server(),store=createPaperReaderStore(s.fetcher);await store.load(['a']);s.setFail(true);assert.equal(await store.set(['a'],'read',true),false);assert.equal(store.getSnapshot().states.a.readAt,null);assert.equal(store.getSnapshot().pending.a,undefined);assert.equal(store.getSnapshot().error,'保存失败')});
test('two failed queued actions cannot resurrect another optimistic action',async()=>{const s=server(),store=createPaperReaderStore(s.fetcher);await store.load(['a']);s.setFail(true);const a=store.set(['a'],'read',true),b=store.set(['a'],'read',false),c=store.set(['a'],'favorite',true);await Promise.all([a,b,c]);assert.deepEqual(store.getSnapshot().states.a,blank('a'));assert.equal(store.getSnapshot().pending.a,undefined)});
test('serialized rapid read and favorite actions preserve last intent',async()=>{const s=server(),store=createPaperReaderStore(s.fetcher);await store.load(['a']);await Promise.all([store.set(['a'],'read',true),store.set(['a'],'favorite',true),store.set(['a'],'read',false)]);assert.equal(s.values.a.readAt,null);assert.equal(s.values.a.favoriteAt,'saved');assert.deepEqual(store.getSnapshot().states.a,s.values.a)});
test('late refresh cannot overwrite a completed newer write',async()=>{let resolve:any;const s=server();const store=createPaperReaderStore(async(url,init)=>{if(!init?.method&&resolve!==undefined)return new Promise(r=>{resolve=()=>r(Response.json({states:{a:blank('a')}}))});return s.fetcher(url,init)});await store.load(['a']);resolve=null;const refresh=store.refresh();await tick();const write=store.set(['a'],'read',true);await tick();resolve();await Promise.all([refresh,write]);assert.equal(store.getSnapshot().states.a.readAt,'saved')});
test('bounded chunks preserve successful partial saves and rollback only failed remainder',async()=>{let puts=0;const s=server(),store=createPaperReaderStore(async(url,init)=>{if(init?.method==='PUT'&&++puts===2)return Response.json({detail:'第二批失败'},{status:503});return s.fetcher(url,init)});const ids=Array.from({length:101},(_,i)=>'p'+i);assert.equal(await store.set(ids,'read',true),false);assert.equal(store.getSnapshot().states.p0.readAt,'saved');assert.equal(store.getSnapshot().states.p100.readAt,null);assert.equal(Object.keys(store.getSnapshot().pending).length,0);for(const c of s.calls){const n=c.init?.method==='PUT'?JSON.parse(c.init.body).ids.length:new URL(c.url,'https://test').searchParams.getAll('id').length;assert.ok(n<=100)}});
