import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {savePaper,rowPaper,combine,initResearch,syncSource} from './research.ts';
import {applyRecord} from './scholarly/api.ts';
import {normalizeRecord} from './scholarly/domain.ts';
import {digest,analysisFields,monthWindow} from './research-pipeline.ts';
import {processRecent,attachAnalyses} from './research-processing.ts';
import {prepareDaily,dailyRead,dailyReceiptText,generateDaily} from './research-daily.ts';
import {seal} from './ai/security.ts';
import {RESEARCH_SOURCES} from './research-config.ts';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {q,args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(ss:any[]){sql.exec('BEGIN');try{const r=ss.map(s=>s.runSync());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,env:{DB:db,HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)}}}
const abstract='We compared TCAD device simulation of GAA transistors with measured interface trap transport. The proposed mechanism explains differences between measurements and model predictions. This abstract reports the device methods and comparative observations but does not establish independently verified reproducibility.';
const paper=(id='a',extra:any={})=>({doi:'10.9999/block-'+id,title:'TCAD interface traps in GAA transistors',url:'https://doi.org/10.9999/block-'+id,publisher:'IEEE',journal:'Test',sourceId:'ieee-ted',issn:'0018-9383',publishedAt:monthWindow().endDate,datePrecision:'day',authors:[],affiliations:[],abstract,keywords:[],provenance:{abstract:'crossref',publishedAt:'crossref'},sourceIndexedAt:null,discovery:'crossref',...extra});
async function settings(f:any){const secret=await seal('UNIT_TEST_NOT_REAL',f.env,'owner|https://api.deepseek.com');f.sql.prepare("INSERT INTO ai_settings(owner_id,endpoint,model,protocol,reasoning,key_ciphertext,enabled,daily_limit,max_tokens,revision,updated_at,test_status) VALUES('owner','https://api.deepseek.com','fixture-model','chat-completions','high',?,1,30,8192,1,?,'ok')").run(secret,new Date().toISOString())}
async function cached(f:any,p:any,extra:any={}){const r=normalizeRecord('semanticscholar',{paperId:'a'.repeat(40),externalIds:{DOI:p.doi},title:p.title,publicationDate:p.publishedAt,abstract,authors:[],journal:{name:p.journal},...extra},'2026-10-04T01:00:00Z'),key='c'.repeat(64);f.sql.prepare('INSERT OR REPLACE INTO scholarly_cache(id,owner_id,service,payload_json,expires_at,created_at) VALUES(?,?,?,?,?,?)').run(key,'owner','semanticscholar',JSON.stringify({records:[r]}),'2030-01-01T00:00:00Z','2026-10-04T01:00:00Z');return {cacheKey:key,recordId:r.recordId}}
const row=(f:any)=>f.sql.prepare('SELECT * FROM research_papers ORDER BY id LIMIT 1').get();
const member=(f:any)=>f.sql.prepare('SELECT * FROM research_batch_members LIMIT 1').get();
test('filling abstract invalidates insufficient cache, queues without payment, and is idempotent',async()=>{const f=fixture(),net=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw Error('no external requests')};try{await settings(f);const p=paper('hash',{abstract:null,provenance:{publishedAt:'crossref'}});const saved=await savePaper(f.db,p,new Date().toISOString(),{runId:'real',batchKey:null});await processRecent(f.db,f.env,{maxPapers:0});const before=row(f);assert.equal(f.sql.prepare('SELECT status FROM research_analyses').get()!.status,'insufficient');const body=await cached(f,p);await applyRecord(f.db,'owner',{...body,paperId:saved.id});const after=row(f);assert.notEqual(after.content_hash,before.content_hash);assert.notEqual(after.metadata_hash,before.metadata_hash);assert.equal(after.priority,before.priority);assert.equal(after.first_seen,before.first_seen);assert.equal(after.content_hash,await digest(analysisFields(rowPaper(after))));assert.equal((await attachAnalyses(f.db,[rowPaper(after)]))[0].analysisStale,true);await processRecent(f.db,f.env,{maxPapers:0});assert.equal((await attachAnalyses(f.db,[rowPaper(row(f))]))[0].analysis.status,'queued');await applyRecord(f.db,'owner',{...body,paperId:saved.id});assert.equal(row(f).metadata_revision,after.metadata_revision);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.equal(calls,0)}finally{globalThis.fetch=net;f.sql.close()}});
test('author-only fill preserves semantic hash while recording metadata revision',async()=>{const f=fixture();try{const p=paper('authors'),saved=await savePaper(f.db,p),before=row(f);const body=await cached(f,p,{authors:[{name:'Real deposited author'}]});await applyRecord(f.db,'owner',{...body,paperId:saved.id});const after=row(f);assert.equal(after.content_hash,before.content_hash);assert.notEqual(after.metadata_hash,before.metadata_hash);assert.equal(after.metadata_revision,Number(before.metadata_revision)+1)}finally{f.sql.close()}});
test('apply time, not cached retrieval time, controls midnight and frozen snapshot protection',async()=>{for(const mode of ['same','midnight','frozen']){const f=fixture();try{const p=paper(mode,{abstract:null,provenance:{publishedAt:'crossref'}}),saved=await savePaper(f.db,p,'2026-10-05T00:01:00Z',{runId:'real',batchKey:null});const before=member(f);if(mode==='frozen')await prepareDaily(f.db,'2026-10-06',new Date('2026-10-06T00:01:00Z'));const body=await cached(f,p);await applyRecord(f.db,'owner',{...body,paperId:saved.id},new Date(mode==='midnight'?'2026-10-05T16:00:00Z':'2026-10-05T12:00:00Z'));const after=member(f);assert.equal(after.run_id,before.run_id);assert.equal(after.first_seen,before.first_seen);if(mode==='same')assert.equal(JSON.parse(after.snapshot_json).abstract,abstract);else assert.equal(after.snapshot_json,before.snapshot_json)}finally{f.sql.close()}}});
test('new owner import atomically records a real unscheduled cohort, hashes, and no scheduled batch',async()=>{const f=fixture();try{const p=paper('import'),body=await cached(f,p),at=new Date('2026-10-05T15:59:00Z');await applyRecord(f.db,'owner',body,at,'owner_web');const m=member(f),r=row(f),run=f.sql.prepare('SELECT * FROM research_runs').get()!;assert.equal(m.batch_key,null);assert.equal(m.daily_cohort_key,'2026-10-05/20');assert.equal(run.entry_point,'owner_web');assert.equal(run.id,m.run_id);assert.equal(run.batch_key,null);assert.equal(r.content_hash,await digest(analysisFields(rowPaper(r))));assert.equal(f.sql.prepare('SELECT count(*) n FROM research_batches').get()!.n,0);await applyRecord(f.db,'owner',body,at);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_runs').get()!.n,1)}finally{f.sql.close()}});
test('cohort failure rolls back owner abstract, hash, changes and evidence together',async()=>{const f=fixture();try{const p=paper('rollback',{abstract:null}),saved=await savePaper(f.db,p,'2026-10-05T00:01:00Z',{runId:'real',batchKey:null}),before=row(f),body=await cached(f,p);f.sql.exec("CREATE TRIGGER reject_cohort BEFORE UPDATE ON research_batch_members BEGIN SELECT RAISE(ABORT,'fixture rollback'); END;");await assert.rejects(applyRecord(f.db,'owner',{...body,paperId:saved.id},new Date('2026-10-05T12:00:00Z')),/fixture rollback/);assert.deepEqual(row(f),before);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_changes').get()!.n,0)}finally{f.sql.close()}});
test('stale collector retries merge and cannot revert concurrent owner evidence or revision',async()=>{const f=fixture();try{const p=paper('race',{abstract:null}),saved=await savePaper(f.db,p),body=await cached(f,p),base=f.db.batch.bind(f.db);let once=true;f.db.batch=async ss=>{if(once){once=false;await applyRecord(f.db,'owner',{...body,paperId:saved.id})}return base(ss)};await savePaper(f.db,p);const r=row(f);assert.equal(r.abstract,abstract);assert.equal(r.content_hash,await digest(analysisFields(rowPaper(r))));assert.ok(Number(r.metadata_revision)>=2)}finally{f.sql.close()}});
test('RSS abstract wins over stale OpenAlex enrichment',()=>{const rss=paper('priority',{abstract:abstract+' RSS original.',provenance:{abstract:'publisher-rss'}}),oa=paper('priority',{abstract:'Different OpenAlex content',provenance:{abstract:'openalex'},discovery:'openalex'});const p=combine(rss,oa);assert.equal(p.abstract,rss.abstract);assert.equal(p.provenance.abstract,'publisher-rss')});
test('source sync saves RSS and commits Crossref progress without inline enrichment',async()=>{const f=fixture(),net=globalThis.fetch,paths:string[]=[];try{await initResearch(f.db);const p=paper('order'),day=monthWindow().endDate;globalThis.fetch=async(url:any)=>{const u=String(url);paths.push(u.includes('openalex')?'oa':u.includes('crossref')?'cr':'rss');if(u.includes('crossref'))return Response.json({message:{items:[{DOI:p.doi,type:'journal-article',title:[p.title],published:{'date-parts':[day.split('-').map(Number)]}}]}});if(u.includes('openalex'))return new Response('',{status:429,headers:{'retry-after':'3600'}});return new Response(`<rss><channel><item><title>${p.title}</title><link>${p.url}</link><description>Abstract: ${abstract}</description><pubDate>${day}</pubDate></item></channel></rss>`)};const result=await syncSource(f.db,RESEARCH_SOURCES[0]!,1,null,'internal',new Date().toISOString(),f.env);assert.ok(paths.includes('rss'));assert.equal(paths.includes('oa'),false);assert.equal(row(f).abstract,abstract);assert.equal(row(f).content_hash,await digest(analysisFields(rowPaper(row(f)))));assert.equal(result.rssStatus,'ok');assert.equal(result.channels.crossref,'ok');assert.equal(result.stages.openalex,'queued');assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.equal(f.sql.prepare("SELECT count(*) n FROM scholarly_usage WHERE service='openalex'").get()!.n,0);assert.ok(f.sql.prepare("SELECT count(*) n FROM research_enrichment_queue WHERE status='pending'").get()!.n>0)}finally{globalThis.fetch=net;f.sql.close()}});
test('all-candidate evidence diagnostics do not hide low-score missing abstracts or rewrite old archive',async()=>{const f=fixture();try{await savePaper(f.db,paper('low',{abstract:null}),'2026-10-05T00:01:00Z',{runId:'real',batchKey:null});f.sql.prepare("UPDATE research_batch_members SET snapshot_json=json_set(snapshot_json,'$.priority',44)").run();const archive=await prepareDaily(f.db,'2026-10-06');const sel=JSON.parse(archive.selection_json);assert.equal(sel.eligible,0);assert.equal(sel.missingAbstract,0);assert.equal(sel.evidenceCoverage.missingOrShortAbstract,1);delete sel.evidenceCoverage;f.sql.prepare('UPDATE research_daily SET selection_json=?').run(JSON.stringify(sel));const before=f.sql.prepare('SELECT * FROM research_daily').get();const read=await dailyRead(f.db,new URLSearchParams('date=2026-10-06'));assert.equal(read.report.diagnostics.reconstructed,true);assert.equal(read.report.diagnostics.evidenceCoverage.missingOrShortAbstract,1);assert.deepEqual(f.sql.prepare('SELECT * FROM research_daily').get(),before)}finally{f.sql.close()}});
test('concurrent freeze loser cannot append groups to a different winning archive',async()=>{const f=fixture();try{const add=async(id:string)=>{const r=await savePaper(f.db,paper(id),'2026-10-05T00:01:00Z',{runId:id,batchKey:null});f.sql.prepare("UPDATE research_batch_members SET snapshot_json=json_set(snapshot_json,'$.priority',90) WHERE paper_id=?").run(r.id);};await add('1');const pending:{go:()=>void}[]=[],base=f.db.batch.bind(f.db);f.db.batch=async ss=>{if(ss[0]?.q.startsWith('INSERT OR IGNORE INTO research_daily('))await new Promise<void>(resolve=>pending.push({go:resolve}));return base(ss)};const a=prepareDaily(f.db,'2026-10-06');while(pending.length<1)await new Promise(setImmediate);await add('2');await add('3');await add('4');const b=prepareDaily(f.db,'2026-10-06');while(pending.length<2)await new Promise(setImmediate);pending[0].go();await a;pending[1].go();await b;const r=f.sql.prepare('SELECT * FROM research_daily').get()!;assert.equal(JSON.parse(r.paper_ids_json).length,1);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_daily_groups').get()!.n,1)}finally{f.sql.close()}});
test('receipt recovery rejects incomplete, failed and tool outputs without a replay',()=>{for(const raw of [{status:'incomplete',output:[]},{status:'failed',output:[]},{choices:[{finish_reason:'length',message:{content:'{}'}}]},{choices:[{finish_reason:'stop',message:{content:'{}',tool_calls:[{}]}}]},{status:'completed',output:[{type:'function_call'}]}])assert.throws(()=>dailyReceiptText(raw));assert.equal(dailyReceiptText({choices:[{finish_reason:'stop',message:{content:'{}'}}]}),'{}')});
test('empty daily reports availability separately instead of a model blocker',async()=>{const f=fixture();try{const result=await generateDaily(f.db,f.env,{maxCalls:0},undefined,new Date('2026-10-06T00:01:00Z'));assert.equal(result.blocked,null);assert.equal(result.modelAvailability,'not_configured');assert.equal(result.attempted,0);assert.equal(result.status,'partial')}finally{f.sql.close()}});
