import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createPaperReaderStore} from '../apps/web/app/lib/paper-reader-store.ts';
const blank=(id:string)=>({id,readAt:null,favoriteAt:null}),ids=(count:number,prefix='p')=>Array.from({length:count},(_,i)=>prefix+i),tick=()=>new Promise(r=>setImmediate(r));
function controlled(){const calls:Array<{ids:string[],resolve:(x:Response)=>void}>=[];let active=0,peak=0;const store=createPaperReaderStore(async(url,init)=>{assert.notEqual(init?.method,'PUT');const requestIds=new URL(url,'https://fixture').searchParams.getAll('id');assert(requestIds.length<=100);active++;peak=Math.max(peak,active);return new Promise<Response>(resolve=>calls.push({ids:requestIds,resolve:(res)=>{active--;resolve(res)}}))});return {store,calls,get peak(){return peak},respond(i:number,fail=false){const c=calls[i]!;c.resolve(fail?Response.json({detail:'fixture failure'},{status:503}):Response.json({states:Object.fromEntries(c.ids.map(id=>[id,blank(id)]))}))}};}
test('1882 states require 19 bounded reads and full load waits for every chunk',async()=>{const f=controlled();let done=false;const load=f.store.load(ids(1882)).then(()=>{done=true});await tick();assert.equal(f.calls.length,3);for(let i=0;i<19;i++){assert.equal(done,false);f.respond(i);await tick()}await load;assert.equal(f.calls.length,19);assert.equal(f.peak,3);assert.equal(Object.keys(f.store.getSnapshot().states).length,1882)});
test('overlapping different batches share the per-store limit and duplicate IDs reuse in-flight load',async()=>{const f=controlled();const a=f.store.load(ids(350));await tick();const b=f.store.load([...ids(350),...ids(250,'q')]);await tick();assert.equal(f.calls.length,3);for(let i=0;i<7;i++){f.respond(i);await tick()}await Promise.all([a,b]);assert.equal(f.peak,3);assert.equal(f.calls.length,7);assert.equal(Object.keys(f.store.getSnapshot().states).length,600)});
test('failure waits for in-flight chunks, stops queued reads and permits explicit retry',async()=>{const f=controlled();const initial=f.store.load(ids(500));const result=initial.then(()=>false,()=>true);await tick();f.respond(1,true);await tick();assert.equal(f.calls.length,3);f.respond(0);f.respond(2);assert.equal(await result,true);assert.equal(f.store.getSnapshot().error,'fixture failure');assert.equal(Object.keys(f.store.getSnapshot().states).length,200);const retry=f.store.load(ids(500));await tick();for(let i=3;i<6;i++)f.respond(i);await retry;assert.equal(Object.keys(f.store.getSnapshot().states).length,500);assert.equal(f.store.getSnapshot().error,'');assert.equal(f.peak,3)});
test('unsubscribed hidden page completion stays read-only and rapid subsets reuse loads',async()=>{const f=controlled();let emits=0;const un=f.store.subscribe(()=>emits++);const a=f.store.load(ids(250));await tick();un();const b=f.store.load(['p101','p202']);for(let i=0;i<3;i++)f.respond(i);await Promise.all([a,b]);assert.equal(emits,0);assert.equal(f.calls.length,3);assert.equal(Object.keys(f.store.getSnapshot().states).length,250)});
