import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {RESEARCH_SOURCES,PUBLISHERS,RESEARCH_PAGE_BUDGET} from './research-config.ts';
import {fromCrossref,sourceAccepts} from './research-domain.ts';
import {monthWindow,inUpdateWindow} from './research-pipeline.ts';
import {initResearch,syncSource,savePaper,researchStatus} from './research.ts';
import {readHkis} from './hkis-publication.ts';
import {journalMetric} from './journal-metrics.ts';
import {collectResearch} from './research-refresh-plan.ts';
import {prepareCrossref,crossrefSummary,reserveCrossrefPage,markCrossrefAttempt,nextCrossrefPage} from './research-crossref.ts';
const additions=RESEARCH_SOURCES.slice(17);
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(ss:any[]){sql.exec('BEGIN');try{const out=ss.map(s=>s.runSync());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const record=(s:any)=>({type:'journal-article',DOI:'10.9999/'+s.id,title:['TCAD simulation of GAA transistor interface traps'],ISSN:[s.issn], 'container-title':[s.name], 'published-online':{'date-parts':[monthWindow().endDate.split('-').map(Number)]},'published-print':{'date-parts':[[2099,12,1]]},abstract:'<jats:p>We compared transistor device simulation with interface trap measurements.</jats:p>',author:[{given:'Test',family:'Author',affiliation:[{name:'Fixture Institute'}]}]});
test('eleven verified journal manifests preserve original seventeen and do not invent RSS/JIF',()=>{assert.equal(additions.length,11);assert.equal(RESEARCH_SOURCES.length,28);assert.equal(RESEARCH_PAGE_BUDGET,31);assert.equal(new Set(RESEARCH_SOURCES.map(s=>s.id)).size,28);assert.equal(new Set(RESEARCH_SOURCES.map(s=>s.issn)).size,28);assert.ok(['IOP','ACS','AIP','SPIE'].every(p=>PUBLISHERS.includes(p)));for(const s of additions){assert.equal(s.rss,null);assert.equal(s.topicFilter,true);assert.ok(s.issns?.includes(s.issn));assert.equal(new Set(s.issns).size,s.issns?.length);assert.equal(journalMetric(s.id).value,null);assert.equal(journalMetric(s.id).status,'unverified')}});
test('new parser identities are exact journal ISSNs, not publisher-wide matches',()=>{for(const s of additions){const w=record(s),p=fromCrossref(w,s)!;assert.equal(p.sourceId,s.id);assert.equal(p.publisher,s.publisher);assert.equal(p.datePrecision,'day');assert.equal(p.publishedAt,monthWindow().endDate);assert.ok(inUpdateWindow(p,monthWindow()));assert.ok(sourceAccepts(p,s));assert.ok(!p.abstract!.includes('<'));assert.deepEqual(p.keywords,[]);assert.equal(p.authors[0]!.corresponding,null);assert.equal(fromCrossref({...w,ISSN:['9999-9999']},s),null);assert.equal(fromCrossref({...w,ISSN:undefined},s),null);assert.equal(fromCrossref({...w,type:'proceedings-article'},s),null);const alternate=s.issns!.at(-1)!;assert.ok(fromCrossref({...w,ISSN:[alternate,alternate]},s));const monthly=fromCrossref({...w,'published-online':undefined,published:{'date-parts':[[2099,2]]}},s)!;assert.equal(monthly.datePrecision,'month');assert.equal(inUpdateWindow(monthly,monthWindow()),false)}});
test('new publisher filters and safe configured source counts work through shared read-only publication',async()=>{const f=fixture();try{const cold:any=await readHkis(f.db,'owner',{section:'status',limit:50});assert.equal(cold.items[0].data.configuredSources,28);assert.equal(cold.items[0].data.sources.length,28);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_sources').first()).n,0);await initResearch(f.db);for(const s of additions)await savePaper(f.db,fromCrossref(record(s),s)!);for(const publisher of ['IOP','ACS','AIP','SPIE','Elsevier']){const r:any=await readHkis(f.db,'owner',{section:'papers',publisher,limit:50});assert.equal(r.items.length,additions.filter(s=>s.publisher===publisher).length);assert.ok(r.items.every((x:any)=>x.data.publisher===publisher))}const status:any=await researchStatus(f.db);assert.equal(status.configuredSources,28);assert.equal(status.collectionPolicy.pageAttemptsPerSlot,31);assert.equal(status.sources.length,28);assert.ok(status.sources.filter((s:any)=>additions.some(x=>x.id===s.id)).every((s:any)=>s.rssConfigured===false));assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0)}finally{f.sql.close()}});
test('Crossref-only sync never fetches invented RSS, tracks unknown scope and uses normal DOI dedupe',async()=>{const f=fixture(),original=globalThis.fetch,s=additions[0]!;let lists=0,other=0;try{await initResearch(f.db);globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.openalex.org')return Response.json({results:[]});assert.equal(u.hostname,'api.crossref.org');if(u.pathname.startsWith('/works/')){other++;return Response.json({message:record(s)})}lists++;return Response.json({message:{items:[record(s),{...record(s),DOI:'10.9999/unknown',title:['A characterization study'],abstract:undefined},{...record(s),DOI:'10.9999/mismatch',ISSN:['9999-9999']}]}})};const result:any=await syncSource(f.db,s,1);assert.equal(result.added,1);assert.equal(result.scopeUnresolved,1);assert.equal(result.rssStatus,'not_configured');assert.equal(result.stages.publisherRss,'not_configured');assert.equal(result.channels.crossref,'ok');assert.equal(lists,1);await savePaper(f.db,fromCrossref(record(s),s)!);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_papers').first()).n,1);assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0);assert.ok(other<=2)}finally{globalThis.fetch=original;f.sql.close()}});
test('budget-deferred plans never count as actual head attempts; null remains highest priority',async()=>{const at='2026-10-07T12:00:00Z';const {state}=prepareCrossref(null,{}, {},monthWindow(new Date(at)),at,null);assert.equal(crossrefSummary(state).lastHeadAttemptAt,null);reserveCrossrefPage(state,nextCrossrefPage(state)!,at);assert.equal(crossrefSummary(state).lastHeadAttemptAt,null);markCrossrefAttempt(state,nextCrossrefPage(state)!,at);assert.equal(crossrefSummary(state).lastHeadAttemptAt,at);const order:string[]=[];await collectResearch([{id:'deferred',crossref:{lastHeadAttemptAt:null,headPlannedThrough:at}},{id:'attempted',crossref:{lastHeadAttemptAt:'2026-10-06'}}],async id=>{order.push(id);return {pending:false}},{maxPagesPerSource:2,maxMs:1000});assert.deepEqual(order,['deferred','attempted'])});
test('orchestration stops all sources after provider rate limit rather than hammering next journal',async()=>{const calls:string[]=[];await collectResearch(RESEARCH_SOURCES,async id=>{calls.push(id);return {status:'error',error:'Crossref HTTP 429; retry deferred 60 seconds'}},{maxPagesPerSource:2,maxMs:260000});assert.equal(calls.length,1)});

test('explicit editorial and correction titles in the new journals never become research evidence',()=>{for(const s of additions)for(const title of ['Erratum: TCAD transistor transport','Editorial: CMOS image sensors','Correction to: TCAD transport','Publication guidelines for semiconductor lithography','Publisher Correction: TCAD transistor transport','Meeting report: TCAD image sensor devices']){assert.equal(fromCrossref({...record(s),title:[title]},s),null)}const s=additions[0]!;assert.ok(fromCrossref({...record(s),title:['Error correction in semiconductor memory arrays']},s))});
test('a cooldown published between optimistic read and lock acquisition is rechecked under lease',async()=>{const f=fixture(),originalFetch=globalThis.fetch,originalPrepare=f.db.prepare;let cooldownReads=0,net=0;try{await initResearch(f.db);f.db.prepare=function(q:string){const statement=originalPrepare(q),first=statement.first;statement.first=async function(){if(q==="SELECT value FROM research_settings WHERE key='crossref_http_cooldown'"&&++cooldownReads===2)return {value:new Date(Date.now()+60000).toISOString()};return first.call(this)};return statement};globalThis.fetch=async()=>{net++;throw Error('must not fetch during raced cooldown')};const r:any=await syncSource(f.db,additions[0]!,1);assert.match(r.error,/shared cooldown/);assert.equal(net,0);assert.equal(r.crossref.lastHeadAttemptAt,null);assert.equal((await f.db.prepare("SELECT value FROM research_settings WHERE key='crossref_http_lock'").first()),null)}finally{globalThis.fetch=originalFetch;f.sql.close()}});

test('Crossref 503 consumes exactly one reserved page attempt without hidden HTTP retries',async()=>{const f=fixture(),original=globalThis.fetch;let net=0;try{await initResearch(f.db);globalThis.fetch=async()=>{net++;return new Response('',{status:503})};const r:any=await syncSource(f.db,additions[0]!,1);assert.equal(net,1);assert.equal(r.crossrefPages.length,1);assert.equal(r.crossref.cycle.pages,1);assert.ok(r.crossref.lastHeadAttemptAt);assert.match(r.error,/HTTP 503/)}finally{globalThis.fetch=original;f.sql.close()}});

test('slow checkpoint cannot erase the shared actual HTTP start spacing',async()=>{const f=fixture(),originalFetch=globalThis.fetch,originalPrepare=f.db.prepare;const starts:number[]=[];let slow=true;try{await initResearch(f.db);f.db.prepare=function(q:string){const statement=originalPrepare(q),run=statement.run;statement.run=async function(){if(slow&&q.startsWith('INSERT INTO research_settings')&&this.args[0]==='crossref:'+additions[0]!.id&&JSON.parse(this.args[1]).lastHeadAttemptAt){slow=false;await new Promise(r=>setTimeout(r,1300))}return run.call(this)};return statement};globalThis.fetch=async()=>{starts.push(Date.now());return Response.json({message:{items:[]}})};await syncSource(f.db,additions[0]!,1);await syncSource(f.db,additions[1]!,1);assert.equal(starts.length,2);assert.ok(starts[1]!-starts[0]!>=1100)}finally{globalThis.fetch=originalFetch;f.sql.close()}});
test('publisher RSS cannot redirect into Crossref outside its shared admission boundary',async()=>{const f=fixture(),original=globalThis.fetch;let crossref=0;try{await initResearch(f.db);globalThis.fetch=async(url:any)=>{if(new URL(String(url)).hostname==='api.crossref.org'){crossref++;return Response.json({message:{items:[]}})}await f.db.prepare("INSERT INTO research_settings(key,value) VALUES('crossref_http_cooldown',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").bind(new Date(Date.now()+60000).toISOString()).run();return new Response('',{status:302,headers:{location:'https://api.crossref.org/redirected-feed'}})};const r:any=await syncSource(f.db,RESEARCH_SOURCES[0]!,1);assert.equal(crossref,1);assert.equal(r.rssStatus,'unavailable');assert.ok(r.warnings.some((s:string)=>s.includes('not an allowed feed')))}finally{globalThis.fetch=original;f.sql.close()}});
