import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {seal} from './ai/security.ts';
import {dailyWindow,localHour,readingScore,prepareDailyPapers,parseDailyOutput,hanCount,DAILY_LIMITS} from './daily-domain.ts';
import {startBatch,finishBatch,previousCoverage} from './research-batches.ts';
import {prepareDaily,generateDaily,dailyRead} from './research-daily.ts';
import {savePaper,researchApi} from './research.ts';
const quote='We compared TCAD device simulations with measurements of interface traps in GAA transistors.';
const abstract=quote+' The mechanism explains differences between model predictions and experimental observations. Methods and comparisons are explicitly described but independent reproducibility is not established by this abstract.';
const parts=['研究围绕栅全环晶体管的界面陷阱问题展开，通过器件仿真与测量结果进行比较，考察模型预测和实验观察之间的差异，摘要将这些差异与所讨论的输运机理联系起来。','方法层面以器件仿真结果和实验测量作为比较对象，摘要明确说明采用了这种对照方式，因此可以把本项工作的进展理解为对模型与观察差异的解释，而非已经确认性能提升。','证据范围仍限于摘要中披露的方法及比较观察，摘要没有建立独立可重复性的结论；阅读时应继续核对全文中具体的实验条件、模型设定和比较过程，避免把摘要描述扩展为已经验证的普遍结论。'];
const p=(id='a',extra:any={})=>({id,doi:'10.9999/'+id,title:'TCAD interface traps in GAA transistors',url:'https://doi.org/10.9999/'+id,publisher:'IEEE',journal:'Test',sourceId:'ieee-ted',issn:'0018-9383',publishedAt:'2026-10-01',datePrecision:'day',authors:[],affiliations:[],abstract,keywords:[],provenance:{abstract:'crossref'},sourceIndexedAt:null,discovery:'crossref',priority:90,ruleVersion:'fixture-rule',reasons:['fixture'],...extra});
function fixture(){const sql=new DatabaseSync(':memory:');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+file,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(ss:any[]){sql.exec('BEGIN');try{const r=ss.map(s=>s.runSync());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,env:{DB:db,HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)}}}
async function settings(f:any,limit=30,endpoint='https://api.deepseek.com'){const secret=await seal('UNIT_TEST_NOT_REAL',f.env,'owner|'+endpoint);await f.db.prepare("INSERT INTO ai_settings(owner_id,endpoint,model,protocol,reasoning,key_ciphertext,enabled,daily_limit,max_tokens,revision,updated_at,test_status) VALUES('owner',?,'configured-current-model','responses','max',?,1,?,384000,1,?,'ok')").bind(endpoint,secret,limit,new Date().toISOString()).run()}
async function member(f:any,id='a',batch='2026-10-02/08',first='2026-10-02T00:05:00Z',extra:any={}){return savePaper(f.db,p(id,extra),first,{runId:'run-'+id,batchKey:batch})}
function output(input:any){return JSON.stringify({groups:input.groups.map((g:any)=>({id:g.id,status:'complete',sentences:parts.map((text,i)=>({text,paperId:g.papers[i%g.papers.length].id,quote:i===0?quote:i===1?'Methods and comparisons are explicitly described':'independent reproducibility is not established by this abstract.'}))}))})}
function response(input:any){return Response.json({output:[{type:'message',content:[{type:'output_text',text:output(input)}]}],usage:{input_tokens:100,output_tokens:400,total_tokens:500}})}
const at=new Date('2026-10-03T00:01:00Z');
test('UTC+08 prior-day window handles midnight, year and leap boundaries, fixed cutoff and only 08 hour',()=>{const w=dailyWindow(at);assert.equal(w.sourceDate,'2026-10-02');assert.equal(w.start,'2026-10-01T16:00:00.000Z');assert.equal(w.cutoff,'2026-10-02T16:00:00.000Z');assert.deepEqual(w.batchKeys,['2026-10-02/08','2026-10-02/20']);assert.equal(dailyWindow(new Date('2026-12-31T16:00:00Z')).sourceDate,'2026-12-31');assert.equal(dailyWindow(new Date('2024-03-01T00:00:00Z')).sourceDate,'2024-02-29');assert.equal(localHour(at),8);assert.throws(()=>dailyWindow(at,'2026-02-30'))});
test('canonical reading priority strictly >75, not relevance/AI/quality/JIF; dedupe and honest evidence/capacity counts',()=>{const prepared=prepareDailyPapers([p('a',{priority:75,relevance:100,importanceScore:100}),p('b',{priority:76}),p('c',{priority:99,abstract:null}),p('d',{priority:null}),p('b',{priority:76})]);assert.equal(prepared.counts.newPapers,4);assert.equal(prepared.counts.eligible,2);assert.equal(prepared.counts.unresolvedScores,1);assert.equal(prepared.counts.missingAbstract,1);assert.equal(prepared.groups.length,1);assert.equal(readingScore(p()).field,'research_papers.priority');assert.equal(prepareDailyPapers(Array.from({length:250},(_,i)=>p('p'+i))).counts.capacityDeferred,10)});
test('complete output requires 200–300 Han, all expected sources, exact per-sentence quotes, no unsupported number',()=>{assert.ok(hanCount(parts.join(''))>=200&&hanCount(parts.join(''))<=300);const input={groups:[{id:'g',papers:[p()],keyword:'TCAD'}]},valid=JSON.parse(output(input));assert.equal(parseDailyOutput(JSON.stringify(valid),input.groups)[0].status,'completed');for(const edit of [(v:any)=>v.groups[0].sentences[0].quote='An invented quotation not present in the source.',(v:any)=>v.groups[0].sentences[0].paperId='wrong',(v:any)=>v.groups[0].sentences[0].text+='提高了9999倍。',(v:any)=>v.groups[0].sentences.forEach((x:any)=>x.text='过短')]){const v=structuredClone(valid);edit(v);assert.equal(parseDailyOutput(JSON.stringify(v),input.groups)[0].status,'failed')}assert.throws(()=>parseDailyOutput('{bad',input.groups));assert.throws(()=>parseDailyOutput(JSON.stringify({groups:[]}),input.groups));assert.equal(parseDailyOutput(JSON.stringify({groups:[{id:'g',status:'insufficient',reason:'缺少足够摘要证据'}]}),input.groups)[0].status,'insufficient')});
test('batch provenance records actual IDs, missing runs and sources; does not label untracked history complete',async()=>{const f=fixture();try{await startBatch(f.db,8,new Date('2026-10-02T00:00:00Z'));await f.db.prepare("INSERT INTO research_runs(id,started_at,finished_at,status,source_id,batch_key,details_json) VALUES('real-run','2026-10-02T00:00:00Z','2026-10-02T00:06:00Z','ok','ieee-ted','2026-10-02/08',?)").bind(JSON.stringify({rssStatus:'ok'})).run();await finishBatch(f.db,'2026-10-02/08',new Date('2026-10-02T00:07:00Z'));await savePaper(f.db,p('legacy'),'2026-10-02T01:00:00Z');const c=await previousCoverage(f.db,'2026-10-03');assert.equal(c.complete,false);assert.equal(c.batches[0].runs[0].id,'real-run');assert.equal(c.batches[0].attemptedSources,1);assert.equal(c.batches[1].status,'missing');assert.equal(c.untrackedNewPapers,1);await assert.rejects(startBatch(f.db,8,new Date('2026-10-02T12:00:00Z')),/窗口/)}finally{f.sql.close()}});
test('first-added membership survives updates; both prior slots included, today 08 and old-publication metadata updates excluded',async()=>{const f=fixture();try{const a=await member(f);await member(f,'b','2026-10-02/20','2026-10-02T12:04:00Z');await member(f,'today','2026-10-03/08','2026-10-03T00:00:00Z');await savePaper(f.db,p('old'),'2020-01-01T00:00:00Z');await savePaper(f.db,p('old',{abstract:abstract+' Updated metadata.'}),'2026-10-02T12:00:00Z',{runId:'update-only',batchKey:'2026-10-02/20'});await savePaper(f.db,p('a',{abstract:abstract+' Later today update.'}),'2026-10-03T00:00:00Z',{runId:'today-update',batchKey:'2026-10-03/08'});const r=await prepareDaily(f.db,'2026-10-03',at);const ids=JSON.parse(r.paper_ids_json);assert.equal(ids.length,2);assert.ok(ids.includes(a.id));const saved=JSON.parse((await f.db.prepare('SELECT input_json FROM research_daily_groups LIMIT 1').first()).input_json);assert.ok(!saved.papers[0].abstract.includes('Later today'));const count=(await f.db.prepare('SELECT count(*) n FROM research_daily_groups').first()).n;await member(f,'late','2026-10-02/20','2026-10-02T13:00:00Z');assert.equal((await prepareDaily(f.db,'2026-10-03',at)).content_hash,r.content_hash);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_daily_groups').first()).n,count)}finally{f.sql.close()}});
test('configured model, shared receipts/quota, frozen archive, per-group evidence and no repeated paid generation',async()=>{const f=fixture(),original=globalThis.fetch;let calls=0;try{await settings(f);await member(f);globalThis.fetch=async(_url:any,init:any)=>{calls++;const payload=JSON.parse(init.body);assert.equal(payload.model,'configured-current-model');assert.equal(payload.max_output_tokens,8192);assert.equal(payload.reasoning.effort,'max');assert.deepEqual(payload.tools,[]);return response(JSON.parse(payload.input[1].content))};const first=await generateDaily(f.db,f.env,{},undefined,at);assert.equal(calls,1);assert.equal(first.attempted,1);await generateDaily(f.db,f.env,{},undefined,at);assert.equal(calls,1);const read=await dailyRead(f.db,new URLSearchParams('date=2026-10-03&month=2026-10'),at);assert.equal(read.report.groups[0].status,'completed');assert.ok(read.report.groups[0].result.hanCharacters>=200);assert.equal(read.days.length,1);assert.equal(read.report.groups[0].papers[0].abstract,undefined);assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,1);assert.equal((await f.db.prepare('SELECT max_tokens FROM ai_settings').first()).max_tokens,384000)}finally{globalThis.fetch=original;f.sql.close()}});
test('budget and Kimi/untested/disabled stop before sending; 20:00 start cannot create or charge',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>{throw Error('must not send')};try{for(const reason of ['budget','kimi','untested','disabled']){const f=fixture();try{await settings(f,reason==='budget'?0:30,reason==='kimi'?'https://api.kimi.com/coding/v1':'https://api.deepseek.com');await member(f);if(reason==='untested')await f.db.prepare('UPDATE ai_settings SET test_status=NULL').run();if(reason==='disabled')await f.db.prepare('UPDATE ai_settings SET enabled=0').run();await generateDaily(f.db,f.env,{},undefined,at);assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0);assert.equal((await f.db.prepare('SELECT status FROM research_daily_groups').first()).status,'queued');await assert.rejects(generateDaily(f.db,f.env,{},undefined,new Date('2026-10-03T12:00:00Z')),/08:00/)}finally{f.sql.close()}}}finally{globalThis.fetch=original}});
test('unknown/invalid attempted outputs are terminal, quota-deferred groups can resume, older queues get priority',async()=>{const f=fixture(),original=globalThis.fetch;let calls=0;try{await settings(f);await member(f);globalThis.fetch=async()=>{calls++;throw Error('network')};await generateDaily(f.db,f.env,{},undefined,at);await generateDaily(f.db,f.env,{},undefined,at);assert.equal(calls,1);assert.equal((await f.db.prepare('SELECT status FROM research_daily_groups').first()).status,'unknown');await member(f,'tomorrow','2026-10-03/08','2026-10-03T00:00:00Z');globalThis.fetch=async(_u:any,init:any)=>{calls++;return response(JSON.parse(JSON.parse(init.body).input[1].content))};await generateDaily(f.db,f.env,{},undefined,new Date('2026-10-04T00:00:00Z'));assert.equal(calls,2);assert.equal((await f.db.prepare("SELECT status FROM research_daily WHERE date='2026-10-03'").first()).status,'needs_review')}finally{globalThis.fetch=original;f.sql.close()}});
test('empty/coverage-missing day is archived without a model request; GET chooses exactly one date and month',async()=>{const f=fixture();try{await settings(f);await generateDaily(f.db,f.env,{},undefined,at);const r=await dailyRead(f.db,new URLSearchParams('date=2026-10-03'),at);assert.equal(r.report.status,'incomplete');assert.equal(r.report.selection.eligible,0);assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0);assert.equal((await dailyRead(f.db,new URLSearchParams('date=2026-10-02'),at)).report,null);assert.equal((await dailyRead(f.db,new URLSearchParams('date=2026-02-30'),at)).invalidDate,true);assert.equal((await dailyRead(f.db,new URLSearchParams('month=2025-01'),at)).days.length,0);const denied=await researchApi(new Request('https://local.test/api/site/research/daily/generate',{method:'POST',headers:{origin:'https://evil.test'},body:'{}'}),f.env);assert.equal(denied.status,403)}finally{f.sql.close()}});
test('daily durable call cap survives repeated triggers; later 08 run resumes older queued groups without regenerating completed ones',async()=>{const f=fixture(),original=globalThis.fetch;let calls=0;try{await settings(f);for(let i=0;i<40;i++)await member(f,'many'+i);globalThis.fetch=async(_url:any,init:any)=>{calls++;return response(JSON.parse(JSON.parse(init.body).input[1].content))};const r=await generateDaily(f.db,f.env,{},undefined,at);assert.equal(calls,2);assert.ok(r.queue.queued>0);await generateDaily(f.db,f.env,{},undefined,at);assert.equal(calls,2);await generateDaily(f.db,f.env,{},undefined,new Date('2026-10-04T00:00:00Z'));assert.equal(calls,3);assert.equal((await f.db.prepare("SELECT count(*) n FROM research_daily_groups WHERE status='queued'").first()).n,0);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_daily').first()).n,2)}finally{globalThis.fetch=original;f.sql.close()}});
test('same-day enrichment can improve the frozen source; later-day and post-midnight changes cannot',async()=>{const f=fixture();try{const saved=await member(f,'enrich','2026-10-02/08','2026-10-02T00:05:00Z',{abstract:null});await savePaper(f.db,p('enrich',{abstract:abstract+' Evidence added same day.'}),'2026-10-02T12:00:00Z',{runId:'enriched',batchKey:'2026-10-02/20'});await savePaper(f.db,p('enrich',{abstract:abstract+' Past cutoff update.'}),'2026-10-02T16:00:00Z',{runId:'late',batchKey:'2026-10-02/20'});const snapshot=JSON.parse((await f.db.prepare('SELECT snapshot_json FROM research_batch_members WHERE paper_id=?').bind(saved.id).first()).snapshot_json);assert.ok(snapshot.abstract.includes('Evidence added same day'));assert.ok(!snapshot.abstract.includes('Past cutoff'));await prepareDaily(f.db,'2026-10-03',at);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_daily_groups').first()).n,1)}finally{f.sql.close()}});

test('generation response reports missing coverage instead of a false complete success',async()=>{const f=fixture();try{await settings(f);const result=await generateDaily(f.db,f.env,{},undefined,at);assert.equal(result.status,'partial');assert.equal(result.report.status,'incomplete');assert.equal(result.report.coverageComplete,false);assert.equal(result.report.batches.length,2);assert.ok(result.report.batches.every((b:any)=>b.status==='missing'));assert.equal(result.attempted,0)}finally{f.sql.close()}});

test('home latest selects most recent persisted archive across month boundary, never synthesizes today or calls provider',async()=>{const f=fixture(),original=globalThis.fetch;globalThis.fetch=async()=>{throw Error('read must not call network')};try{await prepareDaily(f.db,'2026-09-30',new Date('2026-09-30T00:00:00Z'));const r=await dailyRead(f.db,new URLSearchParams('latest=1'),new Date('2026-10-03T00:00:00Z'));assert.equal(r.date,'2026-09-30');assert.equal(r.report.sourceDate,'2026-09-29');assert.equal(r.report.status,'incomplete');assert.equal(r.today,'2026-10-03');assert.equal((await dailyRead(f.db,new URLSearchParams('latest=1&date=2026-10-02'),at)).report,null);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,1)}finally{globalThis.fetch=original;f.sql.close()}});

test('daily archive/groups/work freeze roll back together on failure; existing archived work repairs idempotently and cannot block later day',async()=>{
 const f=fixture();try{await settings(f);await member(f);f.sql.prepare("INSERT INTO research_daily_work(date,source_date,status,created_at,updated_at) VALUES('2026-10-03','2026-10-02','pending','fixture','fixture')").run();f.sql.exec("CREATE TRIGGER injected_freeze_failure BEFORE UPDATE OF status ON research_daily_work WHEN NEW.status='frozen' BEGIN SELECT RAISE(ABORT,'injected_freeze_failure'); END");await assert.rejects(prepareDaily(f.db,'2026-10-03',at),/injected_freeze_failure/);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,0);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_daily_groups').get()!.n,0);assert.equal(f.sql.prepare('SELECT status FROM research_daily_work').get()!.status,'pending');f.sql.exec('DROP TRIGGER injected_freeze_failure');const first=await prepareDaily(f.db,'2026-10-03',at);assert.equal(f.sql.prepare('SELECT status FROM research_daily_work').get()!.status,'frozen');f.sql.prepare("UPDATE research_daily_work SET status='pending'").run();const again=await prepareDaily(f.db,'2026-10-03',at);assert.equal(again.content_hash,first.content_hash);assert.equal(f.sql.prepare('SELECT status FROM research_daily_work').get()!.status,'frozen');f.sql.prepare("UPDATE research_daily_work SET status='pending'").run();f.sql.prepare('UPDATE ai_settings SET enabled=0').run();const later=await generateDaily(f.db,f.env,{},undefined,new Date('2026-10-04T00:00:00Z'));assert.equal(later.date,'2026-10-04');assert.equal(f.sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,2);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);
 }finally{f.sql.close();}
});
