import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {monthWindow,PIPELINE_VERSION} from './research-pipeline.ts';
import {prepareCrossref,nextCrossrefPage,reserveCrossrefPage,markCrossrefAttempt,crossrefURL,commitCrossrefPage,crossrefSummary,collectionCycle,type CrossrefState} from './research-crossref.ts';
import {collectResearch} from './research-refresh-plan.ts';
import {initResearch,syncSource,researchStatus} from './research.ts';
import {RESEARCH_SOURCES,RESEARCH_PAGE_BUDGET} from './research-config.ts';
const t='2026-10-04T00:00:00.000Z',later='2026-10-04T12:00:00.000Z';
const prepare=(raw:any=null,at=t,legacy:any={},window:any={})=>prepareCrossref(raw,legacy,window,monthWindow(new Date(at)),at,null);
function page(state:CrossrefState,n=100,cursor='next',at=t){const job=nextCrossrefPage(state)!;assert.ok(job);reserveCrossrefPage(state,job,at);markCrossrefAttempt(state,job,at);commitCrossrefPage(state,job,n,cursor,at,[]);return job;}
test('new slot always has a fresh indexed-desc head even with fresh and legacy cursors pending',()=>{
 const {state}=prepare(null,t,{cursor:'old-history',window_start:'2026-09-03T00:00:00Z',window_end:'2026-10-03T00:43:40Z'},{version:PIPELINE_VERSION,startDate:'2026-09-03',endDate:'2026-10-03'});
 assert.equal(nextCrossrefPage(state)!.cursor,'*');const a=page(state,100,'fresh-a');assert.equal(a.lane,'latest');assert.equal(state.history[0]!.cursor,'old-history');
 page(state,100,'fresh-b');assert.equal(nextCrossrefPage(state),null);
 const next=prepare(state,later).state;const head=nextCrossrefPage(next)!;assert.equal(head.cursor,'*');assert.notEqual(head.id,a.id);const url=new URL(crossrefURL('1234-5678',head));assert.equal(url.searchParams.get('sort'),'indexed');assert.equal(url.searchParams.get('order'),'desc');assert.equal(next.latest[0]!.cursor,'fresh-b');
 page(next,100,'second-head',later);const history=nextCrossrefPage(next)!;assert.equal(history.cursor,'old-history');assert.equal(history.lane,'history');
});
test('out-of-order window completion cannot jump an unfinished latest watermark',()=>{let {state}=prepare();const a=page(state);state=prepare(state,later).state;page(state,0);assert.equal(state.latestWatermark,null);assert.equal(state.headCheckedThrough,later);assert.equal(state.latest[0]!.id,a.id);state.cycle.pages=1;state.continuationTurn=0;page(state,0);assert.equal(state.latestWatermark,later);});
test('full page without advancing cursor and failures keep query and watermark retryable',()=>{const {state}=prepare();const job=nextCrossrefPage(state)!;state.cycle.pages++;const before=crossrefURL('1234',job);assert.throws(()=>commitCrossrefPage(state,job,100,'*',t,[]),/did not advance/);assert.equal(crossrefURL('1234',nextCrossrefPage(state)!),before);assert.equal(state.latestWatermark,null);assert.equal(state.headCheckedThrough,null);state.cycle.pages++;assert.equal(nextCrossrefPage(state),null);assert.equal(nextCrossrefPage(prepare(state,later).state)!.cursor,'*');});
test('cursor continuation freezes all parameters across UTC+8 date changes',()=>{const {state}=prepare();page(state,100,'frozen');const frozen=crossrefURL('1234',state.latest[0]!);const next=prepare(state,'2026-10-04T16:00:00.000Z').state;assert.equal(crossrefURL('1234',next.latest[0]!),frozen);assert.ok(next.history.some(j=>j.pubTo==='2026-10-05'&&j.indexFrom===null));});
test('pre-indexed newly eligible publication gets a no-lower-index history query',()=>{let {state}=prepare();page(state,0);page(state,0);state=prepare(state,'2026-10-05T00:00:00.000Z').state;page(state,0);const job=nextCrossrefPage(state)!;assert.equal(job.reason,'new_publication_days');const url=new URL(crossrefURL('1234',job));assert.ok(!url.searchParams.get('filter')!.includes('from-index-date'));assert.equal(job.pubFrom,'2026-10-05');});
test('calendar clamp/slot UTC+8 semantics and unbatched compatibility stay bounded',()=>{assert.equal(collectionCycle('2026-10-03T23:59:59Z',null),'2026-10-03/20');assert.equal(collectionCycle(t,null),'2026-10-04/08');assert.equal(collectionCycle(later,null),'2026-10-04/20');assert.equal(prepare(null,'2024-03-31T00:00:00Z').state.latest[0]!.pubFrom,'2024-02-29');let {state}=prepare();page(state);page(state,0);state=prepare(state,'2026-10-04T00:10:00.000Z').state;assert.equal(nextCrossrefPage(state),null);assert.equal(state.cycle.pages,2);});
test('expired unfinished windows create explicit gaps; complete ledger entries omit raw cursors',()=>{let {state}=prepare();page(state);const laterState=prepare(state,'2026-12-05T00:00:00.000Z');state=laterState.state;assert.ok(laterState.events.some(e=>e.status==='expired_incomplete'));assert.ok(state.expiredIncomplete>0);assert.equal(state.watermarkBlocked,true);page(state,0);assert.equal(state.latestWatermark,null);assert.ok(!JSON.stringify(state.ledger).includes('"cursor"'));});
test('queue and ledger limits retain truthful cumulative gaps under extreme/unusual catchup',()=>{let {state}=prepare();for(let n=0;n<150;n++){const at=new Date(Date.parse(t)+n*1000).toISOString();state.cycle.key='test/'+n;state=prepareCrossref(state,{}, {},monthWindow(new Date(at)),at,null).state;page(state,100,'cursor-'+n,at);}assert.ok(state.latest.length<=64);assert.ok(state.history.length<=40);assert.ok(state.ledger.length<=128);assert.ok(state.expiredIncomplete>0);assert.equal(state.watermarkBlocked,true);});
test('legacy migration retains exact query, never treats old/incompatible query as complete',()=>{const old={cursor:'saved-old',window_start:'2026-09-03T00:00:00Z',window_end:'2026-10-03T00:43:40Z',watermark:'2026-09-03T00:00:00Z'},w={version:PIPELINE_VERSION,startDate:'2026-09-03',endDate:'2026-10-03'};const {state}=prepare(null,t,old,w);assert.equal(state.history[0]!.cursor,old.cursor);assert.equal(state.history[0]!.indexTo,old.window_end);assert.equal(state.latestWatermark,null);assert.equal(state.history[1]!.indexFrom,null);const invalid=prepare(null,t,old,{...w,version:'obsolete'});assert.equal(invalid.events[0]!.status,'discarded_incomplete');assert.equal(invalid.state.history[0]!.cursor,'*');});
test('32 source heads precede continuations; total35/source2 and continuation fairness',async()=>{const sources=Array.from({length:32},(_,i)=>({id:String(i).padStart(2,'0'),crossref:{lastContinuationAttemptAt:i<3?t:null}}));const calls:string[]=[];const result=await collectResearch(sources,async id=>{calls.push(id);return {sourceId:id,pending:true,status:'backfill_pending'}},{maxPagesPerSource:2,maxMs:260000});assert.equal(result.length,35);assert.equal(new Set(calls.slice(0,32)).size,32);for(const id of calls)assert.ok(calls.filter(x=>x===id).length<=2);assert.deepEqual(calls.slice(32),['03','04','05']);});
test('time budget and head attempt age rotate interrupted/failing sources',async()=>{let now=0;const sources=[{id:'recent',crossref:{headPlannedThrough:t}},{id:'never'},{id:'older',crossref:{headPlannedThrough:'2026-10-03'}}];const calls:string[]=[];await collectResearch(sources,async id=>{calls.push(id);now+=100;return {pending:true}},{maxPagesPerSource:2,maxMs:150,now:()=>now});assert.deepEqual(calls,['never','older']);});
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(items:any[]){sql.exec('BEGIN');try{const out=items.map(s=>s.runSync());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const record=(doi:string,title='GAA transistor device transport')=>({DOI:doi,type:'journal-article',title:[title],published:{'date-parts':[monthWindow().endDate.split('-').map(Number)]},abstract:'Actual deposited abstract.',author:[{given:'Researcher',family:'One',affiliation:[{name:'Institute'}]}]});
test('SQLite integration: failed head retries, DOI dedupe/update, checkpoint audits and budgets',async()=>{const f=fixture(),original=globalThis.fetch,source=RESEARCH_SOURCES[0]!;let lists=0,net=0;try{await initResearch(f.db);globalThis.fetch=async(url:any)=>{net++;const u=new URL(String(url));if(u.hostname==='api.crossref.org'){if(u.pathname.startsWith('/works/'))return Response.json({message:record(decodeURIComponent(u.pathname.slice(7)))});lists++;if(lists===1)throw Error('fixture connection failed');return Response.json({message:{items:[record('10.9999/retry')]}});}return new Response('<rss><channel/></rss>')};const failed:any=await syncSource(f.db,source,1);assert.equal(failed.status,'error');assert.equal(failed.crossref.latestWatermark,null);const retry:any=await syncSource(f.db,source,1);assert.equal(retry.added,1);assert.equal(retry.crossrefPages[0].head,true);assert.ok(retry.crossref.latestWatermark);const before=net;await syncSource(f.db,source,2);assert.equal(net,before);assert.equal(lists,2);const s:any=(await researchStatus(f.db)).sources.find((s:any)=>s.id===source.id);assert.equal(s.crossref.cycle.pages,2);assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0);const logs=(await f.db.prepare("SELECT metadata_json FROM runtime_logs WHERE event='collection_finished'").all()).results;assert.ok(logs.some((r:any)=>JSON.parse(r.metadata_json).latestPages===1));}finally{globalThis.fetch=original;f.sql.close()}});

test('unstarted publication catchups coalesce under scarce global continuation budget; started jobs stay frozen',()=>{let {state}=prepare();const baseline=state.history[0]!;baseline.pages=1;baseline.cursor='started';const frozen=JSON.stringify(baseline);for(let day=5;day<20;day++)state=prepare(state,`2026-10-${String(day).padStart(2,'0')}T00:00:00.000Z`).state;assert.equal(state.history.length,2);assert.equal(JSON.stringify(state.history[0]),frozen);assert.equal(state.history[1]!.pubFrom,'2026-10-05');assert.equal(state.history[1]!.pubTo,'2026-10-19');assert.equal(state.history[1]!.cursor,'*');});

test('stale/alternating batch keys cannot reopen the same canonical slot budget',()=>{let {state}=prepare(null,later);for(const batchKey of ['2026-10-04/20','2026-10-04/08',null,'2026-10-04/20']){state=prepareCrossref(state,{}, {},monthWindow(new Date(later)),later,batchKey).state;while(nextCrossrefPage(state))page(state,100,'cursor-'+state.cycle.pages,later);assert.equal(state.cycle.pages,2);}assert.equal(state.latest[0]!.pages,2);});
test('shared persistent 35-page slot cap applies across sources and orchestration restarts',async()=>{const f=fixture(),original=globalThis.fetch;let lists=0;try{await initResearch(f.db);globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'){lists++;return Response.json({message:{items:[]}})}return new Response('<rss><channel/></rss>')};for(const source of RESEARCH_SOURCES)await syncSource(f.db,source,1);assert.equal(lists,RESEARCH_SOURCES.length);for(const source of RESEARCH_SOURCES)await syncSource(f.db,source,1);assert.equal(lists,RESEARCH_PAGE_BUDGET);const row=await f.db.prepare("SELECT value FROM research_settings WHERE key LIKE 'collection-budget:%'").first();assert.equal(row.value,String(RESEARCH_PAGE_BUDGET));for(const source of RESEARCH_SOURCES)await syncSource(f.db,source,2);assert.equal(lists,RESEARCH_PAGE_BUDGET);}finally{globalThis.fetch=original;f.sql.close()}});
test('failed durable checkpoint cannot expose an advanced watermark and safe retry is idempotent',async()=>{const f=fixture(),original=globalThis.fetch,prepareDB=f.db.prepare,source=RESEARCH_SOURCES[0]!;let fail=true,lists=0;try{await initResearch(f.db);f.db.prepare=function(q:string){const statement=prepareDB(q),run=statement.run;statement.run=async function(){if(fail&&q.startsWith('INSERT INTO research_settings')&&this.args[0]==='crossref:'+source.id&&JSON.parse(this.args[1]).headCheckedThrough){fail=false;throw Error('fixture checkpoint write failed');}return run.call(this)};return statement;};globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'){lists++;return Response.json({message:{items:[record('10.9999/checkpoint')]}})}return new Response('<rss><channel/></rss>')};const failed:any=await syncSource(f.db,source);assert.equal(failed.status,'error');assert.equal(failed.crossref.latestWatermark,null);assert.equal(failed.crossref.headCheckedThrough,null);const persisted=JSON.parse((await f.db.prepare('SELECT value FROM research_settings WHERE key=?').bind('crossref:'+source.id).first()).value);assert.equal(persisted.latest[0].cursor,'*');assert.equal(persisted.latest[0].pages,0);const first=await f.db.prepare('SELECT first_seen FROM research_papers').first();const retried:any=await syncSource(f.db,source);assert.equal(retried.added,0);assert.equal(retried.updated,0);assert.ok(retried.crossref.latestWatermark);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_papers').first()).n,1);assert.equal((await f.db.prepare('SELECT first_seen FROM research_papers').first()).first_seen,first.first_seen);assert.ok(lists>=2);}finally{globalThis.fetch=original;f.sql.close()}});
