import {test} from 'node:test';
import assert from 'node:assert/strict';
import {runResearchSlot} from './research-slot.ts';
import {spawnSync} from 'node:child_process';
test('slot dispatch is serial, collection finishes before metadata/scoring/daily, no daily at 20',async()=>{let active=0,pages=0;const paths:string[]=[];const result=await runResearchSlot(async(path)=>{assert.equal(active++,0);paths.push(path);await Promise.resolve();active--;if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{pass:'head',nextSourceId:'fixture'}};if(path.endsWith('/sync'))return {crossrefPages:[{}],collectionControl:{stop:++pages===35,nextSourceId:'fixture',pass:pages<32?'head':'continuation'}};return path.endsWith('/finish')?{status:'ok',batchStatus:'finished'}:{status:'ok'};},20,()=>0);assert.equal(pages,35);assert.deepEqual(paths.slice(-3),['/api/site/research/batch/finish','/api/site/research/enrich','/api/site/research/process']);assert.equal(result.status,'ok');});
test('unknown sync/process/daily outcomes never replay or force-finish in-flight collection',async()=>{for(const failure of ['sync','process','daily/generate']){const paths:string[]=[];const result=await runResearchSlot(async(path)=>{paths.push(path);if(path.endsWith(failure))throw Error('network unknown');if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{pass:'head',nextSourceId:'fixture'}};if(path.endsWith('/sync'))return {collectionControl:{stop:true}};return path.endsWith('/finish')?{status:'ok',batchStatus:'finished'}:{status:'ok'};},8,()=>0);assert.equal(result.status,'unknown');assert.equal(paths.filter(p=>p.endsWith(failure)).length,1);if(failure==='sync')assert.ok(!paths.some(p=>p.endsWith('/finish')));}});
test('deadline retains server queue and finishes only after the awaited sync releases leases',async()=>{let time=0;const paths:string[]=[];await runResearchSlot(async(path)=>{paths.push(path);if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{pass:'head',nextSourceId:'fixture'}};if(path.endsWith('/sync')){time=440000;return {collectionControl:{pass:'head',nextSourceId:'fixture'}};}return path.endsWith('/finish')?{status:'ok',batchStatus:'finished'}:{status:'ok'};},8,()=>time);assert.equal(paths.filter(p=>p.endsWith('/sync')).length,1);assert.ok(paths.at(-1)!.endsWith('/finish'));assert.equal(paths.filter(p=>p.endsWith('/process')).length,1);});
test('08 preparation reduces the real available collection budget inside the unchanged 540s ceiling',async()=>{let time=0;const paths:string[]=[];const result=await runResearchSlot(async(path)=>{paths.push(path);if(path.endsWith('/enrich'))time+=80000;if(path.endsWith('/process'))time+=95000;if(path.endsWith('/daily/generate'))time+=100000;if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{pass:'head',nextSourceId:'fixture'}};if(path.endsWith('/sync')){time+=160000;return {collectionControl:{pass:'head',nextSourceId:'fixture'}};}return path.endsWith('/finish')?{status:'ok',batchStatus:'finished'}:{status:'ok'};},8,()=>time);assert.equal(result.preparationMs,275000);assert.equal(result.collectionBudgetMs,155000);assert.equal(paths.filter(p=>p.endsWith('/sync')).length,1);assert.ok(paths.at(-1)!.endsWith('/finish'));assert.ok(result.elapsedMs<=540000);});
test('stdin-only invalid service input terminates without echoing the synthetic credential',()=>{const token='SYNTHETIC_STDIN_SECRET_SENTINEL',r=spawnSync(process.execPath,['sites/run-research-slot.mjs'],{input:JSON.stringify({baseUrl:'https://unverified.example.org',allowedOrigins:[],token,slot:8})+'\n',encoding:'utf8',timeout:5000});assert.equal(r.status,2);assert.ok(!(r.stdout+r.stderr).includes(token));});

test('35 sync HTTP ceiling is independent of page debit; repeated busy/no-source responses stop dispatch',async()=>{for(const mode of ['zero_pages','busy','no_source']){let calls=0;const r=await runResearchSlot(async(path)=>{if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{nextSourceId:'source'}};if(path.endsWith('/sync')){calls++;return {status:mode==='busy'?'deferred':'ok',sourceId:'source',collectionControl:{nextSourceId:mode==='no_source'?null:'source'}};}return path.endsWith('/finish')?{batchStatus:'finished'}:{status:'ok'};},20,()=>0);assert.equal(calls,mode==='zero_pages'?35:1);assert.notEqual(r.status,'unknown');}});

test('HTTP-200 deferred/error finish never starts metadata or scoring; phase deferral prevents dependent dispatch',async()=>{for(const stage of ['finish','enrich','process']){const paths:string[]=[];const r=await runResearchSlot(async(path)=>{paths.push(path);if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{stop:true}};if(path.endsWith('/'+stage))return {status:'deferred',reason:'lock_busy',batchStatus:'running'};return path.endsWith('/finish')?{batchStatus:'finished'}:{status:'ok'};},stage==='process'?8:20,()=>0);if(stage==='finish')assert.ok(!paths.some(p=>p.endsWith('/enrich')||p.endsWith('/process')));if(stage==='enrich')assert.ok(!paths.some(p=>p.endsWith('/process')));if(stage==='process')assert.ok(!paths.some(p=>p.endsWith('/daily/generate')));assert.ok(['deferred','partial'].includes(r.status));}});

test('20 scoring starts only with at least 200s remaining, and finish stays awaited',async()=>{for(const elapsed of [340001,340000]){let time=0,scoring=0;const r=await runResearchSlot(async(path,body)=>{if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{stop:true}};if(path.endsWith('/finish'))return {batchStatus:'finished'};if(path.endsWith('/enrich'))time=elapsed;if(path.endsWith('/process')){scoring++;assert.ok(body.maxMs>=200000);}return {status:'ok'};},20,()=>time);assert.equal(scoring,elapsed===340000?1:0);assert.ok(r.elapsedMs!<=540000);}});

test('collection 429 stops every subsequent dispatch after safe lease-release finish',async()=>{const paths:string[]=[];const result=await runResearchSlot(async(path)=>{paths.push(path);if(path.endsWith('/start'))return {status:'running',batchKey:'fixture',collectionControl:{nextSourceId:'source'}};if(path.endsWith('/sync'))return {status:'error',sourceId:'source',collectionControl:{stop:true,reason:'crossref_rate_limit'}};return {batchStatus:'finished'};},20,()=>0);assert.equal(result.reason,'provider_cooldown');assert.equal(paths.at(-1),'/api/site/research/batch/finish');assert.equal(paths.length,3);});

test('native preflight and stdin time count inside the same 540s automation budget',async()=>{let calls=0;const result=await runResearchSlot(async()=>{calls++;return {};},20,()=>540000,0);assert.equal(calls,0);assert.equal(result.reason,'deadline');});

test('a previously finished slot with a durable 429 marker cannot open a new maintenance dispatch',async()=>{let calls=0;const result=await runResearchSlot(async()=>{calls++;return {status:'finished',batchKey:'fixture',collectionControl:{stop:true,reason:'crossref_cooldown'}};},20,()=>0);assert.equal(calls,1);assert.equal(result.reason,'provider_cooldown');});
