import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {PUBLISHERS,RESEARCH_SOURCES} from './research-config.ts';
import {fromCrossref,parsePublisherRSS,sourceAccepts,evaluate,fromOpenAlex,enrichPaper} from './research-domain.ts';
import {initResearch,savePaper,researchApi,syncSource} from './research.ts';
import {monthWindow} from './research-pipeline.ts';
const source=RESEARCH_SOURCES[0]!;
const record={type:'journal-article',DOI:'10.1109/TEST.2026.1',title:['TCAD analysis of GAA CMOS image sensor interface traps'],resource:{primary:{URL:'https://ieeexplore.ieee.org/document/1234/'}},author:[{given:'Alice',family:'Researcher',sequence:'first',affiliation:[{name:'Example University'}]},{given:'Bob',family:'Researcher',sequence:'additional',affiliation:[]}],published:{'date-parts':[[2026,10]]},subject:['Not author keywords'],indexed:{'date-time':'2026-09-29T12:00:00Z'}};
const liveRecord={...record,published:{'date-parts':[monthWindow().endDate.split('-').map(Number)]}};
const rss='<rss><channel><item><title>TCAD analysis of GAA CMOS image sensor interface traps</title><link>http://ieeexplore.ieee.org/document/1234</link><authors>Alice Researcher;Bob Researcher;</authors><description>Experimental device simulation of pinned photodiode trap mechanisms.</description><pubDate>Tue, 29 Sep 2026 12:00:00 GMT</pubDate></item><item><title>Table of Contents</title><description>null</description><link>https://ieeexplore.ieee.org/document/999</link></item></channel></rss>';
function database(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));return {sql,db:{prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},async run(){return {meta:{changes:Number(s.run(...this.args).changes)}}}}},async batch(statements:any[]){return Promise.all(statements.map(s=>s.run()))}}};}
test('realistic metadata does not invent keywords, dates, or correspondence',()=>{const p=fromCrossref(record,source)!;assert.deepEqual(p.keywords,[]);assert.equal(p.datePrecision,'month');assert.equal(p.publishedAt,'2026-10');assert.equal(p.authors[0]!.corresponding,null);const feed=parsePublisherRSS(rss,source);assert.equal(feed.length,1);assert.equal(feed[0]!.authors.length,2);assert.ok(feed[0]!.abstract?.includes('Experimental'));assert.equal(feed[0]!.url,p.url);assert.throws(()=>parsePublisherRSS('<html>Site Unavailable</html>',source));assert.throws(()=>parsePublisherRSS('<!DOCTYPE rss><rss/>',source));assert.ok(evaluate(p).relevance!>70)});
test('DOI/RSS dedupe and missing-field refresh preserve stored primary evidence',async()=>{const {db,sql}=database();await initResearch(db);const first=await savePaper(db,fromCrossref(record,source)!);const second=await savePaper(db,parsePublisherRSS(rss,source)[0]!);assert.equal(first.id,second.id);assert.equal(second.added,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);let p=second.paper;assert.equal(p.authors[0]!.affiliations[0],'Example University');assert.equal(p.provenance.abstract,'publisher-rss');const latest=await savePaper(db,fromCrossref(record,source)!);assert.equal(latest.paper.abstract,p.abstract);assert.equal(latest.paper.publishedAt,'2026-09-29');const extra=fromOpenAlex({id:'https://openalex.org/W1',doi:'https://doi.org/'+p.doi,authorships:[{raw_author_name:'Bob Researcher',author_position:'last',is_corresponding:true,raw_affiliation_strings:['Second University']}],keywords:[{display_name:'guessed'}]});p=enrichPaper(p,extra);assert.deepEqual(p.keywords,[]);assert.equal(p.authors[1]!.affiliations[0],'Second University');assert.equal(p.authors[1]!.corresponding,true);const response=await researchApi(new Request('https://local.test/api/site/research/papers?min=0&q=TCAD'),{DB:db});assert.equal((await response.json()).total,1);const csrf=await researchApi(new Request('https://local.test/api/site/research/sync',{method:'POST',headers:{origin:'https://evil.test'},body:'{}'}),{DB:db});assert.equal(csrf.status,403);sql.close()});
test('failed publisher RSS is not empty success; successful registry progress and authors persist',async()=>{const {db,sql}=database();await initResearch(db);const original=globalThis.fetch;globalThis.fetch=async (url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'&&u.pathname.startsWith('/works/'))return Response.json({message:liveRecord});if(u.hostname==='api.crossref.org')return Response.json({message:{items:[liveRecord],'next-cursor':'next'}});if(u.hostname==='api.openalex.org')return Response.json({results:[]});return new Response('<html>Site Unavailable</html>')};try{const result:any=await syncSource(db,source,1);assert.equal(result.status,'backfill_pending');assert.equal(result.rssStatus,'unavailable');assert.equal(result.added,1);const row=sql.prepare('SELECT * FROM research_sources WHERE id=?').get(source.id)!;assert.equal(row.watermark,null);assert.ok(result.crossref.latestWatermark);assert.ok(row.rss_error);assert.equal(row.cursor,null);const log=sql.prepare("SELECT * FROM runtime_logs WHERE event='collection_finished'").get()!;assert.equal(log.severity,'warning');assert.equal(log.outcome,'partial');assert.equal(JSON.parse(String(log.metadata_json)).rssOk,false);assert.equal(sql.prepare("SELECT count(*) n FROM runtime_logs WHERE event='collection_started'").get()!.n,1)}finally{globalThis.fetch=original;sql.close()}});

test('Elsevier bibliographic RSS descriptions are not abstracts',()=>{const p=parsePublisherRSS('<rss><channel><item><title>A GAA transistor process</title><link>https://www.sciencedirect.com/science/article/pii/S123456?dgcid=rss_sd_all</link><description>Publication date: 16 December 2026 Source: Journal, Volume 12 Author(s): Alice Researcher, Bob Researcher</description></item></channel></rss>',RESEARCH_SOURCES[6]!)[0]!;assert.equal(p.abstract,null);assert.equal(p.authors.length,2);assert.equal(p.publishedAt,'2026-12-16');assert.ok(!p.url.includes('dgcid'));});

test('Wiley bibliographic descriptions never replace abstracts and ordered names are separated',()=>{const s=RESEARCH_SOURCES[3]!;const p=parsePublisherRSS('<rss><channel><item><title>A ferroelectric transistor</title><link>https://advanced.onlinelibrary.wiley.com/doi/10.1002/example</link><dc:creator>Alice Researcher, Bob Researcher</dc:creator><description>Advanced Electronic Materials, EarlyView.</description></item></channel></rss>',s)[0]!;assert.equal(p.abstract,null);assert.equal(p.authors.length,2);});

test('logic NAND gates are not mislabeled as NAND memory; common device plurals match',()=>{const p=fromCrossref(record,source)!;assert.ok(!evaluate({...p,title:'NAND logic functions in a ferroelectric device',abstract:null}).topics.includes('nand'));assert.ok(evaluate({...p,title:'FinFETs and GAAFETs scaling',abstract:null}).topics.includes('logic'));assert.ok(evaluate({...p,title:'Vertical NAND flash memory process',abstract:null}).topics.includes('nand'));});

const nature=RESEARCH_SOURCES.find(s=>s.id==='nature-electronics')!;
const science=RESEARCH_SOURCES.find(s=>s.id==='science-advances')!;
const natureRSS='<rdf:RDF><item><title>GAA transistor interface &lt;sub&gt;2&lt;/sub&gt; transport</title><link>https://www.nature.com/articles/s41928-026-test</link><content:encoded><![CDATA[<p>Nature Electronics, Published online: 02 October 2026; doi:10.1038/s41928-026-test</p><p>A publisher summary of transistor transport.</p>]]></content:encoded><dc:creator>Alice Researcher</dc:creator><dc:creator>Bob Researcher</dc:creator><dc:date>2026-10-02</dc:date><dc:identifier>doi:10.1038/s41928-026-test</dc:identifier><prism:doi>10.1038/s41928-026-test</prism:doi></item></rdf:RDF>';
test('verified journal manifest includes Nature and Science paper feeds, not Science news',()=>{assert.equal(RESEARCH_SOURCES.length,17);assert.equal(new Set(RESEARCH_SOURCES.map(s=>s.id)).size,17);assert.ok(PUBLISHERS.includes('Nature'));assert.ok(PUBLISHERS.includes('Science'));assert.equal(RESEARCH_SOURCES.find(s=>s.id==='science')!.rss,'https://feeds.science.org/rss/science-aop.xml');assert.equal(science.issn,'2375-2548');assert.ok(RESEARCH_SOURCES.filter(s=>s.publisher==='Nature'||s.publisher==='Science').every(s=>s.topicFilter&&s.initialDays===7&&s.verifiedAt==='2026-10-02'))});
test('Nature RDF preserves repeated authors, DOI and date while keeping publisher summary separate',()=>{const p=parsePublisherRSS(natureRSS,nature)[0]!;assert.equal(p.authors.length,2);assert.equal(p.doi,'10.1038/s41928-026-test');assert.equal(p.publishedAt,'2026-10-02');assert.equal(p.abstract,null);assert.equal(p.provenance.abstract,null);assert.equal(p.provenance.publisherSummary,'A publisher summary of transistor transport.');assert.ok(!p.title.includes('<sub>'));assert.deepEqual(p.affiliations,[]);assert.equal(p.authors[0]!.corresponding,null);assert.ok(sourceAccepts(p,nature));assert.ok(!sourceAccepts({...p,title:'An unrelated biological discovery',abstract:null},nature))});
test('Science Advances only promotes its explicit Abstract section, not a truncated teaser',()=>{const xml='<rss><channel><item><title>Ferroelectric memory endurance</title><link>https://www.science.org/doi/10.1126/sciadv.test</link><description>A teaser...</description><content:encoded><![CDATA[<section id="abstract"><h2>Abstract</h2><p>We measured ferroelectric memory endurance over repeated cycles.</p></section><section id="body">Not an abstract</section>]]></content:encoded><pubDate>Fri, 02 Oct 2026 00:00:00 GMT</pubDate></item></channel></rss>';const p=parsePublisherRSS(xml,science)[0]!;assert.equal(p.abstract,'We measured ferroelectric memory endurance over repeated cycles.');assert.equal(p.provenance.publisherSummary,'A teaser...');assert.equal(p.doi,'10.1126/sciadv.test');assert.equal(p.authors.length,0);const first=parsePublisherRSS(xml.replace(/<content:encoded>[\s\S]*?<\/content:encoded>/,''),RESEARCH_SOURCES.find(s=>s.id==='science')!)[0]!;assert.equal(first.abstract,null)});
test('RSS updated-only and imprecise/invalid dates do not become fabricated publication days',()=>{for(const date of ['2026-02-30','2026-01-99'])assert.equal(parsePublisherRSS(natureRSS.replace('2026-10-02</dc:date>',date+'</dc:date>'),nature)[0]!.publishedAt,null);const month=parsePublisherRSS(natureRSS.replace('2026-10-02</dc:date>','2026-10</dc:date>'),nature)[0]!;assert.equal(month.publishedAt,'2026-10');assert.equal(month.datePrecision,'month');const updated=parsePublisherRSS(natureRSS.replace('<dc:date>2026-10-02</dc:date>','<updated>2026-10-02</updated>'),nature)[0]!;assert.equal(updated.publishedAt,null);assert.equal(updated.provenance.feedUpdatedAt,'2026-10-02')});
test('source screening, cross-channel dedupe and both new publisher filters preserve real metadata',async()=>{const {db,sql}=database();await initResearch(db);const original=globalThis.fetch;globalThis.fetch=async(url:any,options:any)=>{assert.equal(new Headers(options.headers).get('authorization'),null);const u=new URL(String(url));if(u.hostname==='api.crossref.org'&&u.pathname.startsWith('/works/'))return Response.json({message:liveRecord});if(u.hostname==='api.crossref.org')return Response.json({message:{items:[{...liveRecord,DOI:'10.1038/s41928-026-test',title:['GAA transistor interface 2 transport'],abstract:'<jats:p>Actual deposited transistor abstract.</jats:p>'},{...liveRecord,DOI:'10.9999/unrelated',title:['Unrelated biology study']}],'next-cursor':'next'}});if(u.hostname==='api.openalex.org')return Response.json({results:[]});return new Response(natureRSS)};try{const result:any=await syncSource(db,nature,1);assert.equal(result.added,1);assert.equal(result.filteredOut,1);assert.equal(result.pending,true);assert.equal(result.rssStatus,'ok');const row=sql.prepare('SELECT * FROM research_papers').get()!;assert.equal(row.abstract,'Actual deposited transistor abstract.');assert.equal(JSON.parse(String(row.authors_json))[0].affiliations[0],'Example University');assert.equal((await (await researchApi(new Request('https://local.test/api/site/research/papers?publisher=Nature&min=0'),{DB:db})).json()).total,1);assert.equal((await (await researchApi(new Request('https://local.test/api/site/research/papers?publisher=Science&min=0'),{DB:db})).json()).total,0)}finally{globalThis.fetch=original;sql.close()}});
test('long Retry-After does not retry early or advance Crossref watermark; public enrichment cooldown is shared',async()=>{const {db,sql}=database();await initResearch(db);const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'){calls++;return new Response('',{status:429,headers:{'retry-after':'60'}})}return new Response('<rss><channel/></rss>')};try{const r:any=await syncSource(db,science,1);assert.equal(calls,1);assert.equal(r.status,'error');assert.match(r.error,/HTTP 429/);assert.equal(r.channels.crossref,'failed');assert.equal(sql.prepare('SELECT watermark FROM research_sources WHERE id=?').get(science.id)!.watermark,null);let oa=0;globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'&&u.pathname.startsWith('/works/'))return Response.json({message:liveRecord});if(u.hostname==='api.crossref.org')return Response.json({message:{items:[liveRecord]}});if(u.hostname==='api.openalex.org'){oa++;return new Response('',{status:429,headers:{'retry-after':'3600'}})}return new Response('<rss><channel/></rss>')};const a:any=await syncSource(db,nature,1);const b:any=await syncSource(db,science,1);assert.equal(oa,1);assert.equal(a.channels.openalex,'unavailable');assert.equal(b.channels.openalex,'unavailable');assert.ok(sql.prepare("SELECT value FROM research_settings WHERE key='openalex_retry_after'").get());}finally{globalThis.fetch=original;sql.close()}});

test('exact dates survive imprecise publisher refresh and later precise registry dates can repair RSS month',async()=>{const {db,sql}=database();await initResearch(db);try{const base=fromCrossref({...record,DOI:'10.1038/s41928-026-test',title:['GAA transistor interface 2 transport'],'published-online':{'date-parts':[[2026,10,2]]}},nature)!;const monthly=parsePublisherRSS(natureRSS.replace('2026-10-02</dc:date>','2026-10</dc:date>'),nature)[0]!;await savePaper(db,base);let saved=await savePaper(db,monthly);assert.equal(saved.paper.publishedAt,'2026-10-02');assert.equal(saved.paper.datePrecision,'day');const second={...monthly,doi:'10.9999/month-repair',url:'https://doi.org/10.9999/month-repair',title:'A different transistor study'};await savePaper(db,second);saved=await savePaper(db,{...base,doi:second.doi,url:second.url,title:second.title});assert.equal(saved.paper.publishedAt,'2026-10-02');assert.equal(saved.paper.datePrecision,'day');assert.equal(saved.paper.provenance.publishedAt,'crossref');}finally{sql.close()}});
test('final 429 Retry-After is preserved after an earlier short retry',async()=>{const {db,sql}=database();await initResearch(db);const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'&&u.pathname.startsWith('/works/'))return Response.json({message:liveRecord});if(u.hostname==='api.crossref.org')return Response.json({message:{items:[liveRecord]}});if(u.hostname==='api.openalex.org'){calls++;return new Response('',{status:429,headers:{'retry-after':calls===1?'0':'7200'}})}return new Response('<rss><channel/></rss>')};try{const before=Date.now();const r:any=await syncSource(db,nature,1);assert.equal(calls,2);assert.match(r.warnings.join(' '),/7200 seconds/);assert.ok(Date.parse(String(sql.prepare("SELECT value FROM research_settings WHERE key='openalex_retry_after'").get()!.value))-before>=7200000)}finally{globalThis.fetch=original;sql.close()}});

test('publisher Atom links use the final allowed redirect URL before persistence',async()=>{
 const {db,sql}=database();await initResearch(db);const original=globalThis.fetch;const s=RESEARCH_SOURCES.find(s=>s.id==='nature-electronics')!;
 const today=new Date().toISOString().slice(0,10);let redirected=false;
 globalThis.fetch=async(input:any)=>{const u=new URL(String(input));if(u.hostname==='api.crossref.org')return Response.json({message:{items:[]}});if(u.href===s.rss)return new Response(null,{status:302,headers:{location:'/news/final.xml'}});if(u.pathname==='/news/final.xml'){redirected=true;return new Response(`<feed xml:base="../papers/"><entry><title>GAA transistor transport mechanism</title><published>${today}</published><link href="upstream-atom-test"/></entry></feed>`);}throw Error('Unexpected mocked endpoint');};
 try{const result:any=await syncSource(db,s,1);assert.equal(result.rssStatus,'ok');assert.equal(redirected,true);const row=sql.prepare("SELECT url FROM research_papers WHERE title='GAA transistor transport mechanism'").get();assert.equal(row?.url,'https://www.nature.com/papers/upstream-atom-test');}finally{globalThis.fetch=original;sql.close();}
});
