import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {initResearch,syncSource,savePaper} from './research.ts';
import {queueMetadata,enrichMetadata,metadataChunks,metadataRequest} from './research-enrichment.ts';
import {collectionControl} from './research-collection-control.ts';
import {collectionCycle} from './research-crossref.ts';
import {RESEARCH_SOURCES} from './research-config.ts';
import {fromCrossref} from './research-domain.ts';
import {monthWindow} from './research-pipeline.ts';
import {seal} from './ai/security.ts';
import {credentialContext} from './scholarly/settings.ts';
import {SERVICES} from './scholarly/domain.ts';
import {prepareDaily} from './research-daily.ts';
import {finishBatch} from './research-batches.ts';
import {processRecent} from './research-processing.ts';
import {admitRun} from './research-lifecycle.ts';
import {preparationCohort} from './research-cohorts.ts';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db:any={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(items:any[]){sql.exec('BEGIN');try{const out=items.map(s=>s.runSync());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const source=RESEARCH_SOURCES[0]!,record=(doi:string,title='TCAD transistor transport')=>({DOI:doi,type:'journal-article',ISSN:source.issns,title:[title],published:{'date-parts':[monthWindow().endDate.split('-').map(Number)]},author:[{given:'Fixture',family:'Author'}]});
const env={HKIS_AI_ENCRYPTION_KEY:'a'.repeat(64)},abstract='TCAD transistor simulation measured device transport under controlled conditions. '.repeat(4);
async function configured(db:any,service:'openalex'|'semanticscholar'){const endpoint=SERVICES[service].endpoint,cipher=await seal('synthetic-test-key',env,credentialContext('fixture',service,endpoint));await db.prepare("INSERT INTO scholarly_settings(id,owner_id,service,endpoint,key_ciphertext,revision,updated_at,test_status) VALUES(?,?,?,?,?,1,?,'ok')").bind('fixture|'+service,'fixture',service,endpoint,cipher,new Date().toISOString()).run();}
const clearSpacing=(sql:any)=>sql.prepare("DELETE FROM research_settings WHERE key='crossref_http_next'").run();

test('32 successful heads precede at most 3 fair continuations; discovery sends zero enrichment calls',async()=>{
 const {sql,db}=fixture(),old=globalThis.fetch;let heads=0,extras=0;try{await initResearch(db);const started=new Date().toISOString(),key=collectionCycle(started,null),ids=RESEARCH_SOURCES.map(s=>s.id);sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,?,20,'running',?,?)").run(key,key.slice(0,10),JSON.stringify(ids),started);
 globalThis.fetch=async(input:any)=>{const u=new URL(String(input));if(u.hostname==='api.crossref.org'&&u.pathname.endsWith('/works')&&u.searchParams.get('cursor')){heads++;return Response.json({message:{items:Array.from({length:100},(_,i)=>record('10.9999/'+heads+'-'+i)),'next-cursor':'cursor-'+heads}});}if(u.hostname==='api.crossref.org'||u.hostname==='api.openalex.org'||u.hostname==='api.semanticscholar.org'){extras++;throw Error('unexpected enrichment');}return new Response('<rss><channel/></rss>');};
 const order:string[]=[];for(let n=0;n<35;n++){clearSpacing(sql);const control=await collectionControl(db,key);const s=RESEARCH_SOURCES.find(s=>s.id===control.nextSourceId)!;assert.ok(s,JSON.stringify(control));order.push(s.id);const result=await syncSource(db,s,1,key);assert.notEqual(result.status,'error',JSON.stringify(result));}
 assert.equal(new Set(order.slice(0,32)).size,32);assert.equal(order.length,35);assert.equal(heads,35);assert.equal(extras,0);assert.equal((await collectionControl(db,key)).reason,'page_budget');for(const id of ids)assert.ok(order.filter(s=>s===id).length<=2);
 assert.ok(sql.prepare('SELECT count(*) n FROM research_enrichment_queue').get()!.n>0);assert.equal(sql.prepare("SELECT count(*) n FROM research_papers WHERE metadata_status='pending' AND priority<>0").get()!.n,0);assert.equal(sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);
 }finally{globalThis.fetch=old;sql.close();}
});
test('all candidates survive queue capacity; missing abstract remains scope pending; deadline sends nothing',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;let calls=0;try{await initResearch(db);globalThis.fetch=async()=>{calls++;throw Error('forbidden')};const papers=Array.from({length:151},(_,i)=>fromCrossref(record('10.9999/retained'+i),source)!);await queueMetadata(db,papers,true);assert.equal(sql.prepare('SELECT count(*) n FROM research_enrichment_queue').get()!.n,151);const result=await enrichMetadata(db,{}, {maxMs:1});assert.equal(calls,0);assert.equal(result.reason,'deadline');assert.equal(sql.prepare('SELECT count(*) n FROM research_enrichment_queue WHERE scope_pending=1').get()!.n,151);}finally{globalThis.fetch=old;sql.close();}});
test('unified OpenAlex batch deduplicates DOI, matches IDs out of order, scores afterwards, and keeps frozen brief evidence',async()=>{
 const {sql,db}=fixture(),old=globalThis.fetch;let calls=0;try{await initResearch(db);await configured(db,'openalex');const papers=[fromCrossref(record('10.9999/batch-a'),source)!,fromCrossref(record('10.9999/batch-b','TCAD transistor interfaces'),source)!];
 for(const p of papers)await savePaper(db,p,new Date().toISOString(),{runId:'discovery',batchKey:null,deferScoring:true});await queueMetadata(db,[...papers,papers[0]!]);
 sql.prepare("INSERT INTO research_briefs(batch_key,date,slot,status,summary,evidence_json,content_hash,method,created_at,updated_at) VALUES('frozen','2026-10-10',20,'published','frozen','{}','frozen-hash','fixture','x','x')").run();
 globalThis.fetch=async(input:any)=>{const u=new URL(String(input));assert.equal(u.hostname,'api.openalex.org');calls++;assert.equal(u.searchParams.get('filter')!.split('|').length,2);return Response.json({results:[...papers].reverse().map((p,i)=>({id:'https://openalex.org/W'+(i+1),doi:'https://doi.org/'+p.doi,title:p.title,abstract_inverted_index:Object.fromEntries(abstract.split(' ').map((w,i)=>[w,[i]]))}))});};
 // Use a valid unique-position abstract index, avoiding duplicate token positions.
 globalThis.fetch=async(input:any)=>{const u=new URL(String(input));assert.equal(u.hostname,'api.openalex.org');calls++;assert.equal(u.searchParams.get('filter')!.split('|').length,2);const words=abstract.trim().split(/\s+/),index:Record<string,number[]>={};words.forEach((w,i)=>(index[w]??=[]).push(i));return Response.json({results:[...papers].reverse().map((p,i)=>({id:'https://openalex.org/W'+(i+1),doi:'https://doi.org/'+p.doi,title:p.title,abstract_inverted_index:index}))});};
 const result=await enrichMetadata(db,env);assert.equal(calls,1);assert.equal(result.ready,2);assert.equal(sql.prepare("SELECT count(*) n FROM research_papers WHERE metadata_status='ready' AND priority>0").get()!.n,2);assert.equal(sql.prepare('SELECT content_hash FROM research_briefs').get()!.content_hash,'frozen-hash');assert.equal(sql.prepare("SELECT count(*) n FROM research_runs WHERE phase='metadata' AND batch_key IS NULL AND status<>'running'").get()!.n,1);assert.equal(sql.prepare("SELECT count(*) n FROM research_settings WHERE key='lock:__metadata__'").get()!.n,0);
 await queueMetadata(db,papers.map(p=>({...p,abstract,provenance:{...p.provenance,abstract:'openalex'}})));await enrichMetadata(db,env);assert.equal(calls,1,'content version/cached terminal should avoid duplicate outbound');
 }finally{globalThis.fetch=old;sql.close();}
});
test('S2 uses only existing tested key and formal POST batch; null/current author affiliations never erase rich fields',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;let calls=0;try{await initResearch(db);await configured(db,'semanticscholar');const p=fromCrossref(record('10.9999/s2'),source)!;p.affiliations=['Publication Institute'];await queueMetadata(db,[p]);globalThis.fetch=async(input:any,options:any)=>{const u=new URL(String(input));assert.equal(u.pathname,'/graph/v1/paper/batch');assert.equal(options.method,'POST');assert.deepEqual(JSON.parse(options.body).ids,['DOI:'+p.doi]);assert.ok(!u.searchParams.get('fields')!.includes('affiliations'));calls++;return Response.json([{paperId:'a'.repeat(40),externalIds:{DOI:p.doi},title:p.title,abstract,authors:[{name:'Fixture Author',affiliations:['Current Institute']}]}]);};const result=await enrichMetadata(db,env);assert.equal(calls,1);assert.equal(result.ready,1);assert.equal(sql.prepare('SELECT affiliations_json FROM research_papers').get()!.affiliations_json,'["Publication Institute"]');assert.equal(sql.prepare("SELECT used FROM scholarly_usage WHERE service='semanticscholar'").get()!.used,1);}finally{globalThis.fetch=old;sql.close();}});
test('metadata 429 cooldown is durable; repeat run does not retry unknown transport or busy provider in-call',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;let calls=0;try{await initResearch(db);await configured(db,'openalex');await queueMetadata(db,[fromCrossref(record('10.9999/limited'),source)!]);globalThis.fetch=async()=>{calls++;return new Response('',{status:429,headers:{'retry-after':'3600'}});};const a=await enrichMetadata(db,env);assert.equal(a.status,'partial');assert.equal(calls,1);await enrichMetadata(db,env);assert.equal(calls,1);assert.ok(sql.prepare("SELECT cooldown_until FROM scholarly_usage WHERE service='openalex'").get()!.cooldown_until>Date.now());assert.equal(sql.prepare('SELECT status FROM research_enrichment_queue').get()!.status,'deferred');}finally{globalThis.fetch=old;sql.close();}});
test('long/special DOI chunks keep formal provider limits and encoded URL bounds',()=>{assert.equal(metadataChunks('openalex',Array.from({length:101},(_,i)=>'10.9999/a'+i)).flat().length,101);assert.ok(metadataChunks('openalex',Array.from({length:101},(_,i)=>'10.9999/a'+i)).every(c=>c.length<=100));const special='10.9999/a,b';assert.equal(metadataRequest('crossref',[special]).url,'https://api.crossref.org/works/10.9999%2Fa%2Cb');assert.ok(metadataChunks('crossref',Array.from({length:40},(_,i)=>'10.9999/'+('x'.repeat(100))+i)).every(c=>metadataRequest('crossref',c).url.length<=1800));});
test('prior-day new pipeline remains pending before enrichment, post-collection ready evidence keeps origin and frozen daily unchanged',async()=>{const {sql,db}=fixture();try{await initResearch(db);const date=new Date(Date.now()+8*3600000).toISOString().slice(0,10),first=new Date(Date.parse(date+'T00:00:00+08:00')-1000).toISOString(),cohort=collectionCycle(first,null),p=fromCrossref(record('10.9999/prior'),source)!;p.abstract=abstract;const saved=await savePaper(db,p,first,{runId:'original-run',batchKey:null,deferScoring:true});await queueMetadata(db,[p]);sql.prepare('UPDATE research_enrichment_queue SET daily_cohort_key=?,first_seen=?').run(cohort,first);const pending=await prepareDaily(db,date);assert.equal(pending.status,'pending_metadata');assert.equal(sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,0);await enrichMetadata(db,{}, {cohort:'previous_day'});sql.prepare("INSERT INTO ai_settings(owner_id,endpoint,model,protocol,reasoning,enabled,updated_at) VALUES('fixture','https://api.openai.com/v1','fixture-model','responses','low',0,?)").run(new Date().toISOString());const awaitingScore=await prepareDaily(db,date);assert.equal(awaitingScore.status,'pending_scoring');assert.equal(sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,0);await processRecent(db,{HKIS_OWNER_EMAIL:'fixture@example.org'},{maxPapers:0});const prepared=await prepareDaily(db,date);assert.notEqual(prepared.status,'pending_metadata');assert.equal(sql.prepare('SELECT first_seen FROM research_ready_evidence').get()!.first_seen,first);const hash=prepared.content_hash;await enrichMetadata(db,{}, {cohort:'previous_day'});assert.equal((await prepareDaily(db,date)).content_hash,hash);assert.equal(sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);}finally{sql.close();}});
test('pending metadata cannot enter script/AI analysis queue; only ready current cohort is scanned',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;try{await initResearch(db);sql.prepare("INSERT INTO ai_settings(owner_id,endpoint,model,protocol,reasoning,enabled,updated_at) VALUES('fixture','https://api.openai.com/v1','fixture-model','responses','low',0,?)").run(new Date().toISOString());const p=fromCrossref(record('10.9999/no-early-score'),source)!;p.abstract=abstract;await savePaper(db,p,new Date().toISOString(),{runId:'original',batchKey:null,deferScoring:true});globalThis.fetch=async()=>{throw Error('no model request allowed')};const result=await processRecent(db,{HKIS_OWNER_EMAIL:'fixture@example.org'},{maxPapers:0});assert.equal(result.scanned,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_analyses').get()!.n,0);await queueMetadata(db,[p]);await enrichMetadata(db,{});assert.equal((await processRecent(db,{HKIS_OWNER_EMAIL:'fixture@example.org'},{maxPapers:0,cohort:'current'})).scanned,1);assert.equal(sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);}finally{globalThis.fetch=old;sql.close();}});
test('scope_pending resolves after finish with original discovery run/time/cohort and cannot rewrite frozen brief',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;try{await initResearch(db);await configured(db,'openalex');const s=RESEARCH_SOURCES.find(s=>s.id==='nature-electronics')!,at=new Date().toISOString(),key=collectionCycle(at,null),raw={...record('10.9999/late-scope','An unexpected observation'),ISSN:s.issns};sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,?,20,'running',?,?)").run(key,key.slice(0,10),JSON.stringify([s.id]),at);globalThis.fetch=async(input:any)=>new URL(String(input)).hostname==='api.crossref.org'?Response.json({message:{items:[raw]}}):new Response('<rss><channel/></rss>');const discovery=await syncSource(db,s,1,key),queued=sql.prepare('SELECT * FROM research_enrichment_queue').get()!;const frozen=await finishBatch(db,key);const words=abstract.trim().split(/\s+/),index:Record<string,number[]>={};words.forEach((w,i)=>(index[w]??=[]).push(i));globalThis.fetch=async()=>Response.json({results:[{id:'https://openalex.org/W123',doi:raw.DOI,title:raw.title[0],abstract_inverted_index:index}]});await enrichMetadata(db,env,{batchKey:key});const member=sql.prepare('SELECT * FROM research_batch_members').get()!;assert.equal(member.run_id,discovery.runId);assert.equal(member.batch_key,key);assert.equal(member.first_seen,queued.first_seen);assert.equal(member.daily_cohort_key,queued.daily_cohort_key);assert.equal(sql.prepare('SELECT first_seen FROM research_papers').get()!.first_seen,queued.first_seen);assert.equal((await finishBatch(db,key)).brief.contentHash,frozen.brief.contentHash);assert.equal(sql.prepare('SELECT count(*) n FROM research_phase_events WHERE run_id=?').get(discovery.runId)!.n,1);}finally{globalThis.fetch=old;sql.close();}});
test('conflicting and malformed enrichment identifiers leave valid neighbors intact',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;try{await initResearch(db);await configured(db,'openalex');const papers=Array.from({length:3},(_,i)=>fromCrossref(record('10.9999/conflict'+i,'TCAD paper '+i),source)!);await queueMetadata(db,papers);const words=abstract.trim().split(/\s+/),index:Record<string,number[]>={};words.forEach((w,i)=>(index[w]??=[]).push(i));globalThis.fetch=async()=>Response.json({results:[{id:'https://openalex.org/W1',doi:papers[0]!.doi,title:papers[0]!.title},{id:'https://openalex.org/W2',doi:papers[0]!.doi,title:papers[0]!.title},{id:'invalid',doi:papers[1]!.doi,title:papers[1]!.title},{id:'https://openalex.org/W3',doi:papers[2]!.doi,title:papers[2]!.title,abstract_inverted_index:index}]});const result=await enrichMetadata(db,env);assert.equal(result.ready,1);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);assert.equal(sql.prepare("SELECT count(*) n FROM research_enrichment_queue WHERE status='deferred'").get()!.n,2);}finally{globalThis.fetch=old;sql.close();}});

test('metadata and collection admission exclude each other atomically, including manual source runs',async()=>{const {sql,db}=fixture();try{await initResearch(db);const now=new Date().toISOString(),collector=await admitRun(db,source.id,null,'fixture',now);assert.ok(collector);assert.equal(await admitRun(db,'__metadata__',null,'maintenance',now),null);sql.prepare("UPDATE research_runs SET status='ok' WHERE id=?").run(collector.id);sql.prepare('DELETE FROM research_settings WHERE key=?').run(collector.key);const maintenance=await admitRun(db,'__metadata__',null,'maintenance',now);assert.ok(maintenance);assert.equal(await admitRun(db,source.id,null,'fixture',now),null);assert.equal(sql.prepare("SELECT count(*) n FROM research_runs WHERE status='running'").get()!.n,1);}finally{sql.close();}});

test('429 ends the entire maintenance dispatch even when S2 is also configured',async()=>{const {sql,db}=fixture(),old=globalThis.fetch;let calls=0;try{await initResearch(db);await configured(db,'openalex');await configured(db,'semanticscholar');await queueMetadata(db,[fromCrossref(record('10.9999/no-fanout'),source)!]);globalThis.fetch=async(input:any)=>{assert.equal(new URL(String(input)).hostname,'api.openalex.org');calls++;return new Response('',{status:429,headers:{'retry-after':'120'}});};const result=await enrichMetadata(db,env);assert.equal(result.attempted,1);assert.equal(result.reason,'provider_cooldown');assert.equal(calls,1);assert.equal(sql.prepare("SELECT count(*) n FROM scholarly_usage WHERE service='semanticscholar'").get()!.n,0);}finally{globalThis.fetch=old;sql.close();}});

test('a ready subset never freezes the report while another original candidate or assessment remains pending; older attribution resumes',async()=>{const {sql,db}=fixture();try{await initResearch(db);const today=new Date(Date.now()+8*3600000).toISOString().slice(0,10),sourceDay=new Date(Date.parse(today+'T00:00:00Z')-2*86400000).toISOString().slice(0,10),date=new Date(Date.parse(sourceDay+'T00:00:00Z')+86400000).toISOString().slice(0,10),first=sourceDay+'T01:00:00.000Z';const p=fromCrossref(record('10.9999/ready-subset'),source)!;p.abstract=abstract;await savePaper(db,p,first,{runId:'original',batchKey:null,deferScoring:true});await queueMetadata(db,[p]);sql.prepare('UPDATE research_enrichment_queue SET first_seen=?,daily_cohort_key=?').run(first,sourceDay+'/08');sql.prepare("INSERT INTO research_daily_work(date,source_date,status,created_at,updated_at) VALUES(?,?,'pending',?,?)").run(date,sourceDay,first,first);await enrichMetadata(db,{}, {cohort:'previous_day'});const pending=fromCrossref(record('10.9999/pending-neighbor'),source)!;await queueMetadata(db,[pending],true,{runId:'original',batchKey:null});sql.prepare('UPDATE research_enrichment_queue SET first_seen=?,daily_cohort_key=? WHERE doi=?').run(first,sourceDay+'/08',pending.doi);assert.equal(await preparationCohort(db,today),sourceDay);assert.equal((await prepareDaily(db,date)).status,'pending_metadata');assert.equal(sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_daily_groups').get()!.n,0);assert.equal(sql.prepare('SELECT source_date FROM research_daily_work').get()!.source_date,sourceDay);sql.prepare("UPDATE research_enrichment_queue SET status='done' WHERE doi=?").run(pending.doi);sql.prepare("INSERT INTO ai_settings(owner_id,endpoint,model,protocol,reasoning,enabled,updated_at) VALUES('fixture','https://api.openai.com/v1','fixture-model','responses','low',0,?)").run(new Date().toISOString());assert.equal((await prepareDaily(db,date)).status,'pending_scoring');assert.equal((await processRecent(db,{HKIS_OWNER_EMAIL:'fixture@example.org'},{maxPapers:0,cohort:'previous_day'})).scanned,1);assert.equal((await prepareDaily(db,date)).status,'pending_scoring');sql.prepare("UPDATE research_analyses SET status='completed'").run();await prepareDaily(db,date);assert.equal(sql.prepare('SELECT count(*) n FROM research_daily').get()!.n,1);assert.equal(sql.prepare('SELECT status FROM research_daily_work').get()!.status,'frozen');assert.equal(sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);}finally{sql.close();}});
