import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {RESEARCH_SOURCES} from './research-config.ts';
import {fromCrossref,parsePublisherRSS,evaluate,fromOpenAlex,enrichPaper} from './research-domain.ts';
import {initResearch,savePaper,researchApi,syncSource} from './research.ts';
const source=RESEARCH_SOURCES[0]!;
const record={type:'journal-article',DOI:'10.1109/TEST.2026.1',title:['TCAD analysis of GAA CMOS image sensor interface traps'],resource:{primary:{URL:'https://ieeexplore.ieee.org/document/1234/'}},author:[{given:'Alice',family:'Researcher',sequence:'first',affiliation:[{name:'Example University'}]},{given:'Bob',family:'Researcher',sequence:'additional',affiliation:[]}],published:{'date-parts':[[2026,10]]},subject:['Not author keywords'],indexed:{'date-time':'2026-09-29T12:00:00Z'}};
const rss='<rss><channel><item><title>TCAD analysis of GAA CMOS image sensor interface traps</title><link>http://ieeexplore.ieee.org/document/1234</link><authors>Alice Researcher;Bob Researcher;</authors><description>Experimental device simulation of pinned photodiode trap mechanisms.</description><pubDate>Tue, 29 Sep 2026 12:00:00 GMT</pubDate></item><item><title>Table of Contents</title><description>null</description><link>https://ieeexplore.ieee.org/document/999</link></item></channel></rss>';
function database(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));return {sql,db:{prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},async run(){return {meta:{changes:Number(s.run(...this.args).changes)}}}}},async batch(statements:any[]){return Promise.all(statements.map(s=>s.run()))}}};}
test('realistic metadata does not invent keywords, dates, or correspondence',()=>{const p=fromCrossref(record,source)!;assert.deepEqual(p.keywords,[]);assert.equal(p.datePrecision,'month');assert.equal(p.publishedAt,'2026-10');assert.equal(p.authors[0]!.corresponding,null);const feed=parsePublisherRSS(rss,source);assert.equal(feed.length,1);assert.equal(feed[0]!.authors.length,2);assert.ok(feed[0]!.abstract?.includes('Experimental'));assert.equal(feed[0]!.url,p.url);assert.throws(()=>parsePublisherRSS('<html>Site Unavailable</html>',source));assert.throws(()=>parsePublisherRSS('<!DOCTYPE rss><rss/>',source));assert.ok(evaluate(p).relevance!>70)});
test('DOI/RSS dedupe and missing-field refresh preserve stored primary evidence',async()=>{const {db,sql}=database();await initResearch(db);const first=await savePaper(db,fromCrossref(record,source)!);const second=await savePaper(db,parsePublisherRSS(rss,source)[0]!);assert.equal(first.id,second.id);assert.equal(second.added,0);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);let p=second.paper;assert.equal(p.authors[0]!.affiliations[0],'Example University');assert.equal(p.provenance.abstract,'publisher-rss');const latest=await savePaper(db,fromCrossref(record,source)!);assert.equal(latest.paper.abstract,p.abstract);assert.equal(latest.paper.publishedAt,'2026-09-29');const extra=fromOpenAlex({id:'https://openalex.org/W1',doi:'https://doi.org/'+p.doi,authorships:[{raw_author_name:'Bob Researcher',author_position:'last',is_corresponding:true,raw_affiliation_strings:['Second University']}],keywords:[{display_name:'guessed'}]});p=enrichPaper(p,extra);assert.deepEqual(p.keywords,[]);assert.equal(p.authors[1]!.affiliations[0],'Second University');assert.equal(p.authors[1]!.corresponding,true);const response=await researchApi(new Request('https://local.test/api/site/research/papers?min=0&q=TCAD'),{DB:db});assert.equal((await response.json()).total,1);const csrf=await researchApi(new Request('https://local.test/api/site/research/sync',{method:'POST',headers:{origin:'https://evil.test'},body:'{}'}),{DB:db});assert.equal(csrf.status,403);sql.close()});
test('failed publisher RSS is not empty success; successful registry progress and authors persist',async()=>{const {db,sql}=database();await initResearch(db);const original=globalThis.fetch;globalThis.fetch=async (url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org')return Response.json({message:{items:[record],'next-cursor':'next'}});if(u.hostname==='api.openalex.org')return Response.json({results:[]});return new Response('<html>Site Unavailable</html>')};try{const result:any=await syncSource(db,source,1);assert.equal(result.status,'ok');assert.equal(result.rssStatus,'unavailable');assert.equal(result.added,1);const row=sql.prepare('SELECT * FROM research_sources WHERE id=?').get(source.id)!;assert.ok(row.watermark);assert.ok(row.rss_error);assert.equal(row.cursor,null);const log=sql.prepare("SELECT * FROM runtime_logs WHERE event='collection_finished'").get()!;assert.equal(log.severity,'warning');assert.equal(log.outcome,'partial');assert.equal(JSON.parse(String(log.metadata_json)).rssOk,false);assert.equal(sql.prepare("SELECT count(*) n FROM runtime_logs WHERE event='collection_started'").get()!.n,1)}finally{globalThis.fetch=original;sql.close()}});

test('Elsevier bibliographic RSS descriptions are not abstracts',()=>{const p=parsePublisherRSS('<rss><channel><item><title>A GAA transistor process</title><link>https://www.sciencedirect.com/science/article/pii/S123456?dgcid=rss_sd_all</link><description>Publication date: 16 December 2026 Source: Journal, Volume 12 Author(s): Alice Researcher, Bob Researcher</description></item></channel></rss>',RESEARCH_SOURCES[6]!)[0]!;assert.equal(p.abstract,null);assert.equal(p.authors.length,2);assert.equal(p.publishedAt,'2026-12-16');assert.ok(!p.url.includes('dgcid'));});

test('Wiley bibliographic descriptions never replace abstracts and ordered names are separated',()=>{const s=RESEARCH_SOURCES[3]!;const p=parsePublisherRSS('<rss><channel><item><title>A ferroelectric transistor</title><link>https://advanced.onlinelibrary.wiley.com/doi/10.1002/example</link><dc:creator>Alice Researcher, Bob Researcher</dc:creator><description>Advanced Electronic Materials, EarlyView.</description></item></channel></rss>',s)[0]!;assert.equal(p.abstract,null);assert.equal(p.authors.length,2);});

test('logic NAND gates are not mislabeled as NAND memory; common device plurals match',()=>{const p=fromCrossref(record,source)!;assert.ok(!evaluate({...p,title:'NAND logic functions in a ferroelectric device',abstract:null}).topics.includes('nand'));assert.ok(evaluate({...p,title:'FinFETs and GAAFETs scaling',abstract:null}).topics.includes('logic'));assert.ok(evaluate({...p,title:'Vertical NAND flash memory process',abstract:null}).topics.includes('nand'));});
