// Shared durable Crossref page-attempt cap; changing this requires owner approval.
export const RESEARCH_PAGE_BUDGET=35;
export const PUBLISHERS:string[]=['IEEE','Wiley','Elsevier','Nature','Science','IOP','ACS','AIP','SPIE'];
export type Publisher = 'IEEE'|'Wiley'|'Elsevier'|'Nature'|'Science'|'IOP'|'ACS'|'AIP'|'SPIE';
export interface JournalSource {id:string;publisher:Publisher;name:string;issn:string;issns?:string[];rss:string|null;homepage:string;topicFilter?:boolean;initialDays?:number;publisherName?:string;feedCoverage?:string;verifiedAt?:string}
export const RESEARCH_SOURCES:JournalSource[]=[
 {id:'ieee-ted',publisher:'IEEE',name:'IEEE Transactions on Electron Devices',issn:'0018-9383',rss:'https://ieeexplore.ieee.org/rss/TOC16.XML',homepage:'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=16'},
 {id:'ieee-edl',publisher:'IEEE',name:'IEEE Electron Device Letters',issn:'0741-3106',rss:'https://ieeexplore.ieee.org/rss/TOC55.XML',homepage:'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=55'},
 {id:'ieee-sensors',publisher:'IEEE',name:'IEEE Sensors Journal',issn:'1530-437X',rss:'https://ieeexplore.ieee.org/rss/TOC7361.XML',homepage:'https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7361'},
 {id:'wiley-aem',publisher:'Wiley',name:'Advanced Electronic Materials',issn:'2199-160X',rss:'https://onlinelibrary.wiley.com/feed/2199160x/most-recent',homepage:'https://advanced.onlinelibrary.wiley.com/journal/2199160x'},
 {id:'wiley-pssa',publisher:'Wiley',name:'physica status solidi (a)',issn:'1862-6300',rss:'https://onlinelibrary.wiley.com/feed/18626319/most-recent',homepage:'https://onlinelibrary.wiley.com/journal/18626319'},
 {id:'wiley-aom',publisher:'Wiley',name:'Advanced Optical Materials',issn:'2195-1071',rss:'https://onlinelibrary.wiley.com/feed/21951071/most-recent',homepage:'https://advanced.onlinelibrary.wiley.com/journal/21951071'},
 {id:'elsevier-sse',publisher:'Elsevier',name:'Solid-State Electronics',issn:'0038-1101',rss:'https://rss.sciencedirect.com/publication/science/00381101',homepage:'https://www.sciencedirect.com/journal/solid-state-electronics'},
 {id:'elsevier-mee',publisher:'Elsevier',name:'Microelectronic Engineering',issn:'0167-9317',rss:'https://rss.sciencedirect.com/publication/science/01679317',homepage:'https://www.sciencedirect.com/journal/microelectronic-engineering'},
 {id:'elsevier-sna',publisher:'Elsevier',name:'Sensors and Actuators A: Physical',issn:'0924-4247',rss:'https://rss.sciencedirect.com/publication/science/09244247',homepage:'https://www.sciencedirect.com/journal/sensors-and-actuators-a-physical'},
 {id:'nature',publisher:'Nature',name:'Nature',issn:'1476-4687',rss:'https://www.nature.com/nature.rss',homepage:'https://www.nature.com/',topicFilter:true,initialDays:7,publisherName:'Springer Nature',feedCoverage:'综合期刊；RSS 同时含新闻与评论',verifiedAt:'2026-10-02'},
 {id:'nature-electronics',publisher:'Nature',name:'Nature Electronics',issn:'2520-1131',rss:'https://www.nature.com/natelectron.rss',homepage:'https://www.nature.com/natelectron/',topicFilter:true,initialDays:7,publisherName:'Springer Nature',feedCoverage:'电子器件、存储、集成；滚动 RSS 范围有限',verifiedAt:'2026-10-02'},
 {id:'nature-photonics',publisher:'Nature',name:'Nature Photonics',issn:'1749-4893',rss:'https://www.nature.com/nphoton.rss',homepage:'https://www.nature.com/nphoton/',topicFilter:true,initialDays:7,publisherName:'Springer Nature',feedCoverage:'光电器件、探测与成像；按研究主题筛选',verifiedAt:'2026-10-02'},
 {id:'nature-nanotechnology',publisher:'Nature',name:'Nature Nanotechnology',issn:'1748-3395',rss:'https://www.nature.com/nnano.rss',homepage:'https://www.nature.com/nnano/',topicFilter:true,initialDays:7,publisherName:'Springer Nature',feedCoverage:'纳米器件与制造；排除无关方向',verifiedAt:'2026-10-02'},
 {id:'nature-materials',publisher:'Nature',name:'Nature Materials',issn:'1476-4660',rss:'https://www.nature.com/nmat.rss',homepage:'https://www.nature.com/nmat/',topicFilter:true,initialDays:7,publisherName:'Springer Nature',feedCoverage:'界面、介电、铁电与输运；按研究主题筛选',verifiedAt:'2026-10-02'},
 {id:'nature-communications',publisher:'Nature',name:'Nature Communications',issn:'2041-1723',rss:'https://www.nature.com/ncomms.rss',homepage:'https://www.nature.com/ncomms/',topicFilter:true,initialDays:7,publisherName:'Springer Nature',feedCoverage:'综合期刊；滚动 RSS 很短，以注册元数据增量为主',verifiedAt:'2026-10-02'},
 {id:'science',publisher:'Science',name:'Science',issn:'1095-9203',rss:'https://feeds.science.org/rss/science-aop.xml',homepage:'https://www.science.org/journal/science',topicFilter:true,initialDays:7,publisherName:'AAAS',feedCoverage:'First Release 仅含部分提前发表论文，非完整目录',verifiedAt:'2026-10-02'},
 {id:'science-advances',publisher:'Science',name:'Science Advances',issn:'2375-2548',rss:'https://feeds.science.org/rss/science-advances.xml',homepage:'https://www.science.org/journal/sciadv',topicFilter:true,initialDays:7,publisherName:'AAAS',feedCoverage:'综合期刊；TOC RSS 与注册元数据互补',verifiedAt:'2026-10-02'},
 {"id":"iop-sst","publisher":"IOP","name":"Semiconductor Science and Technology","issn":"0268-1242","issns":["0268-1242","1361-6641"],"homepage":"https://iopscience.iop.org/journal/0268-1242","publisherName":"IOP Publishing","feedCoverage":"半导体器件、界面、工艺与模拟；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"iop-jpd","publisher":"IOP","name":"Journal of Physics D: Applied Physics","issn":"0022-3727","issns":["0022-3727","1361-6463"],"homepage":"https://iopscience.iop.org/journal/0022-3727","publisherName":"IOP Publishing","feedCoverage":"应用物理、光电探测、新型器件与工艺；期刊级 Crossref，按主题筛选","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"elsevier-mr","publisher":"Elsevier","name":"Microelectronics Reliability","issn":"0026-2714","issns":["0026-2714","1872-941X"],"homepage":"https://www.sciencedirect.com/science/journal/00262714","publisherName":"Elsevier","feedCoverage":"器件可靠性、失效与缺陷机理；期刊级 Crossref，摘要可能缺失","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"elsevier-mssp","publisher":"Elsevier","name":"Materials Science in Semiconductor Processing","issn":"1369-8001","issns":["1369-8001","1873-4081"],"homepage":"https://www.sciencedirect.com/science/journal/13698001","publisherName":"Elsevier","feedCoverage":"半导体材料、介质界面与加工工艺；期刊级 Crossref，摘要可能缺失","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"acs-aelm","publisher":"ACS","name":"ACS Applied Electronic Materials","issn":"2637-6113","issns":["2637-6113"],"homepage":"https://pubs.acs.org/journal/aaembp","publisherName":"American Chemical Society","feedCoverage":"电子材料、晶体管、存储、介质与探测器；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"aip-apl","publisher":"AIP","name":"Applied Physics Letters","issn":"0003-6951","issns":["0003-6951","1077-3118"],"homepage":"https://pubs.aip.org/aip/apl","publisherName":"AIP Publishing","feedCoverage":"应用物理短报；仅匹配器件、界面和关注方向；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"spie-jm3","publisher":"SPIE","name":"Journal of Micro/Nanopatterning, Materials, and Metrology","issn":"2708-8340","issns":["2708-8340"],"homepage":"https://www.spiedigitallibrary.org/journals/journal-of-micro-nanopatterning-materials-and-metrology","publisherName":"SPIE","feedCoverage":"先进图形化、光刻、刻蚀、工艺整合与计量；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"aip-jap","publisher":"AIP","name":"Journal of Applied Physics","issn":"0021-8979","issns":["0021-8979","1089-7550"],"homepage":"https://pubs.aip.org/aip/jap","publisherName":"AIP Publishing","feedCoverage":"器件物理、输运、缺陷与建模；排除无关物理方向；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"aip-aed","publisher":"AIP","name":"APL Electronic Devices","issn":"2995-8423","issns":["2995-8423"],"homepage":"https://pubs.aip.org/aip/aed","publisherName":"AIP Publishing","feedCoverage":"未来 CMOS、新型存储、器件制造与模型；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"acs-nanoletters","publisher":"ACS","name":"Nano Letters","issn":"1530-6984","issns":["1530-6984","1530-6992"],"homepage":"https://pubs.acs.org/journal/nalefd","publisherName":"American Chemical Society","feedCoverage":"纳米电子器件与新材料；排除无关生物/能源方向；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id":"spie-jei","publisher":"SPIE","name":"Journal of Electronic Imaging","issn":"1017-9909","issns":["1017-9909","1560-229X"],"homepage":"https://www.spiedigitallibrary.org/journals/journal-of-electronic-imaging","publisherName":"SPIE","feedCoverage":"电子成像与传感器；不默认纳入纯图像算法；期刊级 Crossref，未配置已验证 RSS","rss":null,"topicFilter":true,"verifiedAt":"2026-10-07"},
 {"id": "aip-jvsta", "publisher": "AIP", "name": "Journal of Vacuum Science & Technology A", "issn": "0734-2101", "issns": ["0734-2101", "1520-8559"], "homepage": "https://pubs.aip.org/avs/jva", "publisherName": "AVS / AIP Publishing", "feedCoverage": "薄膜沉积、原子层工艺、等离子刻蚀与材料界面；期刊级 Crossref，RSS 正文尚未核实", "rss": null, "topicFilter": true, "verifiedAt": "2026-10-07"},
 {"id": "aip-jvstb", "publisher": "AIP", "name": "Journal of Vacuum Science & Technology B", "issn": "2166-2746", "issns": ["2166-2746", "2166-2754"], "homepage": "https://pubs.aip.org/avs/jvb", "publisherName": "AVS / AIP Publishing", "feedCoverage": "微纳制造、光刻、半导体器件与计量；只用当前刊号，不混入历史刊名，RSS 正文尚未核实", "rss": null, "topicFilter": true, "verifiedAt": "2026-10-07"},
 {"id": "acs-ami", "publisher": "ACS", "name": "ACS Applied Materials & Interfaces", "issn": "1944-8244", "issns": ["1944-8244", "1944-8252"], "homepage": "https://pubs.acs.org/journal/aamick", "publisherName": "American Chemical Society", "feedCoverage": "电子材料、薄膜、界面、器件与存储；保留主题过滤，排除无关生物/能源/催化内容；未配置已验证 RSS", "rss": null, "topicFilter": true, "verifiedAt": "2026-10-07"},
 {"id": "wiley-am", "publisher": "Wiley", "name": "Advanced Materials", "issn": "0935-9648", "issns": ["0935-9648", "1521-4095"], "homepage": "https://advanced.onlinelibrary.wiley.com/journal/15214095", "publisherName": "Wiley", "feedCoverage": "半导体、薄膜、传感、光电子功能材料；按主题筛选，排除无关生物/能源方向；未配置已验证 RSS", "rss": null, "topicFilter": true, "verifiedAt": "2026-10-07"},
];
export const TOPICS=[
 {id:'cis',label:'图像传感器 / CIS / PPD',weight:55,pattern:/\b(?:image sensors?|CMOS imag(?:e|ing)|pinned photodiodes?|single.photon avalanche|SPAD|event.based (?:vision|sensor)|pixel (?:noise|sensor))\b/i},
 {id:'noise',label:'RTS / RTN / 噪声与缺陷',weight:50,pattern:/\b(?:random telegraph|RTS noise|RTN|low.frequency noise|1\/f noise|dark current|interface traps?|trap.assisted|charge traps?)\b/i},
 {id:'logic',label:'先进逻辑器件',weight:45,pattern:/\b(?:FinFETs?|GAAFETs?|gate.all.around|nanosheets?|CFETs?|forksheet|complementary FET|negative capacitance|short.channel|MOSFETs?|field.effect transistors?)\b/i},
 {id:'dram',label:'DRAM',weight:50,pattern:/\b(?:DRAM|dynamic random.access memory|1T1C|1T.1C|capacitorless (?:memory|cell)|DRAM retention)\b/i},
 {id:'nand',label:'NAND / Flash',weight:50,pattern:/\b(?:NAND (?:flash|memor(?:y|ies))|3D NAND|three.dimensional NAND|vertical NAND|flash memor(?:y|ies)|charge.trap memor(?:y|ies)|floating.gate|word.line interference)\b/i},
 {id:'emerging',label:'新型器件与存储',weight:45,pattern:/\b(?:memrist(?:ors?|ive)|FeFETs?|ferroelectric|RRAM|ReRAM|resistive random.access|phase.change memor|spintronic|MRAM|magnetoresistive|tunnel FET|TFET|two.dimensional transistor|2D transistor|neuromorphic device)\b/i},
 {id:'tcad',label:'TCAD / 工艺器件仿真',weight:50,pattern:/\b(?:TCAD|technology computer.aided|device simulation|process simulation|drift.diffusion|Poisson.Schr[oö]dinger|Sentaurus|Silvaco|non.equilibrium Green)\b/i},
 {id:'process',label:'工艺与器件机理',weight:30,pattern:/\b(?:semiconductor|transistors?|photodiodes?|epitax(?:y|ial)|atomic.layer deposition|ion implantation|gate dielectric|gate stack|contact resistance|carrier transport|charge transport|hot.carrier|dielectric breakdown|etch(?:ing)?|lithograph(?:y|ic))\b/i},
];
export const RULE_VERSION='hkis-research-v1.1';
