import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {monthWindow,PIPELINE_VERSION} from './research-pipeline.ts';
import {prepareCrossref,nextCrossrefPage,reserveCrossrefPage,markCrossrefAttempt,crossrefURL,commitCrossrefPage,crossrefSummary,collectionCycle,type CrossrefState} from './research-crossref.ts';
import {collectResearch,collectResearchBatch} from './research-refresh-plan.ts';
import {initResearch,syncSource,researchStatus,researchApi} from './research.ts';
import {RESEARCH_SOURCES,RESEARCH_PAGE_BUDGET} from './research-config.ts';
const t='2026-10-04T00:00:00.000Z',later='2026-10-04T12:00:00.000Z';
const prepare=(raw:any=null,at=t,legacy:any={},window:any={})=>prepareCrossref(raw,legacy,window,monthWindow(new Date(at)),at,null);
function page(state:CrossrefState,n=100,cursor='next',at=t){const job=nextCrossrefPage(state)!;assert.ok(job);reserveCrossrefPage(state,job,at);markCrossrefAttempt(state,job,at);commitCrossrefPage(state,job,n,cursor,at,[]);return job;}
test('new slot always has a fresh indexed-desc head even with fresh and legacy cursors pending',()=>{
 const {state}=prepare(null,t,{cursor:'old-history',window_start:'2026-09-03T00:00:00Z',window_end:'2026-10-03T00:43:40Z'},{version:PIPELINE_VERSION,startDate:'2026-09-03',endDate:'2026-10-03'});
 assert.equal(nextCrossrefPage(state)!.cursor,'*');const a=page(state,100,'fresh-a');assert.equal(a.lane,'latest');assert.equal(state.history[0]!.cursor,'old-history');
 page(state,100,'fresh-b');assert.equal(nextCrossrefPage(state),null);
 const next=prepare(state,later).state;const head=nextCrossrefPage(next)!;assert.equal(head.cursor,'*');assert.notEqual(head.id,a.id);const url=new URL(crossrefURL('1234-5678',head));assert.equal(url.searchParams.get('sort'),'indexed');assert.equal(url.searchParams.get('order'),'desc');assert.equal(next.latest[0]!.cursor,'fresh-b');
 page(next,100,'second-head',later);const history=nextCrossrefPage(next)!;assert.equal(history.cursor,'old-history');assert.equal(history.lane,'history');
});
test('out-of-order window completion cannot jump an unfinished latest watermark',()=>{let {state}=prepare();const a=page(state);state=prepare(state,later).state;page(state,0);assert.equal(state.latestWatermark,null);assert.equal(state.headCheckedThrough,later);assert.equal(state.latest[0]!.id,a.id);state.cycle.pages=1;state.continuationTurn=0;page(state,0);assert.equal(state.latestWatermark,later);});
test('full page without advancing cursor and failures keep query and watermark retryable',()=>{const {state}=prepare();const job=nextCrossrefPage(state)!;state.cycle.pages++;const before=crossrefURL('1234',job);assert.throws(()=>commitCrossrefPage(state,job,100,'*',t,[]),/did not advance/);assert.equal(crossrefURL('1234',nextCrossrefPage(state)!),before);assert.equal(state.latestWatermark,null);assert.equal(state.headCheckedThrough,null);state.cycle.pages++;assert.equal(nextCrossrefPage(state),null);assert.equal(nextCrossrefPage(prepare(state,later).state)!.cursor,'*');});
test('cursor continuation freezes all parameters across UTC+8 date changes',()=>{const {state}=prepare();page(state,100,'frozen');const frozen=crossrefURL('1234',state.latest[0]!);const next=prepare(state,'2026-10-04T16:00:00.000Z').state;assert.equal(crossrefURL('1234',next.latest[0]!),frozen);assert.ok(next.history.some(j=>j.pubTo==='2026-10-05'&&j.indexFrom===null));});
test('pre-indexed newly eligible publication gets a no-lower-index history query',()=>{let {state}=prepare();page(state,0);page(state,0);state=prepare(state,'2026-10-05T00:00:00.000Z').state;page(state,0);const job=nextCrossrefPage(state)!;assert.equal(job.reason,'new_publication_days');const url=new URL(crossrefURL('1234',job));assert.ok(!url.searchParams.get('filter')!.includes('from-index-date'));assert.equal(job.pubFrom,'2026-10-05');});
test('calendar clamp/slot UTC+8 semantics and unbatched compatibility stay bounded',()=>{assert.equal(collectionCycle('2026-10-03T23:59:59Z',null),'2026-10-03/20');assert.equal(collectionCycle(t,null),'2026-10-04/08');assert.equal(collectionCycle(later,null),'2026-10-04/20');assert.equal(prepare(null,'2024-03-31T00:00:00Z').state.latest[0]!.pubFrom,'2024-02-29');let {state}=prepare();page(state);page(state,0);state=prepare(state,'2026-10-04T00:10:00.000Z').state;assert.equal(nextCrossrefPage(state),null);assert.equal(state.cycle.pages,2);});
test('expired unfinished windows create explicit gaps; complete ledger entries omit raw cursors',()=>{let {state}=prepare();page(state);const laterState=prepare(state,'2026-12-05T00:00:00.000Z');state=laterState.state;assert.ok(laterState.events.some(e=>e.status==='expired_incomplete'));assert.ok(state.expiredIncomplete>0);assert.equal(state.watermarkBlocked,true);page(state,0);assert.equal(state.latestWatermark,null);assert.ok(!JSON.stringify(state.ledger).includes('"cursor"'));});
test('queue and ledger limits retain truthful cumulative gaps under extreme/unusual catchup',()=>{let {state}=prepare();for(let n=0;n<150;n++){const at=new Date(Date.parse(t)+n*1000).toISOString();state.cycle.key='test/'+n;state=prepareCrossref(state,{}, {},monthWindow(new Date(at)),at,null).state;page(state,100,'cursor-'+n,at);}assert.ok(state.latest.length<=64);assert.ok(state.history.length<=40);assert.ok(state.ledger.length<=128);assert.ok(state.expiredIncomplete>0);assert.equal(state.watermarkBlocked,true);});
test('legacy migration retains exact query, never treats old/incompatible query as complete',()=>{const old={cursor:'saved-old',window_start:'2026-09-03T00:00:00Z',window_end:'2026-10-03T00:43:40Z',watermark:'2026-09-03T00:00:00Z'},w={version:PIPELINE_VERSION,startDate:'2026-09-03',endDate:'2026-10-03'};const {state}=prepare(null,t,old,w);assert.equal(state.history[0]!.cursor,old.cursor);assert.equal(state.history[0]!.indexTo,old.window_end);assert.equal(state.latestWatermark,null);assert.equal(state.history[1]!.indexFrom,null);const invalid=prepare(null,t,old,{...w,version:'obsolete'});assert.equal(invalid.events[0]!.status,'discarded_incomplete');assert.equal(invalid.state.history[0]!.cursor,'*');});
test('32 source heads precede continuations; total35/source2 and continuation fairness',async()=>{const sources=Array.from({length:32},(_,i)=>({id:String(i).padStart(2,'0'),crossref:{lastContinuationAttemptAt:i<3?t:null}}));const calls:string[]=[];const result=await collectResearch(sources,async id=>{calls.push(id);return {sourceId:id,pending:true,status:'backfill_pending'}},{maxPagesPerSource:2,maxMs:260000});assert.equal(result.length,35);assert.equal(new Set(calls.slice(0,32)).size,32);for(const id of calls)assert.ok(calls.filter(x=>x===id).length<=2);assert.deepEqual(calls.slice(32),['03','04','05']);});
test('time budget and head attempt age rotate interrupted/failing sources',async()=>{let now=0;const sources=[{id:'recent',crossref:{headPlannedThrough:t}},{id:'never'},{id:'older',crossref:{headPlannedThrough:'2026-10-03'}}];const calls:string[]=[];await collectResearch(sources,async id=>{calls.push(id);now+=100;return {pending:true}},{maxPagesPerSource:2,maxMs:150,now:()=>now});assert.deepEqual(calls,['never','older']);});
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(items:any[]){sql.exec('BEGIN');try{const out=items.map(s=>s.runSync());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const record=(doi:string,title='GAA transistor device transport')=>({DOI:doi,type:'journal-article',title:[title],published:{'date-parts':[monthWindow().endDate.split('-').map(Number)]},abstract:'Actual deposited abstract.',author:[{given:'Researcher',family:'One',affiliation:[{name:'Institute'}]}]});
test('SQLite integration: failed head retries, DOI dedupe/update, checkpoint audits and budgets',async()=>{const f=fixture(),original=globalThis.fetch,source=RESEARCH_SOURCES[0]!;let lists=0,net=0;try{await initResearch(f.db);globalThis.fetch=async(url:any)=>{net++;const u=new URL(String(url));if(u.hostname==='api.crossref.org'){if(u.pathname.startsWith('/works/'))return Response.json({message:record(decodeURIComponent(u.pathname.slice(7)))});lists++;if(lists===1)throw Error('fixture connection failed');return Response.json({message:{items:[record('10.9999/retry')]}});}return new Response('<rss><channel/></rss>')};const failed:any=await syncSource(f.db,source,1);assert.equal(failed.status,'error');assert.equal(failed.crossref.latestWatermark,null);const retry:any=await syncSource(f.db,source,1);assert.equal(retry.added,1);assert.equal(retry.crossrefPages[0].head,true);assert.ok(retry.crossref.latestWatermark);const before=net;await syncSource(f.db,source,2);assert.equal(net,before);assert.equal(lists,2);const s:any=(await researchStatus(f.db)).sources.find((s:any)=>s.id===source.id);assert.equal(s.crossref.cycle.pages,2);assert.equal((await f.db.prepare('SELECT count(*) n FROM ai_receipts').first()).n,0);const logs=(await f.db.prepare("SELECT metadata_json FROM runtime_logs WHERE event='collection_finished'").all()).results;assert.ok(logs.some((r:any)=>JSON.parse(r.metadata_json).latestPages===1));}finally{globalThis.fetch=original;f.sql.close()}});

test('unstarted publication catchups coalesce under scarce global continuation budget; started jobs stay frozen',()=>{let {state}=prepare();const baseline=state.history[0]!;baseline.pages=1;baseline.cursor='started';const frozen=JSON.stringify(baseline);for(let day=5;day<20;day++)state=prepare(state,`2026-10-${String(day).padStart(2,'0')}T00:00:00.000Z`).state;assert.equal(state.history.length,2);assert.equal(JSON.stringify(state.history[0]),frozen);assert.equal(state.history[1]!.pubFrom,'2026-10-05');assert.equal(state.history[1]!.pubTo,'2026-10-19');assert.equal(state.history[1]!.cursor,'*');});

test('stale/alternating batch keys cannot reopen the same canonical slot budget',()=>{let {state}=prepare(null,later);for(const batchKey of ['2026-10-04/20','2026-10-04/08',null,'2026-10-04/20']){state=prepareCrossref(state,{}, {},monthWindow(new Date(later)),later,batchKey).state;while(nextCrossrefPage(state))page(state,100,'cursor-'+state.cycle.pages,later);assert.equal(state.cycle.pages,2);}assert.equal(state.latest[0]!.pages,2);});
test('shared persistent 35-page slot cap applies across sources and orchestration restarts',async()=>{const f=fixture(),original=globalThis.fetch;let lists=0;try{await initResearch(f.db);globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'){lists++;return Response.json({message:{items:[]}})}return new Response('<rss><channel/></rss>')};for(const source of RESEARCH_SOURCES)await syncSource(f.db,source,1);assert.equal(lists,RESEARCH_SOURCES.length);for(const source of RESEARCH_SOURCES)await syncSource(f.db,source,1);assert.equal(lists,RESEARCH_PAGE_BUDGET);const row=await f.db.prepare("SELECT value FROM research_settings WHERE key LIKE 'collection-budget:%'").first();assert.equal(row.value,String(RESEARCH_PAGE_BUDGET));for(const source of RESEARCH_SOURCES)await syncSource(f.db,source,2);assert.equal(lists,RESEARCH_PAGE_BUDGET);}finally{globalThis.fetch=original;f.sql.close()}});
test('failed durable checkpoint cannot expose an advanced watermark and safe retry is idempotent',async()=>{const f=fixture(),original=globalThis.fetch,prepareDB=f.db.prepare,source=RESEARCH_SOURCES[0]!;let fail=true,lists=0;try{await initResearch(f.db);f.db.prepare=function(q:string){const statement=prepareDB(q),run=statement.runSync;statement.runSync=function(){if(fail&&q.startsWith('INSERT INTO research_settings')&&this.args[0]==='crossref:'+source.id&&JSON.parse(this.args[1]).headCheckedThrough){fail=false;throw Error('fixture checkpoint write failed');}return run.call(this)};return statement;};globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'){lists++;return Response.json({message:{items:[record('10.9999/checkpoint')]}})}return new Response('<rss><channel/></rss>')};const failed:any=await syncSource(f.db,source);assert.equal(failed.status,'error');assert.equal(failed.crossref.latestWatermark,null);assert.equal(failed.crossref.headCheckedThrough,null);const persisted=JSON.parse((await f.db.prepare('SELECT value FROM research_settings WHERE key=?').bind('crossref:'+source.id).first()).value);assert.equal(persisted.latest[0].cursor,'*');assert.equal(persisted.latest[0].pages,0);const first=await f.db.prepare('SELECT first_seen FROM research_papers').first();const retried:any=await syncSource(f.db,source);assert.equal(retried.added,0);assert.equal(retried.updated,0);assert.ok(retried.crossref.latestWatermark);assert.equal((await f.db.prepare('SELECT count(*) n FROM research_papers').first()).n,1);assert.equal((await f.db.prepare('SELECT first_seen FROM research_papers').first()).first_seen,first.first_seen);assert.ok(lists>=2);}finally{globalThis.fetch=original;f.sql.close()}});

test('Nature 429 publishes a machine-readable slot stop; all subsequent sources preserve budgets and cursors',async()=>{
 const f=fixture(),original=globalThis.fetch,nature=RESEARCH_SOURCES.find(s=>s.id==='nature')!;let requests=0;
 try{await initResearch(f.db);globalThis.fetch=async()=>{requests++;return new Response('',{status:429,headers:{'retry-after':'120'}})};
 const first:any=await syncSource(f.db,nature,2);assert.equal(requests,1);assert.equal(first.collectionControl.stop,true);assert.equal(first.collectionControl.reason,'crossref_rate_limit');assert.ok(first.collectionControl.retryAt);assert.equal(first.crossrefPages.length,1);assert.equal(first.crossref.latestWatermark,null);assert.equal(first.stages.publisherRss,'rate_limit_deferred');
 const stored=f.sql.prepare("SELECT value FROM research_settings WHERE key='crossref:nature'").get()!.value;
 // Even after the provider's cooldown elapses, this slot must not be resumed by a later caller.
 f.sql.prepare("UPDATE research_settings SET value='2000-01-01T00:00:00Z' WHERE key='crossref_http_cooldown'").run();
 for(const source of [nature,RESEARCH_SOURCES[0]!]){const next:any=await syncSource(f.db,source,2);assert.equal(next.status,'collection_stopped');assert.equal(next.collectionControl.stop,true);assert.deepEqual(next.crossrefPages,[])}
 assert.equal(requests,1);assert.equal(f.sql.prepare("SELECT value FROM research_settings WHERE key='crossref:nature'").get()!.value,stored);assert.equal(f.sql.prepare("SELECT value FROM research_settings WHERE key LIKE 'collection-budget:%'").get()!.value,'1');assert.equal(f.sql.prepare('SELECT count(*) n FROM research_runs').get()!.n,1);
 }finally{globalThis.fetch=original;f.sql.close()}
});
test('batched calls freeze due membership and prevent continuation before all first passes, even maxPages2',async()=>{
 const f=fixture(),original=globalThis.fetch,a=RESEARCH_SOURCES[0]!,b=RESEARCH_SOURCES[1]!,at=new Date(),key=collectionCycle(at.toISOString(),null);let requests=0;
 try{await initResearch(f.db);f.sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,?,?,'running',?,?)").run(key,key.slice(0,10),Number(key.slice(-2)),JSON.stringify([a.id,b.id]),at.toISOString());globalThis.fetch=async(url:any)=>{if(new URL(String(url)).hostname==='api.crossref.org')requests++;return new URL(String(url)).hostname==='api.crossref.org'?Response.json({message:{items:[]}}):new Response('<rss><channel/></rss>')};
 const first:any=await syncSource(f.db,a,2,key);assert.equal(first.crossrefPages.length,1);assert.equal(first.collectionControl.nextSourceId,b.id);
 const blocked:any=await syncSource(f.db,a,2,key);assert.equal(blocked.status,'head_pass_pending');assert.equal(requests,1);
 const omitted:any=await syncSource(f.db,RESEARCH_SOURCES[2]!,1,key);assert.equal(omitted.status,'not_due');assert.equal(requests,1);
 await syncSource(f.db,b,2,key);assert.equal(requests,2);const history:any=await syncSource(f.db,a,2,key);assert.equal(history.crossrefPages.length,1);assert.equal(history.crossrefPages[0].lane,'history');assert.equal(requests,3);await syncSource(f.db,a,2,key);assert.equal(requests,3);
 }finally{globalThis.fetch=original;f.sql.close()}
});
test('preflight shared cooldown and expired collection deadline consume no calls, attempts, or source state',async()=>{
 const f=fixture(),original=globalThis.fetch,at=new Date(),key=collectionCycle(at.toISOString(),null);try{await initResearch(f.db);globalThis.fetch=async()=>{throw Error('must not fetch')};f.sql.prepare("INSERT INTO research_settings(key,value) VALUES('crossref_http_cooldown',?)").run(new Date(at.getTime()+60000).toISOString());let result:any=await syncSource(f.db,RESEARCH_SOURCES[0]!);assert.equal(result.collectionControl.reason,'crossref_cooldown');f.sql.prepare("DELETE FROM research_settings WHERE key='crossref_http_cooldown'").run();f.sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,?,?,'running',?,?)").run(key,key.slice(0,10),Number(key.slice(-2)),JSON.stringify([RESEARCH_SOURCES[0]!.id]),new Date(at.getTime()-540001).toISOString());result=await syncSource(f.db,RESEARCH_SOURCES[0]!,1,key);assert.equal(result.collectionControl.reason,'time_budget');assert.equal(f.sql.prepare('SELECT count(*) n FROM research_runs').get()!.n,0);assert.equal(f.sql.prepare("SELECT count(*) n FROM research_settings WHERE key LIKE 'crossref:%' OR key LIKE 'collection-budget:%'").get()!.n,0);}finally{globalThis.fetch=original;f.sql.close()}
});
test('orchestrator honors structured global stop even when HTTP200 has no error text',async()=>{const called:string[]=[];const result=await collectResearch([{id:'a'},{id:'b'}],async id=>{called.push(id);return {pending:true,status:'backfill_pending',collectionControl:{stop:true,reason:'crossref_rate_limit'}}},{maxPagesPerSource:2,maxMs:260000});assert.deepEqual(called,['a']);assert.equal(result.length,1)});


test('server auto-next tolerates stale explicit order, freezes membership and skips exhausted empty history',async(t)=>{
 const next8=Date.parse(new Date(Date.now()+8*3600000+86400000).toISOString().slice(0,10)+'T08:01:00+08:00');t.mock.timers.enable({apis:['Date'],now:next8});
 const f=fixture(),original=globalThis.fetch,[a,b]=RESEARCH_SOURCES,at=new Date(),key=collectionCycle(at.toISOString(),null);const fetched:string[]=[];
 try{await initResearch(f.db);f.sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,?,?,'running',?,?)").run(key,key.slice(0,10),Number(key.slice(-2)),JSON.stringify([a!.id,b!.id]),at.toISOString());
 globalThis.fetch=async(url:any)=>{const u=new URL(String(url));if(u.hostname==='api.crossref.org'){fetched.push(u.pathname);return Response.json({message:{items:[]}})}return new Response('<rss><channel/></rss>')};
 const call=async(sourceId?:string)=>{const r=await researchApi(new Request('https://local.test/api/site/research/sync',{method:'POST',body:JSON.stringify({batchKey:key,maxPages:2,...(sourceId?{sourceId}:{})})}),{DB:f.db});assert.equal(r.status,200);return r.json()};
 const stale=await call(b!.id);assert.equal(stale.sourceId,b!.id);assert.equal(stale.crossrefPages.length,1);assert.equal((await call(b!.id)).status,'head_pass_pending');
 // A later settings edit cannot add the other thirty sources to this frozen batch.
 f.sql.prepare("INSERT INTO research_settings(key,value) VALUES('collection_intervals','{}')").run();
 const first=await call();assert.equal(first.sourceId,a!.id);const second=await call(),third=await call();assert.notEqual(second.sourceId,third.sourceId);assert.equal(second.crossrefPages[0].lane,'history');assert.equal(third.crossrefPages[0].lane,'history');const stopped=await call();assert.equal(stopped.collectionControl.reason,'sources_exhausted');assert.equal(fetched.length,4);assert.equal(new Set(fetched).size,2);
 }finally{globalThis.fetch=original;f.sql.close()}
});


test('shared lease deferral spends no budget, preserves attempt time, and settles an explicit deferred head',async()=>{
 const f=fixture(),original=globalThis.fetch,[a,b]=RESEARCH_SOURCES,at=new Date(),key=collectionCycle(at.toISOString(),null);let requests=0;
 try{await initResearch(f.db);f.sql.prepare("INSERT INTO research_batches(key,date,slot,status,sources_json,started_at) VALUES(?,?,?,'running',?,?)").run(key,key.slice(0,10),Number(key.slice(-2)),JSON.stringify([a!.id,b!.id]),at.toISOString());globalThis.fetch=async(url:any)=>{if(new URL(String(url)).hostname==='api.crossref.org'){requests++;return Response.json({message:{items:[]}})}return new Response('<rss><channel/></rss>')};await syncSource(f.db,a!,1,key);
 f.sql.prepare("INSERT INTO research_settings(key,value) VALUES('crossref_http_lock',?)").run(new Date(Date.now()+60000).toISOString());const blocked:any=await syncSource(f.db,b!,1,key);assert.equal(blocked.crossref.cycle.pages,0);assert.equal(blocked.crossref.lastHeadAttemptAt,null);assert.deepEqual(blocked.crossrefPages,[]);assert.equal(blocked.collectionControl.pass,'continuation');assert.equal(blocked.collectionControl.nextSourceId,a!.id);assert.equal(f.sql.prepare("SELECT value FROM research_settings WHERE key LIKE 'collection-budget:%'").get()!.value,'1');assert.equal((await syncSource(f.db,a!,1,key) as any).status,'deferred');assert.equal(requests,1);
 f.sql.prepare("DELETE FROM research_settings WHERE key='crossref_http_lock'").run();const settled:any=await syncSource(f.db,b!,1,key);assert.equal(requests,1);assert.equal(settled.collectionControl.nextSourceId,a!.id);assert.deepEqual(settled.collectionControl.headDeferredSources,[b!.id]);const continuation=await syncSource(f.db,a!,1,key);assert.equal(continuation.crossrefPages[0].lane,'history');assert.equal(requests,2);assert.equal(continuation.collectionControl.stop,true);
 }finally{globalThis.fetch=original;f.sql.close()}
});
test('full batch client follows server plan independently of current due list, with 35-call and time bounds',async()=>{
 let calls=0;const result=await collectResearchBatch(async()=>{calls++;return {collectionControl:{stop:calls===4,pass:calls<3?'head':'continuation'}}},{maxPagesPerSource:2,maxMs:260000});assert.equal(result.length,4);
 calls=0;assert.equal((await collectResearchBatch(async()=>{calls++;return {collectionControl:{stop:false,pass:'head'}}},{maxPagesPerSource:2,maxMs:260000})).length,35);
 let time=0;assert.equal((await collectResearchBatch(async()=>{time+=100;return {collectionControl:{stop:false,pass:'head'}}},{maxPagesPerSource:2,maxMs:150,now:()=>time})).length,2);
});
