import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {safeLogEntry,writeLog,cleanupLogs,logsApi,LOG_ROW_CAP,transportDiagnostic} from './runtime-logs.ts';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...a:any[]){this.args=a;return this},async first(){return s.get(...this.args)},async all(){return {results:s.all(...this.args)}},async run(){return {meta:{changes:Number(s.run(...this.args).changes)}}}}},async batch(ss:any[]){return Promise.all(ss.map(s=>s.run()))}};return {sql,db}}
const entry={severity:'warning',component:'provider',event:'request_failed',outcome:'unknown',errorCode:'provider_network',phase:'connect',metadata:{transport:'connection_failed'}};
test('central allowlist excludes all free text, secrets, URL queries, content and unknown nested fields',async()=>{const secret='sk-SECRETabcdefghijklmnop';const out=await safeLogEntry({...entry,message:secret,errorCode:secret,requestId:'owner@example.org:'+secret,sourceId:'https://a.test?key='+secret,metadata:{authorization:'Bearer '+secret,cookie:secret,encryptionKey:secret,abstract:secret,body:secret,rawResponse:secret,errorName:secret,transportCode:secret,added:Infinity,updated:-2,round:1e20,pending:true,nested:{key:secret}}});const text=JSON.stringify(out);for(const forbidden of [secret,'owner@example.org','https://','authorization','cookie','abstract','rawResponse'])assert.ok(!text.includes(forbidden),forbidden);assert.equal(out.errorCode,null);assert.equal(out.metadata.updated,0);assert.equal(out.metadata.round,1e9);assert.equal(out.requestId?.length,24);assert.ok(text.length<1000)});
test('transport diagnostics classify only approved names and codes, never raw errors',()=>{assert.deepEqual(transportDiagnostic(Object.assign(new TypeError('secret'),{cause:{code:'ECONNRESET',message:'token'}})),{transport:'connection_failed',errorName:'TypeError',transportCode:'ECONNRESET'});assert.equal(transportDiagnostic({name:'secret',code:'secret'}).errorName,'Other')});
test('logging failures are isolated including sanitizer getters and database outage',async()=>{await writeLog(null,entry);await writeLog({prepare(){throw Error('secret')}},entry);await writeLog({}, {get severity(){throw Error('secret')}})});
test('retention cleanup is bounded and applies only to new logs; expired rows hidden',async()=>{const {sql,db}=fixture();const insert=sql.prepare("INSERT INTO runtime_logs(created_at,severity,component,event,outcome) VALUES(?,'warning','server','unexpected_exception','failed')");for(let i=0;i<450;i++)insert.run('2000-01-01T00:00:00.000Z');sql.prepare("INSERT INTO research_runs(id,started_at,status) VALUES('keep','2000','ok')").run();await cleanupLogs(db);assert.equal(sql.prepare('SELECT count(*) n FROM runtime_logs').get()!.n,250);assert.equal(sql.prepare('SELECT count(*) n FROM research_runs').get()!.n,1);const r=await logsApi(new Request('https://local.test/api/site/logs',{headers:{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.org'}}),{DB:db,HKIS_OWNER_EMAIL:'owner@example.org'});assert.equal((await r.json()).entries.length,0);sql.close()});
test('10,000-row cap holds across repeated writes and reads do not evict current rows',async()=>{const {sql,db}=fixture();const insert=sql.prepare("INSERT INTO runtime_logs(created_at,severity,component,event,outcome) VALUES(?,'warning','server','unexpected_exception','failed')");for(let i=0;i<LOG_ROW_CAP;i++)insert.run(new Date().toISOString());await cleanupLogs(db);assert.equal(sql.prepare('SELECT count(*) n FROM runtime_logs').get()!.n,LOG_ROW_CAP);await writeLog(db,entry);assert.equal(sql.prepare('SELECT count(*) n FROM runtime_logs').get()!.n,LOG_ROW_CAP);sql.close()});
test('owner-only reads, allowlisted filters and stable keyset pagination',async()=>{const {sql,db}=fixture();const env={DB:db,HKIS_OWNER_EMAIL:'owner@example.org'},headers={'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.org'};for(let i=0;i<52;i++)await writeLog(db,entry);await writeLog(db,{...entry,severity:'info',component:'settings'});for(const h of [{},{...headers,'oai-authenticated-user-email':'viewer@example.org'}])assert.equal((await logsApi(new Request('https://local.test/api/site/logs',{headers:h}),env)).status,403);const a=await (await logsApi(new Request('https://local.test/api/site/logs?component=provider',{headers}),env)).json();assert.equal(a.entries.length,50);const b=await (await logsApi(new Request('https://local.test/api/site/logs?before='+a.nextCursor,{headers}),env)).json();assert.equal(b.entries.length,2);assert.ok(b.entries.every((r:any)=>r.id<a.nextCursor));assert.equal((await logsApi(new Request('https://local.test/api/site/logs?component=bad',{headers}),env)).status,400);assert.equal((await logsApi(new Request('https://local.test/api/site/logs',{method:'POST',headers}),env)).status,405);sql.close()});
