import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {initResearch,savePaper} from './research.ts';
import {fromCrossref,fromOpenAlex,enrichPaper,normalizeDoi} from './research-domain.ts';
import {RESEARCH_SOURCES} from './research-config.ts';
const source=RESEARCH_SOURCES[0]!;
function database(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db:any={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},async run(){return {meta:{changes:Number(s.run(...this.args).changes)}}}}},async batch(statements:any[]){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db};}
const paper=(doi:string|null,title='First transistor study',abstract:string|null='Original first paper evidence')=>({...fromCrossref({type:'journal-article',DOI:doi||'10.1234/temp',title:[title],abstract,published:{'date-parts':[[2026,10,10]]}},source)!,doi,url:'https://example.invalid/early-view'});
test('different DOI sharing URL never mixes original abstract, in either order',async()=>{for(const reverse of [false,true]){const {db,sql}=database();try{await initResearch(db);const a=paper('10.1234/a'),b=paper('10.1234/b','Different TCAD study',null);for(const p of reverse?[b,a]:[a,b])await savePaper(db,p);const rows=sql.prepare('SELECT doi,abstract FROM research_papers ORDER BY doi').all();assert.equal(rows.length,2);assert.equal(rows[0]!.abstract,a.abstract);assert.equal(rows[1]!.abstract,null);assert.equal(sql.prepare('SELECT count(*) n FROM research_records').get()!.n,2);}finally{sql.close()}}});
test('DOI-first identity survives changed URL and DOI-less publisher evidence is completed once',async()=>{const {db,sql}=database();try{await initResearch(db);const a=await savePaper(db,paper(null)),b=await savePaper(db,paper('10.1234/a'));assert.equal(a.id,b.id);const c=await savePaper(db,{...paper('10.1234/a'),url:'https://example.invalid/new-url'});assert.equal(c.id,a.id);assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);}finally{sql.close()}});
test('DOI-less shared URL with two known identities does not guess an attachment',async()=>{const {db,sql}=database();try{await initResearch(db);await savePaper(db,paper('10.1234/a'));await savePaper(db,paper('10.1234/b','Different TCAD study',null));const result=await savePaper(db,paper(null,'Unidentified publisher entry',null));assert.equal(result.skipped,'identity_ambiguous');assert.equal(sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,2);assert.equal(sql.prepare('SELECT count(*) n FROM research_records').get()!.n,2);}finally{sql.close()}});
test('DOI canonicalization strips whitespace and doi URL/prefix, rejects malformed identifiers',()=>{for(const value of [' https://doi.org/10.1234/ABC ','doi: 10.1234/ABC','https://dx.doi.org/10.1234/ABC'])assert.equal(normalizeDoi(value),'10.1234/abc');assert.equal(normalizeDoi('10.1234/a?token=x'),'');assert.equal(normalizeDoi({}),'')});

test('historical DOI-less ID upgraded before shared-URL ambiguity is skipped once without changing either identity',async()=>{const {db,sql}=database();try{await initResearch(db);const unknown=await savePaper(db,paper(null)),a=await savePaper(db,paper('10.1234/a'));assert.equal(a.id,unknown.id);await savePaper(db,paper('10.1234/b','Different TCAD study',null));const before=sql.prepare('SELECT * FROM research_papers ORDER BY id').all(),result=await savePaper(db,paper(null,'Unidentified TCAD entry',null));assert.equal(result.skipped,'identity_ambiguous');assert.equal(result.added,0);assert.equal(result.paper,null);assert.deepEqual(sql.prepare('SELECT * FROM research_papers ORDER BY id').all(),before);}finally{sql.close()}});
test('OpenAlex malformed, duplicate, sparse and noninteger indexes never become an abstract',()=>{for(const index of [{A:5},{A:['0']},{A:[0],B:[0]},{A:[0],B:[2]},{A:[20000]},{A:[-1]}]){let extra:any;assert.doesNotThrow(()=>{extra=fromOpenAlex({id:'https://openalex.org/W1',doi:'10.1234/a',abstract_inverted_index:index})});assert.equal(extra.abstract,null)}assert.equal(fromOpenAlex({id:'https://openalex.org/W1',doi:'10.1234/a',abstract_inverted_index:{A:[0,2],B:[1]}}).abstract,'A B A')});
test('later keyword evidence replaces negative cache with provenance and revision',()=>{const p=paper('10.1234/a');p.provenance.keywordEvidence={recordUrl:'https://openalex.org/W1',policy:'first-three-v2',status:'no_keywords',records:[],revision:1,checkedAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'};const next=enrichPaper(p,fromOpenAlex({id:'https://openalex.org/W1',doi:p.doi,keywords:[{display_name:'TCAD',score:.9,id:'K1'}]}));assert.equal(next.provenance.keywordEvidence.status,'found');assert.equal(next.provenance.keywordEvidence.revision,2);assert.equal(next.provenance.keywordEvidence.records[0].terms[0].label,'TCAD');assert.deepEqual(next.keywords,[])});
export {database,paper};
test('invalid Crossref rows are isolated while partially provided author records remain usable',()=>{for(const raw of [null,[],{}, {...recordForInput(),DOI:'invalid'}, {...recordForInput(),title:'wrong shape'}])assert.equal(fromCrossref(raw,source),null);const parsed=fromCrossref({...recordForInput(),author:[null,{given:'Alice',family:'Example',affiliation:[null,{name:'Example University'}]}]},source)!;assert.equal(parsed.authors.length,1);assert.equal(parsed.affiliations[0],'Example University')});
function recordForInput(){return {type:'journal-article',DOI:'10.1234/valid',title:['A TCAD simulation']}}
