import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {weekWindow,publicationDay,buildWeeklyDigest,evidenceExcerpt} from './weekly.ts';
import {JOURNAL_METRICS} from './journal-metrics.ts';
import type {Paper} from './research-domain.ts';
const at=new Date('2026-09-30T15:59:59Z');
function paper(id:string,change:Partial<Paper>={}):Paper&{id:string}{return {id,doi:'10.1002/test.'+id,title:'Ferroelectric MOSFET device simulation',url:'https://example.org/paper/'+id,publisher:'Wiley',journal:'Advanced Electronic Materials',sourceId:'wiley-aem',issn:'2199-160X',publishedAt:'2026-09-25',datePrecision:'day',authors:[],affiliations:[],abstract:'We demonstrate a ferroelectric transistor with improved endurance. The measured endurance reaches 95% after cycling.',keywords:[],provenance:{abstract:'crossref'},sourceIndexedAt:null,discovery:'crossref',priority:60,...change};}
test('UTC+08 seven-calendar-day boundary rolls exactly at local midnight',()=>{assert.equal(weekWindow(at).startDate,'2026-09-24');const next=weekWindow(new Date('2026-09-30T16:00:00Z'));assert.equal(next.startDate,'2026-09-25');assert.equal(next.endDate,'2026-10-01');});
test('online date takes precedence; imprecise and invalid dates are never fabricated',()=>{assert.equal(publicationDay(paper('a',{publishedAt:'2026-12-10',provenance:{publicationDates:{online:'2026-09-24'}}})).date,'2026-09-24');for(const d of ['2026','2026-09','2026-02-30'])assert.equal(publicationDay(paper('b',{provenance:{publicationDates:{online:d}}})).date,null);assert.equal(publicationDay(paper('c',{datePrecision:'month',publishedAt:'2026-09'})).date,null);});
test('inclusive date endpoints, future and missing dates, discovery is irrelevant',()=>{const d=buildWeeklyDigest([paper('start',{publishedAt:'2026-09-24'}),paper('end',{publishedAt:'2026-09-30'}),paper('old',{publishedAt:'2026-09-23'}),paper('future',{publishedAt:'2026-10-01'}),paper('missing',{publishedAt:null}),paper('month',{publishedAt:'2026-09',datePrecision:'month'})],at);assert.deepEqual(d.papers.map(p=>p.id),['end','start']);assert.equal(d.exclusions.futureDate,1);assert.equal(d.exclusions.missingOrImpreciseDate,2);});
test('JIF is descending with publication-date tie break; unknown metrics come last',()=>{const d=buildWeeklyDigest([paper('low',{sourceId:'wiley-pssa'}),paper('high-old',{sourceId:'wiley-aom'}),paper('high-new',{sourceId:'wiley-aom',publishedAt:'2026-09-29'}),paper('unknown',{sourceId:'elsevier-sse',publisher:'Elsevier',publishedAt:'2026-09-30'})],at);assert.deepEqual(d.papers.map(p=>p.id),['high-new','high-old','low','unknown']);assert.equal(d.papers[3]!.metric.value,null);for(const m of JOURNAL_METRICS.filter(m=>m.status==='verified'))assert.ok(m.year&&m.sourceUrl&&m.evidence&&m.value!=null);});
test('topic grouping is de-duplicated and author keywords never equal extracted tags',()=>{const d=buildWeeklyDigest([paper('a'),paper('b',{title:'A ferroelectric FeFET',abstract:null})],at);const g=d.groups.find(g=>g.id==='emerging')!;assert.equal(g.total,2);assert.equal(g.withAbstract,1);assert.equal(g.keywordGroups.find(k=>k.label==='铁电 / FeFET')!.count,2);assert.deepEqual(d.papers[0]!.keywords,[]);assert.equal(d.coverage.withAuthorKeywords,0);});
test('title-only papers never produce evidence, every citation links to its exact DOI',()=>{const p=paper('a',{abstract:null});const d=buildWeeklyDigest([p],at);assert.equal(d.papers[0]!.evidence,null);assert.equal(d.groups.every(g=>g.evidence.length===0),true);assert.equal(d.papers[0]!.url,'https://doi.org/10.1002/test.a');assert.equal(d.papers[0]!.detailUrl,'/research/a');});
test('extract is grounded, contiguous, short, with measured result preferred to generic promise',()=>{const p=paper('a',{abstract:'Two-dimensional materials show promise for memristor applications. Sputtered Al yields highly reproducible switching, achieving 95% yield across 64 devices. Future research remains necessary.'});const e=evidenceExcerpt(p)!;assert.ok(e.text.includes('95%'));assert.ok(p.abstract!.includes(e.text));assert.ok(e.text.split(/\s+/).length<=25);const long=paper('b',{abstract:'We demonstrate improved switching with 100 devices and '+Array(60).fill('performance').join(' ')+'.'});const q=evidenceExcerpt(long)!;assert.ok(long.abstract!.includes(q.text));assert.ok(q.text.split(/\s+/).length<=25);assert.ok(q.truncated);});
test('filters recalculate coverage/groups/references together; empty is honest',()=>{const d=buildWeeklyDigest([paper('a'),paper('b',{publisher:'IEEE',sourceId:'ieee-edl'})],at,{publisher:'IEEE'});assert.equal(d.papers.length,1);assert.equal(d.papers[0]!.reference,1);assert.equal(d.coverage.inScopeWeekly,2);assert.ok(d.groups.every(g=>g.paperIds.every(id=>id==='b')));const empty=buildWeeklyDigest([],at);assert.equal(empty.papers.length,0);assert.equal(empty.groups.length,0);assert.equal(empty.coverage.withAbstract,0);});
