import {test} from 'node:test';
import {strict as assert} from 'node:assert';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {aiApi,parseAnswer} from './api.ts';
import {DEFAULTS} from './settings.ts';
import {endpoint,seal,unseal} from './security.ts';
import {savePaper} from '../research.ts';
import {RESEARCH_SOURCES} from '../research-config.ts';
import {propose,preferences,resolveProposal,searchPapers} from './tools.ts';
function fixture(){const sql=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q:string){const s=sql.prepare(q);return {args:[] as any[],bind(...args:any[]){this.args=args;return this},async first(){return s.get(...this.args)||null},async all(){return {results:s.all(...this.args)}},runSync(){return {meta:{changes:Number(s.run(...this.args).changes)}}},async run(){return this.runSync()}}},async batch(statements:any[]){sql.exec('BEGIN');try{const r=[];for(const s of statements)r.push(s.runSync());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};return {sql,db,env:{DB:db,HKIS_OWNER_EMAIL:'owner@example.org',HKIS_AI_ENCRYPTION_KEY:'11'.repeat(32)}}}
const secret='UNIT_TEST_NOT_A_REAL_CREDENTIAL';
const ownerHeaders={'oai-authenticated-user-id':'owner-123','oai-authenticated-user-email':'owner@example.org'};
async function request(env:any,path:string,body?:any,headers:any={}){return aiApi(new Request('https://local.test/api/site/ai/'+path,{method:body===undefined?'GET':'POST',headers:{...ownerHeaders,...(body===undefined?{}:{origin:'https://local.test','Content-Type':'application/json','X-HKIS-Request':'1'}),...headers},body:body===undefined?undefined:JSON.stringify(body)}),env)}
async function configured(f:ReturnType<typeof fixture>,overrides:any={}){const r=await request(f.env,'settings',{...DEFAULTS,apiKey:secret,confirmedDestination:DEFAULTS.endpoint,revision:0,enabled:true,...overrides});assert.equal(r.status,200,JSON.stringify(await r.clone().json()));return r.json()}
async function paper(f:ReturnType<typeof fixture>,abstract:string|null='The measured device exhibits a 95% yield across 64 samples. TCAD simulation confirms interface trap effects.'){const s=RESEARCH_SOURCES[0]!;return savePaper(f.db,{title:'TCAD interface trap image sensor test',doi:'10.9999/ai-test',url:'https://example.org/paper',publisher:s.publisher,journal:s.name,sourceId:s.id,issn:s.issn,publishedAt:'2026-09-29',datePrecision:'day',authors:[],affiliations:[],abstract,keywords:[],provenance:{abstract:abstract?'crossref':null},sourceIndexedAt:null,discovery:'crossref'})}
const output=(answer:any)=>Response.json({status:'completed',output:[{type:'message',role:'assistant',content:[{type:'output_text',text:JSON.stringify(answer)}]}],usage:{input_tokens:20,output_tokens:30}});
test('defaults preserve exact requested model and reasoning, disabled with no secret readback',async()=>{const f=fixture();const r=await request(f.env,'settings');assert.equal(r.status,200);const data=await r.json();assert.equal(data.model,'gpt-5.6-luna');assert.equal(data.reasoning,'xhigh');assert.equal(data.enabled,false);assert.equal(data.hasKey,false);assert.equal(data.revision,0);f.sql.close()});
test('owner identity, missing runtime owner and missing/cross-origin CSRF fail closed',async()=>{const f=fixture();assert.equal((await request(f.env,'settings',undefined,{'oai-authenticated-user-id':''})).status,403);assert.equal((await request(f.env,'settings',undefined,{'oai-authenticated-user-email':'viewer@example.org'})).status,403);assert.equal((await request({...f.env,HKIS_OWNER_EMAIL:''},'settings')).status,503);for(const headers of [{origin:''},{origin:'https://evil.test'},{'X-HKIS-Request':''},{'sec-fetch-site':'cross-site'}])assert.equal((await request(f.env,'settings',{},headers)).status,403);f.sql.close()});
test('endpoint validation blocks private addresses, redirector paths, non-HTTPS and unknown hosts',()=>{for(const url of ['http://api.openai.com/v1','https://127.0.0.1/v1','https://[::1]/v1','https://169.254.169.254','https://api.openai.com.evil.org/v1','https://api.openai.com/v1?target=evil','https://user:password@api.openai.com/v1','https://api.openai.com/redirect','https://new-provider.example.com/v1'])assert.throws(()=>endpoint(url,{}));assert.equal(endpoint('https://api.openai.com/v1/',{}),DEFAULTS.endpoint)});
test('AES-GCM ciphertext is random, owner and destination bound, no fallback secret',async()=>{const f=fixture(),a=await seal(secret,f.env,'owner|url'),b=await seal(secret,f.env,'owner|url');assert.notEqual(a,b);assert.ok(!a.includes(secret));assert.equal(await unseal(a,f.env,'owner|url'),secret);await assert.rejects(()=>unseal(a,f.env,'other|url'));await assert.rejects(()=>seal(secret,{},'x'));f.sql.close()});
test('settings encrypt keys; destination consent required; safe reads never expose cipher or plaintext',async()=>{const f=fixture();assert.equal((await request(f.env,'settings',{...DEFAULTS,revision:0,apiKey:secret})).status,400);const config=await configured(f);assert.equal(config.hasKey,true);const row=f.sql.prepare('SELECT * FROM ai_settings').get()!;assert.ok(!JSON.stringify(row).includes(secret));const text=await (await request(f.env,'settings')).text();assert.ok(!text.includes(secret));assert.ok(!text.includes('cipher'));assert.equal(JSON.stringify(row).includes('UNIT_TEST'),false);f.sql.close()});
test('missing encryption supports nonsecret settings but rejects key input/enabling',async()=>{const f=fixture();delete (f.env as any).HKIS_AI_ENCRYPTION_KEY;assert.equal((await request(f.env,'settings',{...DEFAULTS,revision:0})).status,200);assert.equal((await request(f.env,'settings',{...DEFAULTS,revision:1,apiKey:secret,confirmedDestination:DEFAULTS.endpoint})).status,503);assert.equal(f.sql.prepare('SELECT key_ciphertext FROM ai_settings').get()!.key_ciphertext,null);f.sql.close()});
test('provider change cannot reuse stored key; removal disables AI, revision protects concurrent writes',async()=>{const f=fixture();await configured(f);assert.equal((await request(f.env,'settings',{...DEFAULTS,endpoint:'https://api.deepseek.com',revision:1})).status,400);assert.equal((await request(f.env,'settings',{...DEFAULTS,revision:0})).status,409);const r=await request(f.env,'settings',{...DEFAULTS,endpoint:'https://api.deepseek.com',revision:1,removeKey:true,enabled:true});assert.equal(r.status,200);const data=await r.json();assert.equal(data.hasKey,false);assert.equal(data.enabled,false);f.sql.close()});
test('invalid reasoning/budget and OpenAI incompatible tool protocol are rejected without downgrading',async()=>{const f=fixture();for(const override of [{reasoning:'super'},{dailyLimit:0},{maxTokens:2},{model:'bad model'},{protocol:'chat_completions'}])assert.equal((await request(f.env,'settings',{...DEFAULTS,revision:0,...override})).status,400);f.sql.close()});
test('proposals are isolated, explicit, cancellable, replay-proof and stale-safe',async()=>{const f=fixture(),value={keywords:['TCAD'],excludedKeywords:['biology'],sourceIntervals:{[RESEARCH_SOURCES[0]!.id]:24}},p=await propose(f.db,'owner-123',value);assert.deepEqual((await preferences(f.db,'owner-123')).value.keywords,[]);await assert.rejects(()=>resolveProposal(f.db,'someone-else',p.id,'confirm'));assert.equal((await resolveProposal(f.db,'owner-123',p.id,'confirm')).status,'applied');assert.deepEqual((await preferences(f.db,'owner-123')).value,value);await assert.rejects(()=>resolveProposal(f.db,'owner-123',p.id,'confirm'));const c=await propose(f.db,'owner-123',{...value,keywords:[]});await resolveProposal(f.db,'owner-123',c.id,'cancel');await assert.rejects(()=>resolveProposal(f.db,'owner-123',c.id,'confirm'));const a=await propose(f.db,'owner-123',{...value,keywords:['a']}),b=await propose(f.db,'owner-123',{...value,keywords:['b']});await resolveProposal(f.db,'owner-123',a.id,'confirm');await assert.rejects(()=>resolveProposal(f.db,'owner-123',b.id,'confirm'));f.sql.close()});
test('proposals reject secret/provider changes, unknown sources and expired confirmations',async()=>{const f=fixture();for(const value of [{keywords:[],excludedKeywords:[],sourceIntervals:{},apiKey:'x'},{keywords:[],excludedKeywords:[],sourceIntervals:{arbitrary:12}},{keywords:[],excludedKeywords:[],sourceIntervals:{[RESEARCH_SOURCES[0]!.id]:0}}])await assert.rejects(()=>propose(f.db,'owner-123',value));const p=await propose(f.db,'owner-123',{keywords:['TCAD'],excludedKeywords:[],sourceIntervals:{}});f.sql.prepare("UPDATE ai_proposals SET expires_at='2000-01-01'").run();await assert.rejects(()=>resolveProposal(f.db,'owner-123',p.id,'confirm'));f.sql.close()});
test('search binds SQL and applies personal exclusion/keyword filters with real stored IDs',async()=>{const f=fixture(),p=await paper(f);let r=await searchPapers(f.db,'owner-123',{q:'TCAD',useKeywords:false});assert.equal(r.papers[0].id,p.id);assert.equal(r.papers[0].aiScore,null);assert.equal((await searchPapers(f.db,'owner-123',{q:"%_';DROP_TABLE"})).total,0);const proposal=await propose(f.db,'owner-123',{keywords:[],excludedKeywords:['TCAD'],sourceIntervals:{}});await resolveProposal(f.db,'owner-123',proposal.id,'confirm');r=await searchPapers(f.db,'owner-123',{q:'TCAD'});assert.equal(r.total,0);assert.equal(f.sql.prepare('SELECT count(*) n FROM research_papers').get()!.n,1);f.sql.close()});
test('unconfigured and disabled chat never contact provider',async()=>{const f=fixture(),original=globalThis.fetch;globalThis.fetch=async()=>{throw Error('must not call')};try{assert.equal((await request(f.env,'chat',{message:'hello',requestId:crypto.randomUUID()})).status,409);await configured(f,{enabled:false});assert.equal((await request(f.env,'chat',{message:'hello',requestId:crypto.randomUUID()})).status,409)}finally{globalThis.fetch=original;f.sql.close()}});
test('real tool loop preserves model/effort, returns citations/evidence, and duplicate request reuses paid result',async()=>{const f=fixture(),p=await paper(f);await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url:any,init:any)=>{assert.equal(String(url),DEFAULTS.endpoint+'/responses');assert.equal(init.redirect,'manual');const body=JSON.parse(init.body);assert.equal(body.model,'gpt-5.6-luna');assert.equal(body.reasoning.effort,'xhigh');assert.equal(body.store,false);assert.ok(!init.body.includes(secret));calls++;if(calls===1)return Response.json({output:[{type:'function_call',call_id:'c1',name:'search_papers',arguments:JSON.stringify({q:'TCAD',publisher:'',useKeywords:false})}]});return output({answer:'该研究提供器件数据 [paper:'+p.id+']',paperIds:[p.id],analyses:[{paperId:p.id,decision:'include',score:85,summary:'与界面陷阱相关',evidence:'The measured device exhibits a 95% yield across 64 samples.'}]})};try{const body={message:'寻找 TCAD 论文并分析',requestId:crypto.randomUUID()};const response=await request(f.env,'chat',body);assert.equal(response.status,200,await response.clone().text());const data=await response.json();assert.equal(data.papers[0].id,p.id);assert.equal(data.analyses[0].score,85);assert.equal(data.providerCalls,2);assert.equal((await request(f.env,'chat',body)).status,200);assert.equal(calls,2);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,2);assert.equal((await request(f.env,'chat',{...body,message:'different'})).status,409)}finally{globalThis.fetch=original;f.sql.close()}});
test('analysis abstains for missing/unmatched abstract evidence and rejects fabricated citations',()=>{const evidence=new Map([['p1',{id:'p1',abstract:null}],['p2',{id:'p2',abstract:'Actual scientific evidence about measured yields.'}]]);const r=parseAnswer(JSON.stringify({answer:'摘要不足',paperIds:['p1','p2'],analyses:[{paperId:'p1',decision:'include',score:99,evidence:'invented'},{paperId:'p2',decision:'include',score:80,evidence:'not in the abstract'}]}),evidence);assert.ok(r.analyses.every((a:any)=>a.score===null&&a.decision==='insufficient'));assert.throws(()=>parseAnswer(JSON.stringify({answer:'[paper:fake]',paperIds:[],analyses:[]}),evidence))});
test('model can only propose config changes; injected delete/key tools cannot execute',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;if(calls===1)return Response.json({output:[{type:'function_call',call_id:'bad',name:'delete_papers',arguments:'{}'},{type:'function_call',call_id:'bad2',name:'propose_preferences',arguments:JSON.stringify({keywords:['injected'],excludedKeywords:[],sourceIntervals:[]})}]});return output({answer:'未执行变更',paperIds:[],analyses:[]})};try{const r=await request(f.env,'chat',{message:'找论文',requestId:crypto.randomUUID(),allowProposals:false});assert.equal(r.status,200);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_proposals').get()!.n,0);assert.deepEqual((await preferences(f.db,'owner-123')).value.keywords,[])}finally{globalThis.fetch=original;f.sql.close()}});
test('daily attempt budget is enforced before transmission, failure is not retried, errors redact credentials',async()=>{const f=fixture();await configured(f,{dailyLimit:1});const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({error:{code:'invalid_api_key',message:'invalid '+secret}},{status:401})};try{const body={message:'hi',requestId:crypto.randomUUID()},r=await request(f.env,'chat',body);assert.equal(r.status,502);const text=await r.text();assert.ok(text.includes('401'));assert.ok(text.includes('invalid_api_key'));assert.ok(!text.includes(secret));assert.equal((await request(f.env,'chat',body)).status,409);assert.equal((await request(f.env,'chat',{...body,requestId:crypto.randomUUID()})).status,429);assert.equal(calls,1);assert.ok(!JSON.stringify(f.sql.prepare('SELECT * FROM ai_receipts').get()).includes(secret))}finally{globalThis.fetch=original;f.sql.close()}});
test('network failure records unknown attempt and does not automatically resend',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;throw new Error('timeout')};try{const body={message:'hi',requestId:crypto.randomUUID()};assert.equal((await request(f.env,'chat',body)).status,502);assert.equal((await request(f.env,'chat',body)).status,409);assert.equal(calls,1);assert.equal(f.sql.prepare('SELECT status FROM ai_receipts').get()!.status,'unknown')}finally{globalThis.fetch=original;f.sql.close()}});
test('connection test validates tool/effort support and counts a receipt without enabling disabled assistant',async()=>{const f=fixture();await configured(f,{enabled:false});const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({output:[{type:'function_call',call_id:'test',name:'connection_check',arguments:'{"ok":true}'}]});try{const response=await request(f.env,'test',{requestId:crypto.randomUUID()});assert.equal(response.status,200);const settings=await (await request(f.env,'settings')).json();assert.equal(settings.testStatus,'ok');assert.equal(settings.enabled,false);assert.equal(settings.callsToday,1)}finally{globalThis.fetch=original;f.sql.close()}});
test('provider truncation, refusal, invalid shape and invalid output return clear errors',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;try{for(const payload of [{status:'incomplete',output:[]},{output:[{type:'message',content:[{type:'refusal',refusal:'No'}]}]},{unrelated:true},{output:[{type:'message',content:[{type:'output_text',text:'not json'}]}]}]){globalThis.fetch=async()=>Response.json(payload);const r=await request(f.env,'chat',{message:'hi',requestId:crypto.randomUUID()});assert.ok([422,502].includes(r.status),await r.text())}}finally{globalThis.fetch=original;f.sql.close()}});
test('Chat Completions is explicit and retains custom model/effort instead of fallback',async()=>{const f=fixture();await configured(f,{endpoint:'https://api.deepseek.com',confirmedDestination:'https://api.deepseek.com',protocol:'chat_completions',model:'custom-model',reasoning:'high'});const original=globalThis.fetch;globalThis.fetch=async(url:any,init:any)=>{assert.equal(String(url),'https://api.deepseek.com/chat/completions');const b=JSON.parse(init.body);assert.equal(b.model,'custom-model');assert.equal(b.reasoning_effort,'high');return Response.json({choices:[{finish_reason:'stop',message:{role:'assistant',content:JSON.stringify({answer:'未找到证据',paperIds:[],analyses:[]})}}]})};try{assert.equal((await request(f.env,'chat',{message:'hi',requestId:crypto.randomUUID()})).status,200)}finally{globalThis.fetch=original;f.sql.close()}});
test('Unicode-escaped credential echoes are redacted after JSON decoding in API errors and receipts',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;globalThis.fetch=async()=>new Response('{"error":{"code":"invalid_api_key","message":"'+[...secret].map(c=>'\\u'+c.charCodeAt(0).toString(16).padStart(4,'0')).join('')+'"}}',{status:401,headers:{'Content-Type':'application/json'}});try{const r=await request(f.env,'chat',{message:'hi',requestId:crypto.randomUUID()});assert.equal(r.status,502);assert.ok(!(await r.text()).includes(secret));const stored=JSON.parse(String(f.sql.prepare('SELECT response_json FROM ai_receipts').get()!.response_json));assert.ok(!JSON.stringify(stored).includes(secret));assert.ok(stored.error.message.includes('已隐藏凭证'))}finally{globalThis.fetch=original;f.sql.close()}});
test('no-evidence scientific claims are suppressed instead of presented as verified',()=>{const answer=parseAnswer(JSON.stringify({answer:'Study 10.1234/invented proves ten-fold efficiency.',paperIds:[],analyses:[]}),new Map());assert.ok(!answer.answer.includes('10.1234'));assert.ok(answer.answer.includes('不能给出科学结论'))});
test('cancel racing with confirmation cannot report that applied settings stayed unchanged',async()=>{const f=fixture(),p=await propose(f.db,'owner-123',{keywords:['TCAD'],excludedKeywords:[],sourceIntervals:{}});let raced=false;const db={...f.db,prepare(q:string){const stmt=f.db.prepare(q);if(q.includes("SET status='cancelled'")){const run=stmt.run.bind(stmt);stmt.run=async()=>{if(!raced){raced=true;await resolveProposal(f.db,'owner-123',p.id,'confirm')}return run()}}return stmt}};await assert.rejects(()=>resolveProposal(db,'owner-123',p.id,'cancel'),/已在其他请求中确认生效/);assert.equal(f.sql.prepare('SELECT status FROM ai_proposals').get()!.status,'applied');f.sql.close()});
test('concurrent attempts cannot overshoot daily budget or duplicate a request ID',async()=>{const f=fixture();await configured(f,{dailyLimit:1});const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return output({answer:'无证据',paperIds:[],analyses:[]})};try{const results=await Promise.all(Array.from({length:5},()=>request(f.env,'chat',{message:'hello',requestId:crypto.randomUUID()})));assert.equal(results.filter(r=>r.status===200).length,1);assert.equal(results.filter(r=>r.status===429).length,4);assert.equal(calls,1)}finally{globalThis.fetch=original;f.sql.close()}});
test('old answer content is cleared but tombstone prevents an old paid request replay',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;globalThis.fetch=async()=>output({answer:'hello',paperIds:[],analyses:[]});try{const body={message:'hi',requestId:crypto.randomUUID()};assert.equal((await request(f.env,'chat',body)).status,200);f.sql.exec("UPDATE ai_requests SET created_at='2000-01-01';UPDATE ai_receipts SET created_at='2000-01-01'");await request(f.env,'settings');assert.equal(f.sql.prepare('SELECT result_json FROM ai_requests').get()!.result_json,null);assert.equal(f.sql.prepare('SELECT response_json FROM ai_receipts').get()!.response_json,null);assert.equal((await request(f.env,'chat',body)).status,409)}finally{globalThis.fetch=original;f.sql.close()}});

test('Kimi Code exact endpoint is admitted without allowing neighboring hosts or paths',()=>{
 assert.equal(endpoint('https://api.kimi.com/coding/v1/',{}),'https://api.kimi.com/coding/v1');
 for(const url of ['https://api.kimi.com','https://api.kimi.com/coding/v1/responses','https://api.kimi.com/coding/v1?redirect=x','https://api.kimi.com.evil.org/coding/v1','https://api.kimi.ai/coding/v1'])assert.throws(()=>endpoint(url,{}));
});
test('Kimi Code Responses preserves kimi-for-coding/max and genuine HKIS identity with no fallback',async()=>{
 const f=fixture();await configured(f,{endpoint:'https://api.kimi.com/coding/v1',confirmedDestination:'https://api.kimi.com/coding/v1',model:'kimi-for-coding',reasoning:'max'});
 const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url:any,init:any)=>{calls++;assert.equal(String(url),'https://api.kimi.com/coding/v1/responses');const body=JSON.parse(init.body);assert.equal(body.model,'kimi-for-coding');assert.deepEqual(body.reasoning,{effort:'max'});assert.equal(init.headers['User-Agent'],'HKIS/1.0 (personal research assistant)');assert.equal(init.redirect,'manual');assert.ok(!init.body.includes(secret));return Response.json({output:[{type:'function_call',call_id:'check',name:'connection_check',arguments:'{"ok":true}'}]})};
 try{const r=await request(f.env,'test',{requestId:crypto.randomUUID()});assert.equal(r.status,200);assert.equal((await r.json()).reasoning,'max');assert.equal(calls,1)}finally{globalThis.fetch=original;f.sql.close()}
});
test('Kimi Code background purpose is blocked before credential access or provider request',async()=>{
 const {providerCall}=await import('./provider.ts');const original=globalThis.fetch;let called=false;globalThis.fetch=async()=>{called=true;throw Error('must not call')};
 try{await assert.rejects(()=>providerCall(null,'owner',{endpoint:'https://api.kimi.com/coding/v1'},null,'job',0,[],'batch'),/Kimi Code 仅用于/);assert.equal(called,false)}finally{globalThis.fetch=original}
});
test('Kimi Code rejection is surfaced once without impersonating another client',async()=>{
 const f=fixture();await configured(f,{endpoint:'https://api.kimi.com/coding/v1',confirmedDestination:'https://api.kimi.com/coding/v1',model:'kimi-for-coding',reasoning:'max'});const original=globalThis.fetch;let calls=0;
 globalThis.fetch=async()=>{calls++;return Response.json({error:{code:'permission_denied',message:'Client is not permitted'}},{status:403})};
 try{const r=await request(f.env,'test',{requestId:crypto.randomUUID()});assert.equal(r.status,502);assert.match((await r.json()).error,/403.*permission_denied.*Client is not permitted/);assert.equal(calls,1)}finally{globalThis.fetch=original;f.sql.close()}
});
test('owner-clicked single-paper analysis reuses the saved Kimi Responses/max configuration',async()=>{
 const f=fixture(),p=await paper(f);await configured(f,{endpoint:'https://api.kimi.com/coding/v1',confirmedDestination:'https://api.kimi.com/coding/v1',model:'kimi-for-coding',reasoning:'max'});const original=globalThis.fetch;let calls=0;
 globalThis.fetch=async(url:any,init:any)=>{calls++;const b=JSON.parse(init.body);assert.equal(String(url),'https://api.kimi.com/coding/v1/responses');assert.equal(b.model,'kimi-for-coding');assert.equal(b.reasoning.effort,'max');assert.ok(b.input.some((m:any)=>m.content.includes(p.id)));return output({answer:'该论文提供器件测试证据 [paper:'+p.id+']',paperIds:[p.id],analyses:[{paperId:p.id,decision:'include',score:85,summary:'与界面陷阱研究相关',evidence:'The measured device exhibits a 95% yield across 64 samples.'}]})};
 try{const r=await request(f.env,'chat',{message:'分析这篇论文',paperIds:[p.id],requestId:crypto.randomUUID()});assert.equal(r.status,200);const result=await r.json();assert.equal(result.model,'kimi-for-coding');assert.equal(result.reasoning,'max');assert.equal(result.analyses[0].paperId,p.id);assert.equal(result.analyses[0].score,85);assert.equal(calls,1)}finally{globalThis.fetch=original;f.sql.close()}
});
test('non-JSON provider rejection retains HTTP diagnostics without storing raw bodies or headers',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return new Response('<html>blocked '+secret+' private prompt</html>',{status:403,headers:{'content-type':'text/html','x-request-id':'req-safe-403','x-private':secret}})};try{const body={requestId:crypto.randomUUID()};const response=await request(f.env,'test',body);assert.equal(response.status,502);assert.ok((await response.text()).includes('HTTP 403'));const row=f.sql.prepare('SELECT * FROM ai_receipts').get()!;assert.equal(row.status,'rejected');const stored=JSON.parse(String(row.response_json));assert.deepEqual(stored.diagnostic,{httpStatus:403,providerRequestId:'req-safe-403',phase:'parse_response',contentKind:'html',cloudflareChallenge:false,cloudflareServer:false});assert.ok(!JSON.stringify(row).includes(secret));assert.ok(!JSON.stringify(row).includes('private prompt'));const settings=await (await request(f.env,'settings')).json();assert.ok(settings.lastTestError.includes('HTTP 403'));assert.equal(settings.testStatus,'failed');assert.equal((await request(f.env,'test',body)).status,409);assert.equal(calls,1)}finally{globalThis.fetch=original;f.sql.close()}});
test('timeout diagnostics survive reload without leaking transport error details or enabling AI',async()=>{const f=fixture();await configured(f,{enabled:false});const original=globalThis.fetch;globalThis.fetch=async()=>{throw Object.assign(new Error('request Authorization: '+secret),{name:'TimeoutError'})};try{const response=await request(f.env,'test',{requestId:crypto.randomUUID()});assert.equal(response.status,502);const row=f.sql.prepare('SELECT * FROM ai_receipts').get()!;assert.equal(row.status,'unknown');const diagnostic=JSON.parse(String(row.response_json)).diagnostic;assert.equal(diagnostic.transport,'timeout');assert.equal(diagnostic.httpStatus,null);assert.equal(diagnostic.phase,'connect');assert.ok(!JSON.stringify(row).includes(secret));const settings=await (await request(f.env,'settings')).json();assert.ok(settings.lastTestError.includes('等待超时'));assert.equal(settings.enabled,false);assert.ok(!JSON.stringify(settings).includes(secret))}finally{globalThis.fetch=original;f.sql.close()}});
test('successful non-JSON reply remains unknown rather than rejected and preserves HTTP status',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;globalThis.fetch=async()=>new Response('upstream body '+secret,{status:200});try{assert.equal((await request(f.env,'test',{requestId:crypto.randomUUID()})).status,502);const row=f.sql.prepare('SELECT * FROM ai_receipts').get()!;assert.equal(row.status,'unknown');assert.equal(JSON.parse(String(row.response_json)).diagnostic.httpStatus,200);assert.ok(!String(row.response_json).includes(secret))}finally{globalThis.fetch=original;f.sql.close()}});
test('JSON rejection stores bounded allowlisted fields and discards arbitrary echoes',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({error:{code:'permission_denied',message:'bad '+secret,raw_request:{authorization:secret,prompt:'private prompt'}},extra:'private extra'},{status:403});try{assert.equal((await request(f.env,'test',{requestId:crypto.randomUUID()})).status,502);const row=f.sql.prepare('SELECT * FROM ai_receipts').get()!;const data=JSON.parse(String(row.response_json));assert.equal(data.diagnostic.httpStatus,403);assert.equal(data.error.code,'permission_denied');assert.ok(data.error.message.includes('已隐藏凭证'));for(const s of [secret,'private prompt','private extra','raw_request'])assert.ok(!String(row.response_json).includes(s))}finally{globalThis.fetch=original;f.sql.close()}});
test('latest budget rejection replaces older provider failure even without a new receipt',async()=>{const f=fixture();await configured(f,{dailyLimit:1});const original=globalThis.fetch;globalThis.fetch=async()=>Response.json({error:{code:'previous_provider_error',message:'previous failure'}},{status:403});try{assert.equal((await request(f.env,'test',{requestId:crypto.randomUUID()})).status,502);assert.equal((await request(f.env,'test',{requestId:crypto.randomUUID()})).status,429);const settings=await (await request(f.env,'settings')).json();assert.ok(settings.lastTestError.includes('调用限额'));assert.ok(!settings.lastTestError.includes('previous'));assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,1)}finally{globalThis.fetch=original;f.sql.close()}});

test('provider redirects are never followed; logs contain safe phase/status and no location, key or chat',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async(_url:any,init:any)=>{calls++;assert.equal(init.redirect,'manual');return new Response('SENSITIVE_BODY',{status:307,headers:{Location:'https://evil.test/?key='+secret}})};try{const r=await request(f.env,'test',{requestId:crypto.randomUUID()});assert.equal(r.status,502);assert.equal((await r.json()).code,'provider_redirect');assert.equal(calls,1);const rows=f.sql.prepare("SELECT * FROM runtime_logs WHERE component='provider'").all();assert.equal(rows.length,1);assert.equal(rows[0]!.http_status,307);assert.equal(rows[0]!.error_code,'provider_redirect');const text=JSON.stringify(f.sql.prepare('SELECT * FROM runtime_logs').all());for(const v of [secret,'SENSITIVE_BODY','evil.test','cipher','Authorization'])assert.ok(!text.includes(v));assert.equal(f.sql.prepare("SELECT count(*) n FROM runtime_logs WHERE component='settings' AND event='config_saved'").get()!.n,1)}finally{globalThis.fetch=original;f.sql.close()}});
test('config and provider failures are instrumented; diagnostics outage does not change primary result',async()=>{const f=fixture();await configured(f);await request(f.env,'settings',{...DEFAULTS,revision:0});assert.equal(f.sql.prepare("SELECT error_code FROM runtime_logs WHERE component='settings' AND event='request_failed'").get()!.error_code,'settings_conflict');f.sql.exec('DROP TABLE runtime_logs');const r=await request(f.env,'settings');assert.equal(r.status,200);f.sql.close()});
test('network diagnostic is owner/CSRF protected and sends only one fixed empty unauthenticated POST',async()=>{const f=fixture();await configured(f,{endpoint:'https://api.kimi.com/coding/v1',confirmedDestination:'https://api.kimi.com/coding/v1',model:'kimi-for-coding',reasoning:'max'});f.sql.exec("UPDATE ai_settings SET key_ciphertext='INVALID_DO_NOT_DECRYPT',enabled=0");delete (f.env as any).HKIS_AI_ENCRYPTION_KEY;const original=globalThis.fetch;let calls=0;globalThis.fetch=async(url:any,init:any)=>{calls++;assert.equal(url,'https://api.kimi.com/coding/v1/responses');assert.equal(init.method,'POST');assert.equal(init.body,'{}');assert.equal(init.redirect,'manual');assert.deepEqual(init.headers,{'Content-Type':'application/json','User-Agent':'HKIS/1.0 (personal research assistant)'});return Response.json({error:{message:'Invalid Authentication'}},{status:401,headers:{'x-trace-id':'reference-123'}})};try{const body={requestId:crypto.randomUUID(),endpoint:'https://evil.invalid',model:'not-used',apiKey:'not-used',message:'not-used'};assert.equal((await request(f.env,'network',body,{'oai-authenticated-user-id':''})).status,403);assert.equal((await request(f.env,'network',body,{origin:'https://evil.invalid'})).status,403);assert.equal(calls,0);const r=await request(f.env,'network',body);assert.equal(r.status,200);const result=await r.json();assert.equal(result.httpStatus,401);assert.equal(result.noCredential,true);assert.equal(result.modelInvoked,false);assert.equal(result.reference.length,24);assert.ok(!JSON.stringify(result).includes('reference-123'));assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.equal((await request(f.env,'network',body)).status,429);assert.equal(calls,1);const row=f.sql.prepare("SELECT metadata_json FROM runtime_logs WHERE event='network_probe'").get()!;assert.equal(JSON.parse(String(row.metadata_json)).purpose,'network')}finally{globalThis.fetch=original;f.sql.close()}});
test('network diagnostic captures only fixed response categories, never raw headers or HTML',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return new Response('<html>secret body '+secret+'</html>',{status:403,headers:{'content-type':'text/html; charset=utf-8','cf-mitigated':'challenge','server':'cloudflare','set-cookie':secret,'x-private':secret,'cf-ray':'safe-ref'}})};try{const r=await request(f.env,'network',{requestId:crypto.randomUUID()});const data=await r.json();assert.equal(data.httpStatus,403);assert.equal(data.contentKind,'html');assert.equal(data.bodyClass,'html');assert.equal(data.cloudflareChallenge,true);assert.ok(data.message.includes('Cloudflare'));const stored=JSON.stringify(f.sql.prepare('SELECT * FROM ai_requests').all())+JSON.stringify(f.sql.prepare('SELECT * FROM runtime_logs').all());for(const word of [secret,'secret body','set-cookie','safe-ref'])assert.ok(!stored.includes(word));assert.equal(calls,1)}finally{globalThis.fetch=original;f.sql.close()}});
test('network diagnostic does not follow redirects or retry network failures and is rate limited',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;if(calls===1)return new Response('',{status:302,headers:{location:'https://evil.invalid/'+secret}});throw Object.assign(new Error(secret),{name:'TimeoutError'})};try{const a=await (await request(f.env,'network',{requestId:crypto.randomUUID()})).json();assert.equal(a.httpStatus,302);assert.ok(a.message.includes('未跟随'));const b=await (await request(f.env,'network',{requestId:crypto.randomUUID()})).json();assert.equal(b.httpStatus,null);assert.equal(b.transport,'timeout');assert.equal((await request(f.env,'network',{requestId:crypto.randomUUID()})).status,429);assert.equal(calls,2);assert.equal(f.sql.prepare('SELECT count(*) n FROM ai_receipts').get()!.n,0);assert.ok(!JSON.stringify(f.sql.prepare('SELECT * FROM ai_requests').all()).includes(secret))}finally{globalThis.fetch=original;f.sql.close()}});
test('network diagnostic bounds response capture and does not read a credential column',async()=>{const f=fixture();await configured(f);const prepare=f.db.prepare;f.db.prepare=(q:string)=>{assert.ok(!/key_ciphertext|SELECT \* FROM ai_settings/.test(q),q);return prepare(q)};const original=globalThis.fetch;globalThis.fetch=async()=>new Response('x'.repeat(20000),{status:403});try{const data=await (await request(f.env,'network',{requestId:crypto.randomUUID()})).json();assert.equal(data.bodyClass,'truncated');assert.ok(JSON.stringify(data).length<1500)}finally{globalThis.fetch=original;f.sql.close()}});
test('network diagnostic retains 403 metadata if the body stream fails after headers',async()=>{const f=fixture();await configured(f);const original=globalThis.fetch;globalThis.fetch=async()=>new Response(new ReadableStream({start(c){c.error(new Error(secret))}}),{status:403,headers:{'content-type':'text/html','cf-mitigated':'challenge'}});try{const data=await (await request(f.env,'network',{requestId:crypto.randomUUID()})).json();assert.equal(data.httpStatus,403);assert.equal(data.cloudflareChallenge,true);assert.equal(data.bodyClass,'read_failed');assert.ok(data.message.includes('已收到 HTTP 403'));assert.ok(!JSON.stringify(data).includes(secret));const log=f.sql.prepare("SELECT http_status,phase FROM runtime_logs WHERE event='network_probe'").get()!;assert.equal(log.http_status,403);assert.equal(log.phase,'read_response')}finally{globalThis.fetch=original;f.sql.close()}});
